typeorm/typeorm

- src/decorator/options/ColumnOptions.ts
- src/driver/PostgresDriver.ts
Using TS 2.1@next gives a typing error on lines 409,415 of PostgresDriver.ts
Needed to tweak these lines to get a clean compile.
> Stronger typing for anonymous inner function

- src/metadata/EntityMetadata.ts
- src/persistment/PersistOperationExecutor.ts
- test/functional/persistence/custom-column-name-pk/custom-column-name-pk.ts
- test/functional/persistence/custom-column-name-pk/entity/Category.ts
- test/functional/persistence/custom-column-name-pk/entity/Post.ts
in some cases the PersistOperationExecutor used the property names instead of column names for update/delete statements.
This PR fixes these problems.
> fixed bug when primary key has custom name

- config/parameters.json
- config/parameters.json.dist
- src/persistment/EntityPersistOperationsBuilder.ts
- src/persistment/EntityPersister.ts
- test/functional/connection-manager/connection-manager.ts
- test/functional/persistence/many-to-many/persistence-many-to-many.ts
- test/functional/persistence/multi-primary-key/entity/Category.ts
- test/functional/persistence/multi-primary-key/entity/Post.ts
- test/functional/persistence/multi-primary-key/multi-primary-key.ts
- test/functional/repository/delete-by-id-and-ids/repository-remove-by-id-and-ids.ts
- test/functional/repository/set-add-remove-relations/repository-set-add-remove-relations.ts
- test/integration/sample2-one-to-one.ts
- test/integration/sample3-many-to-one.ts
- test/integration/sample4-many-to-many.ts
- test/utils/test-utils.ts
by moving the call to `firstPrimaryColumn` under the condition `isManyToMany` wecan enable working inserts with multi primary columns for simple relations.
> quick fix for multi primary columns (and fix another bug)

- src/util/DirectoryExportedClassesLoader.ts
I know very little about the inter-working of this system. This fixed the issue of loading up entities from ormconfig.json using relative path of the root directory.
> resolve entity and schema dir paths

- src/driver/mysql/MysqlDriver.ts
current behavior attempts to insert 'Invalid Date' string into database when moment cannot parse date string. typically due to the default mysql datatime value of 0000-00-00 00:00:00 creates the invalid date issue. This fix allows invalid dates to go into the database as 0000-00-00 00:00:00 and not 01-01-1970 00:00:00 ..
> fixes mysql datetime issues when persisting records

- src/driver/sqlite/SqliteQueryRunner.ts
Error: when attempting to insert an empty row to database using a sqlite driver, it causes an error. Fix: use "insert into default values".
> SQLite driver insert fix

- src/decorator/Index.ts
Fixed an issue when maybeFieldsOrOptions is an array, options would still go for maybeFieldsOrOptions instead of maybeOptions.
Reference to issue #72
> Unique Issue fixed

- ormconfig.travis.json
- src/driver/mysql/MysqlDriver.ts
I found this issue while deploying to google cloud, as they use unix sockets for mysql.
A workaround is just to define `host` as some string, because the mysql driver is preferring `socketPath` over host.
> Allow empty host, if extra.socketPath is set

- src/persistence/SubjectOperationExecutor.ts
Fixes this case:
````
// persist some initial data
// Photo has ManyToMany relation with Tag and Album
let photo = new Photo();
let tag = new Tag();
let album = new Album();
album.tags = [tag];
await connection.entityManager.persist([tag, photo, album]);
// fun starts here
album.photos = [photo]; // add a single photo
album.tags = []; // now remove that single tag
await connection.entityManager.persist(album);
// now load the album which we just updated
let loadedAlbum = await connection.entityManager.findOneById(Album, 1, {
alias: 'album',
leftJoinAndSelect: {
'photo': 'album.photos',
'tag': 'album.tags'
}
});
// relations were not updated
if(loadedAlbum.photos.length === 0) {
console.error('No photos stored, but I've added one!');
}
if(loadedAlbum.tags.length !== 0) { …
```
> Fixed junction bug

- src/commands/MigrationCreateCommand.ts
Hi,
despite adding the missing import for class "EntityManager", I propose some changes to meet some more strict tslint rules.
Please let me know if this will work for you.
Tobias.
> Some fixes in MigrationCreateCommand

- src/driver/postgres/PostgresQueryRunner.ts
- test/functional/uuid/entity/Record.ts
- test/functional/uuid/uuid.ts
This pull request is a quick fix for generated UUID fields.  The `PrimaryGeneratedColumn` decorator works correctly, and newly inserted UUIDs are returned with the entity.
> Correct generated UUID behavior

- src/index.ts
I was creating an API that has a base service class to do common rest commands (i.e. `get`, `find`, `create`), etc, and I was trying to do something like this:
```ts
import { getConnection, EntityManager, ObjectType } from 'typeorm';
export abstract class AbstractService<T> {
protected entityManager: EntityManager;
constructor(private entityClass: ObjectType<T>) {
this.entityManager = getConnection().entityManager;
}
async find(params): Promise<T[]> {
return this.entityManager.find(this.entityClass);
}
// ... other methods...
}
// usage in another file:
export class UserService extends AbstractService<User> {
constructor() {
super(User);
}
}
```
but `ObjectType` isn't exported, so TypeScript was complaining. It wouldn't let me do `import { ObjectType } from 'typeorm/common` either …
> Export ObjectType and ObjectLiteral

- src/entity-manager/EntityManager.ts
- test/github-issues/363/entity/Car.ts
- test/github-issues/363/entity/Fruit.ts
- test/github-issues/363/issue-363.ts
This changes the behavior of `entityManager` to correctly handle persisting and removing multiple unrelated entities in one call.
Resolves #363
> Persist/Remove multiple unrelated entities in one entityManager call

- DEVELOPER.md
- gulpfile.ts
I recently created a PR and felt like the docs could have mentioned some of this to have made it easier to get started!
I also added functionality to `npm test` so that you can run `npm test -- --grep="some-regex-string"` to filter for specific tests to make it easier to just test your newly added tests. I added mention of this to the docs as well.
> Update the developer docs with more info about creating tests

- src/decorator/options/ColumnOptions.ts
- src/driver/mongodb/MongoQueryRunner.ts
- src/driver/mysql/MysqlQueryRunner.ts
- src/driver/oracle/OracleQueryRunner.ts
- src/driver/postgres/PostgresQueryRunner.ts
- src/driver/sqlite/SqliteQueryRunner.ts
- src/driver/sqlserver/SqlServerQueryRunner.ts
- src/driver/websql/WebsqlQueryRunner.ts
- src/metadata/ColumnMetadata.ts
- src/query-runner/QueryRunner.ts
Well, I had some time and as I had mentioned in #343. This pull request tries to implement that feature.
Please take a look and if needed feel free to make any changes in it.
**Some notes:**
I didn't add support to SQLite and Web SQL because I want to discuss some another minor changes.
For example:
`CHARACTER`, `VARCHAR`, `VARYING CHARACTER`, `NCHAR`, `NVARCHAR` are all the same as `TEXT`.
Refer to [3.1.1. Affinity Name Examples](https://www.sqlite.org/datatype3.html#affinity_name_examples)
For this two specific drivers, there is no way to add a `fixedLength` attribute.
This brings some improvements, like this piece of code:
```ts
switch (typeOptions.type) {
case "string":
return "character varying(" + (typeOptions.length ? typeOptions.length : 255) + ")";
case "text":
return "text";
} …
```
> Support fixed length column data type.

- README.md
Correct table name to 'photometadata' in one-to-one relation example in README.md file
> Correct table name to 'photometadata' in one-to-one relation example

- src/repository/Repository.ts
It appears that `Repository.findByIds()` wasn't actually passing the `ids` parameter to `EntityManager.findByIds()`.
> Resolve issue #542

- src/connection/options-reader/ConnectionOptionsEnvReader.ts
It seems that `TYPEORM_MIGRATIONS` variable is missing in `ConnectionOptionsEnvReader.ts`. I've added it. This probably caused migrations failure when using `ormconfig.env` (migrations couldn't be found).
> Add missing TYPEORM_MIGRATIONS

- .travis.yml
- DEVELOPER.md
- gulpfile.ts
- package.json
Updating development docs, `gulpfile.ts` and `.travis.yml` to avoid using global installs.
Using `gulp` and `tsc` commands as global does not guarantee the version being used is the one present on `package.json`, so development environment might be different for each person, which is anti-pattern.
- Added all globally executed packages (`gulp` and `tsc`) as `script`s on `package.json` (Just the ones that I found on `gulpfile.ts`, `.travis.yml` and docs. Are there others that I am not aware of?)
- Updated `gulpfile.ts`, `travis.yml` to use such scripts instead
- Updated `DEVELOPMENT` docs to use `npm run <script>` instead of global `gulp` 
Travis masks this issue by forcing `node_modules/.bin` to be [part of the machine's `$PATH`](https://travis-ci.org/typeorm/typeorm/jobs/248750165#L493), …
> Avoiding global npm installs

- src/util/DirectoryExportedClassesLoader.ts
1. Moved array checking on top of the object checking since Array is the instance/typeof object
2. Replaced ```instanceof``` calls with ```typeof``` calls.
For some reason, the ```exported instanceof Object``` check is giving ```false``` in my Jest test files when i'm creating DB connection so the typeorm is unable to process entities/migrations/subscribers. This may be caused by heavy VM contexts manipulating in Jest itself.
> Improve DirectoryExportedClassesLoader

- src/repository/TreeRepository.ts
While trying to use the `findRoots`method, the `parentPropertyName` field is not using the `joinColumnName` method from the naming strategy. This PR fixes the issue.
> Use the naming strategy on TreeRepository

- README-zh_CN.md
- README.md
As per discussion in [#145](https://github.com/typeorm/typeorm/issues/145), self-initialised arrays on relations may lead to unintended updates as typeorm assumes an empty array means all relations have been removed. Hence, remove references to this practice from the documentation to avoid confusion.
> Update documentation to remove references to self-initialised arrays

- src/entity-manager/EntityManager.ts
- test/functional/query-builder/locking/query-builder-locking.ts
- test/functional/transaction/return-data-from-transaction/entity/Category.ts
- test/functional/transaction/return-data-from-transaction/entity/Post.ts
- test/functional/transaction/return-data-from-transaction/return-data-from-transaction.ts
Resolves #696 
``manager.transaction`` does not allow to use type-safe returns.
``manager.transaction`` should leverage generics & type inference to allow type-safe transaction returns.
It seems that TS compiler sometimes might shout at us for not using explicit returns (look at the "fixed" testcase in file ``query-builder-locking.ts``). It's probably due to the fact that TypeORM is configured to use ``noImplicitReturns`` flag, and with my fix, compiler has to create a union type (earlier it was always ``any``, so it didn't care much). I hope this won't affect acceptance of my PR, I don't think it's that much of a deal (but well, I might be wrong).
> Support type-safe returns when using transactions

- src/metadata-builder/EntityMetadataBuilder.ts
This creates a column drop & create on each connection because in the db this field is not unique, not should it be.
> Parent id field should not be unique

- src/query-builder/SelectQueryBuilder.ts
Before this fix, this exception would be thrown from the db:
" missing FROM-clause entry for table "parentidcolumn_XX"
due to lowercase vs uppercase
> Escape parent id join condition

- src/query-builder/JoinAttribute.ts
Prior to this fix, we assumed that if inheritance exists, relations would only be found on the parent entity.
> Try finding relations in both child and parent entities

- CHANGELOG.md
Adding missing `CHANGELOG` for [0.0.11](https://github.com/typeorm/typeorm/compare/0.0.10...0.0.11) version.
> Adding missing CHANGELOG for 0.0.11 version

- src/schema-builder/RdbmsSchemaBuilder.ts
- src/schema-builder/schema/TableSchema.ts
`MySqlQueryRunner` references `TableSchema#engine`, but the engine parameter wasn't set when creating tables.
> Fix engine option being ignored

- src/metadata/ColumnMetadata.ts
- src/metadata/EntityMetadata.ts
as it is not as it is not always equal to the property name itself (like in the case of inheritance)
> First try getting property name from referencedColumn

- README.md
There was a comma missing in createConnection example in the readme.
> Fixed missing comma in createConnection example

- DEVELOPER.md
The url pointed to the contributing guidelines in angular repo, changed towards the one in this repo.
> Fix contributing guidelines url in DEVELOPER.md

- src/connection/ConnectionOptionsReader.ts
- src/decorator/Index.ts
- src/entity-manager/MongoEntityManager.ts
- test/functional/connection-options-reader/configs/class-entities.ts
- test/functional/connection-options-reader/connection-options-reader.ts
Due to incorrect check, `ConnectionOptionsReader` failed when anything but a array of strings was provided to `entities`, `migrations` or `subscribers` connection options. Fix was to simply change `||` to `&&`.
As for commit with types changes it was simply needed for me to start the work on fix. Typescript 2.4.2 doesn't have a problem with what was previously but using 2.5.2 caused compilation to fail.
> Fix problem with ConnectionOptionsReader when loading config with entities specified directly

- src/migration/MigrationExecutor.ts
"Migration class name should contain a class name at the end of the file. ${migrationClassName} migration name is wrong."
Was receiving this error and was not sure what it meant. I discovered that the migration class name requires a timestamp, but the error thrown did not describe this properly.
${migrationClassName} migration name is wrong. Migration class name should have a UNIX timestamp appended.
> Clarifying Migration Executer Error Msg

- src/driver/cordova/CordovaDriver.ts
While using the cordova driver I found a small bug where the `disconnect` call was wrong. I also added the `location` option to the `open` call of the database. Before the option was specified but never used.
> Cordova driver: Fixes wrong disconnect call and added location option

- src/commands/MigrationGenerateCommand.ts
Spotted two unnecessary imports (according to the latest changelog) in a migration I’ve just generated.
> Remove deprecated imports for generated migrations

- gulpfile.ts
Changes the content of `build/browser` so that it only includes the definition files (.d.ts) and not the source files. As discussed in #857
> browser package: ship definition files instead of source files

- src/find-options/FindOptionsUtils.ts
- test/github-issues/867/entity/User.ts
- test/github-issues/867/issue-867.ts
see #867 
then function `applyOptionsToQueryBuilder` will be called by both `applyFindOneOptionsOrConditionsToQueryBuilder` and `applyFindManyOptionsOrConditionsToQueryBuilder`，but it only check `isFindOneOptions` in source file `src/find-options/FindOptionsUtils.ts` at line 95
> fix bug when apply `skip` and `take` option to findAndCount(fix #867)

- gulpfile.ts
- package.json
As mentioned in #857 the `cli.js` file was missing from the package, which npm complains about. For consistency, I also renamed the internal name for the SystemJS build since otherwise the package would be called `typeorm-browser` but in the code it would still be `import { Entity } from "typeorm"` instead of `import { Entity } from "typeorm-browser"`. Is this a welcome change?
> Browser Package: Adds cli.js and fixes wrong naming for the SystemJS build

- src/driver/Driver.ts
- src/driver/mongodb/MongoDriver.ts
- src/driver/mysql/MysqlDriver.ts
- src/driver/oracle/OracleDriver.ts
- src/driver/postgres/PostgresDriver.ts
- src/driver/sqlite-abstract/AbstractSqliteDriver.ts
- src/driver/sqlserver/SqlServerDriver.ts
- src/schema-builder/schema/TableSchema.ts
- test/functional/database-schema/unique-index/entity/person.ts
- test/functional/database-schema/unique-index/entity/user.ts
- test/functional/database-schema/unique-index/unique-index-test.ts
Add normalizeIsUnique method to driver interface and use it to check if a column is isUnique compared to what the DB schema reports. There are differences on how a DB handles the unique column case.
MySQL - MariaDB consider a column as unique if there is a unique index on the column, without the need for a unique constraint. 
So we need to adjust on how we resolve differences so that we take this into account (only for this DB type).
This fixes #549, #244, #572 and #221
> Fix for issues #549, #244, #572 and #221.

- src/driver/cordova/CordovaDriver.ts
This adds the, in #890 mentioned, check if the `location` option is set. I will write proper docs and an example for it tomorrow.
fixes #890
> Cordova Driver: add check if the location option is set

- test/github-issues/929/entity/TestEntity.ts
- test/github-issues/929/issue-929.ts
When using subqueries parameters are not set in the subquery when executing the main query. 
Subqueries should set their own parameters on execution. This PR add a failing test-case for this.
Example code:
```ts
const queryBuilder = connection.manager.createQueryBuilder(TestEntity, "testEntity");
const subQuery = queryBuilder
.subQuery()
.from(TestEntity, "innerTestEntity")
.select(["id"])
.where("innerTestEntity.id = :innerId", { innerId: 1 });
const mainQuery = queryBuilder
.select("testEntity")
.where(`testEntity.id IN ${subQuery.getQuery()}`);
// .setParameters({innerId: 1}); // this would make it work, but subqueries should set their own parameters on execution
```
The code above currently generates the following query: 
```sql
SELECT "testEntity"."id" AS "testEntity_id", …
```
> test: add failing test case for #929

- src/query-builder/SelectQueryBuilder.ts
`Repository.count()` fails at the moment when using the cordova driver because in the `SelectQueryBuilder` the check was only for `SqliteDriver` and not `AbstractSqliteDriver`
> SelectQueryBuilder: executeCountQuery with the cordova driver

- src/connection/ConnectionOptionsReader.ts
It will introduce a breaking change because it will not locate ormconfig.env, instead it will search for a .env file.
Maybe its better to implement in a way that the 2 files work.
> In the case of .env file, it will load the default (global) .env file name.

- docs/connection-options.md
- src/driver/websql/WebSqlConnectionOptions.ts
Looking at the [standard](https://www.w3.org/TR/webdatabase/#introduction), the version parameter when opening a new websql connection should be a string.
fixed #998
> WebSQL version should be a string

- docs/migrations.md
Simple typo fix I found while reading the migration docs.
> Fix typo in migration docs

- src/metadata/EmbeddedMetadata.ts
- test/functional/columns/embedded-columns/columns-embedded-columns.ts
- test/functional/columns/embedded-columns/entity/Counters.ts
- test/functional/columns/embedded-columns/entity/Information.ts
- test/functional/columns/embedded-columns/entity/Post.ts
- test/functional/columns/embedded-columns/entity/SimpleCounters.ts
- test/functional/columns/embedded-columns/entity/SimplePost.ts
Example from provided test would be "countersInformationDescription" which previously would get database name "countersCountersInformationDescription". Problem was that parentEmbeddedMetadata was already taken into consideration when building prefix so anything deeper than one level would add earlier prefixes multiple times.
Previously `buildParentPrefixes` for `countersInformationDescription` would be `["counters", "counters_information]` and now it is simply `["counters_information"]`.
The base test for insert, update, remove is basically the same as the one for embedded columns for MongoDB.
> Fix column naming for deeper embedded entities

- docs/entities.md
http://typeorm.io/#/tree-entities has the slides, but http://typeorm.io/#/entities does not.
> add missing link to slides

- src/driver/cordova/CordovaDriver.ts
Up to now, foreign keys where disabled in the cordova driver. This enables them by default.
I don't know if this has to be considered a breaking change, since but to know the cordova driver didn't enforce foreign key constraints.
Fixes #1053
> Cordova: PRAGMA  foreign_keys (#1053)

- src/repository/BaseEntity.ts
This PR adds missing `create` overloads in `BaseEntity` to behave just like the `Repository`.
> Add missing `create` overloads in `BaseEntity`

- src/entity-manager/MongoEntityManager.ts
This PR allows to find by object id hex string, like the ids that are stored on frontend side (serialized).
```ts
repository.findOneById("59ef6396f31bc72f0477af8c");
```
However it would be nice to have this kind of feature in `findByIds` method too.
I wanted to do this but I don't know what this line is doing there (MongoEntityManager.ts, line 129):
```ts
return id[metadata.objectIdColumn!.propertyName];
```
Can I safely convert it to the `ObjectId` instance? Or I should check if `id` is string and convert, otherwise let the lookup thing do the work?
> Add MongoDB ObjectId conversion to `findOneById` method

- src/driver/mongodb/MongoConnectionOptions.ts
- src/driver/mongodb/MongoDriver.ts
Connection string has been tuned according to the docs:
https://docs.mongodb.com/manual/reference/connection-string/
> Add support for MongoDB authentication

- docs/relations.md
I think you meant `categoryName` instead of `categoryId` here.
You wrote...
> When we set `@JoinColumn` it creates a column in the database automatically named `propertyName + referencedColumnName`.
... before so I think it should be named `categoryName`.
Please correct me if I'm wrong.
By the way: Can I change this behavior? I would prefer `propertyName + referencedEntityName + referencedColumnName` for my DB design.
> Wrong column name

- src/platform/BrowserPlatformTools.template
- src/platform/PlatformTools.ts
- src/util/DirectoryExportedClassesLoader.ts
To keep spelling consistent between path.normalize and PlatformTools.pathNormalize
Normilize -> Normalize
( i  -> a )
> Correct typo in function name

- package-lock.json
- package.json
Pinned cli-highlight to version 1.1.4 due to incompatibility with Node 4 in later versions.
Fixes: https://github.com/typeorm/typeorm/issues/1242
> Fixed next tests failing on NodeJS 4

- src/entity-manager/EntityManager.ts
- test/github-issues/1245/entity/Post.ts
- test/github-issues/1245/issue-1245.ts
should fix https://github.com/typeorm/typeorm/issues/1245
> [issue-1245] Use `andWhere` instead of `where` in `findByIds`

- docs/entity-manager-api.md
- docs/repository-api.md
- src/entity-manager/EntityManager.ts
- src/error/EntityNotFoundError.ts
- src/repository/Repository.ts
- test/functional/repository/find-methods/repostiory-find-methods.ts
Close #1149 
Seems that simple to implement.
I'm not quite satisfied with testing though:
- I could not find the test for `findOne` on `EntityManager` to add the tests for `findOneOrFail`
- Also I'm not sure copy/pasting the tests for `findOne` is the right thing to do. With pure unit tests I would simply assert that `manager.findOneOrFail` calls `manager.findOne` and does the right thing if it gets `undefined` in return. Then I would test that `repository.findOneOrFail` forwards the call to `manager.findOneOrFail`. These tests are obviously higher level and I don't have enough knowledge of this project to know what's right to do.
> feature: findOneOrFail

- src/connection/BaseConnectionOptions.ts
- src/connection/ConnectionMetadataBuilder.ts
- src/util/OrmUtils.ts
The current implementation forbids mixing strings and objects in the `entities` parameter of a connection:
```typescript
createConnection({
/* ... */
entities:  [
'path/to/entities',
EntityClass
]
});
```
```
Type '(string | typeof EntityClass)[]' is not assignable to type 'string[] | Function[] | undefined'.
Type '(string | typeof EntityClass)[]' is not assignable to type 'Function[]'.
Type 'string | typeof EntityClass' is not assignable to type 'Function'.
Type 'string' is not assignable to type 'Function'.
```
This PR changes the parameter type from `string[]|Function[]` to `(string|Function)[]` allowing the usage above.
> Allow mixed strings and classes in `entities` parameter

- src/driver/cordova/CordovaDriver.ts
fixed #1271 
Additional options can now be passed to the driver via the `extra` option.
> Cordova: support extra options (#1271)

- src/metadata-builder/JunctionEntityMetadataBuilder.ts
- src/naming-strategy/DefaultNamingStrategy.ts
- src/naming-strategy/NamingStrategyInterface.ts
- test/github-issues/1282/entity/Animal.ts
- test/github-issues/1282/entity/Category.ts
- test/github-issues/1282/issue-1282.ts
- test/github-issues/1282/naming/NamingStrategyUnderTest.ts
- test/utils/test-utils.ts
PR for feature request https://github.com/typeorm/typeorm/issues/1282
Including simple tests.
> Naming strategy joinTableColumnName has to know if it is called from the owning or owned (inverse) context

- CHANGELOG.md
- docs/logging.md
- package-lock.json
- package.json
- src/connection/BaseConnectionOptions.ts
- src/logger/DebugLogger.ts
- src/logger/LoggerFactory.ts
- src/platform/PlatformTools.ts
<a href="https://github.com/visionmedia/debug">The debug package</a> is the <a href="https://www.npmjs.com/browse/depended">9th most dependent package</a>, it's used by  express, koa, yeoman, babel, mocha, socket.io, eslint, morgan and <a href="https://www.npmjs.com/browse/depended/debug">more</a>. It works in both node.js and browser.
https://github.com/typeorm/typeorm/pull/634 https://github.com/typeorm/typeorm/issues/633
- `ConnectOptions.logger` has new value `"debug"`
- New debug namespaces introduced:
```
typeorm:query
typeorm:queryError
typeorm:querySlow
typeorm:schemaBuild
typeorm:migration
typeorm:log
typeorm:info
typeorm:warn
```
- Debug dependency (debug itself has only one dependency, module ms)
- `ConnectOptions.logging?: LoggerOptions` is no longer used.
You need set env …
> New DebugLogger

- docs/entities.md
As issue #1045 points out, typeorm does not support `enum` on postgres type, yet it is referenced in the docs as supported.
> enum type currently not supported in postgres

- CHANGELOG.md
- src/driver/sqljs/SqljsDriver.ts
This is mostly a copy-paste of the code in the `sqlite` driver into the `sqljs` driver.
Since SQL.js is a port of sqlite, I think they should behave the same as much as possible.
> Enable foreign keys in sqljs

- CHANGELOG.md
- src/driver/sqljs/SqljsDriver.ts
- test/functional/sqljs/auto-save.ts
- test/utils/test-utils.ts
Follow up to #1321 as that PR went into `next` instead of master.
Also @pleerock's comment about sql.js tests is adressed.
These changes will have to go into `next` as well
> sql.js: enable foreign keys and change tests

- CHANGELOG.md
- src/logger/DebugLogger.ts
The debug package was required outside of DebugLogger which broke the browser support. It has to be required inside the class to only be loaded when the logger is used (in node).
fixes #1336 
fixes typeorm/ionic-example#4
> bug(require/browser): debug package was required outside of class

- src/driver/mysql/MysqlDriver.ts
I noticed the poolClusterOptions were not actually being passed to mysqljs. Looks like mysql2 needs this as well, though I didn't test it.
https://github.com/mysqljs/mysql/blob/master/index.js#L35
https://github.com/mysqljs/mysql#poolcluster-options
https://github.com/sidorares/node-mysql2/blob/ef9fc1b5f4faa53db55a6f1d30f7c4be4bd277bd/index.js#L20
> pass pool cluster options to base mysql library

- docs/working-with-entity-manager.md
For a new user, they may get confused with where the variable `User` come from on line `const user = await entityManager.findOneById(User, 1);`
> Docs: Make variable User obvious

- README.md
- docs/active-record-data-mapper.md
- docs/caching.md
- docs/custom-repository.md
- docs/decorator-reference.md
- docs/entity-manager-api.md
- docs/example-with-express.md
- docs/faq.md
- docs/logging.md
- docs/migrations.md
- docs/relational-query-builder.md
- docs/relations.md
- docs/repository-api.md
- docs/roadmap.md
- docs/select-query-builder.md
- docs/sequelize-migration.md
- docs/support.md
- docs/transactions.md
- docs/tree-entities.md
- docs/using-cli.md
- docs/working-with-repository.md
Minor grammar and punctuation fixes to documentation. Some are for readability, some for comprehension, and others to keep formatting in line with surrounding documentation.
> Documentation Grammar and Punctuation Fixes

- docs/entities.md
- docs/entity-manager-api.md
- docs/listeners-and-subscribers.md
- docs/select-query-builder.md
This should add a few lines of documentation that were mentioned in a few issues I was involved in:
#1490 #1483 #828
> Update documentation for `select`, `NULL`, and subscribers

- gulpfile.ts
- src/query-builder/SelectQueryBuilder.ts
- test/github-issues/1476/entity/Item.ts
- test/github-issues/1476/entity/Plan.ts
- test/github-issues/1476/issue-1476.ts
I'm not completely happy with this fix it doesn't work for postgres and works around the problem rather than fixing it.
The reason postgres is excluded from the tests is that the query that gets generated with the fix looks like this:
```sql
SELECT "b"."planId" AS "b_planId", "b"."planName" AS "b_planName", "i".* FROM "plan" "b"
LEFT JOIN (SELECT COUNT("planId") AS "total",
planId FROM "item" "items" GROUP BY "items"."planId") "i" ON i.planId = "b"."planId"
```
Postgres doesn't like the unescaped column planId in the subquery and i.planId on the "ON"-statement.
From my findings, the both are not escaped because [`SelectQueryBuilder::replacePropertyNames()`](https://github.com/typeorm/typeorm/blob/master/src/query-builder/QueryBuilder.ts#L514) doesn't have any metadata to compare and …
> WIP: Joins with Subquery

- docs/select-query-builder.md
I noticed this while browsing the docs. There were two columns with the name `name`. The example query builder to fetch that column was selecting `password`. So updated the column to reflect that
> Updated the hidden column to reflect the query

- docs/entities.md
removing repeated types of `int`, `tinyint`, `smallint`, `mediumint`, `bigint` at  column types for mysql / mariadb
> fixing repeating column types for mysql / mariadb

- src/connection/ConnectionOptionsReader.ts
- test/functional/connection-options-reader/configs/sqlite-memory.ts
- test/functional/connection-options-reader/connection-options-reader.ts
Fixed an issue where `ConnectionOptionsReader` could not handle `:memory:` database properly.
Fixes #1604.
> Handle SQLite in-memory db in ConnectionOptionsReader

- docs/connection-options.md
Sql.js link on the connection options page points to the wrong url
> fix(docs): link to sqljs connection options

- docs/multiple-connections.md
- src/query-builder/QueryBuilder.ts
Hi
In database replication document, 
https://github.com/typeorm/typeorm/blob/master/docs/multiple-connections.md#replication
`setQueryRunner` returns `void`.
So, this document is wrong.
> Edit database replication document

- src/commands/MigrationRunCommand.ts
I was trying to automate migrations on heroku but the build phase hangs because the migrations:run does not exit process
>  exit process on migrations:run command complete

- src/metadata-builder/EntityMetadataBuilder.ts
- src/metadata-builder/RelationJoinColumnBuilder.ts
- test/functional/persistence/one-to-one/entity/AccessToken.ts
- test/functional/persistence/one-to-one/entity/User.ts
- test/functional/persistence/one-to-one/persistence-one-to-one.ts
- test/functional/query-builder/relational/with-one/query-builder-relational-set-one-to-one-inverse.ts
- test/functional/query-builder/relational/with-one/query-builder-relational-set-one-to-one.ts
Hi!
Before investing more time on a bugfix, do you think those specs are correct?
For relational databases, I want to add a `UNIQUE` constraint on the foreign key column in order to enforce `OneToOne` relation in both ways.
> Specs to show one-to-one relation integrity isn't respected

- src/driver/mysql/MysqlDriver.ts
- src/driver/postgres/PostgresDriver.ts
- src/driver/sqlserver/SqlServerDriver.ts
Fixes #1689 
This is the resolution to the connection drop-out issues for all drivers:
Postgres - Originated the issue. Fixed in this PR
MongoDB - `autoReconnect` flag is the way to go. TypeORM already defaults this to `true`.
MySQL - Similar issue to Postgres. The error handler is on the connection object ([see docs](https://github.com/mysqljs/mysql#error-handling)). Fixed locally.
sqlite - Nothing in [documentation](https://github.com/mapbox/node-sqlite3/wiki/API#new-sqlite3databasefilename-mode-callback). I imagine this doesn't apply due to the nature of the database.
sqljs - Not applicable.
mssql - Same issue as Postgres. Fixed by attaching an error handler to the pool.
websql - Not applicable.
As discussed in the issue, I couldn't see a way to forcefully drop a database connection as …
> Fixes to Postgres, MySQL and MSSQL drivers propagating unhandled errors and crashing the hosting application

- CHANGELOG.md
- docs/migrations.md
- docs/using-cli.md
- src/commands/MigrationCreateCommand.ts
- src/commands/MigrationGenerateCommand.ts
- src/commands/MigrationRevertCommand.ts
- src/commands/MigrationRunCommand.ts
* `migrations:create` becomes `migration:create`
* `migrations:generate` becomes `migration:generate`
* `migrations:revert` becomes `migration:revert`
**BUT** `migrations:run` stays `migrations:run`
fixed #1281
> cli: removed "s" from some migration commands

- docs/using-cli.md
CLI command is `migrations:create` (plural) not `migration:create` (singular)
> Update cli docs for create migration

- src/driver/mysql/MysqlDriver.ts
Check if there are any listeners attached to the database connection already. If not, add one.
This solves an event listener overflow issue as described in #1833 
I haven't figured out a way to write tests for this yet because the raw connection seems to be a protected property. Working on it, but opening a PR for feedback now.
> Fix #1833: Add only one error listener to MySQL connections

- src/driver/mysql/MysqlQueryRunner.ts
PR prevents to set PRIMARY KEY column as NULL in table creation.
[#1389](https://github.com/typeorm/typeorm/commit/9b59503f69ab7e1d90343f1a88b9d08d488e4b79) 
[CI error log](https://travis-ci.org/typeorm/typeorm/builds/322071205?utm_source=github_status&utm_medium=notification)
> fixed breaking caused by PR #1389

- README.md
- docs/supported-platforms.md
This adds the new example to the readme and the supported-platforms page.
> Add link to react-native-example to docs

- package.json
@pleerock One more try with timeout flags and color output. It's important that first run might be long (more than 30s) as the cache is generated then. All subsequent calls will be fast thought. In comparison running single test with `ts-node` takes around 1-2s vs 30s with tsc compiling everything.
> feat(test): Use ts-node with typechecking and timeout

- src/driver/types/ColumnTypes.ts
- test/functional/database-schema/column-types/postgres/column-types-postgres.ts
- test/functional/database-schema/column-types/postgres/entity/PostWithOptions.ts
There was no way to declare common column options for postgres range types.
> Column options for postgres range types

- src/decorator/options/ColumnWithWidthOptions.ts
`WithWidthColumnType` such as `tinyint` or `int` should have `zerofill` and `unsigned` options,  but currently it does not.
The code below cannot be compiled.
```
@Column('tinyint', { unsigned: true })
columnName?: number
```
> Add zerofill and unsigned options to ColumnWithWidthOptions

- src/driver/postgres/PostgresQueryRunner.ts
- test/github-issues/2067/entity/User.ts
- test/github-issues/2067/issue-2067.ts
Fixes #2067 
- Wrapped the code inside the Promise into a try-catch block
- Wrote a test that failed with a timeout in the previous code and now succeeds
> Issue #2067 - Fixed UnhandledPromiseRejectionWarning in PostgresQueryRunner

- src/driver/sqlite-abstract/AbstractSqliteDriver.ts
This PR addresses issue #1981 where boolean values could not be used to `find` entities in a repository using `cordova`. This is because boolean values are represented as numeric values.  
This PR maps the boolean values to their corresponding numerical representation before submitting a query.
> fix issue 1981

- README.md
Async/await have been standardized in ES2017 (aka ES8) not ES7
> Fix wrong ES version in docs for async/await

- docs/transactions.md
- src/decorator/options/TransactionOptions.ts
- src/decorator/transaction/Transaction.ts
- src/driver/mysql/MysqlQueryRunner.ts
- src/driver/oracle/OracleQueryRunner.ts
- src/driver/postgres/PostgresQueryRunner.ts
- src/driver/sqlite-abstract/AbstractSqliteQueryRunner.ts
- src/driver/sqlserver/SqlServerConnectionOptions.ts
- src/driver/sqlserver/SqlServerQueryRunner.ts
- src/driver/types/IsolationLevel.ts
- src/entity-manager/EntityManager.ts
- src/query-runner/QueryRunner.ts
- test/functional/transaction/database-specific-isolation/entity/Category.ts
- test/functional/transaction/database-specific-isolation/entity/Post.ts
- test/functional/transaction/database-specific-isolation/full-isolation-support.ts
- test/functional/transaction/database-specific-isolation/oracle-isolation.ts
- test/functional/transaction/database-specific-isolation/sqlite-isolation.ts
- test/functional/transaction/transaction-decorator/controller/PostController.ts
- test/functional/transaction/transaction-decorator/transaction-decorator.ts
In reference to #2185.
A few notes:
- There is an issue with isolation levels in *SQL Server* versions before 2014 as described [here](http://www.levibotelho.com/development/plugging-isolation-leaks-in-sql-server/) and I did not account for this in the implementation. The **TLDR** is that prior versions do not reset the isolation level when a connection returns to the pool (ie. all future transactions on a connection that explicitly set the isolation level in a previous transaction will use that isolation level and not the default)
- I didn't implement SQL Server's specific `SNAPSHOT` isolation, if that should be required (since the connection options state it is a valid isolation level) then I can see about implementing it
- For Sqlite databases, I couldn't figure out a way to detect if …
> feature: add ability to specify isolation level of transactions

- CHANGELOG.md
- docs/transactions.md
I realized my change to the `transactions.md` file were not actually committed in the original PR, this was due to a plugin I was using that auto-creates and formats the table of contents in markdown files, so I went ahead and added that change to this PR in addition to the changelog update.
> refactor: update changelog with isolation level feature

- test/github-issues/2259/issue-2259.ts
Demonstrates creation of incorrect create table syntax in postgres when using generated columns.
Refs: #2259
> Failing test for incorrect create table syntax

- src/driver/oracle/OracleConnectionCredentialsOptions.ts
- src/driver/oracle/OracleDriver.ts
Updated driver to accept Oracle connect string as specified in https://github.com/oracle/node-oracledb/blob/master/doc/api.md#-813-embedded-connection-strings since Oracle connections can also be made with TNS strings when connecting to a load-balanced service.
> Updated to accept Oracle connectString for TNS based Host resolution

- docs/connection.md
I find this much easier and more compatible with PaaS software. Heroku and Dokku, I believe the most popular, give DB add-ons a single URL environment variable. These URLs can change, too. So manually deconstructing the URL is a bad solution. But come to think of it, `new URL(process.env.DATABASE_URL)` but make parts of that easier. Anyhow, I think `url` should be documented.
> Mentions url attribute that can be used for connecting

- src/query-builder/UpdateQueryBuilder.ts
In InsertQueryBuilder the geospatial types are addressed with GeomFromText() function passed to MySQL/MariaDB so we replicated the same behaviour on UpdateQuerBuilder.
We faced this reported issue: https://github.com/typeorm/typeorm/issues/2329 and needed a quick fix to continue working.
> Fix update of geospatial type column with mysql driver in UpdateQueryBuilder.ts

- docker-compose.yml
- docs/decorator-reference.md
- docs/entities.md
- docs/indices.md
- src/decorator/columns/Column.ts
- src/decorator/options/ColumnOptions.ts
- src/decorator/options/IndexOptions.ts
- src/decorator/options/SpatialColumnOptions.ts
- src/driver/postgres/PostgresDriver.ts
- src/driver/postgres/PostgresQueryRunner.ts
- src/driver/types/ColumnTypes.ts
- src/entity-schema/EntitySchemaIndexOptions.ts
- src/metadata/ColumnMetadata.ts
- src/query-builder/InsertQueryBuilder.ts
- src/query-builder/QueryBuilder.ts
- src/query-builder/SelectQueryBuilder.ts
- src/query-builder/UpdateQueryBuilder.ts
- src/schema-builder/options/TableColumnOptions.ts
- src/schema-builder/table/TableColumn.ts
- src/schema-builder/util/TableUtils.ts
- test/functional/query-builder/order-by/entity/Post.ts
- test/functional/spatial/postgres/entity/Post.ts
- test/functional/spatial/postgres/spatial-postgres.ts
This includes support for both geometry and geography columns as well as GiST indices (used when passing the `spatial: true` option). Client representations use GeoJSON (existing MySQL and MS SQL drivers use WKT (well-known text)) for compatibility with geospatial libraries such as Turf, JSTS, etc.
Fixes #370
> Spatial support for PostgreSQL using PostGIS

- ISSUE_TEMPLATE.md
- README-zh_CN.md
- README.md
- docs/connection-options.md
- docs/entities.md
- docs/supported-platforms.md
- src/connection/ConnectionOptions.ts
- src/driver/DriverFactory.ts
- src/driver/expo/ExpoConnectionOptions.ts
- src/driver/expo/ExpoDriver.ts
- src/driver/expo/ExpoQueryRunner.ts
- src/driver/types/DatabaseType.ts
- src/error/MissingDriverError.ts
Add a driver to support the [Expo](https://expo.io/) platform. In particular it is using the [Expo SQLite API](https://docs.expo.io/versions/latest/sdk/sqlite.html) that ships with Expo.
A few things to note about this pull request:
- Expo apps still need to install `react-native-sqlite-storage` as a dependency. The issue is that the Expo packager still attempts to include this dependency (even though it doesn't need it) because of the `this.sqlite = require("react-native-sqlite-storage");` line in `src/driver/react-native/ReactNativeDriver.ts`. If someone knows how to make the Expo packager ignore this line, I'm all ears! Still, needing to install  `react-native-sqlite-storage` isn't such a big deal. No linking or ejecting of the Expo app is required.
- Expo has an odd way of handling …
> Expo driver

- src/platform/PlatformTools.ts
Webpack can not compile a bundle with sql.js.
`require(<expression>) `
doesn't work without some hints like
`require('/some-dir' + <expression>)`
> Fix Webpack compilation single bundle with sql.js (nodejs)

- docs/one-to-one-relations.md
If you don't assign name, you get this error:
```
UnhandledPromiseRejectionWarning: QueryFailedError: ER_NO_DEFAULT_FOR_FIELD: Field 'name' doesn't have a default value
```
> Assign name in one to one example

- docs/supported-platforms.md
- src/driver/nativescript/NativescriptConnectionOptions.ts
- src/driver/nativescript/NativescriptDriver.ts
Going into the future drivers should come from the userland
or other packages of @typeorm/driver-xxxx
But for now we need to unbreak the 0.2.x release cycle
and only NativeScript broke it
Signed-off-by: Arnav Gupta <arnav@codingblocks.com>
> unbreak release: externalise nativescript

- src/driver/postgres/PostgresQueryRunner.ts
Hi,
A quickfix for PostgreSQL databases running with tables composed of columns of type array+enum.
**Current query**:
```sql
ALTER TABLE "my_table" ALTER COLUMN "my_column" TYPE "my_table_my_column_enum" USING "my_column"::"text"::"my_table_my_column_enum"
```
**Valid query**:
```sql
ALTER TABLE "my_table" ALTER COLUMN "my_column" TYPE "my_table_my_column_enum"[] USING "my_column"::"text"::"my_table_my_column_enum"[]
```
In order to avoid **this error**:
>  invalid input value for enum my_table_my_column_enum: "{1,2}"
Where the column is decorated with:
```typescript
@Column({ name: 'my_column', type: 'enum', enum: MyEnum, array: true, nullable: true })
myColumn: MyEnum[];
```
Let me know if any extra modification is required :smile: 
Thanks for your work.
> fix(pgsql): alter type of array enum cols

- test/functional/observers/observe-count/observers-count-insert.ts
- test/functional/observers/observe-count/observers-count-remove.ts
- test/functional/observers/observe-count/observers-count-update.ts
- test/functional/observers/observe-many-and-count/observers-many-and-count-insert.ts
- test/functional/observers/observe-many-and-count/observers-many-and-count-remove.ts
- test/functional/observers/observe-many-and-count/observers-many-and-count-update.ts
- test/functional/observers/observe-many/observers-many-insert.ts
- test/functional/observers/observe-many/observers-many-remove.ts
- test/functional/observers/observe-many/observers-many-update.ts
- test/functional/observers/observe-one/observers-one-insert.ts
- test/functional/observers/observe-one/observers-one-remove.ts
- test/functional/observers/observe-one/observers-one-update.ts
- test/other-issues/sqlite-bulk-save/sqlite-bulk-save.ts
@pleerock @Kononnable It appears that only 20 tests are being run on the next branch build.
Take a look at the output of the vNext build vs master build.
vNext build: https://travis-ci.org/typeorm/typeorm/jobs/437460875
master build: https://travis-ci.org/typeorm/typeorm/jobs/437717744
It appears that some .only statements are causing a subset of the tests to run. In this PR I've removed those and you can see that more than 20 tests are now running:
https://travis-ci.org/csuich2/typeorm/jobs/437822569
> Removed .only from tests causing only 20 tests to run

- docs/select-query-builder.md
Closing parentheses were missing in the bracket example on select-query-builder.md.
Thus, I added following parentheses on the example.
> add missing parentheses in the bracket example

- src/driver/postgres/PostgresDriver.ts
- test/github-issues/2871/documentEnum.ts
- test/github-issues/2871/entity/Bar.ts
- test/github-issues/2871/enumTools.ts
- test/github-issues/2871/issue-2871.ts
Hi,
Closes to this issue: https://github.com/typeorm/typeorm/issues/2871, it's a quickfix to handle the case when an array of enum is empty within PostgreSQL database.
Current result:
```typescript
const documents: DocumentEnum[] = [];
const barSaved = await repository.save({documents}) as Bar;
const barFromDb = await repository.findOne(barSaved.barId) as Bar;
expect(barFromDb.documents).to.eql(documents);
// AssertionError: expected [ '' ] to deeply equal []
```
But, the expected result is that `barFromDb.documents` to be equal `documents`.
Let me know if I can do anything to or if you have any questions.
Many thanks for your work on this amazing project 😃
> fix(pgsql): empty array enum cols

- DEVELOPER.md
- package.json
I figured I'd throw this out there since it has been very useful for me as I've started to contribute to this project.
```tsc -w``` has helped avoid long compilations
```npm run test-no-compile``` skips the ```tsc``` step when I'm using ```tsc -w```
I'm happy to chat about these if you'd like and my feelings won't be hurt if you don't want to accept them, but I figured I'd share since they have been very helpful to me.
> Added info & package.json script useful for devs

- src/connection/ConnectionOptionsReader.ts
- test/functional/connection-options-reader/configs/test-path-config.js
- test/functional/connection-options-reader/connection-options-reader.ts
Support specification of a full file path with extension using the `-f` option in the cli.
Omitting a file extension will retain the current behavior of looping over possible file extensions for support.
I also updated `normalizeConnectionOptions` to use `baseDirectory` since this seemed more correct, but please let me know if that's not desirable.
Resolves #2339
> Support specifying full config file path in cli using -f option

- src/query-builder/JoinAttribute.ts
#2381 
I don't like the way I implemented it but I don't have a concept how to do it better. Decorators won't be of help here because they work when object is being created. Using generic class just for caching would require changing how it is used  - we can't have a getter to property of type Cache<T> which returns type T, so instead of `obj.relation` we would have to use `obj.relation.value` or something similar.
I hope community will come up with some nicer solution. On problem reproduction repo https://github.com/stelltec/typeorm_testcase1 cached version works ~15x faster with 10240 rows returned.
> Performance of hydration

- src/connection/options-reader/ConnectionOptionsEnvReader.ts
This makes it possible just to provide `TYPEORM_URL`, instead of having to provide also `TYPEORM_CONNECTION`. Standard database URL contains already database connection type in protocol section (e.g. `postgres://hostname:5432/database`).
> Parse connection type from TYPEORM_URL

- src/connection/Connection.ts
- src/driver/mongodb/MongoDriver.ts
- src/driver/postgres/PostgresDriver.ts
- src/entity-manager/EntityManager.ts
- src/error/QueryFailedError.ts
- src/query-builder/Alias.ts
- src/query-builder/JoinAttribute.ts
- src/query-builder/SelectQueryBuilder.ts
- src/query-builder/relation-count/RelationCountAttribute.ts
- src/query-builder/relation-id/RelationIdAttribute.ts
- src/repository/BaseEntity.ts
- src/util/ObjectUtils.ts
fix for https://github.com/typeorm/typeorm/issues/2502
I created a separate function ```ObjectUtils.assign``` to use instead of ```Object.assign``` that will only copy the properties returned by ```Object.getOwnPropertyNames```.
> fix #2502- TypeError: One of the sources for assign has an enumerable key on the prototype chain 

- docs/entities.md
This now matches the example in http://typeorm.io/#/tree-entities (that one doesn't show `@TreeLevelColumn`, despite importing it, but I'm not sure if that's intentional or not).
> Fix typo in closure table section of entities.md

- src/util/OrmUtils.ts
- test/github-issues/2557/entity/dummy.ts
- test/github-issues/2557/issue-2557.ts
- test/github-issues/2557/transformer.ts
In #2557 and maybe also in #2280, luxon DateTime prototype is lost during `save()` before applying the transformer. luxon then sees the DateTime as invalid.
I've added a test with a custom wrapping object to avoid a dependency on luxon only for tests.
> Fix deepMerge to keep object protoype

- src/schema-builder/table/Table.ts
With https://github.com/typeorm/typeorm/issues/1686#issuecomment-382204047 at some point, you get 3 indices on uuid : `FK_`, `REL_` and `IDX_`. `IDX_` is a duplicate of `REL_` and should be removed.
When the schema builder tries to remove `IDX_`, it resets `tableColumn.isUnique` to false even if the `REL_` index keeps it unique. The column is then seen as changed and thus foreign key is dropped and recreated and `IDX_` is also recreated.
I've changed `Table.removeIndex()` to check for other unique indices.
I'm not sure how to add tests.
And `Table.removeUniqueConstraint()` should maybe be changed the same way for other dbms.
> Fix duplicate unique index removal in mysql

- src/metadata/EntityMetadata.ts
- test/functional/table-inheritance/single-table/database-option-inherited/database-option-inherited.ts
- test/functional/table-inheritance/single-table/database-option-inherited/entity/Employee.ts
- test/functional/table-inheritance/single-table/database-option-inherited/entity/Person.ts
Without this children use the default database for the connection which may be undefined or not the same as the one on the parent entity.
> Make children inherit database option from parent

- package.json
Use  rimraf module to delete build directory before each build.
> Clean directories before compile

- src/query-builder/InsertQueryBuilder.ts
- src/query-builder/QueryExpressionMap.ts
- test/github-issues/1780/entity/User.ts
- test/github-issues/1780/issue-1780.ts
Hello, starting from issue #1780 and its relative PR #1793 I've updated the code of #1793 which now is based on the current master.
This solves #1780, support is provided only for MySql and Postgres at the moment.
> Add support to Mysql / Postgres for duplicate entry update or ignore

- src/persistence/SubjectChangedColumnsComputer.ts
Fix misspelled column type.
This causes the following problem: if you have a `simple-array` column, when doing a save on the entity, because the diff algorithm has this column type name misspelled, the column will be always marked for update, even though the value didn't change.
> Fix misspelled column type

- docs/connection-options.md
- src/driver/mysql/MysqlConnectionOptions.ts
- src/driver/mysql/MysqlDriver.ts
Reporting: Bug
Hi there,
👍 for TypeORM - I really like working with it.
On AWS when connecting to Aurora Serverless if the instance is asleep it can take approximately 30 seconds for the TCP connection to be accepted. That results in the following handshake error, you can see the Timeout is being reported as 10,000ms. I have set connectionTimeout to 120,000ms on the connection.
```
Error: Handshake inactivity timeout
at Handshake.<anonymous> (/var/task/src/sqs.js:244:837498)
at emitNone (events.js:106:13)
at Handshake.emit (events.js:208:7)
at Handshake.Sequence._onTimeout (/var/task/src/sqs.js:19:140794)
at Timer._onTimeout (/var/task/src/sqs.js:244:994425)
at ontimeout (timers.js:482:11)
at tryOnTimeout (timers.js:317:5)
at Timer.listOnTimeout (timers.js:277:5)
--------------------
at …
```
> Allow passing the acquireTimeout connection option to MySQL

- src/migration/MigrationExecutor.ts
UNIX timestamps are measured in seconds, while JS timestamps are in milliseconds. So a UNIX timestamp = JS timestamp / 1000.
> Fix error message for migration class naming

- docs/migrations.md
I copy and pasted the code and my linter picked up the missing semicolon ;)
> Missing semicolon on migrations.md

- src/driver/postgres/PostgresQueryRunner.ts
- src/driver/sqlserver/SqlServerQueryRunner.ts
- src/query-builder/DeleteQueryBuilder.ts
- src/query-builder/result/DeleteResult.ts
- test/github-issues/2499/entity/Foo.ts
- test/github-issues/2499/issue-2499.ts
Hi, this is related with #2499 
Here we additionally receive new variable `affected` which is [`rowCount`](https://github.com/brianc/node-postgres/blob/master/lib/result.js#L46-L49) from `pg`.
UPD:
Number of affected rows returns for `mysql`, `mariadb`, `mssql`, `postgres`
I was unable to run Oracle locally, so it is not covered. `sqlite` & `sqljs` seems requires additional queries to getting such information. Mongodb seems to have an internal bug. It is always returns `{ n: 0; ok: 1 }` for me and this is goes not from the nodejs `mongo-core` package, but from db itself, so I think db is bugged. at least for node.js. Mongo console operations works as expected.
Also I limited the launch of tests only for covered databases.
> Return number of affected rows on delete

- test/github-issues/2800/issue-2800.ts
The fix for #2800 includes a new test but it uses `it.only()` to run the test which makes mocha skip the rest of them.
> Run all tests, not just the one for #2800

- docs/connection-options.md
The correct property should be pool.evictionRunIntervalMillis instead of pool.victionRunIntervalMillis
> Fix incorrect property name in documentation

- src/cache/RedisQueryResultCache.ts
On the next branch, the redis key doesn't have an expiry time.
I found this [PR](https://github.com/typeorm/typeorm/pull/2507) for `master`. But no information about why this was not done on `next`.
> feat: add a ttl to the redis key

- src/driver/postgres/PostgresConnectionCredentialsOptions.ts
Reference to https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/pg/index.d.ts#L35
> More accurate type for Postgres ssl parameters

- src/repository/Repository.ts
When saving a new entity with `repository.save(fields)`, the current type definition fails to return to me the right fields types for the generated columns, for example:
```typescript
@Entity()
export default class User {
@PrimaryGeneratedColumn('uuid') id: string
@Column() name: string
@Column({ nullable: true }) address?: string
}
// ...
const user = { name: 'John Doe', address: 'Somewhere' }
const createdUser = await this.repository.save(user)
console.log(createdUser.name) // okay 
console.log(createdUser.address) // okay
console.log(createdUser.id) // compilation error: Property 'id' does not exist on type ...
```
This seems to only make sense when `reload: false` is sent, which is not the case. 
This little change fixes that, while overriding the optional type when the values are …
> Improve Repository.save() return type

- docs/connection-options.md
Fixes a small typo in the migration command on the [connection-options](http://typeorm.io/#/connection-options) page.
> [Docs] Fix typo in connection-options

- src/platform/PlatformTools.ts
This happens in a production bundle `Cannot find module '/var/task/node_modules/app-root-path'` because Webpack doesn't include `app-root-path` in the bundle.
I'm not quite sure why this module is being lazy loaded, but if it's meant to be lazy loaded then it should use dynamic imports, which I'm happy to change to if that's preferred.
> Fix app-root-path import not working with webpack

- docs/connection-options.md
- src/driver/DriverUtils.ts
Based on discussion in https://github.com/typeorm/typeorm/issues/3159, it would be desirable to allow users to override parameters set in *url* connection option (only in mysql/mariadb, postgres, mssql and mongodb).
The current implementation prioritises `url` over the other parameters.
For example...
```
const options = {
url: 'postgres://localhost:5432',
username: 'myuser',
password: 'mypass',
...
};```
...would get initial options from url, and then set username and password as defined in options.
> Change so that parameters from "url" connection option can be overridden by specific connection options

- src/metadata/ColumnMetadata.ts
- src/metadata/RelationMetadata.ts
- src/query-builder/InsertQueryBuilder.ts
- src/query-builder/QueryExpressionMap.ts
- test/github-issues/3047/entity/User.ts
- test/github-issues/3047/issue-3047.ts
In Mysql / Postgres add support to update record during INSERT on conflict / duplicate key using current values, implements, fixes #3047
> Add support to use current values in insert Mysql/Postgres

- src/query-builder/SelectQueryBuilder.ts
@pleerock  check #3179
This enables queries which compute select values to work properly.
In my case I have the following query generated:
```sql
SELECT
DISTINCT "distinctAlias"."event_id" AS "ids_event_id",
"distinctAlias".event_applications
FROM (
SELECT
"event"."id" AS "event_id",
"event"."createdAt" AS "event_createdAt",
"event"."updatedAt" AS "event_updatedAt",
"event"."label" AS "event_label",
"event"."description" AS "event_description",
"event"."capacity" AS "event_capacity",
"event"."credits" AS "event_credits",
"event"."organiserId" AS "event_organiserId",
"event"."processId" AS "event_processId",
COUNT(DISTINCT ("applications"."id")) AS "event_applications"
FROM
"event" "event"
LEFT JOIN "application" "applications" ON "applications"."eventId" = "event"."id"
WHERE
event. …
```
> fix: do not clear group by in subquery if paginating

- .travis.yml
- src/query-builder/InsertQueryBuilder.ts
- test/functional/query-builder/insert-on-conflict/query-builder-insert-on-conflict.ts
Sqlite `ON CONFLICT` clause is supported since `sqlite` `3.24.0`. This PR adds a flag to enable explicit support for it, to avoid breaking changes, and preserves the current behavior otherwise.
It might be necessary to build `sqlite3` from source since precompiled binaries from npm apparently are not build with a recent enough `sqlite` lib.
Tests were added for the driver option and `ON CONFLICT` functionality.
> Add flag to enable ON CONFLICT support for Sqlite.

- src/query-builder/SelectQueryBuilder.ts
This enables queries which compute select values to work properly.
In my case I have the following query generated:
```sql
SELECT
DISTINCT "distinctAlias"."event_id" AS "ids_event_id",
"distinctAlias".event_applications
FROM (
SELECT
"event"."id" AS "event_id",
"event"."createdAt" AS "event_createdAt",
"event"."updatedAt" AS "event_updatedAt",
"event"."label" AS "event_label",
"event"."description" AS "event_description",
"event"."capacity" AS "event_capacity",
"event"."credits" AS "event_credits",
"event"."organiserId" AS "event_organiserId",
"event"."processId" AS "event_processId",
COUNT(DISTINCT ("applications"."id")) AS "event_applications"
FROM
"event" "event"
LEFT JOIN "application" "applications" ON "applications"."eventId" = "event"."id"
WHERE
event. "processId" = …
```
> fix: do not clear group by on subquery

- src/subscriber/Broadcaster.ts
- src/subscriber/event/InsertEvent.ts
- src/subscriber/event/RemoveEvent.ts
- src/subscriber/event/UpdateEvent.ts
When creating a general subscriber, if prototype of an inserted object is not set, it is impossible to get metadata. Typeorm has this information from used repository, but doesn't pass it here. This pull request just passed down this information.
> Add metadata to subscriber events

- .travis.yml
- package.json
- src/driver/DriverUtils.ts
- src/metadata/EmbeddedMetadata.ts
- test/github-issues/2965/entity/note.ts
- test/github-issues/2965/entity/person.ts
- test/github-issues/2965/index.ts
As far as I see, `lint-staged` specified in package.json doesn't run (there is no pre-commit hook that triggers it), so it makes sense to add an additional CI for linting
> Add linting ci step. Fix current linting issues

- src/driver/postgres/PostgresDriver.ts
As suggested by @mattb-prg. Hopefully fixes #2210
> Fix Postgres synchronisation unnecessarily dropping "float" columns

- src/driver/mysql/MysqlQueryRunner.ts
- src/driver/oracle/OracleQueryRunner.ts
- src/driver/postgres/PostgresQueryRunner.ts
- src/driver/sqlserver/SqlServerQueryRunner.ts
Postgres had two spaces before columns.
MySQL, Oracle, and SQL Server had no space between the table and columns.
> Made CREATE INDEX SQL consistent across dialects

- ormconfig.json.dist
- Update credentials for `mariadb`
- Disable `mssql` until test issues fixed
- Partially fix one of issue in https://github.com/typeorm/typeorm/issues/3169
> chore(config): sync ormconfig.json.dist with ormconfig.travis.json

- docs/sequelize-migration.md
- Added few links to other part of codumentation in sequelize migration part. 
- Also mentioned active record pattern and repository api so I hope we can close https://github.com/typeorm/typeorm/issues/2066
> doc(sequelize): Add few links to other docs and small updates

- docs/migrations.md
`ts-node ./node_modules/.bin/typeorm migration:run` does not work on windows
`ts-node ./node_modules/typeorm/cli.js migration:run` works on windows and on linux
> ts-node migration example does not work on windows

- src/decorator/columns/Column.ts
- src/decorator/columns/PrimaryColumn.ts
- src/decorator/options/ColumnOptions.ts
- test/github-issues/2364/entity/dummy.ts
- test/github-issues/2364/entity/dummy2.ts
- test/github-issues/2364/issue-2364.ts
close #2364 
Allows to use `@Column` and `@PrimaryColumn` decorators to create primary columns with generated values.
> fix(column decorator): create generation strategy on generated columns

- docs/using-ormconfig.md
- src/connection/options-reader/ConnectionOptionsEnvReader.ts
Add a new variable called `TYPEORM_MIGRATIONS_TABLE_NAME` as discussed here https://github.com/typeorm/typeorm/issues/3249
PR does not contain tests for this change as there are no tests for the other env variables
> Add env variable for the migrationsTableName conn option

- src/driver/mongodb/MongoConnectionOptions.ts
- src/driver/mongodb/MongoDriver.ts
In mongodb driver `passed` options take precedence over connection string option.
Thats reason why our users have problems with connect to mongo using `url` property like in https://github.com/typeorm/typeorm/issues/3347
- This change will check all valid mongo client options and pass only exists one from `MongoConnectionOptions`.
- Options updated according to http://mongodb.github.io/node-mongodb-native/3.1/api/MongoClient.htm
Do not see any way how to test so if you have any idea give me a kick. Tested locally with atlas cluster.
> fix(mongodb): do not pass false undefined options to mongo client

- src/error/EntityColumnNotFound.ts
- src/error/UpdateValuesMissingError.ts
- src/query-builder/UpdateQueryBuilder.ts
- test/functional/query-builder/update/query-builder-update.ts
- handle emptiness and wrong properties in update query builder
- fix https://github.com/typeorm/typeorm/issues/2849
> fix(query builder): Throw error on missing or unknown properties

- src/cache/QueryResultCacheFactory.ts
- src/cache/RedisQueryResultCache.ts
- src/connection/BaseConnectionOptions.ts
- src/platform/PlatformTools.ts
As a continuation to:
https://github.com/typeorm/typeorm/pull/3289
and my comment about Ioredis cluster object I submit the following tweaks which allow to initialize a Ioredis cluster object as a caching option.
https://github.com/luin/ioredis/blob/master/API.md#Cluster
> Enchancement - Add support for ioredis Cluster object initialization

- src/commands/InitCommand.ts
The version of sqlite3 (3.1.10) referenced by the cli init command is no longer available online for download during installation.  
That is, running 
```
typeorm init --name ormtest --database sqlite
cd ormtest
npm install
```
results in the following error: 
```
node-pre-gyp ERR! Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.13/node-v64-win32-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for sqlite3@3.1.13 and node@10.15.0 (node-v64 ABI) (falling back to source compile with node-gyp)
node-pre-gyp ERR! Tried to download(undefined): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.13/node-v64-win32-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for sqlite3@3.1.13 and node@10.15.0 (node-v64 ABI) (falling back to source …
```
> Bumped sqlite version in InitCommand to resolve cli init bug. 

- src/query-builder/QueryBuilder.ts
- test/functional/repository/find-methods/repostiory-find-methods.ts
Trying to use `in` operator in `findByIds` method for single primary key entities.
```js
await userRepository.findByIds([1, 2, 4]);
```
Before:
```sql
SELECT "User"."id" AS "User_id", "User"."firstName" AS "User_firstName", "User"."secondName" AS "User_secondName"
FROM "user" "User"
WHERE (("User"."id" = $1) OR ("User"."id" = $2) OR ("User"."id" = $3))
-- PARAMETERS: [1,2,4]
```
After:
```sql
SELECT "User"."id" AS "User_id", "User"."firstName" AS "User_firstName", "User"."secondName" AS "User_secondName"
FROM "user" "User"
WHERE ("User"."id" IN ($1, $2, $3))
-- PARAMETERS: [1,2,4]
```
> simplifying findByIds for single primary key entities

- CHANGELOG.md
- src/query-builder/QueryBuilder.ts
- src/query-builder/SelectQueryBuilder.ts
- test/github-issues/2103/entity/Complex.ts
- test/github-issues/2103/entity/Simple.ts
- test/github-issues/2103/issue-2103.ts
respecting logical operators precedence in `whereInIds` (using brackets for multiple `OR` operators)
> fixing query builder regression #2103

- src/driver/DriverUtils.ts
Fix DriverUtils.buildDriverOptions static method to actually assign TYPEORM_URL originated parameters. There has been couple of past PR's for this, so now it's better to make it simpler with only one way to get the parameters.
The new logic assigns parameters by default from the options values, and secondly from parsed TYPEORM_URL originated parameters. Finally the parsed parameters are assigned on top of options.
> Fix DriverUtils.buildDriverOptions

- docs/caching.md
This is a continuation to:
https://github.com/typeorm/typeorm/pull/3364
The Author made an excellent contribution but forgot to update the docs.
This PR contains the changes to the caching docs and tells the users how they can use TypeORM with IORedis's cluster mode functionality.
For reference: This is how a cluster can be initialized: https://github.com/luin/ioredis#cluster
> Enhancement: update caching docs for type IORedis Cluster

- src/query-builder/InsertQueryBuilder.ts
Not tested, but looks like it should be `instanceof AbstractSqliteDriver` (not only `SqliteDriver`)
> instanceof SqliteDriver -> instanceof AbstractSqliteDriver

- docs/active-record-data-mapper.md
My guess is that it was accidentally copied over from the Active Record example.
> Remove an unused import in the Data Mapper example

- CHANGELOG.md
- src/entity-manager/EntityManager.ts
- test/functional/repository/decrement/entity/UserWithEmbededEntity.ts
- test/functional/repository/decrement/repository-decrement.ts
- test/functional/repository/increment/entity/UserWithEmbededEntity.ts
- test/functional/repository/increment/repository-increment.ts
**Root of problem:**
Current implementation of increment/decrement method for embedded property define values to update like this:
```typescript
// ...
.set({
"embedded.property": () => ...
})
// ...
```
But update query builder do not support define key as string with "dot notation path".
**Solution:**
Convert:
```typescript
.set({
"embedded.property": () => ...
})
```
to: 
```typescript
.set({
embedded: {
property: () => ...
}
})
```
*Note: Sure we can add support of "dot notation path" into `set()` method but right now `set()` method accept strongly typed argument and I think it is better keep this functionality and just update increment/decrement function as it is presented in this PR.*
Fixes https://github.com/typeorm/typeorm/issues/3182
> fix(3182): fixed increment/decrement values of embeded entity

- CHANGELOG.md
- src/persistence/SubjectExecutor.ts
- test/functional/mongodb/basic/object-id/entity/PostWithUnderscoreId.ts
- test/functional/mongodb/basic/object-id/mongodb-object-id.ts
We are deleting `_id` property from entity to avoid duplication of object id columns. I did not realize case when `_id` is possible property name. Now we check if property name is not same as "column" name in db.
Fixed #3517
> fix(3517): fixed undefined object id field in case property name is _id

- docs/repository-api.md
The documentation for `findAndCount` referenced the pagination settings as `from` and `take`, but they should be `skip` and `take` instead.
> Fix incorrect pagination argument in documentation

- docs/connection-api.md
Fixes a few links in the **connection-api** docs to point towards more context appropriate pages. 
* "Learn more about Repositories" should navigate to `working-with-repository.md`. Currently links to `working-with-entity-manager.md`.
* "Learn more about custom repositories" should navigate to `custom-repository.md`. Currently also links to `working-with-entity-manager.md`.
> Update links in connection-api docs

- CHANGELOG.md
- docs/connection-options.md
- src/driver/sqljs/SqljsConnectionOptions.ts
- src/driver/sqljs/SqljsDriver.ts
- src/entity-manager/SqljsEntityManager.ts
- test/functional/sqljs/load.ts
- test/functional/sqljs/save.ts
For issue #3554.
I've added an option `useLocalforage` to the SqljsConnectionOptions to switch between the usage of the synchronous local storage (which could freeze the browser, when having lot's of data) and the async. indexedDB for the sql.js driver.
With using this flag, the localforage node module is needed and the localforage.js needs to be added to the page.
Having it enabled, the save & load operations are now asynchron, which means, those operations are not blocking the main thread of the browser anymore, which gives you the opportunity the display smooth loading screens. 
I've also created a small pre-realese, which allows us to use this version of typeorm in current angular projects: https://github.com/ApinautenGmbH/typeorm/releases
> Add localforage as alternative to local storage for sqljs driver

- src/find-options/FindOneOptions.ts
according to docs (https://github.com/typeorm/typeorm/blob/0.2.13/docs/find-options.md) this type should also accept an array of find options
array of options was previously covered by `ObjectLiteral` type, should it be removed then?
#3644
> update FindOneOptions["where"] type

- src/driver/mysql/MysqlQueryRunner.ts
- test/github-issues/3588/entity/Session.ts
- test/github-issues/3588/entity/mysql.ts
- test/github-issues/3588/issue-3588.ts
Changes to make syncing onUpdate work also on mysql 8.0.
Closes #3588
> Fixes #3588 - Migration:generate issue with onUpdate using mysql 8.0

- CHANGELOG.md
- src/query-builder/DeleteQueryBuilder.ts
- test/functional/query-builder/delete/query-builder-delete.ts
Currently delete queries return wrongly initialized DeleteResult object. The logic uses connection name to check type of driver that is not correct for production environment.
> Fix invalid delete result

- src/find-options/FindOptionsUtils.ts
```
someRepository.findOne("anyId", {
loadEagerRelations: false
});
```
in case of the above code, FindOptionsUtils.isFindOneOptions returns false and we need to check one more option(typeof loadEagerRelations).
please check this out. :D
> fix a bug that loadEagerRelations not working

- CHANGELOG.md
- src/decorator/options/ColumnOptions.ts
- src/driver/postgres/PostgresDriver.ts
- src/metadata/ColumnMetadata.ts
- src/schema-builder/options/TableColumnOptions.ts
- src/schema-builder/table/TableColumn.ts
- src/schema-builder/util/TableUtils.ts
- test/github-issues/3587/entity/EquipmentModel.ts
- test/github-issues/3587/issue-3587.ts
Postgres store enum type as string and we support now numeric TS enum so we have to compare array of possible values and values in DB schema as strings.
Fixes https://github.com/typeorm/typeorm/issues/3587
> fix(postgres): Fixed migration issue with postgres numeric enum type

- CHANGELOG.md
- src/decorator/columns/Column.ts
- src/driver/mysql/MysqlDriver.ts
- src/driver/mysql/MysqlQueryRunner.ts
- src/driver/postgres/PostgresDriver.ts
- src/driver/postgres/PostgresQueryRunner.ts
- src/driver/sqlite-abstract/AbstractSqliteDriver.ts
- src/driver/sqlite-abstract/AbstractSqliteQueryRunner.ts
- src/driver/sqlserver/SqlServerDriver.ts
- src/driver/sqlserver/SqlServerQueryRunner.ts
- src/driver/types/ColumnTypes.ts
- src/persistence/SubjectChangedColumnsComputer.ts
- src/util/DateUtils.ts
- test/functional/database-schema/column-types/mssql/column-types-mssql.ts
- test/functional/database-schema/column-types/mssql/entity/Post.ts
- test/functional/database-schema/column-types/mssql/enum/FruitEnum.ts
- test/functional/database-schema/column-types/mysql/column-types-mysql.ts
- test/functional/database-schema/column-types/mysql/entity/Post.ts
- test/functional/database-schema/column-types/postgres-enum/entity/Post.ts
- test/functional/database-schema/column-types/postgres-enum/postgres-enum.ts
- test/functional/database-schema/column-types/postgres/column-types-postgres.ts
- test/functional/database-schema/column-types/postgres/entity/Post.ts
- test/functional/database-schema/column-types/sqlite/column-types-sqlite.ts
- test/functional/database-schema/column-types/sqlite/entity/Post.ts
- test/functional/database-schema/column-types/sqlite/enum/FruitEnum.ts
- test/functional/database-schema/simple-enums-array/entity/EnumArrayEntity.ts
- test/functional/database-schema/simple-enums-array/enums-array.ts
- test/functional/database-schema/simple-enums/entity/SimpleEnumEntity.ts
- test/functional/database-schema/simple-enums/enums.ts
I have added the `simple-enum` column type discussed in #1414. It works like this:
- For MySQL, MariaDB and Postgres, the native `ENUM` type is used
- For SQLite and SQL Server, a `CHECK()` constraint is used, like so:
```
colname CHECK (colname in ('A','B','C')) NOT NULL DEFAULT ('A')
```
The CHECK is also reverse engineered back into an enum when code is being generated from a DB schema
- For Oracle, I found that enum is currently not supported in TypeORM. Since Oracle does have a native `ENUM` type, I believe `simple-enum` should be based on it. I have not added `simple-enum` for Oracle.
> Added simple-enum column type

- gulpfile.ts
- package-lock.json
- package.json
While doing an `npm audit` to verify that [this Issue](https://github.com/typeorm/typeorm/issues/3695) was resolved, I noticed that the package [tslint-stylish](https://github.com/adamfitzpatrick/tslint-stylish) was the only remaining dependency linking to the dangerous version of `minimatch`. It was also listed by its developer as deprecated in favor of one now included by @Palantir in the `tslint` core package.
To remove that last security issue from the codebase (even if it was only in dev), this PR updates the `tslint` version used by typeorm to latest, removes the dependency on `tslint-stylish`, and instead uses the `tslint` native stylish formatter for lint output.
> Migrate TSLint formatter to included stylish formatter

- src/connection/Connection.ts
QueryRunner in Connection.dropDatabase() must be released similarly to Connection.query() method.
```
try {
...
} finally {
queryRunner.release()
}
```
I had a situation where no more queries could be done because I had 10 clients leaked in the query pool.
In my case dropDatabase() method failed because of a deadlock in postgres, this caused no release() to be called. Postgres Pool has a default of max 10 connections. When all 10 connections were failed dropDatabase calls (not released), no more queries could be performed and hanged forever.
> Connection.dropDatabase() leaks an unreleased db client

- docs/multiple-connections.md
Example code that demonstrates querying master instead of a replica for select queries will leak connections.
This was biting us in production and took some time to troubleshoot because we weren't actually getting good errors (on my todolist as to why good errors weren't being thrown in the case, maybe I'll submit another PR when I figure that out), but I think the example code should not be leaking connections and we should mention that the query runner needs to be released manually.
Cheers!
> Change master query docs to not leak connections

- src/driver/DriverUtils.ts
- test/github-issues/3737/issue-3737.ts
Fixes #3716.
Does it require a test?
> Decode the user info of a database URI

- src/driver/postgres/PostgresQueryRunner.ts
When fetching columns metadata on the `loadTables()` method, quotes are missing before casting to postgres type "regtype".
More detail available in the linked issue.
> Fix #3792: Crash on `schema:log` with PostgreSQL

- src/util/OrmUtils.ts
If you try to save a JSONB column with a null value in an object,
you get this error:
TypeError: Cannot read property 'equals' of null
> Fix compare2Objects handling of null.

- CHANGELOG.md
- src/driver/postgres/PostgresQueryRunner.ts
- test/github-issues/3536/entity/Roles.ts
- test/github-issues/3536/issue-3536.ts
Using uppercase letters in enum names seems to be problem in postgres. This PR convert whole enum name into lowercase (not only column name part).
Fixes https://github.com/typeorm/typeorm/issues/3536 https://github.com/typeorm/typeorm/issues/2724
Close https://github.com/typeorm/typeorm/pull/1978 in favour of this PR with tests for inactivity of original PR author.
> fix(3536): fix sync schema issue with postgres enum in case capital letters in entity name

- README.md
v0.2.15 requires to use the version 3.3 or greater of the TypeScript compiler. This PR updates the documentation with this new version.
Related issue: #3823
> [README.md] Update the TS compiler version to 3.3 or greater

- docs/connection.md
Just adding a missing import on documentation that turns it confusing :slightly_smiling_face:
> Improving documentation for connection

- docs/migrations.md
Adds necessary includes (`TableIndex`, `TableColumn` and `TableForeignKey` ) to example migration.
> Documentation update: add extra `includes` to migration example

- src/metadata/EntityMetadata.ts
- test/github-issues/1772/entity/Post.ts
- test/github-issues/1772/issue-1772.ts
I basically copied the code submitted by @pepakriz  into a new branch created against `next`, only I used JS's `Reflect` instead of `ObjectInstantiator`).
Original PR: https://github.com/typeorm/typeorm/pull/1773
> Skip constructor when entity is loaded from database

- docs/repository-api.md
- Updated Repository API docs
Updated description and examples to reflect that save() and remove() return the entities passed in as arguments.
> [Docs] Clarification for save/remove in Repository API

- CHANGELOG.md
- docs/find-options.md
- src/find-options/FindOneOptions.ts
- src/find-options/FindOptionsUtils.ts
- test/functional/repository/find-options-locking/entity/PostWithUpdateDate.ts
- test/functional/repository/find-options-locking/entity/PostWithVersion.ts
- test/functional/repository/find-options-locking/entity/PostWithVersionAndUpdatedDate.ts
- test/functional/repository/find-options-locking/entity/PostWithoutVersionAndUpdateDate.ts
- test/functional/repository/find-options-locking/find-options-locking.ts
`lock` is an object which can be defined as:
```ts
{ mode: "optimistic", version: number|Date }
```
or
```ts
{ mode: "pessimistic_read"|"pessimistic_write" }
```
for example:
```typescript
userRepository.findOne(1, {
lock: { mode: "optimistic", version: 1 }
})
```
> added `lock` option in FindOptions;

- src/connection/BaseConnectionOptions.ts
- src/connection/Connection.ts
- src/entity-factory/DefaultEntityFactory.ts
- src/entity-factory/EntityFactoryInterface.ts
- src/metadata/EntityMetadata.ts
- test/functional/entity-factory/custom-entity-factory.ts
- test/functional/entity-factory/custom-proxifying-entity-factory.ts
- test/functional/entity-factory/default-entity-factory.ts
- test/functional/entity-factory/entity/Post.ts
- test/utils/test-utils.ts
Following PR #3845 
1) Refactored the code to use an EntityFactory to create the entities
2) Added optional "entityFactory" configuration option: this gives full flexibility to end-user to fine-tune how the entities are created by the ORM (for example he might want to stay with previous behaviour when entities are creating by calling the constructor). Default behaviour stays the one implemented in PR #3845 (skipping constructor).
Also using a custom entity factory, end-user can now use ES6 Proxy API to profile the entities created by the ORM.
See examples implemented as tests in the PR.
> Implemented entity factory to create entities

- CHANGELOG.md
- src/decorator/options/RelationOptions.ts
- src/driver/postgres/PostgresQueryRunner.ts
- src/entity-schema/EntitySchemaRelationOptions.ts
- src/entity-schema/EntitySchemaTransformer.ts
- src/metadata-builder/RelationJoinColumnBuilder.ts
- src/metadata/ForeignKeyMetadata.ts
- src/metadata/RelationMetadata.ts
- src/metadata/types/DeferrableType.ts
- src/schema-builder/options/TableForeignKeyOptions.ts
- src/schema-builder/table/TableForeignKey.ts
- test/functional/deferrable/deferrable.ts
- test/functional/deferrable/entity/Company.ts
- test/functional/deferrable/entity/Office.ts
- test/functional/deferrable/entity/User.ts
Related feature request: #2191
I've added deferrable options for foreign keys on Postgres, see `DEFERRABLE` on [CREATE TABLE](https://www.postgresql.org/docs/11/sql-createtable.html), or on [SET CONSTRAINTS](https://www.postgresql.org/docs/11/sql-set-constraints.html). Based on that documentation the following declarations are equivalent (at final of column or constraint definition):
- "" == "`NOT DEFERRABLE`"  (default)
- "`DEFERRABLE`" == "`DEFERRABLE INITIALLY IMMEDIATE`"
- "`DEFERRABLE INITIALLY DEFERRED`"
Thus, with a single property on foreign column options all three cases are covered (undefined means "`NOT DEFERRABLE`", default in postgres):
- `deferrable`: "`INITIALLY IMMEDIATE`" | "`INITIALLY DEFERRED`"
This configuration could be extensible to …
> Deferrable options for foreign keys (postgres)

- CHANGELOG.md
- src/driver/postgres/PostgresQueryRunner.ts
As described in https://github.com/typeorm/typeorm/issues/3828 my PR https://github.com/typeorm/typeorm/pull/3814 cause conflicts with https://github.com/typeorm/typeorm/pull/3793. 
Because #3793 resolves root problem with non-lowercase enum type names this PR revert changes from  https://github.com/typeorm/typeorm/pull/3814 but leaves tests as they are.
Closes #3828
> revert(3814): Revert changes from PR#3814

- test/github-issues/3828/entity/Entity.ts
- test/github-issues/3828/issue-3828.ts
This test shows the crash that happens when trying to migrate tables with uppercase name containing at least one enum that were created with typeorm <= 0.2.14
See issue #3828
> Add failing test for issue #3828

- src/query-builder/InsertQueryBuilder.ts
- test/github-issues/2253/entity/User.ts
- test/github-issues/2253/issue-2253.ts
Currently, saving multiple child entities together results in failure, due to a name collision between the parameter supplied to specify the entity type (`discriminator_value`).  This commit makes the parameter name unique (`discriminator_value_NNN`) in order to avoid that collision and allow insertion of multiple child entities to succeed.
See #2253 for examples of the problem.  Fixes #2253.
> use distinct discriminator_value for each child entity saved

- src/commands/InitCommand.ts
**Problem:**
Newly cli generated projects are not compilable. 
**Solution:**
This PR update typescript version for cli generated projects to version 3.3.3333.
Close https://github.com/typeorm/typeorm/issues/3981
> fix(3981): update typescript deps in cli generated project

- src/entity-schema/EntitySchemaColumnOptions.ts
- src/entity-schema/EntitySchemaTransformer.ts
Adding `spatialFeatureType` and `srid` into `EntitySchemaColumnOptions`.
Fix https://github.com/typeorm/typeorm/issues/3953
> fix(3953): add missing spatial options in entity schema column definition

- CHANGELOG.md
- src/query-builder/InsertQueryBuilder.ts
- test/benchmark/bulk-save-querybuilder/bulk-save-querybuilder.ts
Instead of using Arrays/Maps with lots of `Object.keys()` and `join()` calls, it's much faster to progressively build the query.
We already do this when the metadata is available since https://github.com/typeorm/typeorm/commit/1e71e853d990b1a6e1912ec15fc8ddee268b964e. I just took the same changes and made them for the case where metadata is not available.
The new test helps to measure the difference:
Without changes:
```
benchmark > bulk-save > case-querybuilder
✓ testing bulk save of 10000 objects (186658ms)
```
With changes:
```
benchmark > bulk-save > case-querybuilder
✓ testing bulk save of 10000 objects (380ms)
```
500x improvement :)
closes #3931
> fix: InsertQueryBuilder performance issue for raw tables

- src/connection/Connection.ts
I got this warning when using Webpack compile typeorm.
```
node_modules/typeorm/connection/Connection.d.ts (40,28): Initializers are not allowed in ambient contexts.
```
Maybe relate to this issue:
https://github.com/typeorm/typeorm/issues/3823
> Resolve warning declaration Connection class: Initializers are not allowed in ambient contexts.

- CHANGELOG.md
- package-lock.json
- src/driver/sqlite-abstract/AbstractSqliteDriver.ts
- test/github-issues/3949/entity/Post.ts
- test/github-issues/3949/issue-3949.ts
`AbstractSqliteDriver:prepareHydratedValue` should check for expected time string format before applying safari fixes.
> sqlite date hydration is susceptible to corruption #3949

- src/driver/types/ColumnTypes.ts
#284 ensured TypeORM will support UUID primary generation; this PR adds `"uuid"` to the appropriate type
> Add UUID type for primary generated column

- src/driver/postgres/PostgresQueryRunner.ts
- test/github-issues/3828/issue-3828.ts
Enabling tests added in #3889. Original issue was resolved some time ago, however tests failed because we had some issues with synchronizing enum types.
Typeorm didn't know how to act when enum type had different name then generated one(name was changed manually/column wasn't created by typeorm in the first place) and schema sync was failing.
> fixing schema sync of enum columns

- src/driver/sqlserver/SqlServerQueryRunner.ts
- test/other-issues/mssql-add-column-with-default-value/entity/Post-Fail.ts
- test/other-issues/mssql-add-column-with-default-value/entity/Post-Succeed.ts
- test/other-issues/mssql-add-column-with-default-value/entity/Post.ts
- test/other-issues/mssql-add-column-with-default-value/mssql-add-column-with-default-value.ts
If you try to add a non null column to an existing table, the query will fail on MS-SQL due to a restriction of non-null non-default columns being forbidden when the table already contains rows of data.
In order to work around this, you need to define a default value, but the driver does not add the default value until after the column is created. On MSSQL this causes you to not be able to ever add the column.
This simple patch fixes that.
> Fixed issue with adding columns to existing tables in mssql.

- .circleci/config.yml
- .travis.yml
Removed steps no longer used from CI configs.
Right now circle CI test takes about [3 mins](https://circleci.com/gh/Kononnable/typeorm/18?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link). We could enable mssql there, but it would double the time(so I'm not sure if we need it there). TravisCI still takes it time, but it tests each driver we currently test on CI.
> optimizing CI build times

- .circleci/config.yml
- .gitignore
- .travis.yml
- package.json
Right now we've got coverage badge in readme, but it shows coverage status from quite some time ago. I've enabled code coverage only for TravisCI - no need to slow down CircleCI builds since it's not testing all of the drivers.
> Code coverage

- CHANGELOG.md
- package-lock.json
- package.json
- src/driver/sqljs/SqljsDriver.ts
Fixes https://github.com/typeorm/typeorm/issues/4104
Updated the devDependency to sql.js ^1.0.0, all sql.js tests passing.
Also tested against sql.js ^0.5.0 and all tests still pass.
> Support sql.js v1.0

- CHANGELOG.md
- src/query-builder/InsertQueryBuilder.ts
- test/github-issues/4096/entity/User.ts
- test/github-issues/4096/issue-4096.ts
This PR adds support of `QueryBuilder`'s `orUpdate` for SQLite.
This closes issue #4096 
In PR #3056, support for `ON CONFLICT` was added for MySQL and Postgres when using `orUpdate`, and in this PR #3190 support for Postgres `onConflict` was added for SQLite as they have the same syntax.
> Support orUpdate for SQLite

- src/connection/BaseConnectionOptions.ts
- src/connection/Connection.ts
- src/entity-factory/DefaultEntityFactory.ts
- src/entity-factory/EntityFactoryInterface.ts
- src/entity-factory/OldEntityFactory.ts
- src/metadata/EntityMetadata.ts
- src/naming-strategy/DefaultNamingStrategy.ts
- src/naming-strategy/NamingStrategyInterface.ts
- src/query-builder/SelectQueryBuilder.ts
- test/functional/entity-factory/custom-complex-entity-factory.ts
- test/functional/entity-factory/entity/PostVersioned.ts
- test/functional/entity-factory/old-entity-factory.ts
- test/github-issues/2200/entity/Booking.ts
- test/github-issues/2200/entity/Contact.ts
- test/github-issues/2200/issue-2200.ts
- test/github-issues/2200/naming/NamingStrategyUnderTest.ts
- test/utils/test-utils.ts
Current alias naming is causing issue with some naming strategy (snake case strategy at the very least). Issue was well described in #2200.
Master here #4124 
Added `eagerJoinRelationAlias` in NamingStrategyInterface and added current behaviour in DefaultNamingStrategy as to not change anything for current users.
This allow everyone to decide alias of joins, proposed solution for #2200 is to use the following (notice the double _):
```javascript
eagerJoinRelationAlias(alias: string, propertyPath: string): string {
return alias + "__" + propertyPath.replace(".", "_")
}
```
> Allow join relation alias override from naming strategies

- docs/migrations.md
- docs/zh_CN/migrations.md
Fixed the incorrect sql query for changing the column name in sql, 
it has to be like this:
ALTER TABLE table_name RENAME COLUMN old_name to new_name;
But the docs give the wrong query. I keep failing of making the migration.
reference: 
[https://www.1keydata.com/sql/alter-table-rename-column.html](https://www.1keydata.com/sql/alter-table-rename-column.html)
[https://www.w3schools.com/sql/sql_alter.asp](https://www.w3schools.com/sql/sql_alter.asp)
>  Fixed the incorrect sql query for changing the column name in sql

- CHANGELOG.md
- docs/find-options.md
- docs/select-query-builder.md
- src/find-options/FindOneOptions.ts
- src/find-options/FindOptionsUtils.ts
- src/query-builder/QueryExpressionMap.ts
- src/query-builder/SelectQueryBuilder.ts
- test/functional/query-builder/locking/query-builder-locking.ts
- test/functional/repository/find-options-locking/find-options-locking.ts
Added support for NOLOCK in mssql
Linked to this issue
https://github.com/typeorm/typeorm/issues/4042
> added dirty read(NOLOCK) in SQLServer

- src/decorator/relations/ManyToMany.ts
- src/decorator/relations/ManyToOne.ts
- src/decorator/relations/OneToMany.ts
- src/decorator/relations/OneToOne.ts
- test/github-issues/4190/entity/Category.ts
- test/github-issues/4190/entity/Photo.ts
- test/github-issues/4190/entity/Profile.ts
- test/github-issues/4190/entity/Question.ts
- test/github-issues/4190/entity/User.ts
- test/github-issues/4190/issue-4190.ts
Closes #4190
In addition to
```ts
@OneToOne(type => Profile)
@ManyToOne(type => User, user => user.photos)
@ManyToMany(type => Category)
```
now it's also possible to write:
```ts
@OneToOne('Profile')
@ManyToOne('User','photos')
@ManyToMany('Category')
```
Using this approach can prevent circular dependency issues when TypeORM is used within a frontend/browser application (e.g. when running through Angular CLI).
> feat(RelationDecorators): allow to pass string instead of typeFunction

- docs/many-to-one-one-to-many-relations.md
The documentation for OneToMany and ManyToOne has an error in reference to the decorator applied to photos property in the User entity. This commit rectifies this by switching the ManyToOne reference to the correct OneToMany decorator used in the example.
It fixes issue https://github.com/typeorm/typeorm/issues/4188
> Correct error in decorator reference in documentation example for One to Many/ Many to One.

- CHANGELOG.md
- src/subscriber/Broadcaster.ts
- src/subscriber/EntitySubscriberInterface.ts
- src/subscriber/event/LoadEvent.ts
- test/github-issues/4185/entity/Post.ts
- test/github-issues/4185/issue-4185.ts
- test/github-issues/4185/subscriber/ExtendedAfterLoadSubscriber.ts
- test/github-issues/4185/subscriber/SimpleAfterLoadSubscriber.ts
This brings it in line with the other events which already have the Connection, EntityManager, QueryRunner etc available.
Test Plan: npm test, and more specifically npm test -- --grep='github issues > #4185'
> Extend afterLoad() subscriber interface to take LoadEvent

- CHANGELOG.md
- docs/using-cli.md
- src/cli.ts
- src/commands/MigrationShowCommand.ts
- src/connection/Connection.ts
- src/migration/MigrationExecutor.ts
- test/functional/migrations/show-command/command.ts
- test/functional/migrations/show-command/migration/1530542855524-ExampleMigration.ts
- test/functional/migrations/show-command/migration/1530542855524-ExampleMigrationTwo.ts
As proposed here: https://github.com/typeorm/typeorm/issues/3954
This PR adds a new command `typeorm migration:show`
This lists all migrations and shows whether they are applied or pending.
The command also returns an error code if there are unapplied migrations, so that it can easily be used  in CI pipelines.
> typeorm migration:show

- CHANGELOG.md
- src/query-builder/relation-count/RelationCountLoader.ts
- test/github-issues/3946/entity/Category.ts
- test/github-issues/3946/entity/Image.ts
- test/github-issues/3946/entity/Post.ts
- test/github-issues/3946/issue-3946.ts
> Fixes #3946 - loadRelationCountAndMap fails when entities' primary keys are strings

- CHANGELOG.md
- src/query-builder/transformer/DocumentToEntityTransformer.ts
- test/functional/mongodb/basic/embedded-columns/entity/Counters.ts
- test/functional/mongodb/basic/embedded-columns/entity/EditHistory.ts
- test/functional/mongodb/basic/embedded-columns/entity/ExtraInformation.ts
- test/functional/mongodb/basic/embedded-columns/mongodb-embedded-columns.ts
**Issue type:**
[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue
**Database system/driver:**
[ ] `cordova`
[x] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`
**TypeORM version:**
[x] `latest`
[ ] `@next`
[ ] `0.2.17` (or put your version here)
**Steps to reproduce or a small repository showing the problem:**
```
export class Post {
@Column()
title: string
@Column(type => ExtraInfo)
extraInfo: ExtraInfo
}
export class ExtraInfo {
@Column(type => EditHistory)
lastEdit: EditHistory
}
export class EditHistory {
@Column()
message: string
}
...
await repo.save(somePost);
const [post] = await repo.find();
// UnhandledPromiseRejectionWarning: TypeError: Cannot read property …
```
>  Fix transform embeddeds with no columns but with nested embeddeds (mongodb)

- docs/many-to-many-relations.md
closes #4196
It's a minor documentation fix - should I provide a changelog update for this? I only see generic "update documentation" lines.
> fix(docs): Fixed many-to-many docs

- CHANGELOG.md
- extra/typeorm-class-transformer-shim.js
- package-lock.json
- package.json
- test/github-issues/4219/entity/Photo.ts
- test/github-issues/4219/entity/User.ts
- test/github-issues/4219/issue-4219.ts
- test/github-issues/4219/shim.ts
closes #4219
Solution:
- First check if a `typeFunction` is passed to a decorator and then pass `typeFunction` to `@Type` (this is the current behavior)
- If no `typeFunction` is passed and "reflect-metadata" is imported, try to use `design:type`
So for example:
```ts
@Entity()
export class Photo {
// ...
@CreateDateColumn()
createdAt: Date;
}
// ...
const photo = plainToClass(Photo, {
//...
createdAt: 'Sat Jun 01 2019'
});
photo.createdAt instanceof Date // true
```
Just a small note: 
In order to make it testable I've added "class-transformer" to the devDependencies.
> feat(class-transformer-shim): Added support for metadata reflection

- docs/decorator-reference.md
I found the documentation for https://typeorm.io/#/decorator-reference/unique kind of confusing at first because I thought it was expecting database column names.
I also found an issue where a user asked for more clarity on this.  https://github.com/typeorm/typeorm/issues/3732
> give more clarity on arguments passed to unique

- src/query-builder/RelationLoader.ts
The lazy load getter checks to see if the relation was already loaded by checking to see if the data for the relation is stored on the `dataIndex` key of the entity (i.e. `post.author` will check for `post.__author__` and reuse it if present).
Previously, it checked for a truthy value (just a simple `if (post.__author__)`). However, if the data for that relation was previously loaded, and that relation is empty, then `post.__author__` will be `null`. The simple truthy check will fail, and it will query the DB to attempt to load the relation.
This PR changes the check to explicitly check for `undefined`, rather than any falsey value. That way, preloaded `null` relations can reuse the preloaded value.
> Reuse preloaded null values for lazy loads

- test/functional/mongodb/basic/timestampable-columns/timestampable-columns.ts
Test has `+/-` delta range of 5 milliseconds, because earlier this test fell due to the difference of 1 millisecond.
It fixes issue #4285
> test(mongodb): time comparing is stable

- docs/using-ormconfig.md
It isn't clear that it's possible to pass any typeORM config variable with environment variables. For example [here](https://github.com/typeorm/typeorm/issues/2885)
English isn't my native language, so feel free to improve the text.
> docs: add example for the TYPEORM_DRIVER_EXTRA env variable

- src/driver/cockroachdb/CockroachDriver.ts
`executeQuery` method is not used in `cockroachdb` driver
> refactor(cockroachdb): redundant executeQuery()

- docs/faq.md
change "typedi" to "typed" in how to use TypeORM with a dependency injection tool question
> docs: fix typographical error in faq

- docs/supported-platforms.md
- src/driver/sqljs/SqljsDriver.ts
Fixes #4291 and also adds some more documentation on how to use sql.js in the browser.
> fix: improve sql.js v1.0 support in browser environment

- src/repository/BaseEntity.ts
This brings SaveOptions and RemoveOptions to BaseEntity inherited models methods `remove`and `save` when using ActiveRecord pattern.
> fix: add SaveOptions and RemoveOptions into ActiveRecord

- docs/faq.md
- docs/many-to-many-relations.md
Since I myself ran into the issue and had to rewrite my code based on this solution I hope it may be helpful for others as well 😊
> docs: add explanation ManyToMany with custom properties

- src/query-builder/QueryExpressionMap.ts
- src/query-builder/SelectQueryBuilder.ts
- test/functional/query-builder/select/query-builder-select.ts
A bare-bones `DISTINCT` implementation that just supports standard SQL row-level `SELECT DISTINCT`, nothing fancy like PSQL's `DISTINCT ON` specific columns.
I've added support to the `QueryBuilder`, and also to `Repository#find` (via `JoinOptions`).
Closes #2641 - _However_, there are users who have posted in that issue wanting two separate things `DISTINCT` (i.e. this PR) and `DISTINCT ON`, which is a (very useful) non-standard SQL extension that is unfortunately not covered by this PR. If this merges, I'd suggest opening another issue specifically to track `DISTINCT ON`. 
The use-cases for this functionality in `QueryBuilder` is immediately obvious. However, the benefit to `Repository#find` probably warrants an example. 
e.g. A forum (User + Post models) and you want to get all users …
> feat: add support for DISTINCT queries

- docs/troubleshooting.md
- docs/zh_CN/troubleshooting.md
- src/connection/ConnectionMetadataBuilder.ts
- src/logger/AdvancedConsoleLogger.ts
- src/util/DirectoryExportedClassesLoader.ts
This new feature logs the files that are loaded using the glob patterns to aid in debugging.
Closes: #4162
> feat : log files loaded from glob patterns

- docs/entities.md
- src/driver/postgres/PostgresDriver.ts
- src/driver/types/ColumnTypes.ts
- test/functional/cube/postgres/cube-postgres.ts
- test/functional/cube/postgres/entity/Post.ts
Implements support for the [`cube`](https://www.postgresql.org/docs/10/cube.html) type on PostgreSQL.
Closes #3577.
> feat: add multi-dimensional cube support for PostgreSQL

- docs/using-ormconfig.md
Typo in .env configuration: .*js changed to *.js
> docs: update typo in using-ormconfig.md

- docs/supported-platforms.md
Self-explanatory title. The old link would result in a 404, and that's no fun
> docs: update outdated Expo SQLite link

- docs/separating-entity-definition.md
Typo in line 190: "Categeory" changed to "Category"
> docs: update typo in separating-entity-definition.md

- docs/transactions.md
In the second example the lambda is correctly started with an `async`. It is missing in the first example.
> docs: fix missing async

- src/connection/Connection.ts
[Fixed this issue (link)](https://github.com/typeorm/typeorm/issues/4691)
> fixed issue 4691

- src/driver/mysql/MysqlQueryRunner.ts
- src/driver/postgres/PostgresQueryRunner.ts
- test/github-issues/4630/entity/User.ts
- test/github-issues/4630/issue-4630.ts
Patch for #4630
I'm not a SQL hero, but a simple way of escaping an apostrophe in this context is to simply use two apostrophes and this appears to work well for me. This is likely an issue in other drivers, but I am not familiar.
> Fix: Apostrophe in Postgres enum strings breaks query

- docs/connection-options.md
- src/driver/cockroachdb/CockroachConnectionOptions.ts
- src/driver/cockroachdb/CockroachDriver.ts
- src/driver/postgres/PostgresConnectionOptions.ts
- src/driver/postgres/PostgresDriver.ts
- src/driver/sqlserver/SqlServerConnectionOptions.ts
- src/driver/sqlserver/SqlServerDriver.ts
Add option to customize pool error handling. Users can decide to log these errors with higher level (eg. error), crash application or reconnect.
> feat: Add pool error handler

- docs/example-with-express.md
the `remove` method requires the entity itself as input. To remove a record based on it's id, you need to use `delete`
> docs: use remove instead of delete

- docs/using-ormconfig.md
Since many formats of configuration sources are supported, it makes sense to not have the title specific to `.json`
> docs: clarify title of configuration sources

- CHANGELOG.md
- docs/connection-options.md
- docs/zh_CN/connection-options.md
- src/driver/sqljs/SqljsConnectionOptions.ts
- src/driver/sqljs/SqljsDriver.ts
Fixes https://github.com/typeorm/typeorm/issues/4559
added `sqlJsConfig` connection option for sql.js (v1.x) to inititialize.
> add options to input init config for sql.js

- docs/entities.md
- src/decorator/columns/Column.ts
- src/driver/mysql/MysqlDriver.ts
- src/driver/mysql/MysqlQueryRunner.ts
- src/driver/types/ColumnTypes.ts
- test/github-issues/2779/entity/Post.ts
- test/github-issues/2779/issue-2779.ts
- test/github-issues/2779/set.ts
https://dev.mysql.com/doc/refman/5.7/en/set.html
Very basic set support. Sets are implemented as arrays. Possible values defined using existing enum column option. 
#2779
> feat: add `set` datatype support for MySQL/MariaDB

- src/driver/postgres/PostgresQueryRunner.ts
- src/query-builder/UpdateQueryBuilder.ts
- src/query-builder/result/UpdateResult.ts
- test/github-issues/1308/entity/Author.ts
- test/github-issues/1308/entity/Post.ts
- test/github-issues/1308/issue-1308.ts
* Added 'affected' field in UpdateResult as well as in DeleteResult.
* PostgresQueryRunner returns the number of affected rows properly
* UpdateQueryBuilder retrieves the affected rows returned by PostgresQueryRunner and
sets the added 'affected' field of UpdateResult properly.
Closes: #1308
> feat: UpdateResult returns the affected rows in postgresql

- src/commands/MigrationGenerateCommand.ts
- src/schema-builder/RdbmsSchemaBuilder.ts
MigrationGenerateCommand didn't apply parameters to query and information about ViewTables couldn't be inserted into typeorm_metadata table. Also added code that creates typeorm_metadata table if ViewTables exists
Fixed issue #4123
> fix: view table migrations

- src/driver/postgres/PostgresDriver.ts
- test/github-issues/4719/entity/Post.ts
- test/github-issues/4719/issue-4719.ts
Closes https://github.com/typeorm/typeorm/issues/4719
Add support for empty string keys/values, NULL values, and properly escape key/values.
> Fix "Hstore injection" & properly handle NULL, empty string, backslashes & quotes in hstore key/value pairs

- src/driver/cockroachdb/CockroachQueryRunner.ts
- src/driver/mysql/MysqlQueryRunner.ts
- src/driver/oracle/OracleQueryRunner.ts
- src/driver/postgres/PostgresQueryRunner.ts
- src/driver/sqlite-abstract/AbstractSqliteQueryRunner.ts
- src/driver/sqlserver/SqlServerQueryRunner.ts
- src/metadata/ForeignKeyMetadata.ts
- src/naming-strategy/DefaultNamingStrategy.ts
- src/naming-strategy/NamingStrategyInterface.ts
- test/functional/query-runner/rename-column.ts
- test/functional/query-runner/rename-table.ts
- test/github-issues/3847/entity/Animal.ts
- test/github-issues/3847/entity/Category.ts
- test/github-issues/3847/issue-3847.ts
- test/github-issues/3847/naming/NamingStrategyUnderTest.ts
@see https://github.com/typeorm/typeorm/issues/3847 and https://github.com/typeorm/typeorm/issues/1355
> feat: Add referenced table metadata to namingstrategy to resolve foreignKeyName

- src/commands/MigrationGenerateCommand.ts
- src/connection/Connection.ts
- src/metadata-builder/EntityMetadataBuilder.ts
- src/metadata-builder/EntityMetadataValidator.ts
- src/metadata-builder/JunctionEntityMetadataBuilder.ts
- src/metadata-builder/RelationJoinColumnBuilder.ts
- src/query-builder/DeleteQueryBuilder.ts
- src/query-builder/InsertQueryBuilder.ts
- src/query-builder/SelectQueryBuilder.ts
- src/query-builder/UpdateQueryBuilder.ts
- src/schema-builder/RdbmsSchemaBuilder.ts
- test/functional/schema-builder/change-column.ts
There's a lot of `instanceof MysqlDriver` checks in the code and we need these for aurora driver as well for queries like updates to work correctly.
> fix(aurora): apply mysql query fixes to aurora

- docs/example-with-express.md
In the [examples with express](https://typeorm.io/#/example-with-express/adding-typeorm-to-the-application) the PUT request awaits when it doesn't need to, since .merge doesn't return a promise.
> docs: don't await .merge in example with express

- src/decorator/EntityRepository.ts
- src/metadata-args/EntityRepositoryMetadataArgs.ts
- src/repository/AbstractRepository.ts
- src/subscriber/EntitySubscriberInterface.ts
Currently we cannot pass an `EntitySchema<T>` to the `@EntityRepository` decorator unless we cast it to `any`. But actually it works with an `EntitySchema`, just the types are missing. This PR adds the types.
> fix: allow EntitySchema to be passed to EntityRepository

- src/connection/Connection.ts
- test/github-issues/4753/entity/User.ts
- test/github-issues/4753/issue-4753.ts
This should fix https://github.com/typeorm/typeorm/issues/4753 and also provide a better way to actually get the database name.
> fixes 4753

- docs/entities.md
The `decorator-reference` link is broken. I believe this will fix it
see: https://typeorm.io/#/entities
> docs: fix entities broken link

- src/driver/oracle/OracleQueryRunner.ts
- src/driver/postgres/PostgresQueryRunner.ts
- src/schema-builder/view/View.ts
- test/functional/view-entity/postgres/entity/PostByCategory.ts
- test/functional/view-entity/postgres/view-entity-postgres.ts
We've just started using a materialized view in our project (postgres DB) and noticed that the schema sync task during our tests was not creating a materialized version of the view when passing `{ materialized: true }` in the entity definition.
Looks like a few things were missed in https://github.com/typeorm/typeorm/pull/4478:
1. materialized SQL logic left out of `PostgresQueryRunner.ts`.
2. materialized condition logic was backwards and _always_ adding `MATERIALIZED` to the create view SQL
3. The `materialized` option in the entity definition was always being set to false due to not being passed through
4. [Materialized views are not supported in cockroachdb](https://marsettler.com/docs/v2.1/postgres-ddl-support.html#create-materialized-view) so I've disabled the cockroach driver for …
> fix(postgres): postgres query runner to create materialized view

- src/commands/MigrationGenerateCommand.ts
- src/migration/MigrationExecutor.ts
- src/migration/MigrationInterface.ts
This fixes a problem when after minification process, migrations cannot be loaded because their name is changed to some random value, this happens mostly when using react-native/expo.
There are several topics about this issue in facebook/metro and typeorm repositories, but I couldn't find any pull request for it. It could be fixed by changing the default minifier, but that can break other stuff.
There are also a few steps before merging this PR:
**EDIT**
Created a babel-plugin to automatically add name property:
```js
module.exports = function({ types: t }, options) {
return {
visitor: {
ClassDeclaration(path) {
const migrationName = t.stringLiteral(path.node.id.name)
const migrationTimestamp = parseInt(migrationName.value.substr(-13), 10)
if (!isNaN(migrationTimestamp)) {
const prop = …
```
> Add optional name to MigrationInterface (fixes #3933)

- src/decorator/options/ColumnEnumOptions.ts
- src/decorator/options/ColumnOptions.ts
- src/driver/postgres/PostgresQueryRunner.ts
- src/metadata/ColumnMetadata.ts
- src/schema-builder/options/TableColumnOptions.ts
- src/schema-builder/table/TableColumn.ts
- src/schema-builder/util/TableUtils.ts
- test/github-issues/4106/entity/Animal.ts
- test/github-issues/4106/entity/GenderEnum.ts
- test/github-issues/4106/entity/Human.ts
- test/github-issues/4106/issue-4106.ts
> Add option to Column to specify the complete enumName

- docker-compose.yml
- src/driver/mysql/MysqlQueryRunner.ts
- src/util/VersionUtils.ts
- test/github-issues/4782/entity/Item.ts
- test/github-issues/4782/issue-4782.ts
Fixes #4782. I've explained the issue in great detail there.
- Fixed a check for `CURRENT_TIMESTAMP`, and made it more generic to cover cases like `CURRENT_TIMESTAMP`, `CURRENT_TIMESTAMP()` and `CURRENT_TIMESTAMP(6)`, ignoring the case.
- Fixed a test failure in `test/functional/query-builder/add-column.ts` due to double-quoting:
https://github.com/typeorm/typeorm/blob/13ac22242ad1e2a46cc3aa6af870f4b1cfae1af3/test/functional/query-runner/add-column.ts#L73
- Added `semver` dependency to make it easy to check the version of MariaDB.
> Fix "current_timestamp(6)" !== "CURRENT_TIMESTAMP(6)" for MariaDB >= 10.2

- src/persistence/SubjectChangedColumnsComputer.ts
- src/util/DateUtils.ts
```typescript
@Entity()
export class Post {
@PrimaryGeneratedColumn()
id: number;
@Column({ name: "dt", type: "timestamp with time zone" })  // <-- type is important here
date: Date;
}
const post = new Post();
post.id = 1;
post.date = new Date();
await postRepository.save(post);       // <-- first save, it is ok
const loadedPost = await postRepository.findOneOrFail(1);
await postRepository.save(loadedPost); // <-- was not changed, 
// but typeorm will update the record with the same date
```
Entity property with column type "timestamp with time zone" value is always different for TypeORM on save.
Seems like you forget to normalize these values on value comparison function.
> better entity values comparison on save

- src/migration/MigrationExecutor.ts
- test/github-issues/4697/entity/config.entity.ts
- test/github-issues/4697/entity/item.entity.ts
- test/github-issues/4697/issue-4697.ts
- test/github-issues/4697/migration/1566560354098-UpdateContacts.ts
- test/github-issues/4697/migration/1567689639607-MergeConfigs.ts
* update `loadExecutedMigrations` to get migrations sorted by id from database
* add missing await statements when running mongodb migrations
Fixes #4697
> fix: migrations run in reverse order for mongodb

- src/driver/aurora-data-api/AuroraDataApiQueryRunner.ts
- src/driver/mysql/MysqlQueryRunner.ts
- test/github-issues/2737/entity/TestEntity.ts
- test/github-issues/2737/issue-2737.ts
Part of fix for #2737 and #2943
> fix: resolve MySQL unique index check when bigNumberStrings is false

- docs/relations.md
Currently the docs only describe passing a `boolean` for the cascade option. It's also possible to provide an array of cascade options, so I've updated the docs to reflect that, and provided an example.
> docs: explain cascade options

- docs/many-to-many-relations.md
This adds information on how to delete a many-to-many relation to the docs. Previously it was discussed in the issues (https://github.com/typeorm/typeorm/issues/1420), but it's hard to find when searching for information on the website.
I also added a more headers and a table of contents for the many-to-many-relations page to make it easier to navigate.
> docs: add info on deleting a many-to-many relation

- docs/decorator-reference.md
Found a mistake at line 254.
The type of a _@PrimaryGeneratedColumn("uuid")_ must be a **string** and **not a number**.
> docs: Decorator Reference Mistake | line 254

- docs/zh_CN/logging.md
fix typo in `zh_CN` logging chapter
it should be `有` instead of `又`
> docs: fix typo in `zh_CN` logging chapter

- package-lock.json
- package.json
Fixes incompatbility with pnpm which couldn't find the `ormconfig.json` in the root path.
> Upgrade app-root-path

- docs/connection-api.md
I guess the `synchronize` method has the wrong description. I've changed the description to indicate that `synchronize` is usually used on application starting instead of application shut down.
> Fix docs description 

- src/decorator/Index.ts
- test/github-issues/5004/entity/Foo.ts
- test/github-issues/5004/issue-5004.ts
This PR allow `expireAfterSeconds: 0` to be passed to Index decorator.
Related issue: #5004
> fix: allow expireAfterSeconds 0 in Index decorator (close #5004)

- src/migration/MigrationExecutor.ts
fix: resolve sorting bug for several mongo versions with typeorm migration
refactored the sort string-valued key parameter to an object in order to avoid the `MongoError: Can't canonicalize query: BadValue bad order array [2]` error when running migration
Closes #5115
> fix: resolve sorting bug for several mongo vesions with typeorm migra

- src/driver/aurora-data-api/AuroraDataApiDriver.ts
- src/driver/cockroachdb/CockroachDriver.ts
- src/driver/mysql/MysqlDriver.ts
- src/driver/oracle/OracleDriver.ts
- src/driver/postgres/PostgresDriver.ts
- src/driver/sqlserver/SqlServerDriver.ts
Just accidently discovered that connection options are modified if url is passed.
Steps to reproduce:
```ts
const options = {
type: 'postgres',
url: 'postgresql://postgres:somepassword@localhost:5432/postgres',
...
}
await createConnection(options).connect(); // ok
console.log(options.type); // 'postgresql' (changed from valid postgres)
await createConnection(options).connect(); // will not connect cause of 'postgresql' type is not supported
```
> remove connection options mutation

- package-lock.json
Missed some configurations on my side in the last PR.
See https://github.com/typeorm/typeorm/commit/7f87f0c9da6f74e14d167c3dfffdd351ca2d2f9f#diff-32607347f8126e6534ebc7ebaec4853dR460
Now reverted back to official npm repo for the `app-root-path` package
> Fix repo for app-root-path in lock file

- src/connection/ConnectionOptionsReader.ts
- test/functional/connection-options-reader/configs/test-path-config-async.ts
- test/functional/connection-options-reader/connection-options-reader.ts
This allows a Promise to be returned from a js or ts ormconfig file.
Closes: #4149
> feat: asynchronous ormconfig support

- src/index.ts
- src/migration/MigrationExecutor.ts
This may need a lot of rework and review, but it describes what I tried to explain in #4880
> feat: export Migration Execution API from main package (fixes #4880)

- src/migration/MigrationExecutor.ts
Fix for https://github.com/typeorm/typeorm/issues/5102
> Fixed unescaped column name in order clause of "migrations"

- test/functional/cube/postgres/cube-postgres.ts
Add test case for a bug where Postgres `cube` of zero arity incorrectly hydrates as `[0]` instead of `[]`.
> test(postgres): add test case for zero-arity cubes

- docs/connection-options.md
- docs/zh_CN/connection-options.md
- src/driver/aurora-data-api/AuroraDataApiConnectionOptions.ts
- src/driver/mysql/MysqlConnectionOptions.ts
- src/driver/mysql/MysqlDriver.ts
- src/query-builder/InsertQueryBuilder.ts
- src/query-builder/SelectQueryBuilder.ts
- src/query-builder/UpdateQueryBuilder.ts
- test/github-issues/3702/entity/LetterBox.ts
- test/github-issues/3702/issue-3702.ts
* Add `legacySpatialSupport` option for replacing
dropped functions to new ones
* Use srid column option like PostgreSQL
Implemented the OP's suggestion naively.
Close #3702
> feat: support spatial functions of MySQL 8+

- docs/select-query-builder.md
- src/query-builder/QueryExpressionMap.ts
- src/query-builder/SelectQueryBuilder.ts
- test/functional/query-builder/distinct-on/entity/Category.ts
- test/functional/query-builder/distinct-on/entity/Post.ts
- test/functional/query-builder/distinct-on/entity/User.ts
- test/functional/query-builder/distinct-on/query-builder-distinct-on.ts
- test/functional/query-builder/select/query-builder-select.ts
Following on from #4109. This PR adds support for Postgres distinct on clause.
todo;
> feat: add distinct on() support for postgres

- src/error/CircularRelationsError.ts
I believe this should say `nullable: true`. You only have an impossible circular dependency if both relations are `NOT NULL`.
> Fix circular dependency error message

- src/driver/mysql/MysqlQueryRunner.ts
Mysql driver's `connection.query()` returns `Query` object which is an EventEmitter but not a ReadableStream. In order to get a stream one needs to call `.stream()` on it.
Fixes #5035
> fix: mysql driver query streaming

- src/driver/cockroachdb/CockroachQueryRunner.ts
- src/driver/postgres/PostgresQueryRunner.ts
Replace usage of pg_constraint.consrc with pg_get_constraintdef() in all
cases. PostgreSQL 12 no longer supports consrc. Use the same code in
CockroachDB for consistency.
Closes: #4332
> fix(postgres,cockroachdb): remove consrc usage

- package-lock.json
- src/driver/DriverUtils.ts
- src/util/StringUtils.ts
When selecting relations (e.g. in `find` methods), if a generated alias is longer than the maximum identifier length allowed by the current driver, it would get shortened: for example "Something_somethingElse" would become "Some_soEl" etc.
However, if multiple relations have similar enough aliases, their shortened versions might end up identical. This would lead to conflicts that cause the query to fail.
This commit hashes aliases that are too long, instead. This way there is still a theoretical possibility of a collision, but it's astronomically low. In practice, alias conflicts should disappear.
One drawback of this solution is that it leads to more vague aliases. This may make queries less inspectable. For what it's worth, though, `Some_soEl` doesn't grant a lot of clarity about what …
> feat: hash aliases to avoid conflicts

- src/driver/nativescript/NativescriptConnectionOptions.ts
- src/driver/nativescript/NativescriptDriver.ts
This pull request implements the extra driver options for NativeScript and adds them to the driver specific `ConnectionOptions`, it also fixes passing options using the extra option from `BaseConnectionOptions`. This is required to use the Commercial version of the driver.
> Implement driver options for NativeScript

- src/repository/TreeRepository.ts
The processing speed improves when the number of data is large.
> Speed ​​up id search in buildChildrenEntityTree

- src/query-builder/RelationLoader.ts
- test/github-issues/47/issue-47.ts
Ensure the same promise is being assigned when its being resolved before
caching the value in the entity.
``` typescript
class Post {
@OneToMany
category: Promise<Cateogry>
}
let [category1, category2] = await Category.find()
post  = await Post.findOne()
post.category = Promise.resolve(category1)
await post.category // => expected category1, actual undefined
await post.reload()
const promise = post.category;
post.category = Promise.resolve(category2);
await promise; // => category1
await post.category // => expected category2, actual category1;
```
Related: #2276
> Bugfix lazy relation assignment

- .npmrc
- .travis.yml
- package-lock.json
- package.json
Update node.js versions tested on travis:
- removed nodejs 8.x - EOL
- added 13.x - current
- removed @sap/hdbext from dev dependencies
Looks like @sap/hdbext is not compatible with node 13. I think we should deal with this same way we're currently handling oracledb. It doesn't work in every environment(32 bit), so developer need to install it manually if he wants to use it.
> chore: update node versions tested on travis

- src/driver/sqlserver/SqlServerDriver.ts
- src/driver/sqlserver/SqlServerQueryRunner.ts
- src/query-builder/InsertQueryBuilder.ts
- src/query-builder/QueryBuilder.ts
- src/query-builder/UpdateQueryBuilder.ts
- test/functional/query-builder/entity-updation/entity-updation.ts
- test/github-issues/5160/entity/Post.ts
- test/github-issues/5160/issue-5160.ts
Fixes #5160
When inserting or updating an entity, `QueryBuilder` was using SQL Server's `OUTPUT` clause to return updated values for columns with generated or default values and then update the entity representation.
This breaks when the target table has a trigger defined, with the following error:
```
The target table '...' of the DML statement cannot have any enabled triggers
if the statement contains an OUTPUT clause without INTO clause.
```
This PR changes the behavior of `QueryBuilder` (when connected to SQL Server) to use `OUTPUT INTO` instead of just `OUTPUT`, so the returned values are inserted to a table variable and then selected back, rather than returned directly from the `INSERT` statement.
SQL Server reference: https://docs.microsoft.com/en-us/sql/t-sql/queries/output-clause- …
> fix: use OUTPUT INTO on SqlServer for returning columns

- src/util/OrmUtils.ts
- test/github-issues/3534/entity/Foo.ts
- test/github-issues/3534/entity/RegExpStringTransformer.ts
- test/github-issues/3534/issue-3534.ts
Closes https://github.com/typeorm/typeorm/issues/3534
Before entity column values are transformed, changes are deeply merged using OrmUtils.mergeDeep. This mergeDeep function attempts to merge objects, but wrongly attempted to merge RegExp objects. This merging of RegExp objects breaks the object, rendering them unusable. This commit changes mergeDeep to not merge RegExp objects but overwrite them instead.
To cleanup the mergeDeep function, I also refactored `propertyKey` away, and I changed all references to `source[key]` or `source[propertyKey]` to `value`, also removing the commented code.
> fix: change OrmUtils.mergeDeep to not merge RegExp objects

- src/driver/aurora-data-api/AuroraDataApiDriver.ts
TypeORM uses require() within PlatformTools to load driver packages.
The typeorm-aurora-data-api-driver is exported with export default and packaged with rollup, which, as per https://github.com/webpack/webpack/issues/4742,
causes the require'd module to be available via require('typeorm-aurora-data-api-driver').default property.
Fixes #4788
> fix: load typeorm-aurora-data-api-driver correctly when using webpack

- docs/caching.md
- src/cache/QueryResultCacheFactory.ts
- src/connection/BaseConnectionOptions.ts
- test/functional/cache/custom-cache-provider.ts
- test/functional/cache/entity/User.ts
- test/functional/cache/provider/MockQueryResultCache.ts
- test/utils/test-utils.ts
As of right now, TypeORM only allows to use built-in cache providers, this pull request adds an option to specify a custom cache provider (that should implement QueryResultCache spec) in the ConnectionOptions object:
```
await createConnection({
// ...all of the required options for establishing connection
cache: {
cacheProvider(connection) {
return new MockQueryResultCache(connection);
}
}
});
```
> feat: Add basic support for custom cache providers

- README.md
I was trying to use the following, which does not work with `cascade` as described in the README.
```typescript
metadata.photo = photo; // this way we connect them
```
The code in the README is correct, but the change was not called out.
```typescript
photo.metadata = metadata; // this way we connect them
```
> docs: clarify how cascade option works

- docs/update-query-builder.md
single quotes make error called ER_TRUNCATED_WRONG_VALUE: Truncated incorrect DOUBLE value.
It is working without single quotes.
> docs: delete single quote from "'age' +1"

- src/connection/Connection.ts
This reverts commit 7962036be3c009f8de3030e83002be0346e35d48 
The original PR came about from this issue: https://github.com/typeorm/typeorm/issues/3427.
The author of the original issue has since realized the root problem they were facing was unrelated: https://github.com/typeorm/typeorm/issues/3427#issuecomment-549770047
It seems this "monkeypatch" is causing more problems than any workaround it might have provided is worth. The conditional `metadata.target.name === target.name` in the `findMetadata` function is not a thorough-enough comparison. Function names are often the same in large codebases and especially in minified code (as @Benjamin-Dobell points out https://github.com/typeorm/typeorm/pull/4804#issuecomment-580075220). This results in false positives returned from …
> revert: "fix: connection Reuse is broken in a Lambda environment: (#4804)"

- src/repository/BaseEntity.ts
**What's the problem this PR addresses?**
The version of `BaseEntity.create` that takes an array of `entityLike` objects returns an array of entities but the return type incorrectly specifies that it's a single entity.
**How did you fix it?**
Changed the return type from `T` to `T[]`
> fix(base-entity): set create return type to T[]

- src/driver/mysql/MysqlDriver.ts
- test/github-issues/3636/entity/Post.ts
- test/github-issues/3636/issue-3636.ts
Fixes #3636 
https://mariadb.com/kb/en/json-data-type/
The JSON column type is implemented using LONGTEXT in MariaDB, so every time a table with JOSN column gets synchronized will drop the column and add it again. 
This PR could fix the issue
> .synchronize() drops json column on mariadb

- src/schema-builder/RdbmsSchemaBuilder.ts
- test/github-issues/5119/entity/v1/Post.ts
- test/github-issues/5119/entity/v1/User.ts
- test/github-issues/5119/entity/v2/Account.ts
- test/github-issues/5119/entity/v2/Post.ts
- test/github-issues/5119/entity/v2/User.ts
- test/github-issues/5119/issue-5119.ts
- test/github-issues/5119/migration-updates-foreign-keys.ts
Closes #5119 , based on #5120 
Includes a check for the correct table name when checking for equality of foreign keys, to decide if they should be dropped and made fresh
> update foreign keys when table name changes

- docs/many-to-many-relations.md
for this example, it is referencing associating a custom **createdAt** property but then the actual following example uses an **order** property. I thought it would make sense to match these up.
> docs: update many to many relations with custom properties

- src/driver/sqlserver/SqlServerConnectionOptions.ts
> fix: add the enableArithAbort option to the sql server connection option typings

- src/driver/postgres/PostgresQueryRunner.ts
- src/metadata/ColumnMetadata.ts
Let's assume the entity like this.
```
import { Point, Polygon } from 'geojson';
class SomeTable1 {
...
@Column({type: 'geometry', srid: 4326, spatialFeatureType: 'Polygon'})
my_polygon!: Polygon;
}
class SomeTable2 {
...
@Column({type: 'geometry', srid: 4326, spatialFeatureType: 'Point'})
my_place!: Point;
}
```
Typeorm always think the geometry field has been changed even though I did not change it.
If synchronize option is true, typeorm always run below query whenever server started.
```
query: ALTER TABLE "some_table2" ALTER COLUMN "my_place" TYPE geometry(Point,4326)
```
If synchronize option is false, when I execute `typeorm migration:generate`, it "always" make new migration file below even after I execute typeorm migration:run.
```
public async up(queryRunner: QueryRunner): …
```
> [Fix] not to make typeorm generate alter query on geometry column when that column was not changed

- src/util/StringUtils.ts
Comments for snake case and title case functions was confusing. As in `camelCase` I used comments also as an example.
> docs: Better definition for case functions

- docs/relations.md
The relations.md still has "cascade remove" option.
But as far as I know, "cascade remove" option has been removed from version [0.2.0](https://github.com/typeorm/typeorm/blob/master/CHANGELOG.md#020).
So I remove this option because this could lead to confusion.
> docs: Remove "cascade remove" option from relations.md

- src/query-builder/UpdateQueryBuilder.ts
- test/github-issues/4947/entity/Post.ts
- test/github-issues/4947/issue-4947.ts
- test/github-issues/4947/subscriber/PostSubscriber.ts
When defining a `beforeUpdate` implementation in a subscriber the entity object is undefined on the passed in `event.entity` property when calling `update` on a repository and passing a updated entity object.
Closes: #4947
> fix: entity object undefined in update subscriber

- src/repository/SaveOptions.ts
The number to pass into "chunk" is *not* the number of chunks you desire, it is the desired size of each chunk.
I lost a fair bit of time to this, because I only read the first line of the comment, and didn't realize it conflicted with the example presented later in the comment.
> docs: fix incorrect "chunk" description

- docs/connection-options.md
- docs/zh_CN/connection-options.md
- src/driver/expo/ExpoConnectionOptions.ts
- src/driver/expo/ExpoDriver.ts
This pull request adds a new driver option that allows the user to pass `require('expo-sqlite')` into the driver. The Expo SQLite API changed to use a new `expo-sqlite` module instead of having a `SQLite` object be available on `window`.
I did not want to put `require('expo-sqlite')` directly in the driver code base because [Metro bundler does not allow dynamic imports](https://github.com/facebook/metro/issues/52), which means that all `typeorm/browser` users would be forced to import `expo-sqlite` into their project. (A similar thing happens with `react-native-sqlite-storage` for the React Native driver.)
I have added documentation for the new option, but I would appreciate if someone could check the Chinese translation.
Fixes #4846
> Add driver option to address Expo API change.

- src/driver/aurora-data-api/AuroraDataApiQueryRunner.ts
- src/driver/cockroachdb/CockroachQueryRunner.ts
- src/driver/mysql/MysqlQueryRunner.ts
- src/driver/oracle/OracleQueryRunner.ts
- src/driver/postgres/PostgresQueryRunner.ts
- src/driver/sqlite-abstract/AbstractSqliteQueryRunner.ts
- src/driver/sqlserver/SqlServerQueryRunner.ts
- src/error/NotImplementedError.ts
- test/functional/schema-builder/custom-db-and-schema-sync.ts
This is very minor, but recently bitten by this. I don't see any reason why unimplemented functions should return silently doing nothing.
> Add NotImplementedError for driver functions that do nothing

- src/commands/MigrationGenerateCommand.ts
Convert from `Promise<any>` to `Promise<void>`
This fixes projects that frown upon the use of `any` type
> Change return type of generated migrations up/down

- docs/decorator-reference.md
adds note about the "default" value of the unique option of the `@Column` decorator
I'm pretty sure this is true. Feel free to just close this PR if not. I just noticed some explicit `unique: false`'s in our project and wanted to make this clear in the docs
> add default value note for unique @Column option

- src/cache/RedisQueryResultCache.ts
- src/entity-manager/EntityManager.ts
- src/metadata/RelationMetadata.ts
- src/query-builder/QueryBuilder.ts
- src/query-builder/SoftDeleteQueryBuilder.ts
- src/util/DateUtils.ts
- test/github-issues/587/issue-587.ts
because instanceof Array seems to be problematic on some platforms
> replacing instanceof Array checks to Array.isArray

- docs/relations.md
A bit of information I thought was missing.
https://stackoverflow.com/questions/60619027/referenced-column-undefined-was-not-found-in-entity-postsentity
> Added multi-column informations for JoinColumn

- docs/migrations.md
- docs/zh_CN/migrations.md
- src/commands/MigrationCreateCommand.ts
- test/functional/migrations/show-command/migration/1530542855524-ExampleMigration.ts
- test/functional/migrations/show-command/migration/1530542855524-ExampleMigrationTwo.ts
- test/github-issues/2875/migration/1530542855524-CreateUsersSeq.ts
- test/github-issues/4701/migration/1567759789051-ExampleMigration.ts
- test/github-issues/4701/migration/1567759832591-ExampleMigrationTwo.ts
- test/github-issues/4701/migration/1571426391120-ExampleMigrationThree.ts
Following the open issue https://github.com/typeorm/typeorm/issues/5629 I created a pull request.
I kept the `migration/MigrationInterface.d.ts` to `Promise<any>` so use-case like `test/github-issues/2693/migration/0000000000003-InsertUser.ts` still work.
> update cli migration up and down from any to void

- src/query-builder/UpdateQueryBuilder.ts
- test/github-issues/1308/issue-1308.ts
Set 'affected' property for 'UpdateResult' returned by MySQL
Closes: #1308
> feat: UpdateResult returns affected rows in mysql

- src/util/OrmUtils.ts
- test/github-issues/5762/entity/User.ts
- test/github-issues/5762/issue-5762.ts
> Handle URL objects as column field values

- docs/logging.md
there was no `sql` tag in the example, and `query` made the most sense.
> fixed `sql` to `query` in the last example

- package-lock.json
- package.json
- src/commands/CommandUtils.ts
- src/driver/sqlite/SqliteDriver.ts
mkdirp 0.5.x depends on minimist 0.8.0 which doesn't pass npm audit. 
This pull request updates mkdirp to 1.x and also updates the code using mkdirp to make sure it's working with the new version as the new version returns Promise.
> Update dependency mkdirp to 1.x

- docs/mongodb.md
> Fix readme wording

- docs/select-query-builder.md
The code examples assume many results (see a comment below in each example), but queries were filtered by `user.id`. Instead `groupBy` clausule should be used in order to select `user.id` after using aggregation function.
> docs: fix raw query

- src/driver/expo/ExpoDriver.ts
Currently the disconnect() function does not perform a real call to databaseConnection close, it only sets the queryRunner and databaseConnection to undefined, this behavior may cause problems when you do something like this:
1 - await getConnection().close();
2 - Replace the database file
3 - Try to open connection createConnection(); and do some insert
more info:
https://github.com/expo/expo/issues/8109
> Fix expo sqlite driver disconnect()

- docs/using-cli.md
Just did not work with actual version of ts-node and others modules
> [Doc] Fix typeorm alias for TS

- src/query-builder/transformer/RawSqlResultsToEntityTransformer.ts
- test/github-issues/3874/entity/Settings.ts
- test/github-issues/3874/issue-3874.ts
> fix: use an empty string enum as the type of a primary key column

- src/driver/mysql/MysqlQueryRunner.ts
- test/github-issues/6066/entity/Session.ts
- test/github-issues/6066/issue-6066.ts
> fix: escape column comment in mysql driver

- src/query-builder/QueryExpressionMap.ts
- src/query-builder/SelectQueryBuilder.ts
- test/functional/query-builder/locking/query-builder-locking.ts
Support `FOR NO KEY UPDATE` lock mode on postgresql.
If you will not update primary key, then `FOR NO KEY UPDATE` is better then `FOR UPDATE`, becaues `FOR UPDATE` can make deadlock with `SELECT FOR KEY SHARE` query.
The main difference between `FOR NO KEY UPDATE` and `FOR UPDATE` is `FOR NO KEY UPDATE` will not block `SELECT FOR KEY SHARE`.
The detail is described [this article](https://dba.stackexchange.com/questions/188169/select-for-update-locking-other-tables-in-postgresql).
> [Add] FOR NO KEY UPDATE lock mode for postgresql

- src/decorator/columns/ViewColumn.ts
- src/decorator/options/ViewColumnOptions.ts
- test/functional/view-entity/general/entity/PhotoAlbumCategory.ts
- test/functional/view-entity/general/view-entity-general.ts
- test/functional/view-entity/mssql/entity/PostCategory.ts
- test/functional/view-entity/mssql/view-entity-mssql.ts
- test/functional/view-entity/mysql/entity/PostCategory.ts
- test/functional/view-entity/mysql/view-entity-mysql.ts
- test/functional/view-entity/oracle/entity/PostCategory.ts
- test/functional/view-entity/oracle/view-entity-oracle.ts
- test/functional/view-entity/postgres/entity/PostCategory.ts
- test/functional/view-entity/postgres/view-entity-postgres.ts
- test/functional/view-entity/sqlite/entity/PostCategory.ts
- test/functional/view-entity/sqlite/view-entity-sqlite.ts
Add 'name' option to `@ViewColumn` to align with `@Column`
and allow a different property name for a column in a view.
This is required for views created without using the `sync` option.
Closes #5708
> feat: add name option to view column

- docs/transactions.md
Change "lets" to "let's" in the sentence "since we have errors lets [sic] rollback changes we made".
> docs: fix grammatical error (lets => let's)

- docs/connection-options.md
The "entitySchemas" connection option doesn't work. Instead, schemas are recognized when added to the "entities" connection option. The docs were updated to reflect that.
> DOCS: update connection-options.md

- src/driver/mongodb/typings.ts
This method returns an object with `_id` and `index` properties, according to [the description of `BulkWriteResult`](https://docs.mongodb.com/manual/reference/method/BulkWriteResult/#BulkWriteResult.upserted).
Without this change, TypeScript complains when trying to access the `_id` property.
> Use correct typings for the result of `getUpsertedIds()`

- src/repository/BaseEntity.ts
- test/functional/repository/soft-delete/entity-soft-remove.ts
- test/functional/repository/soft-delete/entity/Post.ts
- test/functional/repository/soft-delete/entity/PostWithoutDeleteDateColumn.ts
Add soft remove and recover methods to entity.
This PR improves https://github.com/typeorm/typeorm/pull/5034
> Feature: Add soft remove and recover methods to entity

- src/driver/postgres/PostgresQueryRunner.ts
- test/functional/migrations/generate-command/command.ts
- test/functional/migrations/generate-command/entity/category.entity.ts
- test/functional/migrations/generate-command/entity/index.ts
- test/functional/migrations/generate-command/entity/post.entity.ts
- test/functional/migrations/generate-command/entity/tag.entity.ts
This is related to #3280 
We are using 0.2.22 with postrgres, but upgrading to 0.2.24 is impossible for us at that point, since migration:generate always generates bunch of FK recreations.
The deleted and the newly created FK are exactly  the same.
In the end I managed to trace this down to the fact that we are explicitly specifying the schema for each entity (we have entities in multiple schema).
So here is a fix. Metadata was building correctly the full table name for table changes, but this wasn't the case for  the FK definitions.
> Fix migrations being generated for FK even if there are no changes

- src/driver/postgres/PostgresQueryRunner.ts
Using Postgres with Postgis, when there are columns of type geometry in tables that are in other schemas than "public", a wrong table name is being used as parameter of the query that returns the column spatial featyre type and srid.
The table name parameter should be just the name of the table, without the schema name prepended.
The following error is being thrown in this situation:
> Error during migration generation:
> TypeError: Cannot read property 'type' of undefined
> Fix wrong table name parameter when not using default schema

- docs/using-ormconfig.md
- Add a missing word to documentation sentence
> docs: add missing text in sentence

- ormconfig.json.dist
- package-lock.json
- package.json
- src/driver/aurora-data-api/AuroraDataApiConnectionOptions.ts
- src/driver/aurora-data-api/AuroraDataApiDriver.ts
- test/functional/connection-manager/connection-manager.ts
The underlying AWS RDS database, accessible through the aurora-data-api driver supports configurations settings, also known as [AWS.ConfigurationOptions](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/RDSDataService.html#constructor-property). It allows you to pass options like max number of retries, Arn regions and impersonation secrets.
The [typeorm-aurora-data-api-driver](https://github.com/ArsenyYankovsky/typeorm-aurora-data-api-driver), which is referenced in this project has now added support for this, see pull request state [here](https://github.com/ArsenyYankovsky/typeorm-aurora-data-api-driver/pull/31). Minimum required version is 1.2.0. 
Changes included in this pull request  allows users of TypeORM to pass the values through AuroraDataApiConnectionOptions. Example:
``` …
```
> Aurora Data API - Support for AWS configuration options through aurora driver

- src/decorator/entity/Entity.ts
I've been making a class decorator composer function, and Function type is not specific enough. I'll augment it locally for the time being.
I suppose some other types would have to be updated as well, hopefully there's a CI in place
> Update Entity decorator return type to ClassDecorator

- src/entity-manager/EntityManager.ts
- test/github-issues/5734/entity/Post.ts
- test/github-issues/5734/issue-5734.ts
- test/github-issues/5734/subscriber/CheckValidEntitySubscriber.ts
As described in issue #5734, the current behaviour seems like an oversight and inconsistent with save() and remove() which already have this handled as a special case.
Test Plan: npm test, and more specifically npm test -- --grep='#5734'
Closes: #5734
> fix: calling EntityManager.insert() with an empty array of entities

- src/util/StringUtils.ts
- test/github-issues/799/issue-799.ts
- tsconfig.json
When using this pattern in the browser it will throw because namespace objects can never be functions, which also throws in Rollup even if it might work in other build tools.
Using the default import form ensures the instance is the exact `module.exports` instance provided by sha.js.
> Fix sha.js import

- docs/entities.md
Got bit by this myself, adding note to documentation.
> docs: note about bigint type being mapped to a string

- src/metadata-builder/EntityMetadataBuilder.ts
- src/naming-strategy/DefaultNamingStrategy.ts
- src/naming-strategy/NamingStrategyInterface.ts
This change makes column names used by the nested set and materialized path tree types configurable through the naming strategy, keeping the ones already in use as defaults.
The rationale is that some of us have to work with legacy databases accessed by other tools as well, in which case altering column names is off the table.
> Names of extra columns for specific tree types moved to NamingStrategy

- src/find-options/FindOneOptions.ts
Fixes a small copy-and-paste error I happened to notice.
> docs: update FindOneOptions lock property comment

- src/driver/postgres/PostgresConnectionCredentialsOptions.ts
This simple change allows providing a function (optionally async) as the password instead of only a string. This change is necessary in order to enable [this node-postgres PR](https://github.com/brianc/node-postgres/pull/1926) to function inside of TypeORM. Fixes #4724.
> Postgres: Allow providing a function for password

- src/commands/MigrationGenerateCommand.ts
When migration was generated without parameters, it had been adding `undefined` 2nd parameter.
> fix: redundant undefined parameters are not generated in migration files anymore

- src/driver/sqljs/SqljsQueryRunner.ts
The statement bind method in sqljs assumes that either an object or an array has been provided.
> [sqljs] Provide a default empty array for parameters.

- package-lock.json
- src/connection/Connection.ts
- test/github-issues/2096/entity/TestEntity.ts
- test/github-issues/2096/issue-2096.ts
Database names can be defined in the options object. Now also connection urls that contain a database can be used to have the database set in the drivers object.
Closes: #2096
> fix: respect database from connection urls

- src/metadata/EntityMetadata.ts
- src/persistence/SubjectChangedColumnsComputer.ts
- src/persistence/subject-builder/ManyToManySubjectBuilder.ts
- src/persistence/subject-builder/OneToManySubjectBuilder.ts
- src/persistence/subject-builder/OneToOneInverseSideSubjectBuilder.ts
- src/query-builder/transformer/RawSqlResultsToEntityTransformer.ts
- src/util/OrmUtils.ts
We've found a TypeORM-based application spending most CPU time in `OrmUtils.deepCompare()`, called from `compareIds()`.
This PR implements a faster code path for the common case when the ID object has the type `{id: string}`. Our application's overall response time has improved from 1.2s to 0.4s!
Before:  
After:  
wdyt?
cc @fresswolf
> perf: Optimized version of EntityMetadata#compareIds() for the common case

- src/entity-manager/EntityManager.ts
- src/repository/BaseEntity.ts
- src/repository/Repository.ts
"plan javascript object" -> "plain javascript object"
> docs: fix typo

- docs/example-with-express.md
> Updated link to TS node

- ormconfig.json.dist
- package-lock.json
- package.json
- src/driver/aurora-data-api-pg/AuroraDataApiPostgresConnectionOptions.ts
- src/driver/postgres/PostgresDriver.ts
- test/functional/connection-manager/connection-manager.ts
With the merge of #5651 typeorm supports aurora data api with postgres, but typeorm has a version missmatch in devDepencies it needs version 1.3.0, pr [here](https://github.com/ArsenyYankovsky/typeorm-aurora-data-api-driver/pull/35).
Like in #5754 pr, the typeorm-aurora-data-api-driver allows passing configuration to underlying awsClient, changes in this PR allows users to pass the values (same code from #5754 but in AuroraDataApiPostgresDriver class).
> Aurora Data API - Add AWS configurationOptions to aurora-data-api-pg connector

- docs/index.md
Weirdly search sent me here, and it took a while to find the real TypeORM website.
> Add a link to TypeORM website

- docs/connection-options.md
- src/driver/postgres/PostgresConnectionOptions.ts
- src/driver/postgres/PostgresDriver.ts
Commit message below to explain more of what's going on -- but before that, I just want to say I'd love some help writing tests. The contribution guidelines suggested this wouldn't get pulled in without them, however, I didn't see any existing test cases that would give me a starting point.
--- 
There was no documented way of setting a connection timeout for the
postgres driver. We recently ran into an issue with our network that
caused a container to hang indefinitely attempting to connect to
postgres.
We managed to resolve the issue by setting 'connectionTimeoutMillis' in
the 'extra' field of our connection options. This approach does not
appear to be documented anywhere.
Seeing that MongoDB and MySQL drivers both support a connection timeout
as part of the documented API, we felt it …
> Add postgres connection timeout option

- README.md
The `repository` variable is not defined in the first Data Mapper pattern example
> Fix undefined `repository` variable on docs

- docs/example-with-express.md
JSON body parser is now built-in by default (>4.16.0), hence no need for body-parser
> docs: replace body-parser with express built-in parser

- docs/supported-platforms.md
Hello!
Just fix a small typo in supported platforms page
i also move the 'file' word to be part of the link text
> [docs] fix typo in supported_platforms.md page

- src/find-options/operator/Raw.ts
I believe it will be called with alias argument at https://github.com/typeorm/typeorm/blob/0.2.25/src/find-options/FindOperator.ts#L121
Unnecessary optional sign causes confusing and extra handling.
[@typescript-eslint/restrict-template-expressions](https://github.com/typescript-eslint/typescript-eslint/blob/v3.4.0/packages/eslint-plugin/docs/rules/restrict-template-expressions.md), which is [recommended since v3](https://github.com/typescript-eslint/typescript-eslint/issues/1423), warns `Invalid type "string | undefined" of template literal expression` for  `` Raw(alias =>`${alias} > NOW()`) ``
> fix: remove unnecessary optionality from Raw operator's columnAlias argument

- src/driver/DriverUtils.ts
- test/github-issues/4878/issue-4878.ts
As per the documentation, the url properties should be getting overridden by the specifically-passed configuration options. They currently are not because of the order of the `Object.assign` call.
This reverses the order of the assign to ensure that any properties which were already defined outside of the url are properly persisted in the final configuration.
There are various reasons for this PR. What drove me to make the change was CI/CD usage. In Gitlab, you are provided a DATABASE_URL, which can have a dynamic url and port due to the kubernetes setup. My typeorm connection kept connecting to the default user's database instead of the `test` database I was providing it, because the url property was overriding the provided `database`.
This PR fixes an issue opened October of last year! …
>  fix: properly override database url properties

- src/connection/ConnectionOptionsReader.ts
- src/util/DirectoryExportedClassesLoader.ts
- test/github-issues/6284/issue-6284.ts
addresses #6284 - if you're running a NodeJS library that has ESM modules enabled, using a `cjs` extension for the `ormconfig` is required to express the configuration in commonjs.
This script allows me to run the CLI in a local environment and a test case is supplied.
> support cjs extension for ormconfig

- src/query-builder/QueryBuilder.ts
- test/github-issues/6399/entities.ts
- test/github-issues/6399/issue-6399.ts
> fix: refactor QueryBuilder.createWhereExpression

- src/entity-schema/EntitySchemaRelationOptions.ts
- src/entity-schema/EntitySchemaTransformer.ts
- test/github-issues/5444/entity/Author.ts
- test/github-issues/5444/entity/Post.ts
- test/github-issues/5444/issue-5444.ts
update type definition and schema transformer
so that - like the decorator - the EntitySchema can define
composite `JoinColumn` definitions
Closes: #5444
> fix: support multiple `JoinColumn`s in EntitySchema

- src/driver/DriverUtils.ts
- test/github-issues/6389/issue-6389.ts
ref #6389
**BC?:**
No
In the future, it may be better to use this library
https://github.com/vitaly-t/connection-string
> fix(driver-utils): correctly parse connection URI with query params

- src/migration/MigrationExecutor.ts
getPendingMigrations currently returns the executed migrations instead of the non-executed ones.
> Fix getPendingMigrations

- src/metadata-builder/JunctionEntityMetadataBuilder.ts
- test/github-issues/6642/entity/v1/entities.ts
- test/github-issues/6642/entity/v2/entities.ts
- test/github-issues/6642/issue-6642.ts
fix: @JoinTable does not respect inverseJoinColumns referenced column width
Closes: #6442
> #6442 fix: @JoinTable does not respect inverseJoinColumns referenced column width

- CONTRIBUTING.md
- README.md
~~the slack links haven't been working since at least May of 2020, so they have been removed~~
Update with the new Slack Invite Link
Closes #6053
> chore: Update Slack Invite Links

- docs/entities.md
- src/driver/postgres/PostgresDriver.ts
- src/driver/types/ColumnTypes.ts
- test/functional/ltree/postgres/entity/Post.ts
- test/functional/ltree/postgres/ltree-postgres.ts
This pr implements support for the ltree postgres extension.
Closes: #4193
Extension Docs: [ltree](https://www.postgresql.org/docs/9.1/ltree.html)
Feature
postgres
> feat: implement postgres ltree

- docs/relational-query-builder.md
* modify docs/relational-query-builder.md
> docs: remove out-of-place 'example:'

- test/github-issues/114/issue-114.ts
- test/github-issues/2096/issue-2096.ts
the test had assumed the username, password, host, and port of
the mysql server
this update changes that so the test instead uses the config properly
while still checking that the test works as expected
> test: remove hardcoded test from github issue tst 2096

- ISSUE_TEMPLATE.md
- docs/support.md
Update the issue template to discourage asking questions through issues and instead direct users to check out the support documentation.
Questions are very often not answered and end up filling up the issues backlog with non-issues - just misconceptions.  If there's a problem with documentation that's one thing, but there are currently 603 open questions that make it much harder to find actual issues with TypeORM.
> chore: discourage questions as issues

- .circleci/config.yml
the lockfile we use was generated on a mac & includes `fsevents` as a dependency. while this is optional for OSX it's not available for linux & this causes problems with the `npm ci` command.
npm v7 will correct this but until we're using that we should switch to using `npm install`
> build: use `npm install` to work around npm/cli#558

- .circleci/config.yml
- docker-compose.yml
for some reason, the CI build started OOM'ing with CockroachDB v20 every once in a while - this pins us on a stable v19 release.
> chore: pin version of cockroach to a known good version 

- test/functional/view-entity/mssql/view-entity-mssql.ts
- test/functional/view-entity/mysql/view-entity-mysql.ts
- test/functional/view-entity/oracle/view-entity-oracle.ts
- test/functional/view-entity/postgres/view-entity-postgres.ts
- test/functional/view-entity/sqlite/view-entity-sqlite.ts
this is a backport of changes from the `next` branch
> chore: remove uneccessary cockroachdriver calls in view-entity tests

- .circleci/config.yml
- ormconfig.circleci-common.json
This updates the CircleCI configuration to utilize `docker-compose` for running the dependent database services we run tests against.
This allows us to more easily deploy more varied and complex systems - such as databases that could normally run us out of memory (eg, CockroachDB) or databases that require authenticated login to fetch the images (eg, OracleDB & SAP Hana)
It also grants us access to a larger machine on the other end of the `docker-remote` - a system with 8GB of RAM instead of the 4GB the normal runner gets.
While the tests take a bit longer to run, there may be mechanisms we could employ to improve that down the line.
> build: use docker-compose for database services

- src/logger/FileLogger.ts
- src/logger/LoggerOptions.ts
- test/github-issues/4410/entity/Username.ts
- test/github-issues/4410/issue-4410.ts
This allows users to override the FileLogger's default filepath.
Closes: [#4410](https://github.com/typeorm/typeorm/issues/4410)
> feat: FileLogger accepts custom file path

- src/commands/CacheClearCommand.ts
- src/commands/EntityCreateCommand.ts
- src/commands/InitCommand.ts
- src/commands/MigrationCreateCommand.ts
- src/commands/MigrationGenerateCommand.ts
- src/commands/MigrationRevertCommand.ts
- src/commands/MigrationRunCommand.ts
- src/commands/MigrationShowCommand.ts
- src/commands/QueryCommand.ts
- src/commands/SchemaDropCommand.ts
- src/commands/SchemaLogCommand.ts
- src/commands/SchemaSyncCommand.ts
- src/commands/SubscriberCreateCommand.ts
- src/commands/VersionCommand.ts
- src/platform/PlatformTools.ts
There's not much point to require `chalk` in the way it's been done - so use `import` instead.
This allows us to use the type definitions for chalk which we weren't before - `require` makes it `any` instead of the `chalk` types
> chore: instead of require, import chalk from chalk

- src/query-builder/SelectQueryBuilder.ts
When creating the query for the `distinctAlias` - Instead of prepending `ids_` to the built alias name we include `ids_` as a prefix.
This means that the generated column alias could potentially be 4 characters longer than the maximum allowed column length defined by the driver.  In the case of Oracle, with its hilariously short identifier length, this comes up very frequently and causes the `ORA-00972` error code to emit.
> bugfix: pass `ids_` to alias builder to prevent length overflow

- src/commands/MigrationCreateCommand.ts
Right now the CLI will ALWAYS prepend the CWD to `options.cli.migrationsDir`. 
This prevents us from using absolute paths there. 
How would we feel about changing that to support absolute paths (by only prepending CLI if the path DOES NOT start with "/")? If we're open to it, I'm happy to make the change for the other CLI commands as well.
> Support absolute paths in migrationsDir for the CLI

- src/driver/sqlite-abstract/AbstractSqliteDriver.ts
- src/driver/sqlite-abstract/AbstractSqliteQueryRunner.ts
- test/github-issues/6636/entity/Test.ts
- test/github-issues/6636/issue-6636.ts
Specifying precision or scale properties on columns with SQLite/sql.js would result in migrations being generated even on an unchanged schema.
This was due to the precision and scale arguments not correctly being inferred when reading the table. This change handles scale and precision in the same way that "length" was already being correctly handled.
Fixes #6636
> fix: Migration issues with scale & precision in sqlite/sql.js

- src/driver/Driver.ts
- src/driver/aurora-data-api/AuroraDataApiDriver.ts
- src/driver/cockroachdb/CockroachDriver.ts
- src/driver/mongodb/MongoDriver.ts
- src/driver/mysql/MysqlDriver.ts
- src/driver/oracle/OracleDriver.ts
- src/driver/postgres/PostgresDriver.ts
- src/driver/sap/SapDriver.ts
- src/driver/sqlite-abstract/AbstractSqliteDriver.ts
- src/driver/sqlserver/SqlServerDriver.ts
- src/schema-builder/RdbmsSchemaBuilder.ts
- src/schema-builder/options/TableIndexOptions.ts
- test/github-issues/6633/entity/Test.ts
- test/github-issues/6633/issue-6633.ts
Fixes #6633 (see issue for root cause explanation)
> fix: Unnecessary migrations for fulltext indices

- src/metadata/EntityMetadata.ts
`extractRelationValuesFromEntity` used `inverseEntityMetadata` which may contains abstract or base entity metadata which coursed child entity that we actually want to save to be treated as it's parent. This commit adds additional check for it.
Fixes: #2544
> fix: Child entities not being saved correctly with cascade actions

- src/query-builder/QueryPartialEntity.ts
User should be able to pass function if field is an array, right now it is only enabled for single values.
Example:
```
await getConnection()
.createQueryBuilder()
.update(Entity)
.set({
arrayField: (() => 'some update query') as unknown as string[],
})
.where('1 = 1')
.execute();
```
This is the workaround I've used so far to hack around TypeScript, with this fix merged, you can drop `as unknown as string[]` and it works as expected
> Update query deep partial TypeScript definition

- test/github-issues/4410/issue-4410.ts
Merging in #6623 caused a test that was merged in slightly before #6642 to start failing because the SQL written is not compatible with Oracle.
As such, this updates that test to properly escape the table name queried.
> escape table name for Github #4410

- src/metadata/EntityMetadata.ts
Defining an Entity for Oracle connection does not recognise the schema value. This fixes that by adding it to the EntityMetadata class
> fix: add missing schema for OracleDriver

- docs/migrations.md
It is a simple refactoring in the doc. I had to search for a while to find out how to create a timestamp column now in postgres. I hope this can help
> Update query runner examples

- src/driver/postgres/PostgresQueryRunner.ts
as touched in https://github.com/typeorm/typeorm/issues/5999
fixes following bug: connections returned from pg-pool do not have 'error' event handler. 'error' events are triggered on connection errors(https://node-postgres.com/api/client events section), thus when a connection error happens it will trigger uncaught exception and process is stopped.
fix:
Add an 'error' event handler to connections returned from pool. The error handler does not do anything else except releasing the pool connection with error - this will remove this connection from the pool, and this connection will not be reused. Note that there is no logging, or anything else in the handler, this is due to fact that if the event is handled and the process does not die, the query() promise will be correctly rejected, thus …
> fix: handle 'error' events from pool connection

- src/driver/aurora-data-api/AuroraDataApiQueryRunner.ts
- src/driver/mysql/MysqlQueryRunner.ts
- src/query-runner/BaseQueryRunner.ts
- test/github-issues/2943/entity/Test.ts
- test/github-issues/2943/issue-2943.ts
In MariaDB, unsigned numeric types (`<tiny,small,medium>int`) without an explicit `width` property set would generate migrations on every run. This is due to an error in setting the default width for unsigned types.
Fixes #2943
> fix: Unnecessary migrations for unsigned numeric types

- package-lock.json
- package.json
- src/driver/sqljs/SqljsQueryRunner.ts
before sql.js 1.2 it seems undefined were treated as if they were null,
but as of 1.2 they cause a query error & fail to execute
this change swaps out any undefined parameters with `null`s
closes #5720
> bugfix: sql.js v1.2+ don't support undefined parameters

- src/common/EntityTarget.ts
- src/connection/Connection.ts
- src/entity-manager/EntityManager.ts
- src/entity-manager/MongoEntityManager.ts
- src/error/EntityMetadataNotFoundError.ts
- src/error/EntityNotFoundError.ts
- src/error/RepositoryNotFoundError.ts
- src/error/RepositoryNotTreeError.ts
- src/index.ts
- src/metadata-args/EntityRepositoryMetadataArgs.ts
- src/query-builder/DeleteQueryBuilder.ts
- src/query-builder/InsertQueryBuilder.ts
- src/query-builder/QueryBuilder.ts
- src/query-builder/SelectQueryBuilder.ts
- src/query-builder/SoftDeleteQueryBuilder.ts
- src/repository/AbstractRepository.ts
- src/repository/Repository.ts
This backports the `EntityTarget` type from the `@next` branch and uses it instead of the bunches of `ObjectType`/`EntitySchema`/`string` union types.
> techdebt: create EntityTarget and use instead of EntitySchema / ObjectType / etc

- src/driver/sqlite/SqliteConnectionOptions.ts
- src/driver/sqlite/SqliteDriver.ts
- src/driver/sqlite/SqliteQueryRunner.ts
- test/functional/sqlite/enable-wal.ts
This is a backport of the SQLite logic to enable WAL & Busy retries
> feat: backport SQLite Busy handler & WAL mode enable

- src/driver/postgres/PostgresQueryRunner.ts
- test/github-issues/6699/issue-6699.ts
move on-error-release code to the queryRunner connect function
so we only need to have one listener per query runner on each
connection - cutting down the number of listeners total &
preventing a problem with too many listeners
this edge case becomes a real problem within transactions where
the queries may be fired off on the same connection long before
they will eventually execute their callbacks
closes #6699
This is related to #6262 - it's a bit of a refactor of that code to handle
the case of transactions
> fix: prevent multiple `release` listeners in PostgresQueryRunner

- src/decorator/relations/OneToMany.ts
Hi, seems like there's an error in the description of the `OneToMany` decorator type (displayed e.g. in editors and IDEs when hovering over the decorator). The comment states that
> One-to-many relation allows to create type of relation when Entity2 can have multiple instances of Entity1. Entity1 have only one Entity2. Entity1 is an owner of the relationship, and storages Entity2 id on its own side.
I think there has to be a mistake since this seems to describe the same side of the relation as the comment on `ManyToOne`
> Many-to-one relation allows to create type of relation when Entity1 can have single instance of Entity2, but Entity2 can have a multiple instances of Entity1. Entity1 is an owner of the relationship, and storages Entity2 id on its own side.
If I'm not mistaken, this PR …
> Correct the comment of OneToMany decorator

- src/find-options/operator/Any.ts
- src/find-options/operator/Between.ts
- src/find-options/operator/In.ts
- src/find-options/operator/Raw.ts
the `next` branch added return types to `FindOperator`s and
this backports that change
> fix: backport FindOperator return types

- package-lock.json
- package.json
this bumps the version of typescript accepted to >=3.9.7,<4.0
we were implicitly pulling in that version (per the package-lock.json)
so this just codifies it in the package.json as well
> chore: explicitly pull in typescript 3.9

- test/github-issues/1960/issue-1960.ts
this test was emitting logs for no real reason so this removes the
`logging: true` when creating the testing connection
> test: disable logging for test 1960

- src/driver/mysql/MysqlQueryRunner.ts
- test/github-issues/6714/entity/session.ts
- test/github-issues/6714/entity/sessionchanged.ts
- test/github-issues/6714/issue-6714.ts
New versions of MariaDB return expressions in lowercase we need to set it  in uppercase so the comparison in MysqlDriver#compareExtraValues does not fail.
example:
```sql
CREATE TABLE `test` (
`test_id` int(11) NOT NULL AUTO_INCREMENT,
`test_update` timestamp() NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
PRIMARY KEY (`test_id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1
```
When you try to generate a new migration always create the next migration file:
```ts
import { MigrationInterface, QueryRunner } from 'typeorm';
export class test261600082802966 implements MigrationInterface {
name = 'test261600082802966';
public async up(queryRunner: QueryRunner): Promise<void> {
await queryRunner.query(
'ALTER TABLE `test` CHANGE `test_update` `test_update` timestamp() NOT NULL …
```
> Migration:generate issue with onUpdate using mariadb 10.4

- docs/connection-options.md
- src/driver/postgres/PostgresConnectionOptions.ts
- src/driver/postgres/PostgresDriver.ts
- test/github-issues/2216/entity/Foo.ts
- test/github-issues/2216/issue-2216.ts
Additional option `logNotifications` for Postgres driver. When true, passes any notice messages or listen/notify events to the client logger with `info` level.
This should close off [issue 2216](https://github.com/typeorm/typeorm/issues/2216).
Please reach out in case of questions or feedback.
> feat: add option to pass postgres notice messages to the client logger

- gulpfile.ts
- package.json
- src/connection/ConnectionOptionsReader.ts
- src/platform/BrowserDirectoryExportedClassesLoader.template
- src/platform/BrowserDisabledDriversDummy.template
- src/platform/BrowserPlatformTools.template
- src/platform/PlatformTools.ts
currently we pull in BetterSqlite3Driver, SqliteDriver, and a few other
drivers & files that aren't possible to use in a browser context.
this change adds some more browser compatibility features so
webpack builds targeted at browsers will be able to complete
closes #6739
> fix: ensure browser builds don't include any non-browser modules

- src/driver/oracle/OracleDriver.ts
- test/github-issues/5067/issue-5067.ts
Use index instead of parameter name for make it shorter alias name.
Closes #6591
Fixes #5067
> fix: resolve issues ora-00972:identifier is too long

- src/connection/options-reader/ConnectionOptionsEnvReader.ts
the expected type of `port` in all drivers is a number - and
in MSSQL this is a problem as the underlying driver does not
properly handle a string port - so we have to parseInt
closes #6781
> fix: coerce port to number in ConnectionOptionsEnvReader

- gulpfile.ts
- package.json
- src/connection/ConnectionOptionsReader.ts
- src/connection/options-reader/ConnectionOptionsEnvReader.ts
- src/connection/options-reader/ConnectionOptionsYmlReader.ts
- src/platform/BrowserConnectionOptionsReaderDummy.template
- src/platform/BrowserFileLoggerDummy.template
Add browser dummies for `FileLogger`, `ConnectionOptionsReader`, and change how we process the `*.template` files in `gulp`.
Ideally, we should move away from this whole process for creating browser builds by monkey-patching random parts of TypeORM in this way - such as restructuring the package or finding some other mechanism to make this happen.. but until then, this solves some of the remaining issues with browser builds according to @chriswep 
Fixes #6739
> fix: add dummy for FileLogger, ConnectionOptionsReaders, and update gulpfile

- src/commands/MigrationGenerateCommand.ts
User error sometimes leads to running the migration generate command with invalid parameters. If the `-n` argument for the name of the migration class is completely missing, it returns a useful error to the user:
```
> typeorm migration:generate -f ormconfig -c development
> Generates a new migration file with sql needs to be executed to update schema.
Options:
-h, --help        Show help                                          [boolean]
-c, --connection  Name of the connection on which run a query.
[default: "default"]
-n, --name        Name of the migration class.                      [required]
-d, --dir         Directory where migration should be created.
-f, --config      Name of the file with connection configuration.
[default: "ormconfig"]
-v, --version     Show version number …
```
> FIX #2719: enforce name argument of migration generate command

- src/find-options/FindOperator.ts
- src/query-builder/QueryBuilder.ts
Migrate the code from `FindOperator.toSql` into `QueryBuilder.computeFindOperatorExpression`.
The `QueryBuilder` is the de-facto location for all of the SQL Dialect generation.
Let's move the `FindOperator.toSQL` to live there too.
Effectively, we were passing a bunch of context from within the `QueryBuilder` back into the
`FindOperator` meaning we couldn't actually use `FindOperator` without `QueryBuilder`.
The `FindOperator` had most of its code in a mechanism that wasn't even used by all drivers
(eg, Mongo).
`QueryBuilder` did not have encapsulation of the SQL dialect & more in-depth changes
to the way we generate SQL based on the `FindOperator` can't be as easily done as
we didn't have context of the rest of the `QueryBuilder`.
> refactor: Migrate `FindOperator` SQL generation into `QueryBuilder`

- package-lock.json
- package.json
- src/entity-manager/MongoEntityManager.ts
- src/find-options/FindOptionsUtils.ts
- tsconfig.json
Because of a breaking feature in Typescript 3.7.0 we cannot upgrade
past that without marooning users of Typescript 3.5 / 3.6 & 4.0+
this locks typescript to ~3.6.0 explicitly and fixes some small
issues that arise in using that version
fixes #6809
fixes #6805
> fix: lock Typescript to 3.6.0

- src/driver/react-native/ReactNativeDriver.ts
Because react native uses the browser context we can't use `PlatformTools.load` so this reverts the behavior for this file to use a standard `require` call
Fixes #6811
> fix: use `require` in `ReactNativeDriver`

- src/commands/EntityCreateCommand.ts
- src/commands/SubscriberCreateCommand.ts
Following up on https://github.com/typeorm/typeorm/pull/6660 and adding absolute path support to the other CLI commands (sorry it took me so long!) 
This is the same change + the type change necessary to prevent a breakage (someone please correct me if I'm missing anything)! 
Thanks!
> Add absolute path support to other CLI commands

- docs/using-ormconfig.md
- src/connection/ConnectionOptionsReader.ts
- test/functional/connection-options-reader/configs/test-path-config-esm.ts
- test/functional/connection-options-reader/connection-options-reader.ts
allows for the use of ESM `export default` for exporting an ORM Config.
fixes #5003
> fix: support ESM in ormconfig js & ts

- src/driver/mysql/MysqlQueryRunner.ts
in #6268 we pulled in a change that fixed the wrong FK
getting loaded in a multi-database / multi-schema environment
but in #6169 the approach was more desirable as it creates
a simpler query that should be easier to change in the future
as such, this pulls over that change from #6169
> refactor: check mysql constraint schema on join

- src/metadata/ColumnMetadata.ts
- src/query-builder/transformer/RawSqlResultsToEntityTransformer.ts
- test/github-issues/6815/entity/ChildEntity.ts
- test/github-issues/6815/entity/ParentEntity.ts
- test/github-issues/6815/issue-6815.ts
Fix issue where attempting to cast bigints to strings also did it for
null values.
Fix issue where transformRelationIds() filtered out null values when
it should only be done for undefined.
Closes: #6815
> fix: return null for nullable RelationId() column

- src/find-options/FindOperator.ts
- src/find-options/operator/Raw.ts
- src/query-builder/QueryBuilder.ts
- test/functional/repository/find-options-operators/repository-find-operators.ts
Currently, find operator ```Raw()``` not supported escaping.
I have updated the code so that it is now possible to use an escaping.
The updated syntax is as follows:
```
await connection.getRepository(Post).find({
likes: Raw((columnAlias, parameters) => {
return `(${columnAlias} = ${parameters[0]}) OR (${columnAlias} = ${parameters[1]})`
}, [2, 3]),
});
await connection.getRepository(Post).find({
likes: Raw((columnAlias, parameters) => {
return `(${columnAlias} = ANY(${parameters[0]})) AND (${columnAlias} < ${parameters[1]})`
}, [[1, 4, 5, 6], 6]),
});
await connection.getRepository(Post).find({
title: Raw((columnAlias, parameters) => {
return `${columnAlias} = ANY(${parameters[0]})`;
}, [["About #1", "About #3", "About #5"]]),
likes: Raw((columnAlias, parameters) => `${columnAlias} IN …
```
> feat: add ability for escaping for Raw() find operator

- src/commands/EntityCreateCommand.ts
- src/commands/MigrationCreateCommand.ts
- src/commands/SubscriberCreateCommand.ts
in some cases - where the connection options couldn't be read -
we would end up with the migration:create and similar commands
failing with a TypeError
this refactors the create commands a bit to defend against
an undefined directory, preventing the TypeError
fixes #6831
> fix: prevent create-type commands edge-case TypeErrors

- src/query-builder/transformer/RawSqlResultsToEntityTransformer.ts
- test/github-issues/6833/entity/test.ts
- test/github-issues/6833/issue-6833.ts
Entities with 'jsonb' primary key are not correctly returned. ( see #6833 )
This PR adds a fix and tests for Issue #6833
> fix: allow for complex jsonb primary key columns 

- src/driver/postgres/PostgresDriver.ts
Solves https://github.com/typeorm/typeorm/issues/2614.
* Current behavior:
Users may provide an URL in the connection options which is parsed by a generic function to fill the following fields: host, port, username, password, database.
* Issue:
You can't give an UNIX socket as host with PostgreSQL.
* Corrected behavior:
Provide a `ConnectionUrlParser` class with different parser functions. The default parser function is left unchanged to prevent any regression with other database types. Concerning PostgreSQL a new function is provided which solves the issue. To prevent any regression, I tested myself the function with multiples strings against the default parser.
* Exemple of tested strings
`postgres://user:password@host:5432/database` (standard) …
> fix: postgresql connection URL can use an UNIX Socket

- docs/find-options.md
- test/functional/repository/find-options-operators/repository-find-operators.ts
Closes https://github.com/typeorm/typeorm/issues/6860
(see the discussion there)
- Improves the doc after the recent merge of https://github.com/typeorm/typeorm/pull/6850 
> (feat: add ability for escaping for Raw() find operator)
- add a missing test
- no code change
- waiting for CI to let new test pass
- I didn't test my changes on website as I don't know how to run the site locally: let me know if that is needed
- I'm not a native English speaker so feel free to comment to improve the wordings, if needed, and I will update the PR.
- maybe we shall merge this once (or just before) the code is deployed on npm.
> docs: improve the doc about Raw operator and add missing test

- src/driver/postgres/PostgresQueryRunner.ts
Typeorm currently excludes partitioned tables from schema synchronization. We could also take them into account as their behavior regarding schema modifications is the same as regular tables.
When a table has foreign keys referencing a partitioned table, the `PostgresQueryRunner` will load the constraints from every partition.
We need to ignore those foreign keys as they are not managed by the user.
Example:
`table_A` has a foreign key constraint referencing `table_B` which is a partitioned table on `key1` and `key2`.
The command `typeorm schema:log` will return this kind of list of queries to remove the FK constraints from `table_A`.
```
------------------------------------------------------------------
-- Schema syncronization will execute following sql queries (220): …
```
> Fix schema synchronization for partitioned tables with PostgreSQL 12+

- test/github-issues/4958/entity/first.ts
- test/github-issues/4958/entity/second.ts
- test/github-issues/4958/issue-4958.ts
in #4958 we found that the PR #4804 caused issues in a variety
of situations.  this adds a test to prevent the issue from recurring
where similar classes get mixed up in our metadata resolver
> test: adds test to prevent #4958 from recurring

- package.json
adds the funding key to the manifest as the opencollective
per https://docs.npmjs.com/configuring-npm/package-json.html#funding
fixes #4649
> chore: add `funding` to the package manifest

- src/query-builder/SelectQueryBuilder.ts
- test/functional/query-builder/count/entity/AmbigiousPrimaryKey.ts
- test/functional/query-builder/count/query-builder-count.ts
currently we use concatenation of multiple primary keys and a
COUNT DISTINCT of that to figure out how many records we have
matched in a query.
however, that fails if the records have keys when the keys
are ambigious when concatenated (`"A", "AA"` & `"AA", "A"`)
the fact that we do a distinct can also be a performance impact
that isn't needed when we aren't doing joins
as such, in MySQL & Postgres we can use the built in counting
of multiple distinct values to resolve some of the issues,
and in other environments we can make it SLIGHTLY better by
adding delimiters between the concatenated values.  It is not
perfect because it technically could run into the same issue
if the delimiters are in the primary keys but it's BETTER
in most cases.
also, in cases where we do not perform any joins …
> fix: handle count multiple PK & edge cases more gracefully

- docs/multiple-connections.md
The docs were not very clear about the behavior of read/write replication when performing raw queries.
> Update docs on replication and raw queries

- docs/repository-api.md
Calling `findOne(undefined)` or `findOne(null)` results in potentially unexpected and dangerous behavior.
Ref:
* https://github.com/typeorm/typeorm/issues/4687
* https://github.com/typeorm/typeorm/issues/2500
* https://github.com/typeorm/typeorm/issues/4448
Given the amount of issues opened regarding this behavior, I think it warrants a note in the docs.
> docs: adds note regarding dangerous findOne behavior

- test/functional/connection/modules/blog/subscriber/TestBlogSubscriber.ts
- test/functional/connection/modules/question/subscriber/TestQuestionSubscriber.ts
- test/functional/connection/modules/video/subscriber/TestVideoSubscriber.ts
- test/functional/connection/subscriber/FirstConnectionSubscriber.ts
- test/functional/connection/subscriber/SecondConnectionSubscriber.ts
- test/functional/migrations/generate-command/command.ts
- test/functional/persistence/custom-column-names/persistence-custom-column-names.ts
- test/github-issues/2703/memory-logger.ts
we have a bunch of console loggers in our tests that cause
extra output to be emitted when we don't need it.  because
these were for debugging & not part of the tests success
this removes them
> test: remove console logging from tests

- src/driver/cockroachdb/CockroachDriver.ts
- src/driver/cockroachdb/CockroachQueryRunner.ts
- src/driver/mysql/MysqlDriver.ts
- src/driver/postgres/PostgresDriver.ts
- src/driver/postgres/PostgresQueryRunner.ts
- test/github-issues/5407/entity/User.ts
- test/github-issues/5407/issue-5407.ts
MySQL/MariaDB decimal column is represented like '0.0'.
MysqlDriver.normalizeDefault didn't consider trailing zeros.
User can bypass this by passing default as string, but we
can't guide the zeros by type, so we should convert user input.
Close #6140
Close #5407
> fix: redundant migration with decimal default

- docs/supported-platforms.md
The sql.js project has moved from https://github.com/kripken/sql.js to https://github.com/sql-js/sql.js and now uses https://sql.js.org as its official website.
> Update link to sql.js

- src/persistence/EntityPersistExecutor.ts
- test/github-issues/2065/entity/Post.ts
- test/github-issues/2065/issue-2065.ts
Due to `instanceof` comparison, object without prototype is mistaken for a privative value, throwing `TypeError: Cannot convert object to primitive value.` when trying to `.toString` said object (inside template string).
This mostly effects usage with `graphql` as `graphql-js`, [by design](https://github.com/graphql/graphql-js/pull/504), creates objects by using Object.create(null).
This fix allows saving these objects.    
The fix uses `typeof` instead of `toString` comparison since I see no reason why `new Number/Boolean/Date` should be a supported use case.
Closes: #2065
> fix: resolves issue proto-less object validation

- src/commands/QueryCommand.ts
the CLI command `query` had an implicit `query` positional
parameter and in earlier versions of yargs that was okay -
but in the later versions aiming for more correct code they've
refactored it to not support that
explicitly define the `query` positional parameter & add a
helpful description so people can tell what it is for
fixes #6896
> fix: explicitly define `query` command's param

- src/query-builder/DeleteQueryBuilder.ts
- src/query-builder/InsertQueryBuilder.ts
- src/query-builder/QueryBuilder.ts
- src/query-builder/QueryExpressionMap.ts
- src/query-builder/SelectQueryBuilder.ts
- src/query-builder/UpdateQueryBuilder.ts
- test/functional/query-builder/comment/entity/Test.ts
- test/functional/query-builder/comment/query-builder-comment.ts
add a `comment` method to the QueryBuilder so we can include an
arbitrary comment in our queries for a variety of purposes -  from
query plan stability to SQL reverse proxy routing, to debugging.
the comment builder is supported in selects, inserts, deletes, and
updates
this is directly inspired by the functionality supported by hibernate
to handle SQL Query comments
it uses C-style queries which are ANSI SQL 2003 & supported in all
of the dialects of SQL that we support as drivers
fixes #3643
> feat: support query comments in the query builder

- src/driver/mongodb/MongoQueryRunner.ts
it was using `Db` but instead it's actually `MongoClient`.  Confirmed via the API docs for `node-mongo`, static analysis, and runtime verification.
fixes #6453
> fix: use correct type for MongoQueryRunner.databaseConnection

- src/driver/mysql/MysqlQueryRunner.ts
This changes how we make queries against the MySQL `INFORMATION_SCHEMA` metadata tables to follow [the performance guidelines in the MySQL documentation.](https://dev.mysql.com/doc/refman/8.0/en/information-schema-optimization.html)  This means that the queries are a LITTLE weird, but I included pretty verbose comments on the implementation.
I did an `EXPLAIN` of every query that this generates & runs - each one requires the minimum amount of data to operate on & doesn't scan the database directories.
This is verified via the tests in other locations that it's working still - Not sure the best technique to verify this.
closes #6820
fixes #6800
> perf: Use Optimized Queries for MySQLQueryRunner.loadTables

- src/query-builder/QueryBuilder.ts
- test/functional/repository/find-options-operators/repository-find-operators.ts
we were supporting an empty `IN` clause for MySQL and Oracle
and this updates the handling to be for all other dialects as well
by making the "empty" clause be `0=1`
This follows the lead of a number of other projects in a similar space:
* [Laravel: `1=0`](https://github.com/laravel/framework/blob/8.x/src/Illuminate/Database/Query/Grammars/Grammar.php#L265-L272)
* [SQLAlchemy: `1!=1`](https://docs.sqlalchemy.org/en/13/core/sqlelement.html#sqlalchemy.sql.operators.ColumnOperators.in_)
* [Knex: `1=0`](http://knexjs.org/#Builder-whereIn)
* [Sequel: `1!=1`](https://github.com/jeremyevans/sequel/blob/67cc4245227a6c01ecb20d0138aaf37b05a5aebc/doc/release_notes/3.32.0.txt#L171)
I've also chosen to use `1=0` in the empty case because it's the most likely technique which allows the various query …
> fix: support empty `IN` clause across all dialects

- docs/select-query-builder.md
- src/query-builder/SelectQueryBuilder.ts
- test/functional/query-builder/select/query-builder-select.ts
This adds a `getOneOrFail` which which is to `getOne` as
`findOneOrFail` is to `findOne` - it never returns `undefined`,
it will instead throw an `EntityNotFoundError`
closes #6246
> feat: Add SelectQueryBuilder.getOneOrFail()

- src/commands/QueryCommand.ts
When a query fails and returns `undefined` instead of an actual query set the `QueryCommand` has a `TypeError`.
fixes #6612
> fix: Handle undefined querysets in QueryCommand

- docs/caching.md
Correct the description for setting a custom table name for the typeorm cache.
> docs: correct grammar error in cache description

- test/functional/query-builder/comment/query-builder-comment.ts
The query comment test was causing problems in a few other PRs because it expects a very specific comment then verb pattern - which may or may not always be the case.
> test: make test for query comment less restrictive

- src/driver/DriverUtils.ts
- src/driver/mongodb/MongoDriver.ts
- test/github-issues/6900/entity/Warn.ts
- test/github-issues/6900/issue-6900.ts
When Driver URLs are passed without a database or with other options missing this change will prevent them from overriding explicitly defined values with their undefined values.
fixes #6900
> fix: handle Undefined values in driver URL options

- src/driver/mysql/MysqlDriver.ts
- src/driver/mysql/MysqlQueryRunner.ts
- test/functional/columns/comments/columns-comments.ts
- test/functional/columns/comments/entity/Test.ts
- test/functional/migrations/generate-command/command.ts
- test/functional/schema-builder/change-column.ts
in the mysql driver, column comments were only half supported -
adding them to new columns & new tables was possible, but updating
existing columns to include comments was not possible
adds support to add comments to existing columns & creates tests
to verify the behavior
Closes #6336
> fix: support changing comments in MySQL columns

- src/driver/cockroachdb/CockroachDriver.ts
- src/driver/cockroachdb/CockroachQueryRunner.ts
- src/driver/postgres/PostgresDriver.ts
- src/driver/postgres/PostgresQueryRunner.ts
- test/functional/columns/comments/columns-comments.ts
- test/functional/schema-builder/change-column.ts
adds support for column comments to both the Postgres and
CockroachDB driver - for migrations & in metadata.  also includes
new tests that validate the functionality works as expected
closes #4461
fixes #3360
> feat: Support column comments in Postgres and CockroachDB

- src/logger/Logger.ts
I haven't inspected the code to know if string or any other type does get returned, but this can at least inform people without needing to inspect the code that it can be an easily parsable Error instance.
Closes #6933
> Allow Error to be a type of logQueryError param

- src/metadata-builder/EntityMetadataValidator.ts
- test/github-issues/2984/entity/commit/note.ts
- test/github-issues/2984/entity/issue/note.ts
- test/github-issues/2984/entity/issue/ownernote.ts
- test/github-issues/2984/entity/wiki/note.ts
- test/github-issues/2984/entity/wiki/ownernote.ts
- test/github-issues/2984/issue-2984.ts
If an entity has the same discriminator value as one using
@TableInheritance this should be allowed as there is no way for them to
conflict. Fixes #2984.
> Only check for discriminator conflicts on STI entities

- src/query-builder/QueryBuilder.ts
- test/functional/repository/find-options-operators/repository-find-operators.ts
https://github.com/typeorm/typeorm/issues/4418
Although this issue is already closed, I thought it could do a bit more. It makes ILIKE compatible with non Postgres drivers.
> fix: ILike operator generally available for any driver

- src/repository/TreeRepository.ts
- test/github-issues/6947/entity/Category.ts
- test/github-issues/6947/issue-6947.ts
Previously "id" was hardcoded, thus errors when an entity has a custom primary column name other than "id". 
Now it fetches the column name from metadata instead.
> fix: TreeRepository based entities primary column supports custom name.

- src/metadata/ColumnMetadata.ts
- src/persistence/Subject.ts
- src/query-builder/transformer/RawSqlResultsToEntityTransformer.ts
- test/github-issues/6416/entity/Post.ts
- test/github-issues/6416/entity/PostAttachment.ts
- test/github-issues/6416/entity/PostTag.ts
- test/github-issues/6416/issue-6416.ts
handle setting values deeply in entities with relations in ColumnMetadata,
also check for a virtual relationship column in rawsqlresultstoentitytransformer
this allows us to handle a case where `many-to-one` with explicit composite PKs
columns were failing to persist a second time- instead of correctly updating the
field they would cause an insert to occur leading to a unique PK constraint error
Fixes #6416 
Fixes #4969
Fixes #4122
> fix: support combination of many-to-one/cacade/explicit composite PK 

- docs/many-to-many-relations.md
- docs/one-to-one-relations.md
This will fix the linting error as the `no unused variable` rule is widely used.
> docs: Remove unused variable

- README.md
In the many-to-many photos/albums example - photo.views is required field
I was following through the tutorial using postgres, and my `views` column is defined as:
```typescript
@Column()
views: number
```
Later, I was required to provide `photo.views = 1` for the photo/albums example
> photo.views/isPublished are required fields

- src/decorator/entity/ChildEntity.ts
- src/metadata-builder/EntityMetadataBuilder.ts
- src/metadata-builder/EntityMetadataValidator.ts
- src/query-builder/transformer/RawSqlResultsToEntityTransformer.ts
- test/functional/table-inheritance/single-table/non-virtual-discriminator-column/entity/Other.ts
- test/functional/table-inheritance/single-table/non-virtual-discriminator-column/non-virtual-discriminator-column.ts
- test/functional/table-inheritance/single-table/numeric-types/entity/Person.ts
- test/functional/table-inheritance/single-table/numeric-types/entity/Student.ts
- test/functional/table-inheritance/single-table/numeric-types/entity/Teacher.ts
- test/functional/table-inheritance/single-table/numeric-types/numeric-types.ts
This allows discriminator values in Single Table Inheritance - such as 0, "", or `null`
Before, if you attempted to use a discriminator for `0` you'd receive errors about an invalid
discriminator value, or the metadata just wouldn't register correctly.
Now, you can use a discriminator value that's "falsey" but not `undefined`.
fixes #3891
> fix: allow falsey discriminator values

- src/query-builder/InsertQueryBuilder.ts
- test/github-issues/2434/entity/Item.ts
- test/github-issues/2434/entity/Post.ts
- test/github-issues/2434/issue-2434.ts
change generated insert query to allow inserting an array of objects to oracle
fixes: #2434
> fix: support multiple row insert on oracle

- docs/using-cli.md
- src/commands/MigrationGenerateCommand.ts
This makes `migration:generate` exit with error code 1 if no changes were found. In general I think this qualifies as a non-successful run, but the main benefit is that it allows the command to be used to verify that there are no changes between the code and the current database schema.
I am not sure how best to make a test case for this. Any pointers on this would be appreciated.
Fixes #3037
> Exit with code 1 if no changes were found

- src/repository/TreeRepository.ts
- test/github-issues/6948/entity/Category.ts
- test/github-issues/6948/issue-6948.ts
Previously `findRoots` assumes the primary column of an entity to be named `id`
https://github.com/typeorm/typeorm/blob/a5eb946117a18d94c0157188b6a39542c8d50756/src/repository/TreeRepository.ts#L35-L37
This PR will instead use the column defined by entity class
Fixes #6948, #2361
> fix: findRoots should get the defined primary key column

- src/driver/postgres/PostgresQueryRunner.ts
Use es6 style when making postgres query. 
This helps debugging by avoiding manually constructed promises that have some features broken like stacktraces and CLS support.
> Use pg es6 style when making a query
