src/cli.ts

Use `import yargs = require("yargs")` instead of `import *` to work around [this issue](https://github.com/yargs/yargs/issues/1432#issuecomment-564723085)
Without this change, i see the following behaviour:
```
» typeorm migration:generate --help
Options:
--help     Show help                                                 [boolean]
--version  Show version number
```
with this change, we get the full help
```
» typeorm migration:generate --help
typeorm migration:generate
Generates a new migration file with sql needs to be executed to update schema.
Options:
-h, --help        Show help                                          [boolean]
-c, --connection  Name of the connection on which run a query.
[default: "default"]
-n, --name        Name of the migration class.             [string] …
```

fix: use require style import of yargs for --help

---

src/commands/QueryCommand.ts

Fix TypeError in CLI query command. 
Switch to using the named query property for the CLI `query` command. https://github.com/typeorm/typeorm/pull/6899 modified the command definition with a named positional argument. This leads to an error in 0.2.29 when executing e.g. When executing `npx typeorm query -f path/to/ormconfig.js "query" "SELECT 1"`:
```
Error during query execution:
TypeError: Cannot read property 'replace' of undefined
at escape (/projectPath/node_modules/highlight.js/lib/highlight.js:71:18)
at Object.highlight (/projectPath/node_modules/highlight.js/lib/highlight.js:799:18)
at Object.highlight (/projectPath/node_modules/cli-highlight/dist/index.js:76:21)
at Function.PlatformTools.highlightSql (/projectPath/node_modules/typeorm/platform/PlatformTools.js:186:32)
at …
```

fix: Fix CLI query command TypeError

---

src/query-builder/QueryBuilder.ts
test/github-issues/7030/entity/Post.ts
test/github-issues/7030/issue-7030.ts

we should always prioritize replacement of any property path first,
then property names, then database names, then relation values
whenever there's ambiguous values
fixes #7030

fix: handle overlapping property / database names in querybuilder

---

src/driver/mongodb/MongoDriver.ts

As described in [MongoDB Docs](https://docs.mongodb.com/manual/reference/connection-string/#dns-seed-list-connection-format), an additional connection string format called DNS Seed List Connection format can be used. As this is the default format for MongoDB Atlas, the hosted service of MongoDB, this should be available also for typeorm. 
The connection format is identified by the url-schema "mongodb+srv" and does not allow specifying a port.
When using the DNS seed connection list format, `mongodb+srv` must be used as URL schema and a port must not be provided!
Can simply be verified with a free account of [MongoDB Atlas](https://cloud.mongodb.com), where this connection format is the default when using MongoDB driver 3.6+
Fixes #3347
Fixes #3133
Fixes #7009

fix,feat: support MongoDB DNS seed list connection

---

src/query-builder/QueryExpressionMap.ts
test/github-issues/7203/issue-7203.ts

Closes: #7203
Added missing "comment" filed to QueryExpressionMap.clone() method.
In my understanding, clone method should copy every field, including the "comment" one.
Seems that clone() method was not updated after adding "comment" field to QueryExpressionMap.
In my case I have used "comment" for something special and when calling getManyAndCount(), count query was missing the "comment".
Added a unit test to confirm that clone method copies comment as well.
- [x ] Code is up-to-date with the `master` branch
- [ x] `npm run lint` passes with this change
- [x ] This pull request links relevant issues as `Fixes #7203 `
- [x ] There are new or updated unit tests validating the change
- [ x] The new commits follow conventions explained in …

fix: add missing "comment" field to QueryExpressionMap.clone() method

---

src/common/EntityFieldsNames.ts
src/find-options/FindOneOptions.ts

In "order" clause it should be possible only to pass field-names, not methods.
Fixes: #7178

Github issue 7178: order should allow only model fields, not methods

---

package-lock.json
package.json
src/driver/postgres/PostgresQueryRunner.ts
src/query-builder/SelectQueryBuilder.ts
test/github-issues/7109/entity/Dummy.ts
test/github-issues/7109/issue-7109.ts

Don't release the queryRunner too early from SelectQueryBuilder when streaming queries.
Fixes #7109 
In release 0.2.26, streaming queries for postgres were broken. The problem is that SelectQueryBuilder releases the queryRunner too early (when it might not be connected yet), and therefore prevents release at the appropriate moment (using the release callback) to happen (since it will think that it's already released, and quit).
This PR fixes this by delegating the release of the query runner to the stream callback functions, ensuring that it's called when a connection is certainly established.
To test that streaming queries now work again, I had to add `pg-query-stream` to the dev dependencies.
The unit test I added fails as expected without this PR's changes, but passes with the changes.

fix: avoid early release of PostgresQueryRunner (#7109)

---

README.md

This registry is deprecated now: <https://blogs.sap.com/2017/05/16/sap-npm-registry-launched-making-the-lives-of-node.js-developers-easier/>

Remove SAP registry

---

src/driver/postgres/PostgresQueryRunner.ts
test/github-issues/6990/entity/foo.ts
test/github-issues/6990/issue-6990.ts

Fixes #6990. 
PostgresQueryRunner method loadTables is used to determine if the database is in sync with the entity definitions. This change updates how loadTables determines the length value of array columns. It uses the postgres-specific pg_catalog.pg_attribute table and the pg_catalog.format_type function to find the data type name, which includes the length for types that have a length attribute. Previously, loadTables relied solely on character_maximum_length in information_schema.columns, which is null for array columns. Because of this, array columns with a length attribute were always dropped. 
This also includes a test that confirms the issues is resolved by this fix.

fix: get length attribute of postgres array columns

---

src/repository/Repository.ts

Fixed typos in method documentations:
Intended use of "present" in its meaning as an adjective should be preceded with a verb (in this case, "are").
Fixed an indefinite article before plural noun: "an entities" -> "entities"

Fix typos in Repository.ts

---

src/commands/MigrationCreateCommand.ts
src/commands/MigrationGenerateCommand.ts

This is a proposal that attempts to address the discussion here: https://github.com/typeorm/typeorm/issues/1675
Added a new `-o` / `--outputJs` option to the `migrate:create` and `migrate:generate` commands, to be able to output directly to Javascript. This would help for Javascript only projects in which having TypeScript files as part of the project would complicate maintenance, and eliminates the need for an extra `ts-node` transpiling command to run the `migrate:run`. 
Tested locally the `migrate:create`, by manually running the compiled project `cli.js` file. I didn't manage to link my local build version to work with the generate. I'd like some help or instructions to be able to compile and test the other command.

[FEAT] Optionally output migrations as Javascript files instead of TypeScript

---

src/query-builder/SelectQueryBuilder.ts
test/functional/query-builder/locking/query-builder-locking.ts

Adds `SKIP LOCKED` (pessimistic_partial_write) and `NOWAIT` (pessimistic_write_or_fail) support for Mysql drivers. 
Database support as follows
Database | SKIP LOCKED | NOWAIT
------------ | ------------- | ------------
MySQL | 8.0 | 8.0
MariaDB | Unsupported | 10.3.0
Added test cases, but they do not pass with the current versions listed in docker-compose. (Have tested with the versions listed above and they pass). Generally, how does typeorm handle cases like this?
References: 
https://dev.mysql.com/doc/refman/8.0/en/innodb-locking-reads.html
https://jira.mariadb.org/browse/MDEV-13115
https://mariadb.com/kb/en/wait-and-nowait/

[FEAT] Add NOWAIT and SKIP LOCKED lock support for MySQL

---

src/entity-manager/EntityManager.ts

Workaround is no longer needed after #6927.

fix: Remove Oracle multirow insert workaround (since #6927)

---

src/persistence/EntityPersistExecutor.ts

Floating promises are causing issues with lost stack traces.  Summary of a change:
``` diff
+        await Promise.resolve();
+       // do whatever
-        return Promise.resolve().then(async () => {
-          // do whatever
-       });
```
This hack was added in a4e5abe1610f0eec7061898097f3aa70e8c27c10 and related tests are passing.
Old stack trace in my app:
```
ObjectInvalid: An instance of Domain has failed the validation:
at Domain.validateOrReject (lib/entities/Model.ts:171:13)
```
New stack trace in my app:
```
ObjectInvalid: An instance of Domain has failed the validation:
at Domain.validateOrReject (lib/entities/Model.ts:171:13)
at Domain.captureStack (lib/entities/Model.ts:163:19)
at EntityListenerMetadata.execute (src/metadata/EntityListenerMetadata.ts:71:45)
at …
```

Fix stack traces when using EntityPersistExecutor

---

src/query-builder/RelationLoader.ts
test/github-issues/7146/entity/Category.ts
test/github-issues/7146/entity/Post.ts
test/github-issues/7146/issue-7146.ts

Fix an issue where a lazy relation returns a Promise that resolves to 'undefined'. As implied by
documentation, if the database has a NULL or no results, the result should be a literal 'null'
in Javascript. Also added units tests to hilight the three scenarios in which this occurred.
This PR is to fix reported issue #7146.

 fix: return 'null' (instead of 'undefined') on lazy relations that have no results

---

docs/find-options.md

Add `withDeleted` option to the list of find options on the documentation page.
After reading up on softDelete in #534, it was a bit unclear to me whether soft deleted entities are included in the find results or not and how to change the behavior.

Document withDeleted option

---

docs/find-options.md

Seems like there was an unclosed code block added in #7132 that broke the documentation page's appearance:

Fix invalid code block in "find many options" article

---

src/decorator/options/RelationOptions.ts
src/metadata/RelationMetadata.ts
src/persistence/subject-builder/OneToManySubjectBuilder.ts
test/functional/persistence/delete-orphans/delete-orphans.ts
test/functional/persistence/delete-orphans/entity/Category.ts
test/functional/persistence/delete-orphans/entity/Post.ts

Rebase of #1665 with some modifications.
---
Per @adenhertog from the original PR:
This adds an additional option on one-to-many relationships where child entities are deleted, rather than having their foreign key set to null, when removed from their parent.
Many times we have the situation where a parent entity "owns" a child. An example of this is when a User has a set of `RoleAssignment` in the context of permissions. When a `RoleAssignment` is removed from the user, we expect for the row to be deleted. Previously the row would remain in the database but with the `userId` column set to `null`, leaving an orphaned row that would clog up the table.
This fix allows for `RoleAssignment` to specify on its relationship with `User` that it should be deleted, rather than orphaned, when the …

feat: relations: Orphaned row action

---

src/driver/postgres/PostgresQueryRunner.ts
test/github-issues/7106/entity/ReallyReallyVeryVeryVeryLongTableName.ts
test/github-issues/7106/entity/ShortTableName.ts
test/github-issues/7106/issue-7106.ts

Changes the sequence name generator to handle cases where PostgreSQL auto-generated sequence name differed from TypeORM generated sequence name.
Closes: #7106
Current behaviour: sequence name generator for PostgreSQL does not match PostgreSQL automatic sequence name  implementation for some cases.
New behaviour: now it does.

fix: resolves Postgres sequence identifier length error

---

src/query-builder/SelectQueryBuilder.ts
test/github-issues/7079/entities.ts
test/github-issues/7079/issue-7079.ts

Using `findColumnWithPropertyPath` instead of `findColumnWithPropertyName` in `createOrderByCombinedWithSelectExpression` to fix sorting by embedded entity properties.
Fixes #7079

fix: Error when sorting by an embedded entity while using join and skip/take

---

src/metadata/ColumnMetadata.ts
test/github-issues/6995/entity/default-update-date.ts
test/github-issues/6995/issue-6995.ts

Closes: #6995
When generating migration for MySQL and MariaDB, `@UpdateDateColumn()` now generate a default `ON UPDATE` clause in the `up()` method

fix: resolve migration for UpdateDateColumn without ON UPDATE clause

---

docs/usage-with-javascript.md
docs/zh_CN/usage-with-javascript.md

Updated Javascript usage example in docs/usage-with-javascript.md and docs/zh_CN/usage-with-javascript.md to pass EntitySchema objects in the ConnectionOptions instead of plain objects and changed type:"string" in the schemas to type:"varchar". Also updated docs/zh_CN/usage-with-javascript.md to use "entities" instead of "entitySchemas" in the ConnectionOptions.

docs: fix javascript usage examples

---

test/github-issues/7068/issue-7068.ts

Remove `describe.only` from spec file as this was stopping all other
spec files from running.
Closes #7284

fix: Stop test suite from only running one spec file

---

src/connection/options-reader/ConnectionOptionsEnvReader.ts

`ioredis` cache type does not work when reading from `.env` file or Environment Variables. This PR aims to fix it.

Fix cache from ENV: add ioredis support

---

src/decorator/transaction/Transaction.ts

As mentioned in the issue, I'm renaming `@TransactionEntityManager` to `@TransactionManager` at this file location `typeorm/src/decorator/transaction/Transaction.ts`
Fixes #7304

docs: minor documentation change

---

docs/view-entities.md

I think there was a missing `AS`, isn't it?

chore: fixed Alias in SQL expression

---

src/decorator/columns/PrimaryGeneratedColumn.ts
src/driver/types/ColumnTypes.ts

passing `{type: "uuid"}` as a parameter to `PrimaryGeneratedColumn` is valid given the TS types. but strategy is set to `increment` instead of `uuid`
this change fixes it. I think it would be worthwhile to tighten the parameters type definition instead of having a large union
Fixes #6039

better postgres uuid column handling

---

src/query-builder/SelectQueryBuilder.ts
test/github-issues/6265/entity/Role.ts
test/github-issues/6265/entity/User.ts
test/github-issues/6265/issue-6265.ts

This pull request includes fix for soft delete behavior when including soft deletes relationships. 
fix: resolve issue with find with relations returns soft-deleted entities #6265

fix: resolve issue with find with relations returns soft-deleted entities

---

src/driver/oracle/OracleConnectionOptions.ts
src/driver/oracle/OracleDriver.ts
src/driver/postgres/PostgresConnectionOptions.ts
src/driver/postgres/PostgresDriver.ts

If useUTC is set to true, then for Oracle set environment variable 'ORA_SDTZ' and for postgres set 'PGTZ'.
Based on documentation I thought 'useUTC' was used for all databases, but it was actually set only for MSSQL.
If this option is set to true then I am setting environment variables for oracle and Postgres.

useUTC for oracle and postgres

---

docs/migrations.md

Incorrect table is referenced in an example that shows how to use migrations API.
This change references the correct tables that allow migrations:revert to  drop the foreign key and newly added column.
Here is the error when `migrations:revert` is run on the Migrations API example code.
```
Error during migration revert:
Error: Supplied foreign key was not found in table question
```
After applying the change, here is the output when `migrations:revert` was run in a test migration
```
Migration TestQuestionAnswer1610926293858 has been executed successfully.
query: COMMIT
✨  Done in 5.26s.
```
- [n/a] `npm run lint` passes with this change
- [n/a] `npm run test` passes with this change
- [n/a ] This pull request links relevant issues as `Fixes #0000`
- [n/a] There are new or updated unit …

docs: fix revert example code for migration api

---

package-lock.json
package.json
src/driver/sqlserver/SqlServerQueryRunner.ts

This upgrades the `mssql` driver to version 7 to resolve #3202. This
issue was created in the bulk insert test adding a datetime2 field
with a time of midnight.
v7 no longer allows numeric parameter names and was throwing an error
inside tedious but you can see that `node-mssql` is expecting a string.
https://github.com/tediousjs/node-mssql/blob/76585f973dd8cad48836fe302f99f67d47ff6129/lib/base/request.js#L101
Another user saw this issue in the comments of issue #3202.
https://github.com/typeorm/typeorm/issues/3202#issuecomment-734926616
Stringifying the numeric parameter names before it enters the driver
resolves this issue.
Now all mssql tests pass locally once you provide additional config in
`ormconfig.json` locally required for a locally running docker instance
of mssql which uses a …

fix: datetime2 rounding in mssql

---

src/query-builder/InsertQueryBuilder.ts
test/functional/query-builder/insert-on-conflict/entity/Post.ts
test/functional/query-builder/insert-on-conflict/query-builder-insert-on-conflict.ts

Fixies this use-case
```typescript
await repository
.createQueryBuilder()
.insert()
.values({
name,
code,
createdAt: new Date(),
updatedAt: new Date(),
})
.orUpdate({
conflict_target: ['name'],
overwrite: ['code', 'updatedAt'],
})
.execute();
```
because it generates:
```sql
INSERT INTO "my_table"("id", "name", "code", "createdAt", "updatedAt") VALUES (DEFAULT, $1, $2, $3, $4) ON CONFLICT  ( name )  DO UPDATE SET code = EXCLUDED.code, updatedAt = EXCLUDED.updatedAt
```
and it causes:
```
ERROR:  column excluded.updatedat does not exist
LINE 1: ...  DO UPDATE SET code = EXCLUDED.code, updatedAt = EXCLUDED.u...
^
HINT:  Perhaps you meant to reference the column "excluded.updatedAt".
```
instead of:
```sql
INSERT INTO "my_table"("id", "name", "code", "createdAt", "updatedAt") VALUES …
```

escape columns in InsertQueryBuilder.orUpdate

---

src/decorator/columns/PrimaryColumn.ts
test/github-issues/4570/issue-4570.ts

Every supported back-end requires that primary key columns be non-nullable.
As of this PR, this mistake is caught at compile-time rather than as part of execution.
BREAKING CHANGE: passing `ColumnOptions` to `@PrimaryKeyColumn` does not function anymore. One must use `PrimaryKeyColumnOptions` instead.
Forbid primary columns from being marked as nullable. This condition is expected by all currently-supported back-ends and is generally understood to be standard.
As of the time this PR was opened, some of the tests aren't passing on my machine, and I've not touched documentation. I'd like to validate that this change is desired and likely to be merged before spending more time on it.

fix: reject nullable primary columns

---

src/driver/mysql/MysqlQueryRunner.ts

Fixes #2691
query failed: ALTER TABLE `customer` CHANGE `fullName` `fullName` varchar(255) AS (CONCAT(`firstName`, ' ', `lastName`)) VIRTUAL NULL
error: Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'NULL' at line 1

Fix MariaDB VIRTUAL [NOT NULL|NULL] error

---

src/query-builder/InsertQueryBuilder.ts
test/github-issues/2199/issue-2199.ts

Allow explicit insertion of preset values for mssql IDENTITY columns. These are the equivalent to
auto-incrementing primary keys in MySQL, but require special conditional treatment.
Closes: #2199 for mssql

fix: enable explicitly inserting IDENTITY values into mssql

---

src/driver/Driver.ts
src/driver/aurora-data-api/AuroraDataApiDriver.ts
src/driver/cockroachdb/CockroachDriver.ts
src/driver/mongodb/MongoDriver.ts
src/driver/mysql/MysqlDriver.ts
src/driver/mysql/MysqlQueryRunner.ts
src/driver/oracle/OracleDriver.ts
src/driver/postgres/PostgresDriver.ts
src/driver/postgres/PostgresQueryRunner.ts
src/driver/sap/SapDriver.ts
src/driver/sqlite-abstract/AbstractSqliteDriver.ts
src/driver/sqlserver/SqlServerDriver.ts
src/metadata/ColumnMetadata.ts
src/query-builder/InsertQueryBuilder.ts
test/functional/migrations/generate-command/command.ts
test/functional/migrations/generate-command/entity/category.entity.ts
test/functional/migrations/generate-command/entity/post.entity.ts
test/functional/migrations/generate-command/entity/tag.entity.ts
test/github-issues/6950/entity/post_with_null_1.entity.ts
test/github-issues/6950/entity/post_with_null_2.entity.ts
test/github-issues/6950/issue-6950.ts

Fixed wrong migration generation when column `default` value is set to `null`.
Additionally fixed wrong `comment` comparisons.
refactor: removed `public` schema from test since it is not related to the testing subject and causes `mssql` driver fail because `public` is reserved keyword in SqlServer.
Fixes: #6950

fix: wrong migration generation when column default value is set to null #6950

---

src/entity-manager/EntityManager.ts

This brings it in line with the [equivalent method](https://github.com/typeorm/typeorm/blob/fde9f0772eef69836ff4d85816cfe4fd6f7028b4/src/repository/Repository.ts#L122-L144) in Repository, which was originally changed with #2796.
* As long as `{ reload: false }` isn't specific in the `options`, the response should be `T & Entity`, not just `T`.
* The docstrings for the non-array versions should be singular, not plural.
- I can't find a relevant issue for this.
- Since this is just a typings change, I don't think there are any additional unit tests to make for it?

fix: improve EntityManager.save() return type

---

src/repository/TreeRepository.ts
test/github-issues/7415/entity/Category.ts
test/github-issues/7415/entity/Slug.ts
test/github-issues/7415/issue-7415.ts

Closes: #7415
Simply replaced all occurrences of
```ts
entity[this.metadata.primaryColumns[0].propertyName]
```
with
```ts
this.metadata.primaryColumns[0].getEntityValue(entity)
```
in the TreeRepository to be consistent in order for the comparisons to be processed correctly. More explanation in the linked issue.

fix: resolve issue building tree entities with embeded primary column

---

src/connection/Connection.ts
src/driver/DriverUtils.ts
src/driver/mongodb/MongoConnectionOptions.ts
src/driver/mongodb/MongoDriver.ts

- Dupplicate buildDriverOptions for mongodb especially
- Add hostReplicaSet to MongoConnectionOptions properties for collect host replica list
- Adjust buildConnectionUrl to build replica set connection url
```
case "mongodb":
return DriverUtils.buildMongoDBDriverOptions(options).database;
```
Use dupplicate DriverOptions for MongoDB especially (not effect another driver).
```
static buildMongoDBDriverOptions(options: any, buildOptions?: { useSid: boolean }): any {
if (options.url) {
const urlDriverOptions = this.parseMongoDBConnectionUrl(options.url) as { [key: string]: any };
```
Dupplicate DriverOptions for MongoDB especially to call specific parseConnectionUrl (not effect another driver).
```
if (afterBase && afterBase.indexOf("?") !== -1) {
// split params to get replica set …
```

fix: Adjust mongodb driver options & connect driver to support replica set

---

src/query-builder/relation-id/RelationIdLoader.ts
test/github-issues/5691/enity/Child1.ts
test/github-issues/5691/enity/Child2.ts
test/github-issues/5691/enity/Root.ts
test/github-issues/5691/enity/Shared.ts
test/github-issues/5691/issue-5691.ts

Fixes #5691
Fixing performance issues of `RelationId`.
For example, we have users and a company.
We want to select the company with relation ids.
There are 100k users, and all of them belong to the same company.
So we select `users.company`,
it selects 100k users and 100k companies, but these 100k companies are the same entity,
because all users belong to the same company.
Let's imagine, that the company has adminId, and we want it to be selected via `RelationId`.
The issue is that currently typeorm simply joins ids of entities,
so the query has 100k times `company.id = NNN or company.id = NNN or ...`, whereas NNN is the same id,
and because the query is very long, MySQL dies when parses it.
The changes reduce ids to be an unique array, so 100k ids will become a single id.

Fixing performance issues of `RelationId`.

---

src/driver/postgres/PostgresDriver.ts
test/github-issues/1532/entity/User.ts
test/github-issues/1532/issue-1532.ts

Array defaulting for PostgreSQL would generate a change to the comment and the default value every time you ran `typeorm migration:generate`.
Example:
```
await queryRunner.query(`
COMMENT ON COLUMN "users"."array" IS NULL
`);
await queryRunner.query(`
ALTER TABLE "users"
ALTER COLUMN "array"
SET DEFAULT '[]'
`);
```
Fixes #1532

fix(1532) Array type default value should not generate SQL commands without change

---

src/commands/MigrationGenerateCommand.ts

There was some disagreement with a previous change I suggested in https://github.com/typeorm/typeorm/pull/6978. The proposal to (also) add a "check" mode makes sense, so I have added that here, but kept backwards compatibility when the new flag is not used.
In addition there was a feeling that the original issue, https://github.com/typeorm/typeorm/issues/3037, was not resolved, and rightly so. So I have also added a "dryrun" mode that will print out the migration instead of writing it to a file.
Hopefully fixes #3037

feat: Add check and dryrun to migration generate

---

src/metadata-builder/EntityMetadataBuilder.ts
test/other-issues/table-name-relation/entity/Category.ts
test/other-issues/table-name-relation/entity/Photo.ts
test/other-issues/table-name-relation/entity/Profile.ts
test/other-issues/table-name-relation/entity/Question.ts
test/other-issues/table-name-relation/entity/User.ts
test/other-issues/table-name-relation/table-name-relation.ts

Supplemental to #4190/#4195, also allows specifying the table name as a string in the relation.
WIth
```
@Entity('profiles')
class Profile {
// ...
}
// then the relation can be made with
@OneToOne('profiles')
```

feat(RelationDecorators): allow to pass the given table name as string

---

src/persistence/SubjectChangedColumnsComputer.ts
test/other-issues/transformed-json-column-update-compute/entity/json-entity.ts
test/other-issues/transformed-json-column-update-compute/entity/jsonb-entity.ts
test/other-issues/transformed-json-column-update-compute/test-transformer.ts
test/other-issues/transformed-json-column-update-compute/transformed-json-column-update-compute.ts

Changes introduced in #5700 lead to JSON / JSONB columns with transformers incorrectly computed for updates, leading to an update being computed even when the column data has not changed.

fix: correctly compute update changes for json / jsonb columns with transformers

---

docs/many-to-one-one-to-many-relations.md

Change word alternative to alternatively as this is the correct English grammar.

fix typo: docs - one to many

---

src/driver/aurora-data-api/AuroraDataApiDriver.ts
test/github-issues/2131/issue-2131.ts

Closes: #7385
Propagate the same fix that was done mysql to the Aurora Data API driver implementation.
This will make the InsertResult.identifiers property contain the correct IDs for bulk-inserts.

fix: (aurora-data-api) get correct increment primary key for multiple entities inserted

---

src/query-builder/DeleteQueryBuilder.ts
src/query-builder/UpdateQueryBuilder.ts
test/github-issues/1308/issue-1308.ts
test/github-issues/2499/issue-2499.ts

Closes: #7386
Add correct parsing of raw result for Aurora Data API (mysql-based) driver so that number of records updated are copied to the "generic" affected property.

fix: [aurora-data-api] Return number of affected rows in UpdatedResult and DeleteResult

---

src/driver/mysql/MysqlDriver.ts
src/query-builder/RelationQueryBuilder.ts
test/functional/transaction/transaction-with-load-many/entity/Category.ts
test/functional/transaction/transaction-with-load-many/entity/Post.ts
test/functional/transaction/transaction-with-load-many/transaction-load-many.ts

Pass queryRunner in order to use existing transaction. **Since testing is not complete, changes can not be merged yet.**
Todo:
- Find a way to test which connection from connection pool is used 
Fixes: #5338

relationLoader: load with existing queryRunner

---

src/driver/mysql/MysqlConnectionCredentialsOptions.ts
src/driver/mysql/MysqlDriver.ts

Currently, Typeorm doesn't support socket connections for replicas. We use Google CloudSQL (mysql) and the preferred way to connect to CloudSQL from Cloud Run is sockets. The implementation is pretty straight forward and works the same as the none replica configuration; when a socketPath is set the host and port are ignored.

Added socketPath support for replicas

---

src/driver/sqlserver/SqlServerConnectionCredentialsOptions.ts
src/driver/sqlserver/SqlServerDriver.ts
src/driver/sqlserver/authentication/AzureActiveDirectoryAccessTokenAuthentication.ts
src/driver/sqlserver/authentication/AzureActiveDirectoryMsiAppServiceAuthentication.ts
src/driver/sqlserver/authentication/AzureActiveDirectoryMsiVmAuthentication.ts
src/driver/sqlserver/authentication/AzureActiveDirectoryPasswordAuthentication.ts
src/driver/sqlserver/authentication/AzureActiveDirectoryServicePrincipalSecret.ts
src/driver/sqlserver/authentication/DefaultAuthentication.ts
src/driver/sqlserver/authentication/NtlmAuthentication.ts

When I was modifying `mmsql` package, I noticed that it accepts `authentication` parameters in the config object. See discussion under PR https://github.com/tediousjs/node-mssql/pull/1208 and documentation I've updated https://github.com/tediousjs/node-mssql#tedious. It passes authentication configuration directly to the `tedious` library, which supports the following authentication types.
- `DefaultAuthentication`
- `NtlmAuthentication`
- `AzureActiveDirectoryAccessTokenAuthentication`
- `AzureActiveDirectoryMsiAppServiceAuthentication`
- `AzureActiveDirectoryMsiVmAuthentication`
- `AzureActiveDirectoryPasswordAuthentication`
- `AzureActiveDirectoryServicePrincipalSecret`
I copied authentication options interfaces directly from the `tedious` repository and modified TypeORM code to …

Add support for Access Token Authentication for SQL Server Driver (mssql)

---

src/query-builder/transformer/RawSqlResultsToEntityTransformer.ts
test/github-issues/7041/entity/Admin.ts
test/github-issues/7041/entity/Organization.ts
test/github-issues/7041/entity/OrganizationMembership.ts
test/github-issues/7041/entity/User.ts
test/github-issues/7041/entity/index.ts
test/github-issues/7041/issue-7041.ts

Closes: #7041
If there is a nested join for example User->OrganizationMembership->Organization and there is no OrganizationMembership for an User currently 
- it's returning empty Entity (all fields are nulls) for oneToOne relations
- it's returning an array with one element - empty Entity for many relations
the new behavior
- returns null for oneToOne relations
- returns empty array for many relations
Example old
User{id: "1", name: "me", membership: {id: null, organization: null}}
User{id: "1", name: "me", membership: [{id: null, organization: null}}]
Example new
User{id: "1", name: "me", membership: null}
User{id: "1", name: "me", membership: []}
Fixes #7041 
Fixes #3163
Fixes #3145

fix: empty entity when query with nested relations

---

src/driver/postgres/PostgresQueryRunner.ts
test/functional/query-runner/rename-table.ts

rename a sequence related to generated primary key when a table is renamed

---

src/driver/aurora-data-api/AuroraDataApiQueryRunner.ts
src/driver/cockroachdb/CockroachQueryRunner.ts
src/driver/mysql/MysqlQueryRunner.ts
src/driver/postgres/PostgresQueryRunner.ts
test/github-issues/7479/entity/Post.ts
test/github-issues/7479/issue-7479.ts

Fixed column `comment` escaping for databases that currently supports `comment` option: 
* PostgreSQL
* MySQL
* CockroachDB
* AuroraDataAPI
Fixes #7479

fix: Only first single quote in comments is escaped

---

docs/find-options.md

This PR updates `docs/find-options.md` to reflect actually supported lock modes and their behavior in [latest master](https://github.com/typeorm/typeorm/blob/e1e94236e71c14a4682356ada7774d657eba8936/src/query-builder/SelectQueryBuilder.ts) (looking at a few other PRs I assumed this is the only file lock modes get interpreted) .

docs: update lock modes in find-options.md

---

src/driver/DriverUtils.ts
src/find-options/FindOptionsUtils.ts
src/query-builder/SelectQueryBuilder.ts
src/query-builder/relation-id/RelationIdLoader.ts
src/query-builder/transformer/RawSqlResultsToEntityTransformer.ts

Fixes #7508
I've found the issue, its [here](https://github.com/typeorm/typeorm/blob/fde9f0772eef69836ff4d85816cfe4fd6f7028b4/src/find-options/FindOptionsUtils.ts#L264), the function is missing the length check for the `relationAlias` var. I decided to use `StringUtils.hash(relationAlias)` (used [here](https://github.com/typeorm/typeorm/blob/fde9f0772eef69836ff4d85816cfe4fd6f7028b4/src/driver/DriverUtils.ts#L52)) and changed `StringUtils.shorten(relationAlias)` (used [here](https://github.com/typeorm/typeorm/blob/fde9f0772eef69836ff4d85816cfe4fd6f7028b4/src/find-options/FindOptionsUtils.ts#L240)) to use the hash function to keep it consistent.

fix: Postgres identifier exceeds limit on eager relations (#7508)

---

src/error/QueryFailedError.ts

Defining those properties allow users to access a typed error like:
```ts
if (error instanceof QueryFailedError) {
// This will be typed
console.log(error.query, error.parameters);
}
```

fix: define class properties for QueryFailedError

---

src/driver/mongodb/typings.ts

deprecation was overturned
see: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/mongodb/index.d.ts#L1488-L1507

fix: mongodb typings for findOne method

---

src/driver/aurora-data-api/AuroraDataApiDriver.ts
src/driver/aurora-data-api/AuroraDataApiQueryRunner.ts
src/driver/cockroachdb/CockroachDriver.ts
src/driver/cockroachdb/CockroachQueryRunner.ts
src/driver/mysql/MysqlDriver.ts
src/driver/mysql/MysqlQueryRunner.ts
src/driver/postgres/PostgresDriver.ts
src/driver/postgres/PostgresQueryRunner.ts
test/github-issues/7521/entity/Post.ts
test/github-issues/7521/issue-7521.ts

fixed escaping in column `comment`.
Fixes #7521

fix: only first `\0` is removed in comments, only first `\\` is escaped etc.

---

src/metadata/IndexMetadata.ts
src/metadata/UniqueMetadata.ts
test/github-issues/6752/entity/Block.ts
test/github-issues/6752/entity/PlanOfRecord.ts
test/github-issues/6752/issue-6752.ts

fix: column name with empty spaces causes bug in `Index`/`Unique` decorators

---

src/driver/sqlite-abstract/AbstractSqliteQueryRunner.ts
test/github-issues/2376/entity/User.ts
test/github-issues/2376/issue-2376.ts

Fixed `@Unique` constraint name behavior in SQLite. Looks like other drivers was already fixed because test is successfully passing.
Fixes #2376 
Fixes #4795
Fixes #5155

fix: `@Unique` constraint is not created with specified name

---

docs/select-query-builder.md

When using the QueryBuilder, unique parameters need to be provided in WHERE expressions. This commit adds that information to the docs, as it's easy to overlook for users. Took us 2 hours to figure out this was causing a bug in our application.
Also reported in https://github.com/typeorm/typeorm/issues/1322#issuecomment-351032081

docs: add note about unique parameters in QueryBuilder

---

src/driver/DriverUtils.ts
test/github-issues/7401/issue-7401.ts
test/github-issues/7437/issue-7437.ts

- Loop every options in mongodb connection url and turn it as object to merge with connection url object before return of method "parseMongoDBConnectionUrl"
- unit test of mongodb replicaset parse connectionurl of #7401
- unit test of mongodb options parse connectionurl of #7437
```
const optionsList = afterQuestionMark.split("&");
let optionKey: string;
let optionValue: string;
optionsList.forEach(optionItem => {
optionKey = optionItem.split("=")[0];
optionValue = optionItem.split("=")[1];
optionsObject[optionKey] = optionValue;
});
```
Loop to create option object **"optionsObject"**. Example, with connection string below
```
mongodb://testuser:testpwd@test-primary.example.com:27017/testdb?retryWrites=true&w=majority&useUnifiedTopology=true
```
It'll turn options to 
```
{
retryWrites: …
```

fix: mongodb connectionurl parse options [Update Clear PR without Merge commits]

---

src/entity-schema/EntitySchemaRelationOptions.ts
src/entity-schema/EntitySchemaTransformer.ts

Adds support for setting the action for orphaned relation rows when using separate entity definitions
Fixes #7417
As described in #7105 it's useful to be able to delete an orphaned relationships row however that pull request only added support for enabling the behaviour with decorators. This pull request also adds support for the `orphanedRowAction` prop in `EntitySchemaRelationOptions` so we can also use it when defining our models using separate entity schemas.

feat: add schema support for orphanedRowAction

---

docs/one-to-one-relations.md

Reason: When documentation opened in browser, on clicking the "cascades" link, it indeed redirects to `https://typeorm.io/#/https://github.com/typeorm/typeorm/blob/master/docs/relations/cascades` instead of `https://github.com/typeorm/typeorm/blob/master/docs/relations/cascades`

Fix Redirecting for "cascades"

---

src/metadata/ColumnMetadata.ts
test/github-issues/7651/entity/order-test.entity.ts
test/github-issues/7651/entity/order.ts
test/github-issues/7651/issue-7651.ts

Fixes: #7651
In case if we are working with enums that contains functions (declaration merging, described in details in [issue ticket](https://github.com/typeorm/typeorm/issues/7651)) corrupted SQLs are generated for migration which leads into failure on the DB side. This fix addresses that issue by filtering out such functions from metadata.

fix: resolve issue when enum that has functions is used in entity

---

docs/select-query-builder.md
src/query-builder/QueryExpressionMap.ts
src/query-builder/SelectQueryBuilder.ts
test/functional/query-builder/select/query-builder-select.ts

Support  `MAX_EXECUTION_TIME` hint for MySQL driver.
Fix #7639

Support max execution time for MySQL driver.

---

src/driver/aurora-data-api/AuroraDataApiDriver.ts
src/driver/aurora-data-api/AuroraDataApiQueryRunner.ts

The set type was already added to typeorm with tests, but it was not yet added to aurora-data-api. This simply adds the same needed code there, and has been tested with a migration on another codebase that successfully created a 'set' column using data-api.
Uses same changes from https://github.com/typeorm/typeorm/pull/4538 but in the data-api files.

add set datatype support for aurora-data-api

---

src/metadata-builder/JunctionEntityMetadataBuilder.ts
test/github-issues/4980/entity/Author.ts
test/github-issues/4980/entity/Book.ts
test/github-issues/4980/issue-4980.ts

Closes: #4980
I'm not sure if onDelete/onUpdate options are handled properly, it seems to me that they must be applied to foreign keys pointing to OPPOSITE entity, not to entity they are used in, but such changes break existing tests, so I considered to fix this issue not breaking them.

fix: pass `ManyToMany` `onUpdate` option to foreign key metadata

---

src/driver/postgres/PostgresDriver.ts

Fix #7691
I just removed `PostgresDriver.enableExtension` on slave connections.

Fixes `PostgresDriver.enableExtensions` is runned on slave connection

---

src/driver/mongodb/MongoDriver.ts

Change was for MongoDriver's buildConnectionUrl method for building a connection url for a replica set.
Currently the host that is used is the config option called "hostReplicaSet"
The change updates this so that if this option is not provided it uses a provided "host" with the given port.
It also defaults to using "127.0.0.1" as a host if none is provided, and "27017" if no port was provided.
This change was needed because I did not provide a connection url to my typeorm config, but I provided all other neccessary info to build a connection url. However, I provided only a "host" and not "hostReplicaSet" which caused it to create a url with the host "undefined". I tested this on an environment with a replica set.

fix:use host if hostReplicaSet is not provided

---

src/query-builder/SelectQueryBuilder.ts
test/github-issues/5809/entity/Role.ts
test/github-issues/5809/entity/User.ts
test/github-issues/5809/issue-5809.ts

There's a small bug (for at least Postgres) when you make a query like the following one:
```typescript
qb.select("post.name")
.where({
category: {id: 1},
title: "foo",
})
```
This will result in both parameters being listed as `$1` in the resulting query. This PR fixes this by resetting the `parameterIndex` in `buildWhere()` to the new value after relation conditions have been applied.
Current workaround for this issue is to list properties of the parent in the find conditions first and the relations last.
I was initially writing a test for that, but ran into another bug, which is pretty hard for me to solve due to the architecture, so I hope a maintainer can have a look at that:
When calling `getSql()`, findOptions are not being applied, this is only done when calling query methods like …

Increment parameter index after relation condition

---

src/metadata-args/MetadataArgsStorage.ts
src/metadata-builder/EntityMetadataBuilder.ts
test/functional/table-inheritance/single-table/no-type-column/entity/Author.ts
test/functional/table-inheritance/single-table/no-type-column/entity/Employee.ts
test/functional/table-inheritance/single-table/no-type-column/entity/Note.ts
test/functional/table-inheritance/single-table/no-type-column/entity/Person.ts
test/functional/table-inheritance/single-table/no-type-column/entity/PostItNote.ts
test/functional/table-inheritance/single-table/no-type-column/entity/StickyNote.ts
test/functional/table-inheritance/single-table/no-type-column/no-type-column.ts

This allows using a single table for multiple entities without using a
type column. Some databases infer the type from the context of how/where
the row is loaded.

Use most specific matching relation type

---

src/metadata-args/MetadataArgsStorage.ts
src/metadata-builder/EntityMetadataBuilder.ts
src/query-builder/transformer/RawSqlResultsToEntityTransformer.ts
test/functional/table-inheritance/single-table/no-type-column/entity/Author.ts
test/functional/table-inheritance/single-table/no-type-column/entity/Employee.ts
test/functional/table-inheritance/single-table/no-type-column/entity/Note.ts
test/functional/table-inheritance/single-table/no-type-column/entity/Person.ts
test/functional/table-inheritance/single-table/no-type-column/entity/PostItNote.ts
test/functional/table-inheritance/single-table/no-type-column/entity/StickyNote.ts
test/functional/table-inheritance/single-table/no-type-column/no-type-column.ts
test/functional/table-inheritance/single-table/relations/child-relation-type/child-relation-type.ts
test/functional/table-inheritance/single-table/relations/child-relation-type/entity/Accountant.ts
test/functional/table-inheritance/single-table/relations/child-relation-type/entity/Data.ts
test/functional/table-inheritance/single-table/relations/child-relation-type/entity/Department.ts
test/functional/table-inheritance/single-table/relations/child-relation-type/entity/Person.ts
test/functional/table-inheritance/single-table/relations/child-relation-type/entity/Specialization.ts
test/functional/table-inheritance/single-table/relations/child-relation-type/entity/Teacher.ts

Note: This requires (and includes the commit from) PR #2967 otherwise you don't get the right type in the child's relation anyway.
If an STI child overrides a parent property and uses a different type doing a query on the parent type will skip the relation. This happens because the query's join is built using the parent relation but when mapping to an entity the child's relation is fetched so they don't match. Instead, we now use the relation's `propertyPath` to allow using relations that reference the same property. We also copy the child's relation type into the join to ensure we get the right type in the child as well.

Fix STI types on children in joins

---

src/driver/postgres/PostgresQueryRunner.ts
test/github-issues/5132/entity/foo.entity.ts
test/github-issues/5132/issue-5132.ts
test/github-issues/7110/entity/foo.entity.ts
test/github-issues/7110/issue-7110.ts

Use better regex to remove only type conversion, not the whole string to the end
Closes: 7110
When loading schema with postgres driver typeorm currently strips explicit type conversions from column default value. But current RegExp in some cases does this incorrectly, that leads to part of string after conversion being stripped to the end. 
For example value `to_char(nextval('orders_display_id_seq'::regclass), 'FMU999'::text)` is stripped to just `to_char(nextval('orders_display_id_seq'`. This behaviour causes duplications when generating migrations.  
Fixes #7110
Fixes #5132

fix: correctly strip type conversion in postgres for default values

---

src/driver/postgres/PostgresDriver.ts
test/github-issues/7650/entity/Test.ts
test/github-issues/7650/issue-7650.ts

Hello. First of all, I am not a typeorm expert but this is my attempt at solving a problem that I encountered. Please feel free to update this branch to make any kind of change (maintainers can update the branch). I may very well have missed certain edge cases since I did not test this extensively.
Postgres sorts the `json` and `jsonb` values before saving them. Additionally, postgres has different whitespacing than `JSON.serialize` so just pre-sorting the values will still cause persistent migrations. So if you have anything other than an empty object then you will always see a persistent migration. This PR adds a new method that parses the JSON default that is used in the table, and then does a `deepCompare` on the two objects.
This kind of thing is already done in another part of the …

fix: postgres: do a deep comparison to see if the default value has changed for json types

---

docs/zh_CN/separating-entity-definition.md

fix description of Spread Operator from " ``` " (×) to "..."（√）in separating-entity-definition.md

---

src/connection/options-reader/ConnectionOptionsYmlReader.ts
test/functional/connection-options-reader/configs/yaml/test-yaml.yaml
test/functional/connection-options-reader/connection-options-reader.ts

this uses the correct `load` function instead of `loadAll`
Fixes #7531

fix: correctly load yml in ConnectionOptionsYmlReader

---

test/functional/connection-options-reader/connection-options-reader.ts

Remove "properly loads config from yaml" as an exclusive test run

Remove "properly loads config from yaml" as an exclusive test run

---

docker-compose.yml

Updates our `docker-compose` so that we are using cockroachDB v21 in our tests.
It has a number of improvements that help with performance in single-node scenarios
such as testing infrastructure.

Use CockroachDB v21 when testing

---

src/commands/MigrationGenerateCommand.ts

Continuation of #6807. It seems one CLI command was missed when supporting absolute paths.
I simply copied the solution from [migration create](https://github.com/typeorm/typeorm/blob/master/src/commands/MigrationCreateCommand.ts#L71-L74).

Support absolute path in migration:generate

---

package-lock.json
package.json

fixes #7489
this bumps our cli-highlight package so we no longer
get deprecation warnings during normal use

chore: bump cli-highlight package to 2.1.11

---

src/entity-manager/MongoEntityManager.ts
test/github-issues/7788/entity/test.entity.ts
test/github-issues/7788/issue-7788.ts
test/utils/test-utils.ts

Update operation should update all matched documents, but now it updates the first found document
Closes: #7788
In current solution, when you perform update operation for MongoDB, only the first found document, that is matching the search condition, is updated. This PR is fixing this problem, making update to all documents which are supposed to be modified making update operation.

fix: update operation in MongoDB impact all matched documents

---

.circleci/config.yml

node v10 EOL was 2021-04-30 and is no longer supported
as an LTS release.  as such, we're going to start seeing
failures with dependencies against it and will not be
developing with automated tests against it

chore: drop node v10 and add v14 to the circleci tests

---

src/query-builder/DeleteQueryBuilder.ts
src/query-builder/SelectQueryBuilder.ts
src/query-builder/SoftDeleteQueryBuilder.ts
src/query-builder/UpdateQueryBuilder.ts
src/query-builder/WhereExpression.ts

updates interface + implementations so `andWhere` and `orWhere` will accept `ObjectLiteral` and `ObjectLiteral[]` as parameters.
the underlying code supported it but it wasn't typed correctly.

fix: add ObjectLiteral to andWhere / orWhere

---

docs/connection-options.md
src/connection/BaseConnectionOptions.ts
src/metadata/EmbeddedMetadata.ts
src/metadata/EntityMetadata.ts
src/query-builder/transformer/DocumentToEntityTransformer.ts
src/query-builder/transformer/PlainObjectToNewEntityTransformer.ts
src/query-builder/transformer/RawSqlResultsToEntityTransformer.ts
test/functional/entity-metadata/entity-metadata-create.ts
test/functional/entity-metadata/entity/TestCreate.ts

this adds the option for bypassing the constructor when deserializing
the Entities.  note that this may cause problems with class-based
JavaScript features that rely on the constructor to operate - such as private
properties or default values
fixes #1772

feat: add connection option `entitySkipConstructor`

---

src/driver/aurora-data-api-pg/AuroraDataApiPostgresQueryRunner.ts
src/driver/postgres/PostgresQueryRunner.ts

fixes #5112 
passes the error back to the `pg-pool` release callback.
there aren't tests, though - because we don't really do mocking of the database for our tests & forcing a failing database is rather difficult.  until we can more gracefully do mocks / spies / etc, I'm not sure the best way to verify this functionality.
I did verify it by running a long running query, `kill -TERM`ing the postgres database & then observing the code flow.

fix: prevent reuse of broken connections in postgres pool

---

src/query-builder/QueryBuilder.ts
src/query-builder/QueryExpressionMap.ts
src/query-builder/SelectQueryBuilder.ts

the parent query builder bits weren't really used in the expression-map, just as part of the query builder itself.  Instead, put it in the QueryBuilder and have it be protected. 
Update the `setParameter` to also call parent query builders
Update `Brackets` to use this instead of setting everything manually.

refactor: clean up parent query builder & Brackets in `where`

---

src/entity-manager/MongoEntityManager.ts
test/github-issues/7809/entity/test.entity.ts
test/github-issues/7809/issue-7809.ts

Delete operation should remove all matched documents, but now it removes the first found document
Closes: #7809
In current solution, when you perform delete operation for MongoDB, only the first found document, that is matching the search condition, is removed. This PR is fixing this problem, removing all documents which are supposed to be removed making delete operation.

fix: delete operation in MongoDB impact all matched documents

---

src/connection/Connection.ts
src/driver/aurora-data-api-pg/AuroraDataApiPostgresDriver.ts
src/driver/aurora-data-api/AuroraDataApiDriver.ts
src/driver/cockroachdb/CockroachDriver.ts
src/driver/mongodb/MongoDriver.ts
src/driver/mysql/MysqlDriver.ts
src/driver/oracle/OracleDriver.ts
src/driver/postgres/PostgresDriver.ts
src/driver/sap/SapDriver.ts
src/driver/sqlite-abstract/AbstractSqliteDriver.ts
src/driver/sqlserver/SqlServerDriver.ts

refactor: cleaning up the code some
instead of the connection setting the database name from outside
the driver we instead set the database name from within the
driver's constructor providing better encapsulation

refactor: set database variable within driver contructor

---

src/driver/postgres/PostgresDriver.ts
test/functional/json/entity/Record.ts
test/functional/json/jsonb.ts

fixes #7810
there was an edge case where the tableColumn.default was not a string
and thus caused a TypeError to be emitted when we tried to `substring`
it.  instead, we check the type first and only if that type is a
string do we try to decode it

fix: handle postgres default when tableColumn.default is not string

---

src/query-builder/transformer/DocumentToEntityTransformer.ts
test/github-issues/7760/entity/test.entity.ts
test/github-issues/7760/issue-7760.ts

fix: find operation in MongoDB do not include nullable values from documents
Find operation should add all nullable values from documents if they exist
Closes: #7760
In current solution, when you perform find operation for MongoDB, nullable values are missing in final entities generated from our documents data. This PR is fixing this problem, adding all nullable values from documents if they exist making find operation.

fix: find operation in MongoDB do not include nullable values from documents

---

docs/find-options.md
src/find-options/FindOptionsUtils.ts
src/metadata/EntityMetadata.ts
src/query-builder/QueryBuilder.ts
src/query-builder/UpdateQueryBuilder.ts
test/functional/query-builder/select/entity/Category.ts
test/functional/query-builder/select/entity/HeroImage.ts
test/functional/query-builder/select/entity/Post.ts
test/functional/query-builder/select/entity/Tag.ts
test/functional/query-builder/select/query-builder-select.ts

updates the `QueryBuilder` to support building `WHERE` clauses via `ObjectLiteral`s that go across relations.
Most of this was done to migrate the `whereInIDs` over to using native QueryBuilder features, and abstract the query compilation away from the `QueryBuilder` interface.
for example
```typescript
const postsWithFoo = await connection.createQueryBuilder(Post, "post")
.select("post.id")
.leftJoin("post.category", "category_join")
.disableEscaping()
.where({
"category": {
"name": "Foo"
}
})
.getMany()
```
This also applies to `FindOptions`
```typescript
const postsWithFoo = await connection
.getRepository(Post).findOne({ where: { "category": { "name": "Foo" } } })
```
Fixes #1847
Fixes #2707
Fixes #7251
Fixes #4906
Fixes #6264
Fixes #4837
Fixes #4787

 fix: better support of one-to-one and many-to-one relation-based properties in where clauses

---

src/decorator/options/ColumnEmbeddedOptions.ts
src/metadata/ColumnMetadata.ts
src/metadata/EntityMetadata.ts
src/persistence/SubjectExecutor.ts
src/util/OrmUtils.ts
test/functional/columns/value-transformer/entity/Post.ts
test/functional/columns/value-transformer/value-transformer.ts
test/functional/mongodb/basic/array-columns/entity/Post.ts
test/functional/mongodb/basic/array-columns/mongodb-array-columns.ts
test/functional/mongodb/basic/mongo-repository/mongo-repository.ts
test/functional/mongodb/basic/repository-actions/entity/Counters.ts
test/functional/mongodb/basic/repository-actions/entity/Post.ts
test/functional/mongodb/basic/repository-actions/entity/User.ts
test/functional/mongodb/basic/repository-actions/mongodb-repository-actions.ts
test/functional/util/OrmUtils.ts
test/github-issues/5762/entity/User.ts
test/github-issues/5762/issue-5762.ts

based on the work of #5097
fixes #5096
fixes #5762
fixes #6181
fixes #5487
fixes #5321

refactor: only merge simple objects in `ORMUtils.mergeDeep`

---

src/driver/aurora-data-api/AuroraDataApiDriver.ts
src/driver/cockroachdb/CockroachDriver.ts
src/driver/mysql/MysqlDriver.ts
src/driver/oracle/OracleDriver.ts
src/driver/postgres/PostgresDriver.ts
src/driver/sap/SapDriver.ts
src/driver/sqlite-abstract/AbstractSqliteDriver.ts
src/driver/sqlserver/SqlServerDriver.ts
src/metadata/ColumnMetadata.ts

this makes the column default type match the actual types
possible for use instead of just `any`.  in particular,
this enforces that `function`s must return strings and limits
the types of objects that are applicable
this also means that the normalizeDefault implementations
always return a string, preventing invalid operations on
numbers or other types (eg, `toUpperCase()`)
fixes #7730 
closes #7731

refactor: stricter types for Column defaults

---

src/driver/sqljs/SqljsQueryRunner.ts
src/query-builder/DeleteQueryBuilder.ts
src/query-builder/InsertQueryBuilder.ts
src/query-builder/QueryBuilder.ts
src/query-builder/SoftDeleteQueryBuilder.ts
src/query-builder/UpdateQueryBuilder.ts

the autosave callback should always be called & shouldn't be peppered
throughout our codebase

refactor: move the sqljs autosave hook into the queryrunner

---

src/find-options/FindOperator.ts
src/index.ts
src/query-builder/Brackets.ts
src/query-builder/DeleteQueryBuilder.ts
src/query-builder/QueryBuilder.ts
src/query-builder/QueryExpressionMap.ts
src/query-builder/SelectQueryBuilder.ts
src/query-builder/SoftDeleteQueryBuilder.ts
src/query-builder/UpdateQueryBuilder.ts
src/query-builder/WhereClause.ts
src/query-builder/WhereExpressionBuilder.ts
test/functional/query-builder/select/query-builder-select.ts

this updates the way `QueryBuilder` works to only build the expression
strings when we are actually building queries.  this means we can more
easily separate the concerns between compiling the query and building
queries.  it also allows us to support database specific where features
more readily

refactor: represent wheres internally as objects instead of strings

---

src/driver/mysql/MysqlDriver.ts
src/driver/sqlserver/SqlServerDriver.ts
src/query-runner/BaseQueryRunner.ts
src/schema-builder/util/TableUtils.ts

the driver's `getColumnLength` was ignored in most places.  to improve consistency during schema sync
this refactors locations so that they always use the helper function off the driver
this is a pre-req for PR #7831 & PR #7853

feat: use column length from driver when creating columns

---

docs/connection-options.md
src/driver/postgres/PostgresConnectionOptions.ts
src/driver/postgres/PostgresDriver.ts
test/github-issues/7662/entity/Dummy_UUID.ts
test/github-issues/7662/issue-7662.ts
test/github-issues/7662/memory-logger.ts

There are cases wherein the credentials given to the service are READONLY. In these cases, installing extensions automatically fails. There is no reason to run these everytime as they trigger unnecessary error logs.
Fixes #7662

feat: make postgres extensions install optional

---

src/metadata-builder/EntityMetadataBuilder.ts

I spotted a few possibly unintended variable names while trying to familialize myself with typeorm's code base.
I fixed those variables, but the change is very insignificant, so please feel free to close PR if this is not welcome.
Thanks!

style: fix reduction variable names in `EntityMetadataBuilder`

---

src/driver/Driver.ts
src/driver/aurora-data-api/AuroraDataApiDriver.ts
src/driver/cockroachdb/CockroachDriver.ts
src/driver/mongodb/MongoDriver.ts
src/driver/mysql/MysqlDriver.ts
src/driver/oracle/OracleDriver.ts
src/driver/postgres/PostgresDriver.ts
src/driver/sap/SapDriver.ts
src/driver/sqlite-abstract/AbstractSqliteDriver.ts
src/driver/sqlserver/SqlServerDriver.ts
src/metadata/EntityMetadata.ts
src/schema-builder/table/Table.ts
src/schema-builder/view/View.ts
test/functional/schema-builder/custom-db-and-schema-sync.ts
test/github-issues/3857/issue-3857.ts
test/utils/test-utils.ts

refactors the way tablePath is handled in `EntityMetadata` to use the driver's `buildTableName` we don't keep a list elsewhere of who supports a schema in their table name and who doesn't.

refactor: Move `tablePath` calculation out of the `EntityMetadata` class

---

src/subscriber/event/UpdateEvent.ts
test/github-issues/1369/subscriber/AbstractEntitySubscriber.ts
test/github-issues/3256/subscriber/PostSubscriber.ts
test/other-issues/entity-change-in-subscribers/subscriber/PostSubscriber.ts
test/other-issues/mongodb-entity-change-in-subscribers/subscriber/PostSubscriber.ts

This change was requested as part of https://github.com/typeorm/typeorm/pull/7724.
That change has made us realise that the type of `UpdateEvent.entity` is not strictly correct as just `Entity`.
1. The `UpdateEvent` in case of an `update`, the `entity` was `undefined`
- In https://github.com/typeorm/typeorm/pull/5443 this was changed for `beforeUpdate` to be a Partial<Entity>
- In https://github.com/typeorm/typeorm/pull/7724 this will be changed for `afterUpdate` to be a `Partial<Entity>`
2. The `UpdateEvent` in case of a `soft delete`, the `entity` is `undefined`
- There is no PR to try and update this
This PR corrects the type for all scenarios which is `entity: Partial<Entity> | undefined`.
I decided to split this out into a seperate PR from https://github.com/typeorm/typeorm/pull/7724 …

fix: `entity` to be `Partial<Entity> | undefined` in `UpdateEvent`

---

docs/connection-options.md
docs/zh_CN/connection-options.md
src/driver/sqlserver/SqlServerConnectionOptions.ts

fix: drop pool.autostart from mssql options because it's unused

---

package.json

somehow we ended up with `ioredis` defined twice in our peer dependencies which isn't 100% valid
but wasn't causing any overt issues.
This drops the duplicate

chore: remove duplicate ioredis from peer dependencies

---

src/entity-manager/MongoEntityManager.ts
src/persistence/SubjectExecutor.ts

this updates the mongo entity manager to return the correct
values for both UpdateResult and DeleteResult instead of an
empty object
fixes #2415

fix: return correct DeleteResult and UpdateResult for mongo

---

src/driver/mysql/MysqlDriver.ts
test/functional/uuid/mysql/uuid-mysql.ts

uses `CHAR(36)` for all `uuid` types in MySQL.
fixes #7228

feat: use char(36) for uuid representation in mysql

---

src/persistence/EntityPersistExecutor.ts
test/functional/entity-subscriber/query-data/entity/Example.ts
test/functional/entity-subscriber/query-data/query-data.ts
test/functional/entity-subscriber/query-data/subscribers/MockSubscriber.ts
test/functional/entity-subscriber/transaction-flow/entity-subscriber-transaction-flow.ts

this resets the `data` passed from `SaveOptions` to `QueryRunner`
once the persistence operation has completed
fixes #4146

fix: only pass `data` from SaveOptions during that query

---

src/query-builder/SelectQueryBuilder.ts

the condition seems to have been accidentally marked as required when
it's actually optional in the underlying implementation.  this marks
the condition in any join within `SelectQueryBuilder` as optional
fixes #5243

fix: condition is optional in SelectQueryBuilder joins

---

src/driver/sqlserver/SqlServerDriver.ts

this prevents the deprecation message & also prevents us from
disabling `ARTITHABORT` which is the default on SQL Server

feat: set `enableArithAbort` for SQLServerDriver

---

src/driver/sqlserver/SqlServerQueryRunner.ts
test/functional/query-runner/stream.ts

the sql server query runner wasn't actually returning a ReadStream as expected
and there were no tests that confirmed the stream functionality.  this corrects
both of those problems

fix: actually return a working ReadStream from SQL Server query runner

---

src/util/StringUtils.ts

As regex example at comment is not matched with actual one, fix it properly.
And remove invalid example link as it is not represent current code.

docs: fix invalid comment at snakeCase method

---

src/driver/sap/SapQueryRunner.ts
src/driver/sqlserver/SqlServerQueryRunner.ts
src/query-runner/QueryLock.ts

this refactors both SAPQueryRunner & SQLServerQueryRunner to use
a new QueryLock class which cleans up the code significantly.  the
refactor unravels the Promise wrapping & also cleans up the
stream function for MSSQLQueryRunner

refactor: create a lock class for fifo query execution locks

---

src/query-builder/UpdateQueryBuilder.ts
test/github-issues/2809/entity/Post.ts
test/github-issues/2809/issue-2809.ts
test/github-issues/2809/subscriber/PostSubscriber.ts

Similar to #5443, just for the `afterUpdate` subscribers.
This, alongside #5443 should fix the bug raised in https://github.com/typeorm/typeorm/issues/2809 and https://github.com/typeorm/typeorm/issues/2246.

fix: entity object undefined in `afterUpdate` subscriber

---

src/driver/sqlserver/SqlServerQueryRunner.ts
test/functional/multi-schema-and-database/multi-schema-and-database-basic-functionality/multi-schema-and-database-basic-functionality.ts

COLUMNPROPERTY only works in the same database so this query was
always incorrect.  instead, use `SYS.COLUMNS` and the `is_identity`
field to check for idenitty columns

fix: use correct query for cross-database mssql identity check

---

src/subscriber/event/UpdateEvent.ts

The typing going into `UpdateEvent.entity` is always an `ObjectLiteral`, so update the typing on the `UpdateEvent` to match.

fix: use ObjectLiteral in UpdateEvent rather than `Entity`

---

src/driver/sap/SapQueryRunner.ts

the `REFERENCED_TABLE_NAME` was being pulled from `dbTable` instead of `dbForeignKey` where that field actually exists.

fix: foreign keys in SAP were loading from the wrong table

---

src/driver/sqlserver/SqlServerQueryRunner.ts

this allows us to properly do lookups even when multiple schemas
are in use

fix: do OBJECT_ID lookup for column constraint instead of name in mssql

---

src/driver/mongodb/MongoDriver.ts
test/functional/driver/MongoDriver.ts
test/functional/driver/driver-utils.ts
test/functional/mongodb/basic/mongo-repository/mongo-repository.ts

From typeorm > 0.2.28 parsing the connection string broke our database setup. In our setup we use a replicaSetup - however the required parameters tls and replicaSet were never added to the connection string.
This PR will add the two parameters, in addition to a new test that parses the connection string (as I was looking for how the parsing works).
There is no new test for the actual adding of the two query parameters. If you can point me towards an example test case, I can also provide one for this case.

fix: mongo replica set

---

src/cache/DbQueryResultCache.ts
src/driver/aurora-data-api/AuroraDataApiQueryRunner.ts
src/driver/cockroachdb/CockroachQueryRunner.ts
src/driver/mysql/MysqlQueryRunner.ts
src/driver/oracle/OracleQueryRunner.ts
src/driver/postgres/PostgresQueryRunner.ts
src/driver/sap/SapQueryRunner.ts
src/driver/sqlite-abstract/AbstractSqliteQueryRunner.ts
src/driver/sqlserver/SqlServerQueryRunner.ts
src/migration/MigrationExecutor.ts
src/query-runner/BaseQueryRunner.ts
src/schema-builder/RdbmsSchemaBuilder.ts
src/schema-builder/options/TableForeignKeyOptions.ts
src/schema-builder/options/TableOptions.ts
src/schema-builder/table/Table.ts
src/schema-builder/table/TableForeignKey.ts
test/functional/multi-schema-and-database/multi-schema-and-database-basic-functionality/multi-schema-and-database-basic-functionality.ts

Adds database & schema to `TableForeignKey`.
Also drops `path` from `Table`.

feat: add referenced database & schema to TableForeignKey

---

package.json

the mongodb module has released major version 4 which is not
backwards compatible.  this pins the available peer module version
to the major release 3 to encourage our users to add compatible
versions until we can upgrade

chore: pin mongodb to major version 3

---

src/driver/aurora-data-api/AuroraDataApiQueryRunner.ts
src/driver/cockroachdb/CockroachQueryRunner.ts
src/driver/mysql/MysqlQueryRunner.ts
src/driver/oracle/OracleQueryRunner.ts
src/driver/postgres/PostgresQueryRunner.ts
src/driver/sap/SapQueryRunner.ts
src/driver/sqlite-abstract/AbstractSqliteQueryRunner.ts
src/driver/sqlserver/SqlServerQueryRunner.ts
src/query-runner/BaseQueryRunner.ts
src/schema-builder/RdbmsSchemaBuilder.ts

Whenever possible, pass the `table`, `foreignkey` or `entitymetadata` to the helper methods to make it a simpler transition when we need to refactor them.

refactor: Use `getTablePath`, `parseTableName`, and `escapePath` more uniformly

---

src/driver/aurora-data-api/AuroraDataApiQueryRunner.ts
src/driver/cockroachdb/CockroachQueryRunner.ts
src/driver/mysql/MysqlQueryRunner.ts
src/driver/oracle/OracleQueryRunner.ts
src/driver/postgres/PostgresQueryRunner.ts
src/driver/sap/SapQueryRunner.ts
src/driver/sqlserver/SqlServerQueryRunner.ts
src/metadata-builder/RelationJoinColumnBuilder.ts
src/metadata/CheckMetadata.ts
src/metadata/ExclusionMetadata.ts
src/metadata/ForeignKeyMetadata.ts
src/metadata/IndexMetadata.ts
src/metadata/UniqueMetadata.ts
src/naming-strategy/DefaultNamingStrategy.ts
test/functional/commands/templates/result-templates-generate.ts
test/functional/schema-builder/create-foreign-key.ts
test/github-issues/4415/results-templates.ts
test/github-issues/5119/issue-5119.ts
test/github-issues/6442/issue-6442.ts

this refactors `escapePath` and `parseTableName` so that when we parse
and serialize the table names they should work the same between the two

feat: consistent parsing and escaping of table names in QueryRunners

---

src/driver/oracle/OracleDriver.ts

oracle queries cannot support the identifier including the database in this way (`XE.SYSTEM.table`)
Instead, if you should specify a separate database a link must be set up and then
the database link identifier is included after the table. (`SYSTEM.table@XE`)
However, because that's rather difficult to set up lets not for now & just prevent
inclusion of the database in the case that we fetch it.

fix: oracle cannot support DB in table identifiers

---

src/driver/Driver.ts
src/driver/aurora-data-api/AuroraDataApiDriver.ts
src/driver/aurora-data-api/AuroraDataApiQueryRunner.ts
src/driver/cockroachdb/CockroachDriver.ts
src/driver/cockroachdb/CockroachQueryRunner.ts
src/driver/mongodb/MongoDriver.ts
src/driver/mysql/MysqlDriver.ts
src/driver/mysql/MysqlQueryRunner.ts
src/driver/oracle/OracleDriver.ts
src/driver/oracle/OracleQueryRunner.ts
src/driver/postgres/PostgresDriver.ts
src/driver/postgres/PostgresQueryRunner.ts
src/driver/sap/SapDriver.ts
src/driver/sap/SapQueryRunner.ts
src/driver/sqlite-abstract/AbstractSqliteDriver.ts
src/driver/sqlserver/SqlServerDriver.ts
src/driver/sqlserver/SqlServerQueryRunner.ts

this adds an analogue to the buildTableName method on every
driver which is the inverse.  parseTableName takes in a variety
of types (EntityMetadata, Table, View, etc) and creates an object
which has a normalized `database`, `schema`, and `tableName`
this may be used throughout the drivers & is also incredibly
useful for the Schema Builder to utilize

feat: add parseTableName to Driver interface

---

src/index.ts
src/query-builder/WhereExpressionBuilder.ts

fix: add deprecated `WhereExpression` alias for `WhereExpressionBuilder`

---

src/commands/MigrationGenerateCommand.ts
test/functional/commands/templates/result-templates-generate.ts
test/github-issues/4415/results-templates.ts

because we escape the backticks in template string literals we can use
them for mysql.  this is important because standard strings cannot cross
multiple lines when you do `pretty` + migrations
fixes #6968

fix: always generate migrations with template string literals

---

docs/connection-options.md
src/driver/postgres/PostgresConnectionOptions.ts
src/driver/postgres/PostgresDriver.ts
test/functional/driver/postgres/specific-options.ts

As the "extra" parameter should be deprecated in the future, the need for
passing driver specific options via the respective config objects is given.
The addition of the "applicationName" parameter is a step forward in this 
direction. This parameter is visible in logs and statistics and helps db
administrators to see which connection belongs to which application.
This change also enables the user to use code completion in case they
didn't even knew this options exists

feat: add possibility to pass application_name via postgres specific config

---

src/driver/sqlserver/SqlServerQueryRunner.ts
test/github-issues/7932/entity/Example.ts
test/github-issues/7932/issue-7932.ts

When we are converting MS-SQL parameters from typeorm's to native, we allow the `varchar` case to fall through to `nvarchar`, and `char` to `nchar`, in order to correctly enable saving strings to columns of those types that contain characters longer than one byte.
Fixes #7932

fix: allow char and varchar cases to fall through when creating parameters

---

docs/tree-entities.md
src/find-options/FindOptionsUtils.ts
src/find-options/FindTreeOptions.ts
src/repository/TreeRepository.ts
test/github-issues/7974/entity/Category.ts
test/github-issues/7974/entity/Site.ts
test/github-issues/7974/issue-7974.ts

Add possibility to load relations of tree entities
The change adds an optional `options` parameter to the findTrees() function. 
The only option that can currently be set is `relations` which is an array of all relations that should be loaded for the entities. It works the same way as the `relations` array for the find() method.
**Example:** 
```typescript
await connection.getTreeRepository(Category).findTrees({ relations: ["sites"] });
```
Results in: 
```
[
Category {
pk: 1,
title: 'Category 1',
sites: [ [Site], [Site] ],
childCategories: [ [Category] ]
},
Category {
pk: 2,
title: 'Category 2',
sites: [],
childCategories: []
}
]
```
Because findTrees() is depending on the findDescendantsTree() and findRoots() functions those two also implement this new optional `options` parameter. …

feat: add relations option to tree queries

---

docs/supported-platforms.md

since release 0.2.36 typeorm uses yargs 17.0.1 which only support node >=12
Update the node js supported version in docs.

docs: update node supported versions

---

src/driver/aurora-data-api/AuroraDataApiDriver.ts
src/driver/cockroachdb/CockroachDriver.ts
src/driver/mysql/MysqlDriver.ts
src/driver/oracle/OracleDriver.ts
src/driver/postgres/PostgresDriver.ts
src/driver/sap/SapDriver.ts
src/driver/sqlite-abstract/AbstractSqliteDriver.ts
src/driver/sqlserver/SqlServerDriver.ts
src/query-builder/QueryBuilder.ts
test/functional/query-builder/parameters/entity/Example.ts
test/functional/query-builder/parameters/query-builder-parameters.ts

updates the character set for parameter identifiers to include
periods.  also update the `setParameter` function on query builder
to validate these identifiers to ensure have explicit failures
when invalid keys are used
fixes #8015

fix: allow periods in parameter identifiers

---

src/query-builder/QueryBuilder.ts
src/query-builder/WhereClause.ts
test/functional/query-builder/brackets/query-builder-brackets.ts
test/functional/query-builder/select/query-builder-select.ts

Fixes a regression where `Brackets` do not add parentheses if there's only one item in the condition
fixes #8043

fix: prevent flattening of `Brackets` so we get consistent queries

---

src/driver/oracle/OracleQueryRunner.ts
test/functional/query-runner/implicit-results.ts

Add support for Oracle Implicit Results (please see issue #8046 )
@imnotjames sorry I have to recreate the PR, but this time with unit test

Add support for Oracle Implicit Results

---

src/metadata/ColumnMetadata.ts
test/github-issues/8026/entity/Sailing.ts
test/github-issues/8026/entity/ScheduledSailing.ts
test/github-issues/8026/issue-8026.ts

Closes: #8026
Allows for date columns that are part of a relation to have data inserted into them.
Fixes: #8026

fix: resolve get entity value for date columns that are related

---

src/driver/cockroachdb/CockroachDriver.ts
src/driver/oracle/OracleDriver.ts
src/driver/postgres/PostgresDriver.ts
src/driver/sap/SapDriver.ts
src/driver/sqlserver/SqlServerDriver.ts

the `Driver.database` was getting set only from the options and
completely ignored the connection URLs being passed to them.  this
meant that in some cases the migrations would apply to the wrong
database or schema if connection url strings were used
fixes #8057

fix: some drivers set the wrong database name when defined from url

---

package.json

the changelog command was generating logs for two versions instead of one which was not correct

chore: only generate one changelog entry instead of 2

---

src/query-runner/BaseQueryRunner.ts
src/schema-builder/RdbmsSchemaBuilder.ts
test/functional/schema-builder/custom-db-and-schema-sync.ts
test/github-issues/7867/entity/Example.ts
test/github-issues/7867/issue-7867.ts

The changes made as part of #7575 fixed some issues and introduced others.  The problem became that the table name would be compared against the `EntityMetadata` `tablePath`.  This would fail in some cases because while the `EntityMetadata` would specify `database`, it'd be the "default"/current database & would be omitted from the table name.
To work around that this PR introduces the database & schema on the table objects as well as a fully-qualified table path property which will always include all of them for comparing against `EntityMetadata`.
fixes #8109
fixes #8102 
fixes #7867 
fixes #7812
fixes #7737
fixes #6744
fixes #5960
fixes #5958
fixes #5439
fixes #5304

 fix: use full path for table lookups 

---

src/util/StringUtils.ts
test/functional/util/StringUtils.ts

Fix a specific case of converting device1Status -> device1_status
the change in eb680f99 has broke one case of how cammelCase is converted to snake_case, specifically:
device1Status -> device1status
this PR restores the correct behavior:
device1Status -> device1_status

fix: snakecase conversion for strings with numbers

---

src/driver/sqlite/SqliteQueryRunner.ts
test/functional/query-builder/delete/query-builder-delete.ts

uses the sqlite `run` function for deletes, updates, and inserts - instead of just inserts.  this means the affected count should get through to the query builder
fixes #8120

fix: support DeleteResult in SQLiteDriver

---

src/driver/nativescript/NativescriptQueryRunner.ts

Making the promise async now correctly scopes the handler. this.driver is now defined.
Additional corrections were made to the syntax, eg conditionals.
Closes #8180
I believe making the promise async will now correctly scope `this` in the handler function. When it references this.driver, on running a query the app would throw an exception stating that driver was undefined. 
Tested this change with NS8 projects and it doesn't throw the error anymore.

fix: NativescriptQueryRunner's query method fails when targeting es2017

---

src/driver/cockroachdb/CockroachQueryRunner.ts
test/github-issues/5132/issue-5132.ts
test/github-issues/7110/entity/foo.entity.ts
test/github-issues/7110/issue-7110.ts

This fixes column default value in cockroachdb continuously producing schema changes when there should be none
Refs: #7110
I am simply applying an existing postgres fix to cockroachdb. Cockroachdb is postgres "compatible".  See #7110

fix: defaults type cast filtering

---

src/query-builder/SelectQueryBuilder.ts
test/github-issues/3736/entity/Photo.ts
test/github-issues/3736/entity/User.ts
test/github-issues/3736/issue-3736.ts

Fixes #3736
This PR adds the missing column to the select clause inside the sub query when ordering is done by a property of a related entity.
Example:
```typescript
const queryBuilder: SelectQueryBuilder<Photo> = await connection.getRepository(Photo).createQueryBuilder("photo");
await queryBuilder
.select()
.leftJoin("photo.user", "user")
.take(5)
.orderBy("user.name")
.getManyAndCount();
```
Generates the following valid SQL query:
```diff
SELECT
DISTINCT "distinctAlias"."photo_id" AS "ids_photo_id",
"distinctAlias"."user_name"
FROM
(
SELECT "photo"."id" AS "photo_id",
"photo"."url" AS "photo_url",
"photo"."userId" AS "photo_userId",
+		"user"."name" AS "user_name" 
FROM
"photo" "photo"
LEFT JOIN "user" "user" ON
"user"."id" = "photo"."userId") "distinctAlias"
ORDER BY …
```

fix: ordering by joined columns for PostgreSQL (#3736)

---

gulpfile.ts
package.json

This makes it easier to install custom builds in local projects
Adds a "pack" script (similar to the "package" script) that produces a .tgz file in the ./build directory.

chore: add a script to produce a packed tgz of the module

---

src/commands/InitCommand.ts

This small feature addition is to reduce beginner stumbling when initializing a project with the `typeorm init` command.
When someone runs the `typeorm init` command using the current TypeORM CLI, the `scripts` section of the package.json generated at that time looks like this:
```
"scripts": {
"start": "ts-node src/index.ts"
}
```
Also, the `entities`, `migrations` and `subscribers` section of ormconfig.json looks like this:
```
"entities": [
"src/entity/**/*.ts"
],
"migrations": [
"src/migration/**/*.ts"
],
"subscribers": [
"src/subscriber/**/*.ts"
],
```
In this project, when I run a command like `typeorm schema:log` or `npm run typeorm schema:log`, I will get the following error:
```
$ typeorm schema:log
/tmp/typeorm-newproject/src/entity/User.ts:1
import {Entity, …
```

feat: add `typeorm` command wrapper to package.json in project template

---

docs/tree-entities.md
src/find-options/FindOptionsUtils.ts
src/repository/TreeRepository.ts
test/github-issues/8076/entity/Category.ts
test/github-issues/8076/entity/Member.ts
test/github-issues/8076/entity/Site.ts
test/github-issues/8076/issue-8076.ts

Closes: #8076
Added the `relations` option to all treeRepository methods.
The changes are more or less the same I made in the previous pull request, just that I did it on all other methods too. I created test cases for each method, with and without the option set.

feat: add relation options to all tree queries

---

src/find-options/FindOptionsUtils.ts
test/functional/repository/find-options-locking/find-options-locking.ts

FOR NO KEY UPDATE was introduced in typeorm 0.2.25 but the relevant query
part was never added due to missing check in FindOptionUtils as @ykovalenko-gentech
stated out. I've added a test to ensure this behaviour will not change in the future.
Fixes #7717

fix: attach FOR NO KEY UPDATE lock to query if required

---

docs/select-query-builder.md
src/query-builder/QueryExpressionMap.ts
src/query-builder/SelectQueryBuilder.ts
test/functional/query-builder/select/query-builder-select.ts

Support using custom index for MySQLDriver.

Support using custom index for MySqlDriver.

---

docs/tree-entities.md
src/find-options/FindTreeOptions.ts
src/repository/FindTreesOptions.ts
src/repository/TreeRepository.ts
test/functional/tree-tables/closure-table/closure-table.ts
test/functional/tree-tables/materialized-path/materialized-path.ts
test/functional/tree-tables/nested-set/nested-set.ts

feat: add depth limiter optional parameter when loading nested trees when using TreeRepository's findTrees() and findDescendantsTree()
Modified TreeRepository's findTrees() and findDescendantsTree() public methods to now accept an optional object with config options.
For now, said object contains a depth parameter that, if set, will limit how far down the tree those methods will crawl and retrieve nested entities.
BREAKING CHANGE: TreeRepository's protected method buildChildrenEntityTree() now requires a 4th argument. Anyone affected by this break should also review and update their implementation, otherwise this feature will not work.
Closes: #3909
Unrelated tests are failing for me both on the branch and on master. I ran the individual tests I added to cover my changes, and hopefully CI …

feat: add depth limiter optional parameter when loading nested trees

---

src/driver/postgres/PostgresQueryRunner.ts
test/github-issues/3076/entity/SomeEntity.ts
test/github-issues/3076/issue-3076.ts

added "/." to PostgresQueryRunner regex for default value retrieving to prevent regenerating migrations for enum columns with default type when the object is within a schema.
**Previous Behaviour:**
on any migration generation, a new migration has been created for enum default values when the object is within a named schema
**Expected Behaviour:**
no migration as long as the default value is not changed
A broader discussion around the issue: https://github.com/typeorm/typeorm/issues/3076 for which it extends the current workaround

fix: postgres enum in schema regenerated migrations

---

src/driver/mongodb/MongoConnectionOptions.ts

Add `retryWrites` property to `MongoConnectionOptions` to match change to `MongoDriver` made in #7869.
I encountered this missing type when using `TypeOrmModuleOptions` from `@nestjs/typeorm`, which is based on the `MongoConnectionOptions` interface.
The doc string is taken from https://docs.mongodb.com/v4.0/reference/method/Mongo.startSession/.

fix: add `retryWrites` to `MongoConnectionOptions`

---

src/cache/DbQueryResultCache.ts
src/driver/mongodb/MongoQueryRunner.ts
src/query-runner/BaseQueryRunner.ts
src/query-runner/QueryRunner.ts
test/github-issues/5919/entities.ts
test/github-issues/5919/issue-6399.ts

Fix #5919 
I just added a new method `QueryRunner.getReplicationMode` to check if we can insert cache into `DbQueryResultCache.storeInCache`. If query runner is in slave mode, we create a new one in master mode

Fix Caching won't work with replication enabled

---

docs/find-options.md
src/query-builder/SelectQueryBuilder.ts
test/functional/query-builder/locking/query-builder-locking.ts
test/functional/repository/find-options-locking/find-options-locking.ts

fixes #8249
allow the same lock modes as postgres - https://www.cockroachlabs.com/docs/stable/select-for-update.html
currently an exception is thrown when a lock is used in a transaction
Adds Support for:
* pessimistic_write
* pessimistic_write_or_fail
* for_no_key_update

allow lock modes for cockroachdb

---

src/driver/sqlserver/SqlServerQueryRunner.ts

For MS SQL Server change uppercase table reference "SYS"."COLUMNS" to lowercase "sys"."columns" to avoid table name mismatch when database collation is ALTER'ed to a case-sensitive collation.
Per issue #8400 changed the only occurrence of uppercase reference `"SYS"."COLUMNS"` to lowercase `"sys".columns"`.
_I am a contractor and due to resource constraints of only having one shared MS SQL Server DB instance I was unable to implement/run any tests!_

fix: For MS SQL Server use lowercase "sys"."columns" reference. (#8400)

---

docs/repository-api.md

It seems like the wrong method(`update`) was used in the `upsert` example so I changed it to `upsert`.

docs: fix wrong upsert example

---

src/entity-schema/EntitySchemaOptions.ts
src/entity-schema/EntitySchemaTransformer.ts

A previous pull request (#4688) added support for `withoutRowid` to `EntityOptions` but did not extend this support all the way into `EntitySchemaOptions`
This PR adds this missing piece.
Fixes: #8429

fix: adds entity-schema support for withoutRowid

---

docs/caching.md
src/cache/RedisQueryResultCache.ts

- Fixes https://github.com/typeorm/typeorm/issues/8420
- v4.0.0 and newer of node-redis will no longer auto-connect, so we need to add that step
- For backwards compatibility, we check for the existence of a "v4" property so we don't try to call `connect` on older versions of the client
- A `legacyMode` flag exists in the new v4.0.0 of node-redis to keep a similar calling style without having to change any code
- This option can be passed via the createClient options, so I've added documentation to indicate that this is required if users would like to use v4.0.0 of node-redis
- Note that the legacyMode flag is **required** to be passed if the calling code isn't going to be changed

Add support for node-redis v4.0.0 and newer

---

src/entity-manager/MongoEntityManager.ts

Add support for mongodb 4.2
Closes: 8146
mongodb@4.2 does not export a Cursor, instead it exports a FindCursor. This change provides compatibility support to TypeORM so it works with both mongodb@3.6.4 and mongodb@4.2
Some notes on the tests:
- test/functional/commands/migration-create.ts
- test/functional/commands/migration-generate.ts
- test/functional/connection-options-reader/connection-options-reader.ts
- test/functional/persistence/delete-orphans/delete-orphans.ts
These tests were not passing prior to any changes and were disabled to complete the other tests. The remaining tests were ran successfully for both MongoDB version 4.4.10 using mongdb@4.2 driver and using MongoDB version 3.7 (using the docker image) and mongodb@3.6.4 driver.

fix: find() throws error while using mongodb

---

src/decorator/Unique.ts
src/decorator/options/UniqueOptions.ts
src/driver/postgres/PostgresQueryRunner.ts
src/entity-schema/EntitySchemaTransformer.ts
src/entity-schema/EntitySchemaUniqueOptions.ts
src/metadata-args/UniqueMetadataArgs.ts
src/metadata/UniqueMetadata.ts
src/schema-builder/options/TableUniqueOptions.ts
src/schema-builder/table/TableUnique.ts
test/functional/deferrable/deferrable-unique.ts
test/functional/deferrable/entity/Company.ts
test/functional/deferrable/entity/Office.ts

Added a deferrable option to `@Unique` decorator and support for Postgres.

Added Deferrable option for Unqiue constraints (Postgres)

---

src/metadata-builder/EntityMetadataValidator.ts
test/github-issues/8522/entity/BaseEntity.ts
test/github-issues/8522/entity/ClientRole.ts
test/github-issues/8522/entity/InternalRole.ts
test/github-issues/8522/entity/InternalUser.ts
test/github-issues/8522/entity/Role.ts
test/github-issues/8522/entity/User.ts
test/github-issues/8522/issue-8522.ts

Fixes: #8522 
When there are two unrelated child entities following the single table inheritance pattern with same discriminator value, if both entities inherit from a class that just adds some common columns it, it throws an error. So the change is to be sure that we are only checking within entities that have the same db table.

fix: Single table inheritance returns the same discriminator value error for unrelated tables where their parents extend from the same entity 

---

docs/connection-api.md

getEntityManager no longer exists. We should write getManager in the docs

update connection-api docs to fix getEntityManager

---

docs/find-options.md

Fixes #8495, adds documentation to find-options stating that when undefined is passed to find, all items in the table will be returned, and if undefined is passed to findOne the first item in the table will be returned. There is also an example SQL statement to give readers a better idea of what is being executed when undefined is passed.

Adding undocumented behavior to find-options doc

---

docs/listeners-and-subscribers.md

Add documentation on base properties for subscriber's event object.
Add note to listeners about not running database calls.
I have seen people incorrectly use database calls inside listeners, including myself, leading to unresponsiveness. This is because the original QueryRunner used in the event that triggers the listeners is not released until after the broadcasting methods are finished.
This might be obvious to some, but I didn't realize this until after exploring the TypeORM code base further. This PR updates the documentation to add a note not to make database calls in listeners and instead opt for subscribers. The subscriber event methods all receive the event object that contains the original QueryRunner/EntityManager instance which when used  solves the race condition issue. 
The …

docs: update listeners/subscribers documentation

---

src/driver/better-sqlite3/BetterSqlite3Driver.ts
src/driver/sqlite/SqliteDriver.ts

fix: must invoke key pragma before trying to do any other interaction with the sqlite
See documentation: [SQLite Encryption Extension](https://www.sqlite.org/see/doc/release/www/readme.wiki)
> Using the "key" PRAGMA
> You must invoke this pragma before trying to do any other interaction with the database. 
Closed: #8475

fix: must invoke key pragma before do any other interaction with the sqlite

---

docs/select-query-builder.md
src/index.ts
src/query-builder/NotBrackets.ts
src/query-builder/QueryBuilder.ts
test/functional/query-builder/not/entity/User.ts
test/functional/query-builder/not/query-builder-not.ts

You can add a negated complex `WHERE` expression into an existing `WHERE` using `NotBrackets`
```typescript
createQueryBuilder("user")
.where("user.registered = :registered", { registered: true })
.andWhere(new NotBrackets(qb => {
qb.where("user.firstName = :firstName", { firstName: "Timber" })
.orWhere("user.lastName = :lastName", { lastName: "Saw" })
}))
```
Which will produce the following SQL query:
```sql
SELECT ... FROM users user WHERE user.registered = true AND NOT((user.firstName = 'Timber' OR user.lastName = 'Saw'))
```
Closes feature request #4442.
We can't use `Not` as class because it's already exported in [src/find-options/operator/Not.ts](https://github.com/typeorm/typeorm/blob/master/src/find-options/operator/Not.ts).

feat: query builder negating with "NotBrackets" for complex expressions

---

src/driver/aurora-data-api/AuroraDataApiQueryRunner.ts
src/driver/cockroachdb/CockroachQueryRunner.ts
src/driver/mysql/MysqlQueryRunner.ts
src/driver/oracle/OracleQueryRunner.ts
src/driver/postgres/PostgresQueryRunner.ts
src/driver/sap/SapQueryRunner.ts
src/driver/sqlite-abstract/AbstractSqliteQueryRunner.ts

Add indexName to error msg, when index is not existing by drop Index.
Nothing to close because I guess
"Small Features can be crafted and directly  submitted as a Pull Request"
If the index to be dropped does not exist, the index name is displayed in the thrown error message to make it easier to debug the problem.

feat: Add index name in error msg

---

src/globals.ts

Closes #8567
Because Promise.all() returns after the first error, some connection may still connect even though the tests already continue to the next unit. This results in a dangling connection which may prevent other tests to continue. Because this is a race condition it happened only sometimes.

test: prevent the creation of a dangling connection by test issue-8522

---

src/query-builder/DeleteQueryBuilder.ts
src/query-builder/UpdateQueryBuilder.ts
src/query-builder/WhereExpressionBuilder.ts

`whereInIds()` has incorrect documentation identical to `andWhereInIds()`, indicating that it performs an `AND WHERE`, when in fact it does not. Instead, it performs a `WHERE`, totally overwriting any previous set of conditions.
Several of us have tripped on this due to this improper documentation so I'd like to remedy with this pull request please.

docs: fix incorrect docs for whereInIds()

---

src/query-builder/RelationLoader.ts
test/functional/relations/eager-relations/lazy-nested-eager-relations/entity/Category.ts
test/functional/relations/eager-relations/lazy-nested-eager-relations/entity/Editor.ts
test/functional/relations/eager-relations/lazy-nested-eager-relations/entity/Post.ts
test/functional/relations/eager-relations/lazy-nested-eager-relations/entity/Profile.ts
test/functional/relations/eager-relations/lazy-nested-eager-relations/entity/User.ts
test/functional/relations/eager-relations/lazy-nested-eager-relations/lazy-nested-eager-relations.ts

Given the scenario:
```
Entity A {
id
b: any type of relationship to Entity B | lazy
}
Entity B {
id
c: any type of relationship to something else | eager
d: any type of relationship to something else | eager
}
```
this change intends to fix a bug that happens when lazy-loading a relationship with `await entityA.b`. All `eager` relations from _Entity B_ are not loaded, and are set as `undefined`. This happens with all `find` methods and the Query Builder, breaking type-safety, specially for people using `strictNullChecks` in _tsconfig_.
Fixes #8328 https://github.com/typeorm/typeorm/issues/7841#issuecomment-889425844

fix: error where eager relations in a lazy-loaded entity would be undefined

---

src/repository/TreeRepository.ts
test/github-issues/8556/entity/category.entity.ts
test/github-issues/8556/issue-8556.ts

Closes: #8556
If subquery in findDescendants `CONCAT(${subQuery.getQuery()}, '%')` returns null when entity parent does not exist, the search string becomes `LIKE '%'`, because CONCAT ignores NULL. This `LIKE '%'` results on returning everything instead of nothing.
Now with `NULLIF` fix, search will be `LIKE NULL`, which returns nothing for a non existing tree parent.
In case of Sqlite, `LIKE ${subQuery.getQuery()} || '%'` is already evaluated as `LIKE NULL` when subquery returns null.
- [x ] Code is up-to-date with the `master` branch
- [ x] `npm run lint` passes with this change
- [ x] `npm run test` passes with this change
- [ x] This pull request links relevant issues as `Fixes #0000`
- [x ] There are new or updated unit tests validating the change
- [ x] The new commits follow …

fix: find descendants of a non-existing tree parent

---

src/find-options/FindOneOptions.ts
src/find-options/FindOptionsUtils.ts
test/functional/repository/find-options/repository-find-options.ts

Allows users to pass in comments for queries issued through the entity manager
like they are for the query builder (added in #6892).

feature: add comment param to FindOptions.

---

docs/migrations.md
package-lock.json
src/commands/CommandUtils.ts
src/commands/MigrationCreateCommand.ts
src/commands/MigrationGenerateCommand.ts
test/functional/commands/migration-create.ts
test/functional/commands/migration-generate.ts
test/functional/commands/templates/result-templates-create.ts
test/functional/commands/templates/result-templates-generate.ts

An option in the CLI to specify a custom timestamp when creating or generating a migration.
Closes: #8500
An option in the CLI to specify a custom timestamp when creating / generating a migration.

feat: add custom timestamp option in migration creation

---

docs/one-to-one-relations.md

Update the method that allows **loading** a specific relation inside the find method.
This method is found on the one-to-one-relations [page](https://typeorm.io/#/one-to-one-relations).
_Change:_  `const users = await userRepository.find({ relations: ["profile"] });` to `const users = await userRepository.find({ relations: {profile: true});`.

docs: update loading relation in find method (v 0.3.0)

---

docs/working-with-entity-manager.md

change the "What is EntityManager?" page to be up-to-date with v 0.3.0
1. line 6 changes from
`You can access the entity manager via 'getManager()' or from 'Connection'.`
to 
`You can access the entity manager via DataSource's manager.`
2. the import on `getManager` in line 10 becomes `DataSource`  directly imported from typeorm:
`import {getManager} from "typeorm";`
becomes 
`import {DataSource} from "typeorm";`
3. change entityManager definition in line 13 and user load in line 14:
from
`const entityManager = getManager(); // you can also get it via getConnection().manager`
`const user = await entityManager.findOne(User, 1);`
to
`const myDataSource = new DataSource({ /*...*/ });`
`const user = await myDataSource.manager.findOne(User, 1);`

docs: update entitymanager definition

---

src/driver/postgres/PostgresQueryRunner.ts

Right now, when using PostgreSQL, relations that point to tables in a different schema will have their foreign constraints generated every migration, even if they already exist. 
This is because when checking for the constraint's target, `referencedSchema` is used to prefix the column name(s). However, in PostgresQueryRunner, `referencedSchema` is never set, so the query runner thinks the existing constraint is pointing to `public` schema, even if it isn't 
This PR adds `referencedSchema` to the PostgresQueryRunner loading of foreign keys.
Fixes #8565
I didn't know what tests to add as there were no existing tests regarding `referencedSchema`  
Also I don't believe this exists in the documentation

fix: add referencedSchema to PostgresQueryRunner

---

src/query-builder/SelectQueryBuilder.ts
test/github-issues/4764/entity/Cart.ts
test/github-issues/4764/entity/CartItems.ts
test/github-issues/4764/entity/User.ts
test/github-issues/4764/issue-4764.ts

Typeorm didn't supported LOCK clause in MSSQL SELECT + JOIN query. 
For example, when we write code with typeorm like this
```typescript
await getConnection()
.createQueryBuilder()
.select("order")
.setLock("dirty_read")
.from(Order, "order")
.innerJoinAndSelect("order", "order.OrderItems")
.where("1=1")
.getMany()
```
we would expect the corresponding SQL of this statement is 
```sql
SELECT      *
FROM        Order O     WITH (NOLOCK)
LEFT JOIN   OrderItems  WITH (NOLOCK)
WHERE       1=1
```
but typeorm generates SQL like this 
```sql
SELECT      *
FROM        Order O     WITH (NOLOCK)
LEFT JOIN   OrderItems  
WHERE       1=1
```
This pull request enables LOCK with SELECT + JOIN sql query.
This pull request will prevent deadlock situations while querying SELECT statements during …

fix: add WITH (lock) clause for MSSQL select with join queries

---

docs/relations-faq.md

The following grammatical adjustments are related to the `Avoid relation property initializers` section, found in the relations-faq [page](https://typeorm.io/#/relations-faq/avoid-relation-property-initializers);
1.  Adjust the grammatical error found in the following phrase `But if you have initializer` by **adding** `an` before the word `initializer`.
2.  Adjust the grammatical error found in the following phrase `the loaded object will look like as follow` by **removing** the `like` word and **adding** an `s` to `follow`.

docs: Adjust grammatical error

---

src/entity-schema/EntitySchemaRelationOptions.ts
src/entity-schema/EntitySchemaTransformer.ts

A previous pull request (https://github.com/typeorm/typeorm/pull/7277) added support for `createForeignKeyConstraints` to EntityRelationOptions but did not extend this support all the way into EntitySchemaRelationOptions
This PR adds this missing piece.
Fixes #8489

fix: adds entity-schema support for createForeignKeyConstraints

---

src/entity-manager/EntityManager.ts
src/util/OrmUtils.ts
test/functional/repository/basic-methods/entity/OneToOneRelation.ts
test/functional/repository/basic-methods/repository-basic-methods.ts

Fixes #8587 
One-to-one relations create a unique index, that index should be suitable for an upsert conflict target.

fix: upsert should find unique index created by one-to-one relation

---

src/entity-manager/MongoEntityManager.ts
test/github-issues/7113/entity/Configuration.ts
test/github-issues/7113/issue-7113.ts
test/github-issues/7113/repository/ConfigurationRepository.ts

Closes: #7113
`MongoRepository` `find`, `findAndCount`, `findByIds`, `findOne` methods do not select rows that was soft deleted.

fix: mongodb repository.find filters soft deleted rows

---

src/commands/MigrationShowCommand.ts

Currently `typeorm migration:show` prints out a list of migrations, and returns an error exit code if there are any unapplied migrations. 
The error code is useful in CI contexts, to assert that all migrations have been applied, perhaps before a code deploy.
Issue #7349 points out that this error code is noisy/annoying for local development. This PR introduces a `--quiet` flag to supress that exit code.

feat: add --quiet option to migration:show command (Fixes #7349)

---

src/common/DeepPartial.ts
src/entity-manager/EntityManager.ts
test/github-issues/2904/entity/Comment.ts
test/github-issues/2904/issue-2904.ts
test/github-issues/7079/issue-7079.ts

Fixes #2904.
This change improves the DeepPartial check and prevents TypeScript from errorring unnecessarily in cases described in the aforementioned issue. On the flipside, it now errors on `.save()` in case a string property is passed instead of a `Date`. As such this PR will be a breaking change. I created a second commit that highlights what resolving the breaking change would look like.
What are your thoughts?

Improve DeepPartial using recursive types

---

src/metadata-builder/RelationJoinColumnBuilder.ts
test/functional/entity-metadata/entity/Counters.ts
test/functional/metadata-builder/column-metadata/entity/Counters.ts
test/functional/query-builder/relation-id/many-to-many/embedded-with-multiple-pk/entity/Counters.ts
test/functional/query-builder/relation-id/many-to-one/embedded-with-multiple-pk/entity/Counters.ts
test/functional/query-builder/relation-id/many-to-one/embedded/entity/Counters.ts
test/functional/query-builder/relation-id/one-to-many/embedded-with-multiple-pk/entity/Counters.ts
test/functional/query-builder/relation-id/one-to-many/embedded/entity/Counters.ts
test/functional/query-builder/relation-id/one-to-one/embedded-with-multiple-pk/entity/Counters.ts
test/functional/query-builder/relation-id/one-to-one/embedded/entity/Counters.ts
test/github-issues/6977/entity/Embedded.ts
test/github-issues/6977/entity/User.ts
test/github-issues/6977/issue-6977.ts

Replaces old PR: #6981
Searches embedded entity columns for relation ID column if relation column is in embedded entity. If not found, creates new relation ID with embedded metadata set to match the relation column.
Fixes: #2254
Fixes: #3132
Fixes: #3226
Fixes: #6977
See #6977. 
Currently the relation column's `entityMetadata` is searched for columns matching the join column, rather than `embeddedMetadata` (when present):
https://github.com/typeorm/typeorm/blob/a5eb946117a18d94c0157188b6a39542c8d50756/src/metadata-builder/RelationJoinColumnBuilder.ts#L136
This changes that behavior to match:
https://github.com/typeorm/typeorm/blob/a5eb946117a18d94c0157188b6a39542c8d50756/src/metadata-builder/EntityMetadataBuilder.ts#L152-L156
This breaks any existing schemas that had relations inside …

fix: prefix relation id columns contained in embedded entities (#6977)

---

src/driver/sqlite-abstract/AbstractSqliteQueryRunner.ts
test/github-issues/8644/entity/my-table.entity.ts
test/github-issues/8644/issue-8644.ts

fix: Allow special keyword as column name for simple-enum type on sqlite

---

src/persistence/tree/MaterializedPathSubjectExecutor.ts
test/functional/tree-tables/materialized-path/entity/Category.ts
test/functional/tree-tables/materialized-path/entity/Product.ts
test/functional/tree-tables/materialized-path/materialized-path.ts

When tree entities are saved implicitly (through another related entity which hasMany tree-entities and "cascade" set to true) the ORM generates materialized-path strings prefixed with `undefined`. Resulting in materialized paths like `undefined1.2.3`. This pull request fixes that. Root cause was that the materialized path always relies on the previously inserted entity mpath which is `undefined` for the root-tree-entity.
- [ x] The new commits follow conventions explained in [CONTRIBUTING.md](https://github.com/typeorm/typeorm/blob/master/CONTRIBUTING.md)

fix: materialized path being computed as "undefined1."

---

src/metadata-builder/EntityMetadataValidator.ts
test/github-issues/8444/entity/StrictlyInitializedEntity.ts
test/github-issues/8444/issue-8444.ts

Fixes #8444
See related issue https://github.com/typeorm/typeorm/issues/8444

fix: make EntityMetadataValidator comply with entitySkipConstructor

---

src/persistence/SubjectExecutor.ts
test/github-issues/8416/8416.ts
test/github-issues/8416/entity/Author.ts
test/github-issues/8416/entity/Category.ts
test/github-issues/8416/entity/Post.ts

The soft-delete would update recursively the related entities without loading them
related to - https://github.com/typeorm/typeorm/issues/8416
The Problem
Today, the cascade soft delete update the related entities just if we would load all the entities that we want to soft-remove
This behavior is bad in term of performance and in addition, don't work recursively
Because there is no feature like that today, a lot of developers write soft delete flow for every entity that includes a lot of code because they need to kill the children as well, and that causes a lot of bugs
The Solution
Change the soft-remove flow to soft-remove all related entities recursively and automatically
- soft remove the entity
- get the entity relations and soft remove the inverse entities where the parent id is the …

Soft delete recursive cascade

---

src/driver/sqlite-abstract/AbstractSqliteDriver.ts
test/github-issues/2286/entity/Example.ts
test/github-issues/2286/entity/Post.ts
test/github-issues/2286/issue-2286.ts

In sqlite, Date objects are persisted as UtcDatetimeString.
But a Date object parameter was escaped with .toISOString(), making such queries impossible.
This commit aligns both transforms.
This bug does *not* apply to better-sql where you can only bind numbers, strings, bigints, buffers,
and null.
This is breaking for when the user inserted their dates manually as ISO and relied on this old
maltransformation, after this their find()s by Date won't work anymore.
BREAKING CHANGE: Change Date serialization in selects
fixes #2286
fixes #3426

fix: find by Date object in sqlite driver

---

src/driver/better-sqlite3/BetterSqlite3QueryRunner.ts
src/driver/capacitor/CapacitorQueryRunner.ts
src/driver/cordova/CordovaQueryRunner.ts
src/driver/expo/ExpoQueryRunner.ts
src/driver/mongodb/MongoQueryRunner.ts
src/driver/nativescript/NativescriptQueryRunner.ts
src/driver/react-native/ReactNativeQueryRunner.ts
src/driver/sqlite/SqliteQueryRunner.ts
src/driver/sqljs/SqljsQueryRunner.ts
src/migration/MigrationExecutor.ts
src/query-runner/BaseQueryRunner.ts
src/query-runner/QueryRunner.ts
src/schema-builder/RdbmsSchemaBuilder.ts
test/functional/schema-builder/change-column.ts
test/functional/schema-builder/entity/Post.ts
test/functional/sqljs/auto-save.ts

this moves the `PRAGMA` calls to where we need them in the sqlite migration generation / synchronize
fixes #2576

fix: disable SQLite FK checks in synchronize / migrations

---

src/query-builder/InsertQueryBuilder.ts

the SAP HANA SQL dialect does not support inserts with multiple values
but it does support `INSERT ... SELECT` as well as a `SELECT ... FROM dummy`
with that in mind, the `InsertQueryBuilder` has been modified to support
this dialect similar to how we do for Oracle
fixes #7899

fix: correctly handle multiple-row insert for SAP HANA driver

---

test/github-issues/8627/entity/long-name.entity.ts
test/github-issues/8627/entity/other-long-name.entity.ts
test/github-issues/8627/issue-8627.ts

Currently, when having really long names for entities (in the code, not the table name) or deeply nested structures, joins do not work correctly because it can be that junction aliases do not get shortened. In the driver (e.g. Postgres has a limit of 63 characters), they will be truncated and then two different junction aliases map to the same string, resulting in the query failing because of aliases not being unique.
~~With this fix, junction aliases are being hashed and thus are short enough.~~
See below... **tl;dr: The fix was already implemented in 0.3.0. This PR adds a test for that fix.**
*Note that this does worsen the ability to read the query as the shortened / hashed aliases are harder to read.*
If you have suggestions on how to now loose the readability while still fixing the …

fix: keep junction aliases short

---

package.json

Support using `require` on internal module files without explicitly writing `.js` at the end of the path.
For example, this code would work now:
```js
// in ESM projects
import {snakeCase} from "typeorm/util/StringUtils.js";
// in CommonJS projects
const {snakeCase: snakeCase1} = require("typeorm/util/StringUtils"); // this line previously thrown an error, this PR fixes that
const {snakeCase: snakeCase2} = require("typeorm/util/StringUtils.js");
console.log(snakeCase === snakeCase1); // true
console.log(snakeCase === snakeCase2); // true
```
Closes #8656
Closes https://github.com/tonivj5/typeorm-naming-strategies/issues/16

fix: support `require` to internal files without explicitly writing `.js` in the path

---

src/util/ImportUtils.ts

Support importing absolute paths of ESM file on Windows.
For example, this code would work now:
```js
import {importOrRequireFile} from "./util/ImportUtils";
await importOrRequireFile("./index.mjs");
await importOrRequireFile("./index.cjs");
// on macOS / Linux
await importOrRequireFile("/Users/user/Documents/index.mjs");
await importOrRequireFile("/Users/user/Documents/index.cjs");
// on Windows
await importOrRequireFile("C:\\Users\\user\\Documents\\index.mjs"); // this line previously thrown an error, this PR fixes that
await importOrRequireFile("C:\\Users\\user\\Documents\\index.cjs");
```
Closes #8651

fix: support imports of absolute paths of ESM files on Windows

---

src/driver/sap/SapQueryRunner.ts

Related feature request: #6098, #2191.
I've added deferrable (check time) options for foreign keys on SAP HANA. See `<references_specification>` in the [CREATE TABLE](https://help.sap.com/viewer/4fe29514fd584807ac9f2a04f6754767/2.0.04/en-US/20d58a5f75191014b2fe92141b7df228.html#loio20d58a5f75191014b2fe92141b7df228__create_table_references_specification) and [ALTER TABLE](https://help.sap.com/viewer/4fe29514fd584807ac9f2a04f6754767/2.0.04/en-US/20d329a6751910149d5fdbc4800f92ff.html#loio20d329a6751910149d5fdbc4800f92ff__references_specification) specification:
```EBNF
<references_specification> ::= 
REFERENCES <referenced_table> [ ( <referenced_column_name_list> ) ]
[ <referential_triggered_action> ]
[ <constraint_enforcement> ]
[ <constraint_check_time> ]
<constraint_check_time> ::= …
```

Implement deferrable foreign keys for SAP HANA

---

docker-compose.yml
src/driver/Driver.ts
src/driver/mysql/MysqlDriver.ts
src/error/ReturningStatementNotSupportedError.ts
src/persistence/SubjectExecutor.ts
src/query-builder/DeleteQueryBuilder.ts
src/query-builder/InsertQueryBuilder.ts
src/query-builder/QueryBuilder.ts
src/query-builder/ReturningResultsEntityUpdator.ts
src/query-builder/SoftDeleteQueryBuilder.ts
src/query-builder/UpdateQueryBuilder.ts
test/github-issues/7235/entity/Animal.ts
test/github-issues/7235/issue-7235.ts

Closes: #7235
- Allow `delete().returning()` on MariaDB >= 10.0.5
- Allow `insert().returning()` on MariaDB >= 10.5.0
- Can check DML type(ex: `select`, `update`, `delete`) on
`Driver.isReturningSqlSupported()` and `QueryBuilder.createReturningExpression()`

feat: allow `{delete,insert}().returning()` on MariaDB

---

package.json

Instruct Webpack to import the CommonJS version or browser-native ESM version of TypeORM directly when using TypeORM's default import, ignoring `index.mjs` file meant for nodejs ESM projects.
In nodejs the `index.mjs` file is used to refer to the same loaded instance of TypeORM from both ESM and CommonJS imports, it's needed in order to maintain the same state across ESM and CommonJS imports that may occur in different places in the same project.
When using Webpack, only one module system can be used to import the same library, so providing different import methods should not cause state problems.
Closes #8674

fix: ng webpack default import

---

src/query-builder/RelationLoader.ts
test/github-issues/8690/entity/entities.ts
test/github-issues/8690/issue-8690.ts

Use column transforms when rendering queries during relation loading. Previously, transforms were ignored by the relation loader, causing unexpected values to be put into sql queries.
See #8690 for a description of the expected vs actual behavior. This PR implements the expected behavior.
Fixes #8690

fix: alter relation loader to use transforms when present

---

src/metadata/ColumnMetadata.ts
test/other-issues/get-id-for-composite-primary-key/entity/Category.ts
test/other-issues/get-id-for-composite-primary-key/entity/Post.ts
test/other-issues/get-id-for-composite-primary-key/entity/PostCategory.ts
test/other-issues/get-id-for-composite-primary-key/get-id-for-composite-primary-key.ts

`entityManager.getId` currently returns undefined for an entity with composite primary key if primary key columns are also foreign keys with lazy relations, for e.g., in a custom join table. This commit tries to fix that.
The reason for `getId` returning `undefined` is that `columnMetadata.getEntityValueMap` doesn't take into account the fact that the value for lazy-relations is a getter which returns a `Promise`. This PR adds a check for this condition.
To reproduce the issue, refer https://github.com/ranjan-purbey/typeorm-composite-primary-key-test
Closes: #7736 (maybe)

fix: fix entityManager.getId for custom join table

---

package.json

Force web bundlers to ignore `index.mjs` and use `browser/index.js` instead
Closes #8709

fix: force web bundlers to ignore `index.mjs` and use the browser ESM version directly

---

docs/view-entities.md
src/decorator/options/ViewColumnOptions.ts
test/functional/view-entity/general/entity/PhotoAlbum.ts
test/functional/view-entity/general/view-entity-general.ts
test/functional/view-entity/mssql/entity/PostCategory.ts
test/functional/view-entity/mssql/view-entity-mssql.ts
test/functional/view-entity/mysql/entity/PostCategory.ts
test/functional/view-entity/mysql/view-entity-mysql.ts
test/functional/view-entity/oracle/entity/PostCategory.ts
test/functional/view-entity/oracle/view-entity-oracle.ts
test/functional/view-entity/postgres/entity/PostCategory.ts
test/functional/view-entity/postgres/view-entity-postgres.ts
test/functional/view-entity/sqlite/entity/PostCategory.ts
test/functional/view-entity/sqlite/view-entity-sqlite.ts

Resolves #4339 
This pull request adds a `transformer` field to `ViewColumnOptions`, to allow a view column to be unmarshalled by a custom ValueTransformer. This is the same functionality that currently exists for `ColumnOptions` and regular table entities. Note that you can already get the same result as this PR using `@ts-ignore`:
```
export const uppercase: ValueTransformer = {
to: (entityValue: string) => {},
from: (databaseValue: string) => databaseValue.toLocaleUpperCase()
};
@ViewEntity({ expression: `
SELECT "post"."id" "id", "post"."name" AS "name", "category"."name" AS "categoryName"
FROM "post" "post"
LEFT JOIN "category" "category" ON "post"."categoryId" = "category"."id"
`})
export class PostCategory {
@ViewColumn()
id: number;
@ViewColumn({ name: "name" })
postName: string; …
```

feat: add transformer to ViewColumnOptions

---

src/query-builder/UpdateQueryBuilder.ts
test/github-issues/8723/entity/Photo.ts
test/github-issues/8723/entity/User.ts
test/github-issues/8723/issue-8723.ts

Closes: #8723
This change is to discard duplicated columns when building an update query. 
Fixes #8723

fix: discard duplicated columns on update

---

src/index.ts
src/repository/TreeRepository.ts
src/util/TreeRepositoryUtils.ts

This PR migrates all protected methods under TreeRepository to TreeRepositoryUtils and adds an `extend` method override in TreeRepository so it returns the correct type TreeRepository including all the tree methods

feature: export tree repository helper methods

---

docs/custom-repository.md
src/connection/options-reader/ConnectionOptionsEnvReader.ts
src/data-source/BaseDataSourceOptions.ts
src/data-source/DataSource.ts
src/entity-manager/EntityManager.ts
src/repository/BaseEntity.ts
src/util/InstanceChecker.ts
test/functional/base-entity/base-entity.test.ts
test/functional/base-entity/entity/User.ts
test/functional/custom-repository/custom-repository.test.ts
test/functional/custom-repository/entity/User.ts
test/functional/entity-model/entity-model.ts
test/functional/relations/lazy-relations/lazy-relations-loading-via-base-entitiy-finders/index.ts
test/functional/repository/find-options-operators/repository-find-operators.ts
test/github-issues/2201/issue-2201.ts
test/github-issues/2313/issue-2313.ts

fixes #8762; #8759; #8758; #8757;

Fixes bugs introduced in 0.3.0

---

CHANGELOG.md
docs/find-options.md
src/driver/postgres/PostgresDriver.ts
src/find-options/FindOperatorType.ts
src/find-options/operator/ArrayContainedBy.ts
src/find-options/operator/ArrayContains.ts
src/find-options/operator/ArrayOverlap.ts
src/query-builder/QueryBuilder.ts
src/query-builder/WhereClause.ts
test/benchmark/bulk-save-case2/entity/Document.ts
test/functional/find-options/array-contained-by-operator/array-contained-by-operator.test.ts
test/functional/find-options/array-contained-by-operator/entity/Post.ts
test/functional/find-options/array-contains-operator/array-contains-operator.test.ts
test/functional/find-options/array-contains-operator/entity/Post.ts
test/functional/find-options/array-overlap/array-overlap-operator.test.ts
test/functional/find-options/array-overlap/entity/Post.ts
test/functional/json/entity/Record.ts
test/functional/json/jsonb.ts
test/github-issues/1314/issue-1314.ts
test/github-issues/204/entity/Record.ts
test/github-issues/204/issue-204.ts
test/github-issues/3496/entity/Post.ts
test/github-issues/3496/issue-3496.ts
test/github-issues/3636/issue-3636.ts
test/github-issues/7650/issue-7650.ts
test/other-issues/transformed-json-column-update-compute/transformed-json-column-update-compute.ts

Added new find operators:
* `ArrayContains`
* `ArrayContainedBy`
* `ArrayOverlap`
BREAKING CHANGES: 
* we do not call `JSON.stringify()` to `json`/`jsonb` column types in Postgres. Instead, we delegate value directly to underlying `pg` driver. This is a correct way of handling jsons.
* `array: true` must be explicitly defined for array json/jsonb values
* strings being JSON-stringified must be manually escaped
I should have included it in `0.3.0`, but missed it. So, breaking change comes in `0.3.1` now.

feat: new array find operators

---

src/commands/CacheClearCommand.ts
src/commands/CommandUtils.ts
src/commands/MigrationGenerateCommand.ts
src/commands/MigrationRevertCommand.ts
src/commands/MigrationRunCommand.ts
src/commands/MigrationShowCommand.ts
src/commands/QueryCommand.ts
src/commands/SchemaDropCommand.ts
src/commands/SchemaLogCommand.ts
src/commands/SchemaSyncCommand.ts

Using the CLI in ESM projects is broken in version 0.3.1, this PR fixes that.
The CLI currently tries to `require( ... )` the `data-source.ts` file of the project regardless of the project type (CommonJS/ESM), the fix is to use the `importOrRequireFile` function instead.

fix: broken CLI in ESM projects since version 0.3

---

docs/faq.md
docs/migrations.md
docs/using-cli.md
docs/zh_CN/faq.md
docs/zh_CN/migrations.md
docs/zh_CN/using-cli.md
package-lock.json
package.json
src/cli-ts-node-commonjs.ts
src/cli-ts-node-esm.ts
src/commands/InitCommand.ts

Add `typeorm-ts-node-commonjs` and `typeorm-ts-node-esm` CLI commands.
This removes the need to manually write `node --require ts-node/register ./node_modules/typeorm/cli.js` or `node --loader ts-node/esm ./node_modules/typeorm/cli.js` in order to use TypeORM CLI without transpiling the code in advance.
This is more useful now than before since the new CLI in version 0.3 requires you to specify a file path instead of just a file name, so being able to `cd` to a folder and then run a simple and intuitive command is now more important.
Previous usage of the CLI in version 0.3:
```bash
cd src/db/migrations
node --loader ts-node/esm ../../../node_modules/typeorm/cli.js migration:generate -d ../data-source.ts --pretty SomeMigrationName
```
New possible usage of the CLI:
```bash
cd …
```

feat: add typeorm CLI variations that include `ts-node`

---

src/driver/postgres/PostgresDriver.ts
test/benchmark/bulk-save-case2/entity/Document.ts
test/functional/find-options/array-contained-by-operator/array-contained-by-operator.test.ts
test/functional/find-options/array-contains-operator/array-contains-operator.test.ts
test/functional/find-options/array-contains-operator/entity/Post.ts
test/functional/find-options/array-overlap/array-overlap-operator.test.ts
test/functional/find-options/array-overlap/entity/Post.ts
test/functional/json/basic-jsonb/basic-jsonb.test.ts
test/functional/json/basic-jsonb/entity/Record.ts
test/functional/json/jsonb-defaults/entity/Post.ts
test/functional/json/jsonb-defaults/jsonb-defaults.test.ts
test/github-issues/204/entity/Record.ts
test/github-issues/3496/entity/Post.ts

I have to revert breaking changes introduced in #8766
My assumptions were wrong regarding on how `json`/`jsonb` arrays work in postgres.
Also I faced issue that `node-pg` (underlying package used by TypeORM for postgres support) doesn't really plays well with JSON arrays, so we **must** call `JSON.stringify` to properly support all JSON use cases (see https://github.com/brianc/node-postgres/issues/374 and https://github.com/brianc/node-postgres/issues/442) for more details.
So, this change reverts all breaking changes introduced in 0.3.1 back to how they were in 0.3.0 and earlier versions.
fixes #8772

fix: reverted json/jsonb changes introduced in 0.3.1

---

src/driver/mysql/MysqlConnectionOptions.ts
src/driver/mysql/MysqlDriver.ts

In attempt to resolve  #8534, I'm cherry-picking this small change.
This is necessary to eventually resolve #8713
This allows user using `ormconfig.json` to specify connector package.

feat: allows user to specify which mysql package should be used

---

src/data-source/DataSource.ts
src/repository/BaseEntity.ts
test/functional/base-entity/base-entity.test.ts

Closes: #8768
In the 0.3 release, DataSource stopped resolving entities correctly when specified as Globs. This results in the data source information not being set correctly into the entities. This PR fixes it by correctly importing the classes when globs are specified.

fix: resolve entities correctly in datasource when globs are specified

---

src/query-builder/SelectQueryBuilder.ts

Closes: #8792
Just remove unwanted console.log calls from SelectQueryBuilder.ts.

fix: remove console.log calls from SelectQueryBuilder

---

src/driver/cockroachdb/CockroachConnectionOptions.ts
src/driver/cockroachdb/CockroachDriver.ts

Add `applicationName` parameter in connection option that is missed for CockroachDB. This parameter is supported and tested that the "Application Name" value can be seen in the CockroachDB's console web UI.

feat: applicationName parameter for CockroachDB

---

src/query-builder/InsertQueryBuilder.ts
test/functional/query-builder/insert-on-conflict/query-builder-insert-on-conflict.ts

Adds support for alias on insertQueryBuilder. This is particularly useful when dealing with `ON CONFLICT` as you can reference the original table to do an update or nothing based on a condition.
Fixes #4003 
As an aside question - would it be possible to un-deprecate `onConflict` as it is still useful for this sort of complex `ON CONFLICT` work which isn't possible with `orUpdate` or `orIgnore`

feat: Add support for insert with alias #4003

---

src/entity-manager/EntityManager.ts
src/repository/BaseEntity.ts
test/functional/entity-model/entity-model.ts
test/functional/entity-model/entity/Category.ts
test/functional/entity-model/entity/Post.ts
test/functional/relations/multiple-primary-keys/multiple-primary-keys-one-to-many/multiple-primary-keys-one-to-many.ts
test/functional/repository/find-methods/repostiory-find-methods.ts
test/functional/repository/find-options-locking/find-options-locking.ts
test/functional/repository/find-options/repository-find-options.ts
test/functional/table-inheritance/single-table/no-type-column/no-type-column.ts
test/github-issues/1720/issue-1720.ts
test/github-issues/3118/issue-3118.ts
test/github-issues/7932/issue-7932.ts

fix: BaseEntity.reload method regression and made `findOne` to throw error on missing conditions in runtime

---

src/query-builder/SelectQueryBuilder.ts
test/github-issues/8796/entity/User.ts
test/github-issues/8796/issue-8796.ts

If you pass false to a field in the select object, it will not select that field.
Before this PR, it would select fields marked as false.
<br>
Example:
```
userRepository.find({
select: {
firstName: true,
lastName: false, // note false
},
})
```
**would return even properties marked as false** 
```
{
firstName:  'foo',
lastName:  'bar',
},
```
**now returns**
```
{
firstName:  'foo',
},
```
This PR Fixes https://github.com/typeorm/typeorm/issues/8796
I wasn't able to run all the tests, but I ran mine, and it passed.
PS: this is my first PR ever.

Fixes #8796

---

src/cli-ts-node-commonjs.ts
src/cli-ts-node-esm.ts

Added a workaround in nodejs itself to use `ts-node` instead of relying on shebang parameters, as they seem to work a bit differently on some linux distros, and using the `-S` parameter (`#!/usr/bin/env -S node <parameters>`) breaks the CLI on Windows.
Closes #8818

fix: broken shebang parameters of `cli-ts-node-commonjs` and `cli-ts-node-esm` on some linux distros

---

src/driver/postgres/PostgresDriver.ts
test/other-issues/hstore-allow-transformer/entity/hstore-entity.ts
test/other-issues/hstore-allow-transformer/hstore-allow-transformer.ts
test/other-issues/hstore-allow-transformer/test-transformer.ts

The HSTORE type is the only type bypassing the transformer
column options.
This fix makes the option available to this column type as well.
If the current behavior was intentional then the documentation should be updated to inform developers that transformers are not applicable to the HSTORE type in Postgres.

fix: allow hstore type to use transformers in driver postgres

---

docs/migrations.md

`migration:generate` requires data-source path as argument and was not provided at doc.

docs: missing argument at migration:generate

---

docs/custom-repository.md

The name of the function declared in the repository does not match with the function name used in the examples.

docs: fix function name

---

src/persistence/EntityPersistExecutor.ts
test/github-issues/2927/entity/Content.ts
test/github-issues/2927/entity/Photo.ts
test/github-issues/2927/entity/Post.ts
test/github-issues/2927/entity/SpecialPhoto.ts
test/github-issues/2927/issue-2927.ts

When using a STI scheme and an EntityManager or Repository with base class target, the wrong discriminator was written to the database despite giving a concrete entity.
This was because of the entity's target being ignored in favour of the target of the Repository or the EntityManager, which then is the (abstract) base class.
This PR introduces a fix by **figuring out the concrete subclass of an entity when saving**.
Further questions from my side:
* Currently, it allows for subclass entities to be found by querying the class from `childEntityMetadatas` for every entity. What about performance problems?
* Should this behaviour be deactivatable?
* Is there any documentation that has to be updated?
This PR fixes #2927 (which was closed by the author without the problem being resolved).

fix: Use concrete subclass for saving with single table inheritance

---

src/index.ts

New functions from 0.3.1 are missing in index.ts file
- [ x ] Code is up-to-date with the `master` branch
- [ x ] `npm run format` to apply prettier formatting
- [ x ] `npm run test` passes with this change
- [ x ] This pull request links relevant issues as `Fixes #8844`

chore: add missing exports to index.ts (#8844)

---

src/commands/CommandUtils.ts

Today, the error message is misleading. It states that the file does not export a datasource when it's juste trying to open the module.
Clarifying the error message and adding the root Exception message helps whith debugging.

fix: Clarify error message on datasource loading

---

src/data-source/BaseDataSourceOptions.ts

This PR changes (fixes) the JSDoc description of `migrations` parameter of `BaseDataSourceOptions`.
The current description of that parameter is confusing, because it suggests that the value can be pointing to a directory, for example `dist/migrations/`, and _optionally_ you can use a glob pattern.
Actually what happens in the source code [^1] is that the value is _always_ resolved as a glob pattern and all the matching files are used as the migration files. So if you provide a path to a folder, no migrations will be found at all.
My suggestion is to keep the current behaviour, but reword the description of the parameter, so that it does not create confusion to how it works under the hood. You could even argue that the source code in the footnotes could also be refactored (by renaming …

docs: fix migrations option description

---

src/decorator/options/ColumnOptions.ts

Add ColumnOptions nullable default docs
- [✔] Code is up-to-date with the `master` branch
- [✔ ] `npm run format` to apply prettier formatting
- [✔ ] `npm run test` passes with this change
- [✔] This pull request links relevant issues as `Fixes #0000`
- [✔] There are new or updated unit tests validating the change
- [✔] Documentation has been updated to reflect this change
- [✔] The new commits follow conventions explained in [CONTRIBUTING.md](https://github.com/typeorm/typeorm/blob/master/CONTRIBUTING.md)

docs: add ColumnOptions nullable default docs

---

docs/supported-platforms.md

Changed bold line to h4 title to improve the search index of `Webpack configuration`, it looks the same though.

docs: change bold line to h4 title to improve search index

---

docs/find-options.md
src/find-options/FindOneOptions.ts
src/find-options/FindOptionsUtils.ts
src/query-builder/QueryExpressionMap.ts
src/query-builder/SelectQueryBuilder.ts
test/functional/query-builder/locking/query-builder-locking.ts
test/functional/repository/find-options-locking/find-options-locking.ts

Adds support for new lock mode `for_key_share` - generating FOR KEY SHARE lock. 
Lock applies only to driver type postgres. Otherwise LockNotSupportedOnGivenDriverError error is thrown.
Closes: #8878

feat: add `for_key_share` ("FOR KEY SHARE") lock mode for postgres

---

package.json

Add the documentation site as `homepage` in `package.json`.
This way the npm module page will also link to the documentation site, instead of displaying 2 links to the same github page.

docs: add the documentation site as `homepage` in `package.json`

---

src/cache/RedisQueryResultCache.ts

Fixes https://github.com/typeorm/typeorm/pull/8725#issuecomment-1099525610

fix: Add missing connect call on RedisQueryResultCache connect

---

src/commands/InitCommand.ts

Use `AppDataSource` instead of `dataSource`. Looks like a bug introduced into the `InitCommand` from https://github.com/typeorm/typeorm/commit/3b8a031ece508820651a3a8f99f9cbf87319812c

fix: InitCommand AppDataSource Bug

---

test/benchmark/multiple-joins-querybuilder/entity/Eight.ts
test/benchmark/multiple-joins-querybuilder/entity/Five.ts
test/benchmark/multiple-joins-querybuilder/entity/Four.ts
test/benchmark/multiple-joins-querybuilder/entity/Nine.ts
test/benchmark/multiple-joins-querybuilder/entity/One.ts
test/benchmark/multiple-joins-querybuilder/entity/Seven.ts
test/benchmark/multiple-joins-querybuilder/entity/Six.ts
test/benchmark/multiple-joins-querybuilder/entity/Ten.ts
test/benchmark/multiple-joins-querybuilder/entity/Three.ts
test/benchmark/multiple-joins-querybuilder/entity/Two.ts
test/benchmark/multiple-joins-querybuilder/multiple-joins-querybuilder.ts

Motivation: the query builder (and within it, replacePropertyNames and
associated functions) is pretty CPU intensive. For our workload, it's
one of the hottest functions in our entire stack.
While improved in https://github.com/typeorm/typeorm/pull/4760,
There are still outstanding issues relating to perf e.g. https://github.com/typeorm/typeorm/issues/3857
As we all know though, the first step in optimization is to measure
systematically ;)
https://wiki.c2.com/?ProfileBeforeOptimizing
On my machine, this benchmark runs in ~3550ms or about 0.35ms/query.
This tells us there's a way to go - on my stack, that's about 1/3 of a
typical query's latency!

test: add benchmark for select querybuilder

---

src/query-builder/QueryBuilder.ts
src/util/escapeRegExp.ts

Context: the query builder is pretty CPU intensive, and can be slow -
e.g. https://github.com/typeorm/typeorm/issues/3857
One of the things which makes this slow is `escapeRegExp` in the query
builder: we freshly construct the same RegExp once per
`replacePropertyName` invocation (many times per overall query!) and
since the RegExp itself is constant -- we can lift it out and construct
it once.
Over-all this saves about 5% on our query build times as measured by
#8955.

perf: don't recompile escapeRegExp for every query

---

src/schema-builder/options/TableForeignKeyOptions.ts

`TableForeignKeyOptions.name` reflects the name of the foreign key. The name of the table where this foreign key resides is actually referenced by `referencedTableName`.

docs: update TableForeignKeyOptions.name description

---

package.json

in node16/nodenext module mode of TyepScript 4.7+, If package has `exports` entry on package.json, needs "types" field in `exports.*` for typings.
without this change, TypeScript 4.7+ (on node16/nodenext module mode) can't find typings.
```
src/backend/db/entities/local-user.ts:1:69 - error TS7016: Could not find a declaration file for module 'typeorm'. '/Users/user/work/github.com/rinsuki/alice/node_modules/typeorm/index.mjs' implicitly has an 'any' type.
If the 'typeorm' package actually exposes this module, try adding a new declaration (.d.ts) file containing `declare module 'typeorm';`
1 import { Column, Entity, JoinColumn, OneToOne, PrimaryColumn } from "typeorm";
```
so just I added it.
ref. https://devblogs.microsoft.com/typescript/announcing-typescript-4-7/

chore: support TS 4.7+ node16/nodenext module mode

---

src/query-builder/QueryBuilder.ts
test/benchmark/multiple-joins-querybuilder/multiple-joins-querybuilder.ts

Digging further into #3857.
See also #8955, #8956.
As [previously discussed](https://github.com/typeorm/typeorm/issues/3857#issuecomment-699505893), the query builder currently suffers from poor performance in two ways:
1. quadratic numbers of operations with respect to total table/column
counts
2.  poor constant factor performance (regexps can be expensive
to build/run!)
The constant-factor performance is the more tractable problem: no longer
quadratically looping would be a chunky rewrite of the query builder,
but we can locally refactor to be a bunch cheaper in terms of regexp
operations.
This change cuts the benchmark time here in ~half (yay!).
We achieve this by simplifying the overall replacement regexp (we don't
need our column names in there, since we already have a plain object …

perf: partially lift matching from regexp to js

---

src/commands/CacheClearCommand.ts
src/commands/MigrationRevertCommand.ts
src/commands/MigrationRunCommand.ts
src/commands/MigrationShowCommand.ts
src/commands/QueryCommand.ts
src/commands/SchemaDropCommand.ts
src/commands/SchemaSyncCommand.ts

Fixes https://github.com/typeorm/typeorm/issues/8885.
The issue can be reproduced here:
https://gist.github.com/gillepsi-swyftx/d595a281ec08c019ea12abbfa20ea058
Most of the CLI commands currently run `dataSource.destroy()` in a `catch {}` block when an error occurs during the command ([see here](https://github.com/typeorm/typeorm/blob/506133e2179529bf3add2b0b982613835d321af6/src/commands/MigrationRunCommand.ts#L73)). This call to `destroy()` is throwing, which masks the underlying issue. The error caught in the `catch {}` block should be logged regardless of whether `destroy()` throws.
This PR moves the log entries in the `catch {}` block above the call to `destroy()`. This ensures that the error will be logged regardless of whether `destroy()` throws.

feat: log command error prior to calling destroy

---

src/entity-schema/EntitySchemaOptions.ts
src/entity-schema/EntitySchemaRelationIdOptions.ts
src/entity-schema/EntitySchemaTransformer.ts
src/metadata-args/RelationIdMetadataArgs.ts

Implement support for RelationIds in EntitySchemas.

feat: implement support for relationids in entity schemas

---

docs/migrations.md

The current documentation of the migration:create command uses the old cli syntax
```
typeorm migration:create -n PostRefactoring
```
This throws an error as newer versions greater than 0.30 require the full path to be passed.
```
typeorm migration:create /path-to-migrations-dir/PostRefactoring
```
The above command creates the migration in the path with the name {timestamp}-PostRefactoring.ts successfully.

fixed full path requirement in migration:create command

---

package.json

Version bump of the 0.3.6 release was not committed to master.

Bump version to v0.3.6

---

src/commands/CacheClearCommand.ts
src/commands/MigrationRevertCommand.ts
src/commands/MigrationRunCommand.ts
src/commands/MigrationShowCommand.ts
src/commands/QueryCommand.ts
src/commands/SchemaDropCommand.ts
src/commands/SchemaSyncCommand.ts

If there is some problem in the configuration options in DataSource (e.g wrong hostname), the dataSource is not initialized, so calling `dataSource.destroy()` will cause error `Cannot execute operation on "${connectionName}" connection because connection is not yet established.`. I add simple check if the dataSource is initialized, so this error will not occur and user can focues on the real problem.

Fix: Call `dataSource.destroy` only on initialized dataSource in commands

---

docs/tree-entities.md

Repository should be replaced by dataSource.manager.getTreeRepository(Category)

Repository replaced by dataSource.manager.getTreeRepository(Category)

---

src/query-builder/transformer/DocumentToEntityTransformer.ts
test/github-issues/9049/entity/comment.ts
test/github-issues/9049/entity/post.entity.ts
test/github-issues/9049/entity/value.ts
test/github-issues/9049/issue-9049.ts

fix the recursive call to `addEmbeddedValuesRecursively`, which was running for
array and object embedded properties, which should only run for non-array ones.
The call for array properties is already placed right
Closes: #9049
Fixes #9049.
According to what is described in the issue, when using typeorm with mongodb driver, if you have an entity which has an array attribute, and this array has another array attribute, typeorm will send an `document[embedded.prefix].map is not a function` error. 
In the current version, the [addEmbeddedValuesRecursively](https://github.com/typeorm/typeorm/blob/master/src/query-builder/transformer/DocumentToEntityTransformer.ts#L147) method calls itself recursively, expecting to have an object as the second argument, even if the object is an array. In the …

fix: fixes recursive document to entity attributes mapping

---

src/cache/DbQueryResultCache.ts

Fixes #4866
When calling `DbQueryResultCache.remove`, if the optional `queryRunner` is not provided, currently, a new runner is created.
This new runner is not released after executing the query.

fix: release newly created runner when no runner provided

---

docs/data-source-options.md
src/driver/better-sqlite3/BetterSqlite3ConnectionOptions.ts
src/driver/better-sqlite3/BetterSqlite3Driver.ts
test/functional/driver/better-sqlite3/better-sqlite3-native-binding.ts

better-sqlite3 allows to set the `nativeBinding` option since version v7.5.0. It allows to define a custom path for the native api binary `better_sqlite3.node`. This feature is very important for developers who want to create binaries of their node apps for different platforms (e.g. with pkg). [More information](https://github.com/WiseLibs/better-sqlite3/blob/master/docs/api.md#new-databasepath-options=).
- The test just checks if the `nativeBinding` option was set to the driver options.
- I tested the new build in my project with better-sqlite3 v7.5.3, it works fine.
- The `nativeBinding` option is only available in better-sqlite3 >= v7.5.0. Because "^7.1.2" already includes the latest package, I did not update the package.json. If someone uses < v7.5.0 setting `nativeBinding` does not …

feat: add nativeBinding option to better-sqlite3 driver

---

.circleci/config.yml

Changes CI tests to be run on Node 16 (latest LTS version) instead of 13 (not supported anymore).

test: replace Node 13 with 16 in tests

---

src/commands/CommandUtils.ts

Support async import for DataSource in CLI. Fixes #8914

Fix: #8914

---

docs/migrations.md

The current migration documentation still reveres to the option `-c` (for `Connection`):
https://github.com/typeorm/typeorm/blob/15f90e0be897f5bd2f4dac1d1e8d24f539a842a8/docs/migrations.md?plain=1#L224-L230
This option was replaced by `-d` (for `DataSource`) in [v0.3.0](https://github.com/typeorm/typeorm/commit/3b8a031ece508820651a3a8f99f9cbf87319812c). 
This PR updates the documentation for this option.

docs: migration replace `Connection` with `DataSource` option

---

src/driver/mysql/MysqlQueryRunner.ts

As of MySQL v8.0, a new synonymous was introduced for "GeometryCollection" - "GeomCollection".
The preferred type name is "GeomCollection".
This fix will change the synonym name to its full name.

fix: resolve potential issues with new synonymous for GeometryCollection type

---

docs/entities.md

Previously, the documentation said that it's using the `findOne`
function (see [here](https://github.com/typeorm/typeorm/blob/master/docs/entities.md?plain=1#L164)), but it used the `findBy` and `findOneBy` functions (see [here](https://github.com/typeorm/typeorm/blob/master/docs/entities.md?plain=1#L168) and [here](https://github.com/typeorm/typeorm/blob/master/docs/entities.md?plain=1#L169)). In order
to be coherent, this commit changes all those to `findOneBy`.

docs: fix wrong function used in entity documentation

---

src/entity-manager/MongoEntityManager.ts
test/functional/mongodb/basic/mongo-repository/entity/Post.ts
test/functional/mongodb/basic/mongo-repository/mongo-repository.ts

Fixes #9250 
Fix `filterSoftDelted` of `MongoEntityManager` not to reset query filter.
Previous version replaced cursor query filter with `where this.deletedDateColumn.propertyName == null`. 
So there is a bug that the cursor queries all of not deleted data if the entity has DeletedDateColumn.

fix: find query mongodb properly with @DeleteDateColumn()

---

docs/migrations.md

On line 73 have 'three options' to setup, but is actually only two as you can see.
- [N/A] `npm run format` to apply prettier formatting
- [N/A] `npm run test` passes with this change
- [N/A] There are new or updated unit tests validating the change

docs: update text on data-source setup section

---

docs/select-query-builder.md
src/query-builder/SelectQueryBuilder.ts
test/github-issues/9240/entity/post.entity.ts
test/github-issues/9240/issue-9240.ts

Fixes #9240
Fix `groupBy` to receives string array to maintain consistency with `select`.
Before:
```
// groupBy() | groupBy(string)
.groupBy(a)
.addGroupBy(b)
.addGroupBy(c)
```
After:
```
// groupBy() | groupBy(string) | groupBy(string[])
.groupBy([a,b,c])
```

feat: add array parameter on groupBy

---

src/driver/sqlite-abstract/AbstractSqliteQueryRunner.ts
test/github-issues/9176/entity/Author.ts
test/github-issues/9176/entity/Post.ts
test/github-issues/9176/entity/User.ts
test/github-issues/9176/issue-9176.ts
test/github-issues/9176/migration/1656926770819-CreatePostTable.ts
test/github-issues/9176/migration/1656939116999-CreateAuthorTable.ts
test/github-issues/9176/migration/1656939646470-AddAuthorIdColumn.ts
test/github-issues/9176/migration/1657066872930-CreateUserTable.ts
test/github-issues/9176/migration/1657067039714-CreateUniqueConstraintToUser.ts
test/github-issues/9176/migration/1657067039715-CreateCheckedUserTable.ts
test/github-issues/9176/migration/1657067039716-CreateCheckConstraintToUser.ts
test/utils/test-utils.ts

In migration steps, finally temporary table name is renamed to original table name. these constraints name should be created from original table name not temporary table name.
Fixes #9176

fix: don't use temporary table name to create foreign key, unique, check constraint with SQLite

---

src/persistence/SubjectTopoligicalSorter.ts
test/github-issues/9241/entity/Employee.ts
test/github-issues/9241/entity/Photo.ts
test/github-issues/9241/entity/User.ts
test/github-issues/9241/entity/UserPhoto.ts
test/github-issues/9241/issue-9241.ts

Take inheritance into consideration when sorting insert commands
Closes: #9241
The insert commands are executed in correct order when an entity has nested relation inherited from a parent entity through @TableInheritance

fix: handle inherited relations insert order

---

src/driver/sqlite-abstract/AbstractSqliteQueryRunner.ts

Fixes #9237
The regex for SQLite constraints now accepts both space and no-space syntaxes for `FOREIGN KEY`, `CHECK` and `UNIQUE` constraints.
Both syntaxes exist on the web:
- no-space: https://www.sqlite.org/foreignkeys.html
- space: https://www.sqlitetutorial.net/sqlite-foreign-key/

fix: allow space and no-space syntaxes for SQLite constraints

---

src/util/DateUtils.ts
test/github-issues/9230/issue-9230.ts

Update DateUtils to correctly handle years less than 999.  For instance, a date of 0999-01-01 should parse to the same string value with a leading 0 for the year.  Previously, the output would not contain the leading 0.
Fixes: #9230

fix: update date utils to parse year correctly for years 1-999

---

docs/data-source-options.md
docs/zh_CN/connection-options.md
src/driver/sqlserver/SqlServerConnectionOptions.ts

The [default value](https://github.com/tediousjs/node-mssql#tedious) is `true`.

docs: correct mssql encrypt default value

---

src/entity-manager/EntityManager.ts
test/functional/entity-schema/basic/entity-schema-basic.ts
test/functional/entity-schema/basic/entity/PostEntity.ts

Currently the entity manager remove method does not recognise the first param if it is an entity schema. With this change it works correctly.

Fix entity the manager remove method

---

src/driver/postgres/PostgresQueryRunner.ts

I believe the intent in #7792 was to pass the error, if any, to the release callback from `pg-pool`, but it doesn't look like the error wasn't actually propagated through that release callback. The original issue (#5112) describes the motivation. #9055 also looks related.
Existing tests don't appear to cover this branch, and I haven't added any here. I validated this by adding logging and following the suggested steps in #5112: issue a long-running query, and kill the process or container. I note that with the steps I took, pg-pool still managed to clean up properly by seeing that [the client is not `_queryable`](https://github.com/brianc/node-postgres/blob/4fa7ee891a456168a75695ac026792136f16577f/packages/pg-pool/index.js#L331), but I imagine there are cases where this wouldn't happen.

fix: pass error to pgpool release

---

src/driver/postgres/PostgresQueryRunner.ts
test/github-issues/9063/entity/Post.ts
test/github-issues/9063/issue-9063.ts

Fixes #9063. 
If the column type of a Postgres column is not `uuid`, we should not treat it as a generated column, but rather just a column with a default. This will allow us to define columns that are type `varchar` with `uuid_generate_v4()` while producing the correct migration scripts.
I'm not quite sure how to write tests for this fix. Any pointers would be appreciated!

fix: support postgres column with varchar datatype and uuid_generate_v4() default

---

src/driver/postgres/PostgresDriver.ts
src/driver/postgres/PostgresQueryRunner.ts
test/functional/cube/postgres/cube-postgres.ts
test/github-issues/9318/issue-9318.ts

Change Postgres driver version checking query to add compatibility with the Postgres compatible AWS Redshift database.
When connecting using the Postgres driver, the afterConnect method is running the SQL `SHOW server_version;` as part of feature support detection. This command works on postgres and cockroachdb, but is incompatible with the postgres compatible redshift database.
This change adjusts the postgres `SHOW server_version` query to use `SELECT version()` which is supported by Postgres and CockroachDB, and gives compatibility with AWS Redshift database
Example command outputs:
**Redshift**
`SELECT version();`
PostgreSQL 8.0.2 on i686-pc-linux-gnu, compiled by GCC gcc (GCC) 3.4.2 20041017 (Red Hat 3.4.2-6.fc3), Redshift 1.0.40677
**Postgresql**
`SELECT version();`
PostgreSQL 14.5 …

fix #9318 change postgres driver version checking query

---

docs/find-options.md
docs/select-query-builder.md
src/driver/Driver.ts
src/driver/DriverUtils.ts
src/driver/mysql/MysqlDriver.ts
src/driver/postgres/PostgresDriver.ts
src/find-options/FindOneOptions.ts
src/query-builder/QueryExpressionMap.ts
src/query-builder/SelectQueryBuilder.ts
test/functional/query-builder/locking/query-builder-locking.ts
test/functional/repository/find-options-locking/find-options-locking.ts

Fixes #8911
This adds a function `addOnLocked` to the select query builder. Instead of adding multiple new values to the `lockMode` enum to support `FOR SHARE`, `FOR KEY SHARE` and `FOR NO KEY UPDATE`, this changes the pattern to add a `onLocked` to the expression map. Valid values for `onLocked` are `nowait` or `skip_locked`.
As part of this change we should deprecate `"pessimistic_partial_write"` and `pessimistic_write_or_fail` because they are no longer necessary with this change and remove them on the next major version change.
Added tests and updated the docs with the new option `setOnLocked`

feat: add setOnLocked for SKIP LOCKED and NOWAIT

---

src/commands/CommandUtils.ts

fix: #9330
Change [for...of](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...of) to [for...in](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...in)

fix: #9330

---

src/entity-schema/EntitySchemaColumnOptions.ts
src/entity-schema/EntitySchemaTransformer.ts
test/functional/entity-schema/custom-constraint-names/foreign-key/entity/Animal.ts
test/functional/entity-schema/custom-constraint-names/foreign-key/entity/Breed.ts
test/functional/entity-schema/custom-constraint-names/foreign-key/entity/Category.ts
test/functional/entity-schema/custom-constraint-names/foreign-key/entity/Name.ts
test/functional/entity-schema/custom-constraint-names/foreign-key/foreign-key.ts
test/functional/entity-schema/custom-constraint-names/index/entity/Post.ts
test/functional/entity-schema/custom-constraint-names/index/index.ts
test/functional/entity-schema/custom-constraint-names/primary-key/entity/Post.ts
test/functional/entity-schema/custom-constraint-names/primary-key/entity/User.ts
test/functional/entity-schema/custom-constraint-names/primary-key/primary-key.ts
test/functional/entity-schema/custom-constraint-names/unique/entity/Post.ts
test/functional/entity-schema/custom-constraint-names/unique/unique.ts

* adds missing support for `primaryKeyConstraintName` property in EntitySchema definition
* adds tests for another custom constraint names in EntitySchema definition
Fixes #9309

fix: add missing support for `primaryKeyConstraintName` property in EntitySchema

---

src/query-builder/RelationIdLoader.ts
test/github-issues/9379/entity/SuperLongTableName.ts
test/github-issues/9379/entity/SuperLongTableNameIsRelatedToOriginal.ts
test/github-issues/9379/issue-9379.ts

Update RelationIdLoader to use DriverUtils.getAlias to prevent aliases being possibly trimmed by database.
Closes: #9379
Updates `RelationIdLoader` class to use `DriverUtils.getAlias` to generate column aliases. This resolves issues with databases that have hard limit on column aliases such as Postgres.
**I've never contributed to this project so I'm definitely not sure if this fix is correct**, but it did resolve the issue with `relationLoadStrategy: query` I was having. There may be other places that don't use this util? Maybe this breaks some other behaviour that expects the columns to be properly named?

fix: Update RelationIdLoader to use DriverUtils.getAlias

---

src/query-builder/SelectQueryBuilder.ts
test/github-issues/9272/entity/User.ts
test/github-issues/9272/issue-9272.ts

Fixes #9272
Update `SelectQueryBuilder.buildSelect` method to correctly build the property path for deeply nested embedded entities.
Previously, selecting a specific deeply nested embedded entity through the `FindOptionsSelect` object on the `find*` methods resulted in a runtime error, due to `SelectQueryBuilder.buildSelect` building the wrong property path for the embedded entity.

fix: malformed query when selecting deeply nested embedded entities

---

src/driver/sqljs/SqljsDriver.ts
src/driver/sqljs/SqljsQueryRunner.ts

Fixes: #9100
When calling `autoSave` in a transaction, typeorm automatically closes the transaction in the `export` method. Therefore, when calling `commitTransaction`, the transaction is already committed and sqljs throws an exception "Cannot commit, no transaction is active".
This fix disables `autoSave` during the transaction to avoid this. Of course, `autoSave` is still called after the transaction, when calling commit. 
There was another PR for this issue (https://github.com/typeorm/typeorm/pull/9101) but this fix is not working when saving the database inside a transaction. If we call a `find` on the repository, typeorm releases the connection and it's calling `autoSave`. Waiting for the transaction to finish before saving was not working as we wait indefinitely.

fix: fix "Cannot commit, no transaction is active" error in sql.js

---

README.md

I've created a couple of packages that others in the TypeORM community might find useful.
-   Easy manipulation of `relations` objects - [typeorm-relations](https://npmjs.com/package/typeorm-relations)
-   Automatically generate `relations` based on a GraphQL query - [typeorm-relations-graphql](https://npmjs.com/package/typeorm-relations-graphql)
I was wondering if it might be acceptable to link to these from the "Extensions" section in the README?
N/A, docs only

docs: add typeorm-relations to Extensions section

---

docs/migrations.md

docs: fixed typo 
Datasoure ==> Datasource
Fixed a typo in docs
Datasoure => Datasource
- [NA] `npm run format` to apply prettier formatting
- [NA] `npm run test` passes with this change
- [NA] This pull request links relevant issues as `Fixes #0000`
- [NA] There are new or updated unit tests validating the change

Fix typo in migrations doc

---

docs/listeners-and-subscribers.md

You can define a method with any name in the entity and mark it with `@AfterRecover` and TypeORM will call it after the entity is recovered using repository/manager `recover`. Example:
```typescript
@Entity()
export class Post {
@AfterSoftRemove()
updateStatus() {
this.status = "recovered"
}
}
```
`@AfterSoftRemove()` should be `@AfterRecover`

Fix decorator typo for @AfterRecover()

---

README.md

- The link to the vesper framework was incorrect - it now points to the repository on github, which does seems to be inactive but at least the link now works.

docs: update incorrect link

---

test/functional/connection/connection.ts

syncSchema was renamed to synchronize but nobody updated the test case name.
Consistency of terminology helps especially newcomers to work on the project.
This change does not affect behavior, just replaces the earlier name with the current one.
- [N/A] There are new or updated unit tests validating the change

fix: old name fixed in test case name

---

src/driver/postgres/PostgresQueryRunner.ts

Fixes #9432
If a `TableForeignKey` is without a name on `dropForeignKey` so it's create a name like on `createForeignKey`

fix: resolve nameless TableForeignKey on drop foreign key

---

src/driver/aurora-mysql/AuroraMysqlQueryRunner.ts
test/github-issues/9477/entity/Test.ts
test/github-issues/9477/issue-9477.ts

Replicates a fix that has been done for MySQL to the AWS Aurora data api driver. (#6632) Unsigned Integers cause unwanted migrations due to difference in reported width.
Fixes #9477 

fix: resolve issue with migrations and unsigned int columns in aurora-data-api

---

src/util/OrmUtils.ts

Fixes OrmUtils crashing when checking objects with `null prototype`. Instead, always returns false. This is recommended by eslint https://eslint.org/docs/latest/rules/no-prototype-builtins

Fix orm utils prototype check

---

package-lock.json
src/find-options/operator/Any.ts
src/find-options/operator/ArrayContainedBy.ts
src/find-options/operator/ArrayContains.ts
src/find-options/operator/ArrayOverlap.ts
src/find-options/operator/In.ts

Mark the array arguments to find operators like `In` and `ArrayContains` as `readonly`. This makes it possible to use them with readonly arrays as parameters without casting or having to make copies.

Mark array arguments to find operators as read-only

---

src/driver/better-sqlite3/BetterSqlite3QueryRunner.ts
src/driver/sqlite-abstract/AbstractSqliteDriver.ts
test/functional/driver/abstract-sqlite/abstract-sqlite-escape-query-parameters.ts

(Re-)Fixes: #1981
The issue in #1981 re-occurred after 0.3.0 because `nativeParameters` became deprecated and new `find` methods use `parmeters` instead which where not fixed in #7122. This PR adds the boolean parameter escape for all kind of parameters and also makes additional transformations as implemented in the `BetterSqlite3QueryRunner` obsolete. 
The problem seems to be mainly related to the `CordovaDriver` where I also encountered this problem after migration to > 0.3.0. However, I think it's appropriate to have this fixed in the `AbstractSqliteDriver` because it is obviously affecting `BetterSqlite3` too and a correct way of handling boolean properties in SQLite anyways :). 
A similar approach was already submitted via: #9009 which was closed unfortunately but I added test-cases …

Fix parameter escape in SQLiteDriver

---

src/query-builder/RelationLoader.ts

Change to makes properties for entity relation explicitly non-enumerable, which resolves a "rare" issue that leads to a memory leak.
In some environments it seems like an entity object was created with column values set to undefined, thus Object.defineProperty uses already defined value for enumerable - true. This leads to RawSqlResultsToEntityTransformer.transform() run-getters on relation fields (as they were enumerable) resolving the promises - running queries which eventually leads to the Free memory exhaustion on the machine :)
Closes: #6631 
Unfortunately while trying to find a way to replicate the issue in a couple of ways:
- Trying to make entity class derivative of BaseEntity
- Trying to run compiled tests
- Replicating my project entities in close to 1:1 way
I wasn't able to …

fix: explicitly define property for entity relation as enumerable

---

README.md

I've just removed one `\` from the documentation. Comments are defined by `\\`, and the three slashes (`\\\`) are sometimes used for automatic documentation generation[^1].
[^1]: [What does the three slashes in javascript do?](https://stackoverflow.com/a/10423481)

I think that now is better 😅 (Tiny modification in README.md file)

---

src/commands/MigrationRevertCommand.ts

Closes #9561
passed fake argument to `undoLastMigration` in `MigrationRevertCommand`

Pass fake argument to undoLastMigration Fixes #9561

---

src/driver/react-native/ReactNativeQueryRunner.ts

Correctly return the `insertId` in `ReactNativeQueryRunner.ts`, thus returning the updated entity with `save()` when inserting.
I've just re-ordered the code. Previously, the `insertId` was overwritten a few lines below.
Fixes #9482

fix: correctly return insertId for react-native

---

package-lock.json
src/repository/Repository.ts
src/repository/TreeRepository.ts

additionally remove duplicated TreeRepository.extend method
For example, if you use 
```typescript
dataSource.getMongoRepository(Foo).extend({ findSomething: () => {} })
``` 
right now it will returns typing like this
```typescript
Repository<Foo> & { findSomething: (): void }
```
with this fix it will return 
```typescript
MongoRepository<Entity> & { findSomething: (): void }
```

fix: typings for Repository.extend function

---

docs/entity-manager-api.md
docs/repository-api.md

This is a suggestion to improve the documentation.
In the [Repository API section](https://typeorm.io/repository-api), under the `update` API documentation, the first usage example is the following:
```typescript
await repository.update({ firstName: "Timber" }, { firstName: "Rizzrak" })
// executes UPDATE user SET firstName = Rizzrak WHERE firstName = Timber
```
Because of the use of 2 "`firstName`" in the API, I got confused and reversed the **WHERE** condition and the actual **change**.
Thus, this doc change PR is just a suggestion to avoid that kind of confusion.

Doc: Improve comprehension of update repository API

---

docs/using-cli.md

related: #8185
migration:show command already does not return error code.

docs: update "migration:show error code" description

---

src/driver/sqlite/SqliteConnectionOptions.ts
src/driver/sqlite/SqliteDriver.ts
test/functional/sqlite/file-open-flags.ts

Add the ability to pass in open DB connection flags and DB URI's for the sqlite3 driver.  This allows for sharing of the drive/in-memory DB between threads. 
Unfortunately, the better-sqlite3 driver isn't yet able to do this:
https://github.com/WiseLibs/better-sqlite3/issues/483
https://github.com/WiseLibs/better-sqlite3/pull/735
Here is where it was added in the sqlite3 upstream driver:
https://github.com/TryGhost/node-sqlite3/issues/1032
https://github.com/TryGhost/node-sqlite3/pull/1078
Example usage in sqlite:
https://github.com/TryGhost/node-sqlite3/blob/master/test/open_close.test.js
Flags:
https://www.sqlite.org/c3ref/c_open_autoproxy.html
Example usage of this fix:
https://github.com/WeWatchWall/stark-db

SQLite Driver: Add Open DB Flags and URI DB Name

---

src/data-source/DataSource.ts

Fixes #9454
Update the `initialize()` method of the DataSource class. Only set `isInitialized: true` at the very end to ensure everything has been properly loaded.
Note: is there is a guide on how to run test ?

fix(DataSource): assign isInitialized: true at the end of initialize

---

src/query-builder/SelectQueryBuilder.ts
test/functional/cache/custom-cache-provider.ts
test/functional/cache/entity/Address.ts
test/functional/cache/entity/User.ts

The cacheId is set to undefined when finding entities with relations and the pagination(s) option(s) is/are set (take/skip).
It seems the cacheId is set to undefined for the main request used for pagination when we load related entities.
I appended a `-pagination` to the identifier of the pagination request.
Related #5983

fix: cacheId not used when loading relations with take

---

docs/data-source-options.md
src/driver/postgres/PostgresConnectionOptions.ts
src/driver/postgres/PostgresDriver.ts
test/github-issues/9341/entity/TestEntity.ts
test/github-issues/9341/issue-9341.ts

Closes #9341
Add `parseInt8` option to the Postgres driver.
Uses the underlying pg drivers `pg.defaults.parseInt8` - see https://github.com/brianc/node-postgres/blob/e087305f316b364bdbd3045f5c5339b80f757174/lib/defaults.js#L66-L70

feat: add parseInt8 option to postgres driver. Closes #9341

---

docs/supported-platforms.md
src/driver/cordova/CordovaDriver.ts
src/persistence/EntityPersistExecutor.ts
test/functional/persistence/persistence-options/transaction/persistence-options-transaction.ts

The [cordova-sqlite-storage](https://github.com/litehelpers/Cordova-sqlite-storage) plugin does not support regular transactions at the moment.
See: https://github.com/storesafe/cordova-sqlite-storage#other-limitations
> User-defined savepoints are not supported and not expected to be compatible with the transaction locking mechanism used by this plugin. In addition, the use of BEGIN/COMMIT/ROLLBACK statements is not supported.
This conflicts with the way typeORM is handling save / remove operations via the `EntityPersistExecutor` by default leading to errors when not explicitly disabling the transaction on each method call via the respective option (e.g. `connection.manager.save(ExampleEntity, { transaction: false })`. Prior version 0.2.34 this was not a problem since the transaction was …

Disable transactionSupport option for CordovaDriver

---

src/data-source/DataSource.ts
src/driver/better-sqlite3/BetterSqlite3Driver.ts
src/driver/capacitor/CapacitorDriver.ts
src/driver/cordova/CordovaDriver.ts
src/driver/expo/ExpoDriver.ts
src/driver/nativescript/NativescriptDriver.ts
src/driver/react-native/ReactNativeDriver.ts
src/driver/sqlite/SqliteDriver.ts

* make sure we update database in the driver if it was dynamically set via dataSource.setOptions
* removed validation for database since we definitely shouldn't have it in the constructor, database can be set later on (e.g. datasource.setOptions)
`DataSource.setOptions` doesn't work properly if we update database name using it, e.g.
```ts
dataSource.setOptions({ database: "database-defined-later" })
```
This PR fixes this problem.

fix: DataSource.setOptions doesn't properly update the database in the drivers

---

src/driver/sqlite-abstract/AbstractSqliteQueryRunner.ts
test/functional/multi-database/multi-database-basic-functionality/multi-database-basic-functionality.ts

Optimized DDL queries during DB synchronization in SQLite.
Before:
```sql
SELECT * FROM "sqlite_master" WHERE "type" = 'table' AND "name" IN ('user')
SELECT * FROM "sqlite_master" WHERE "type" = 'table' AND "name" IN ('question')
SELECT * FROM "sqlite_master" WHERE "type" = 'table' AND "name" IN ('answer')
SELECT * FROM "sqlite_master" WHERE "type" = 'table' AND "name" IN ('category')
```
After:
```sql
SELECT * FROM "sqlite_master" WHERE "type" = 'table' AND "name" IN ('user', 'question', 'answer', 'category')
```

fix: multiple select queries during db sync in sqlite

---

src/driver/postgres/PostgresDriver.ts

Correct a typo in an error message, where it shows there is an error creating ltree extension, the original error message mentions a cube type column instead of ltree.

fix: correct a typo

---

package-lock.json
src/driver/sqlite/SqliteConnectionOptions.ts
src/driver/sqlite/SqliteDriver.ts
test/functional/sqlite/busy-timeout.ts

**support busy_timeout parameter for sqlite driver**
Fixes https://github.com/typeorm/typeorm/issues/9622

feat: support busy_timeout parameter for sqlite

---

src/query-builder/QueryBuilder.ts
test/functional/query-builder/cte/materialized-cte.ts

Fix implementation of materialized hints in common table expressions.
Previous behavior did not account for NOT MATERIALIZED hints, also placed materialized hints in wrong place (before "AS").
This change only affects drivers that support materialized hints (currently, postgres and cockroachdb)
I stumbled upon this while using your excellent library at work and trying to optimize queries using CTEs with postgres.
I'm sorry if I skipped opening an issue first. If it is necessary I'll do that and move the tests to an issue folder.

fix: materialized hints support for cte

---

src/driver/oracle/OracleQueryRunner.ts
test/github-issues/9601/entity/Foo.ts
test/github-issues/9601/entity/FooView.ts
test/github-issues/9601/issue-9601.ts

Modify OracleQueryRunner to workaround potentially bad inputs to insertViewDefinitionSql(), where the View object passed in does not have schema defined, but the name of the view already has the schema as a prefix. Use parseTableName() to separate the schema and the view name.
Fixes #9601

Synchronizing view with schema broken for oracle

---

src/driver/cockroachdb/CockroachQueryRunner.ts
src/index.ts
test/functional/query-builder/time-travel-query/entity/Person.ts
test/functional/query-builder/time-travel-query/time-travel-query.ts

fixed: #9712 
I can't run test code because file importing grammar error
I saw the below errors
```
Error: Cannot find module '../../util/VersionUtils.js'
...
Error: Cannot find module './driver/types/GeoJsonTypes.js'
...
```
So I removed file extensions when file importing. (It's not not a js file.)

Fix - remove extension when importing file

---

docs/many-to-many-relations.md

There's a grammar (verbal agreement) mistake in the first paragraph: "B contain multiple instances of A" instead of "B contains multiple instances of A".

docs: Fix grammar error in the first paragraph.

---

src/find-options/FindOptionsWhere.ts
test/github-issues/9152/entity/Test.ts
test/github-issues/9152/issue-9152.ts

Fixes #9152 
Some CI have failed (edited: now CI passed by re-run), but it seems there is no problem based on the following points:
- I made changes to the type definitions but not to the implementation
- `tsc` succeeds
- The added tests do not depend on the database, and there is a successful CI for Postgres, etc.
- updates doesn't seem necessary

fix: allow `FindOptionsWhere` to accept `LessThan` with Union

---

src/query-builder/SelectQueryBuilder.ts
test/github-issues/9690/entity/Foo.ts
test/github-issues/9690/issue-9690.ts

Closes: #9690
- fix sql expression when `where` parameter is empty array

fix: sql expression when `where` parameter is empty array

---

docs/data-source-options.md
docs/migrations.md
docs/using-cli.md
docs/zh_CN/connection-options.md
docs/zh_CN/migrations.md
docs/zh_CN/using-cli.md

- remove cli.entitiesDir description
- remove cli.subscribersDir description
- remove cli from Data Source Options example
- extend migration:run examples with -- -d path-to-datasource-config
- extend migration:revert examples with -- -d path-to-datasource-config
- extend migration:show examples with -- -d path-to-datasource-config
- extend migration:create examples with path-to-migrations-dir/migrationName

docs: update cli related docs

---

package-lock.json
src/driver/better-sqlite3/BetterSqlite3ConnectionOptions.ts
src/driver/better-sqlite3/BetterSqlite3Driver.ts
test/github-issues/9410/issue-9410.ts

Fixes #9410 
The better sqlite3 driver lacks the enableWal flag in its options. Moreover, the WAL mode always gets enabled, since this configuration is hardcoded in the [driver itself](https://github.com/typeorm/typeorm/blob/master/src/driver/better-sqlite3/BetterSqlite3Driver.ts#L171). Neither the [sqlite driver](https://github.com/typeorm/typeorm/blob/master/src/driver/sqlite/SqliteDriver.ts#L177) nor the better-sqlite3 library itself enable this mode by themselves, so I see no reason to have it always enabled.
The `enableWal` flag will force the WAL mode when turned on, but keeps the existing default for the database if not set or set to false. This guarantees backwards compatibility with existing databases.

feature: support enableWal for the better-sqlite3 driver

---

src/driver/postgres/PostgresQueryRunner.ts
test/github-issues/9684/entity/Foo.ts
test/github-issues/9684/issue-9684.ts

This PR is to get the default enum value when creating migrations correctly. 
Closes: https://github.com/typeorm/typeorm/issues/9684
expected enum default value `UNPAID` from `'UNPAID'::module-payment_order_entity_enum` constraint, but the return was incorrect `'UNPAID'-payment_order_entity_enum"`

default enum value when creating migrations

---

docs/repository-api.md
src/common/PickKeysByType.ts
src/entity-manager/EntityManager.ts
src/repository/BaseEntity.ts
src/repository/Repository.ts
test/functional/repository/aggregate-methods/entity/Post.ts
test/functional/repository/aggregate-methods/repository-aggregate-methods.ts

This addresses #673, and adds a convenient way to call aggregate functions via the repository API.

feat: Add support for SQL aggregate functions SUM, AVG, MIN, and MAX to the Repository API

---

src/driver/react-native/ReactNativeDriver.ts
src/driver/react-native/ReactNativeQueryRunner.ts

This PR temporary merges AbstractSqliteDriver code into ReactNativeDriver because of circular dependencies in the project the latest version of TypeORM doesn't work in react-native in ESM projects.
Proper solution is to refactor the codebase and get rid of circular dependencies.

fix: react-native doesn't properly work in ESM projects because of circular dependency

---

src/platform/PlatformTools.ts

Fixes #9766
Replace backslashes with forward slashes when normalizing a path on Windows, in order to make the path work for glob pattern resolving.

Use forward slashes when normalizing path on Windows

---

docs/select-query-builder.md

It covers using getQuery() and getQueryAndParameters() which are both useful when trying to figure out why your query isn't doing what you might expect it should do.
I added it because I had to go digging through the source code to find out that these wonderful methods existed, and wanted to save future users the same hassle.

Added a documentation section on debugging query builder

---

src/driver/sqlserver/SqlServerDriver.ts
test/github-issues/9399/entity/ExampleEntity.ts
test/github-issues/9399/issue-9399.ts

Resolves issue with mssql column recreation when length max is i)n lower case
Fixes: #9399 
[~] Documentation has been updated to reflect this change

fix: resolves issue with mssql column recreation

---

src/find-options/FindOptionsOrder.ts
test/github-issues/9895/entity/ExampleEntity.ts
test/github-issues/9895/issue-9895.ts

When using an Entity column transformer for an object type, the underlying database column may be sortable, despite the static TypeScript type being an object. The `FindOptionsOrder` typing should allow sorting on that object property and not require further nesting.
Fixes issue #9895.

Allow type FindOptionsOrderValue for order by object property (#9895)

---

test/functional/repository/aggregate-methods/repository-aggregate-methods.ts

In this case, 50 instead of 50.5. Apparently the ANSI standard for SQL is silent on this issue, so either behavior should be considered acceptable.
Modify test to accept the answer that SQL Server gives for AVG even though it is mathematically inaccurate.

When calling AVG on an integer column, MS SQL Server returns an int (test only fix)

---

src/driver/sqlite-abstract/AbstractSqliteQueryRunner.ts
test/github-issues/9266/issue-9266.ts
test/github-issues/9266/migrations/init.ts

Closes: #9266
Currently, the AbstractSQLiteQuerryRunner expects the FK to be defined as `CONSTRAINT "FK_ID" FOREIGN KEY  ("columnName") REFERENCES  "table"("id")`. 
However, this is also a valid way to declare a FK:  `columnName TEXT REFERENCES table(id)`.
In that case, there is no foreign key id and the code was throwing an exception on this line: https://github.com/typeorm/typeorm/blob/58fc08840a4a64ca1935391f4709a784c3f0b373/src/driver/sqlite-abstract/AbstractSqliteQueryRunner.ts#L1573

fix: loading tables with fk in sqlite query runner

---

src/query-builder/SelectQueryBuilder.ts
test/functional/query-builder/select/query-builder-select.ts

Fixes the error message that is thrown on `QueryBuilder.findOneOrFail` if no entity is found.
Currently, a message like `Could not find any entity of type "Organization" matching: [object Object]` is displayed in that case.  This happens because `this` is passed to the error constructor, instead of the parameters that did not return a result.

fix: EntityNotFound error message in QueryBuilder.findOneOrFail

---

src/driver/postgres/PostgresQueryRunner.ts
test/github-issues/9829/entity/ExampleEntity.ts
test/github-issues/9829/issue-9829.ts

Closes: https://github.com/typeorm/typeorm/issues/9829

[Postgres]fix: proper default value on generating migration when a default value is a function calling

---

src/metadata/EmbeddedMetadata.ts

Fixes #9824. Allows embedded entities to skip constructor when entitySkipConstructor is set.

fix: use object create if entity skip constructor is set

---

src/migration/MigrationExecutor.ts
test/functional/migrations/show-command/command.ts
test/github-issues/9770/entity/Bar.ts
test/github-issues/9770/entity/Foo.ts
test/github-issues/9770/issue-9770.ts
test/github-issues/9770/migration/1675779246631-amendFoo.ts

Schema changes in migrations batch cannot be done on table which has referring
foreign keys with ON DELETE CASCADE without deleting its content.
Closes: #9770
Closes: #2584
Complemente the PR #7922 by executing beforeMigration before each migration and execting afterMigration after each migration right before Transaction is started and right after transaction is being commited.
As specified in [sqlite doc](https://www.sqlite.org/pragma.html#pragma_foreign_keys) : 
> This pragma is a no-op within a transaction; foreign key constraint enforcement may only be enabled or disabled when there is no pending [BEGIN](https://www.sqlite.org/lang_transaction.html) or [SAVEPOINT](https://www.sqlite.org/lang_savepoint.html).
So the change is to run PRAGMA foreign_keys = OFF before starting the …

fix: prevent foreign key support during migration batch under sqlite

---

src/util/StringUtils.ts
test/functional/util/StringUtils.ts

Fixed `firstCapital` parameter in `camelCase` function.
```ts
// before
camelCase("test_string", true) // testString
// after
camelCase("test_string", true) // TestString
```
* fixes #7331
* closes #9720
* closes #9837
- n/a Documentation has been updated to reflect this change

fix: firstCapital=true not working in camelCase() function

---

.circleci/config.yml

Fixes ci error 
```
ORA-12514: TNS:listener does not currently know of service requested in connect descriptor
```
because port-scan is not enough to determine wether oracledb is ready to handle connections.
[this comment](https://github.com/typeorm/typeorm/pull/9926#issuecomment-1505815061)

ci: wait if oracle db is enabled in test suite

---

src/schema-builder/RdbmsSchemaBuilder.ts

During `migration:generate`, when a column is renamed, the table name is omitted in the log.
Before:
```
renaming column "MyOldName" in to "MyNewName"
```
After:
```
renaming column "MyOldName" in "MyTable" to "MyNewName"
```

fix rename column log

---

src/driver/sqlite-abstract/AbstractSqliteDriver.ts

https://github.com/typeorm/typeorm/pull/9744 introduced json column type for sqlite with different handling as it is for simple-json. but it is indeed the same as for simple-json. so we can reuse the same helper methods for both.

refactor: combine json and simple-json handling sqlite

---

src/cache/DbQueryResultCache.ts
src/cache/QueryResultCacheOptions.ts
src/cache/RedisQueryResultCache.ts

This patch allows the `getFromCache` caller to only pass in `identifier` or `query` field, as `getFromCache`only needs **either, or neither** `identifier` or `query` to be present.
Currently as a caller of `getFromCache`, one is required to pass both `identifier` and `query` value, which is unnecessary because only one will be used for execution, with `identifier` taking precedence.

fix: make cache optional fields optional

---

src/metadata-builder/RelationJoinColumnBuilder.ts
test/github-issues/8485/issue-8485.ts

As described in #8485, a relation creates besides the foreign key on the main entity, also an unique index on the referenced entity. This happens even though the column (or combination of columns) already is the primary of the referenced entity. Until now, exceptions have been made for certain dialects, however, as discussed in https://github.com/typeorm/typeorm/pull/9677#issuecomment-1422963665, this is not necessary.
This PR fixes #8485 for all SQL dialects (including MySQL and SAP HANA), not just Oracle.

fix: prevent unique index identical to primary key (all sql dialects) fixes #8485

---

src/persistence/SubjectChangedColumnsComputer.ts
test/github-issues/9948/entity/Post.ts
test/github-issues/9948/issue-9948.ts
test/github-issues/9948/subscriber/PostSubscriber.ts

Closes: #9948
Fixes issue #9948 with duplicate update columns in after update subscriber method if before update method is defined by filtering `Subject.diffColumns`

fix: resolve duplicate subscriber updateed columns

---

src/data-source/DataSource.ts
src/entity-manager/EntityManager.ts

the query methods can now accept a generic type that is used as the return type. If no generic were passed, it will default to any (the current behavior). This way it allows the consumer of the library to decide what should be the return type without type casting (`as`). 
I wrote an ESLint plugin ([SafeQL](https://github.com/ts-safeql/safeql)) that helps validate the return type of a raw query based on the generic type, which is the main reason I raised this PR. Currently, type augmentation is the only way to integrate TypeORM with SafeQL which hurts DX (which I'm trying to avoid) 🙂.

query methods should accept generic for return type

---

docker-compose.yml
docs/entities.md
src/driver/mysql/MysqlDriver.ts
src/driver/types/ColumnTypes.ts
src/metadata-builder/JunctionEntityMetadataBuilder.ts
src/metadata-builder/RelationJoinColumnBuilder.ts
test/github-issues/6540/entity/order.entity.ts.ts
test/github-issues/6540/issue-6540.ts
test/github-issues/8832/badEntity/BadInet4.ts
test/github-issues/8832/badEntity/BadInet6.ts
test/github-issues/8832/badEntity/BadUuid.ts
test/github-issues/8832/entity/Address.ts
test/github-issues/8832/entity/User.ts
test/github-issues/8832/entity/UuidEntity.ts
test/github-issues/8832/issue-8832.ts

Fixes #8832
Adds uuid, inet4, inet6 column data types for appropriate mariadb versions

feat: mariadb uuid inet4 inet6 column data type support

---

src/driver/mysql/MysqlDriver.ts
test/github-issues/9903/entity/User.ts
test/github-issues/9903/issue-9903.ts

This addresses the defaulting of json to longtext where users of later versions are unable to use the alias of JSON for the column type which creates an automatic JSON check constraint.
Fixes #9903

fix: allow json as alias for longtext in applicable mariadb versions

---

src/query-builder/RelationIdLoader.ts
src/query-builder/SelectQueryBuilder.ts
test/github-issues/9988/entity/category.ts
test/github-issues/9988/entity/product.ts
test/github-issues/9988/issue-9988.ts

fix issue - createQueryBuilder in repository loses queryplanner when wrapped in txn upsteam until RelationIdLoader
Closes: #9988
When we create relationships within a transaction using `createQueryBuilder` and `relationLoadStrategy: "query"`, RelationIdLoader queries relationships outside of the transaction that creates these relationships.
This causes the relationships to always be [], when that isn't the case.

fix: RelationIdLoader has access to queryPlanner when wrapped in transaction

---

docs/data-source-options.md
src/driver/sqlserver/SqlServerConnectionOptions.ts

Add `trustServerCertificate` option to `SqlServerConnectionOptions` interface. No updates to driver code are necessary since the entire `options` object is passed to the driver.
Closes #8093

fix: add `trustServerCertificate` option to `SqlServerConnectionOptions`

---

src/driver/sqlserver/SqlServerConnectionOptions.ts

Fixes #7686 
Added instanceName to SqlServerConnectionOtions.
This property was present in the docs (data-source-options.md) but missing in code.
The existing workarounds to put the instanceName in extra did not work for me.

added instanceName to options

---

src/cli-ts-node-esm.ts

Use child process exit code in parent process to properly indicate that child process (migration running) fails. Previously parent process always exists with code 0.
Closes: #10029

fix: for running cli-ts-node-esm use exit code from child process

---

src/query-builder/transformer/RawSqlResultsToEntityTransformer.ts
test/other-issues/auto-increment-id-as-string/auto-increment-id-as-string.ts
test/other-issues/auto-increment-id-as-string/entity/Role.ts
test/other-issues/auto-increment-id-as-string/entity/User.ts

When I use auto-incremented id as a string and call findOne with the "loadRelationIds:true" option, I get an empty array for the "relationIds" property, even though the relation exists.

fix: Convert the join table ID to the referenceColumn ID type

---

src/driver/mongodb/MongoDriver.ts
test/github-issues/9885/issue-9885.ts

It fix an unauthorized error when connecting to mongodb using the character `@` in the credentials

fix: correct encode mongodb auth credentials

---

docs/data-source-options.md
src/driver/cockroachdb/CockroachConnectionOptions.ts
src/driver/cockroachdb/CockroachQueryRunner.ts
test/github-issues/9984/entity/Post.ts
test/github-issues/9984/issue-9984.ts

fix: added transaction retry logic in cockroachdb

---

test/github-issues/7558/entity/Animal.ts

Oracle does not have a `onUpdate: 'CASCADE'` option. Thus, the test fixtures had to be adapted.
Checking for the correct `onUpdate` actions for Oracle was introduced in #9786.
Related To #9034

test: fix test from #9034 with STI for Oracle

---

src/migration/MigrationExecutor.ts

There was missing `await` that cause `QueryRunnerAlreadyReleasedError`.

fix: add missing await

---

docs/listeners-and-subscribers.md

fix typo on given example. it should log `entity`, instead of `post`

fix typo on given example

---

src/driver/sqlserver/SqlServerConnectionOptions.ts
src/driver/sqlserver/SqlServerQueryRunner.ts
test/github-issues/10131/entity/Example.ts
test/github-issues/10131/issue-10131.ts

This adds a new property `disableAsciiToUnicodeParamConversion` to `SqlServerConnectionOptions` to control whether the `MssqlParameter` types `char`, `varchar`, and `text` are converted to their unicode equivalents `nchar`, `nvarchar`, and `ntext`. This defaults to `false`, maintaining the current behavior.
Example:
```
andWhere('"name" = :firstName', {
firstName: new MssqlParameter('Bill', 'varchar', 100)
})
```
- The current behavior: `firstName` is treated as an `nvarchar`
- This PR introduces configuring this behavior: setting `disableAsciiToUnicodeParamConversion` to `true` treats `firstName` as `varchar`. If `disableAsciiToUnicodeParamConversion` is set to `false` or omitted from the ORM configuration values, `firstName` remains `nvarchar`
See full description of the issue, …

fix: add mssql disableAsciiToUnicodeParamConversion option and tests

---

src/driver/sqlserver/SqlServerConnectionCredentialsOptions.ts
src/driver/sqlserver/authentication/AzureActiveDirectoryDefaultAuthentication.ts

Tedious Supports the DefaultAzureCredential via specifying `azure-active-directory-default` as the auth type and an optional clientId. These types are missing from the TS contract that typeorm accepts
http://tediousjs.github.io/tedious/api-connection.html#function_newConnection
This is an additional option to what was introduced here: https://github.com/typeorm/typeorm/pull/7477
Fixes: https://github.com/typeorm/typeorm/issues/10223

feat: Adding TS Types for DefaultAzureCredential usage

---

src/persistence/Subject.ts
test/github-issues/10249/entity/example.ts
test/github-issues/10249/issue-10249.ts

Closes: #10249
With this change, EntityManager.save won't throw an error when all changes of a subject are for columns with `update: false`.
Fixes #10249

fix: ignore changes for columns with `update: false` in persistence

---

src/commands/CommandUtils.ts

Fixes #10168 
The check in `CommandUtils.ts` for detecting whether the DataSource-source is a promise is broken.
Rather than testing whether it's a promise, simply await the value and use it. The `await` operator is defined in such way that if the thing is not awaitable we simply get the value back
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/await#return_value

fix: using async datasource to configure typeorm

---

src/commands/EntityCreateCommand.ts
src/commands/MigrationCreateCommand.ts
src/commands/MigrationGenerateCommand.ts
src/commands/SubscriberCreateCommand.ts
test/functional/commands/migration-create.ts
test/functional/commands/migration-generate.ts
test/functional/commands/templates/result-templates-create.ts

Add `positionals` as [other commands](https://github.com/typeorm/typeorm/blob/a100a7a7f1c17432549e5e93fb141d0f52062213/src/commands/QueryCommand.ts#L20-L23) to improve the `--help` output
it adds it to:
- MigrationCreateCommand
- MigrationGenerateCommand
- SubscriberCreateCommand
- EntityCreateCommand
Also **fixes** and **reactivates** the tests for `migration - create` and `migration - generate`
```
cli.js migration:create <path>
Creates a new migration file.
Options:
-h, --help       Show help                                           [boolean]
-o, --outputJs   Generate a migration file on Javascript instead of Typescript
[boolean] [default: false]
-t, --timestamp  Custom timestamp for the migration name
[number] [default: false]
-v, --version    Show version number …
```

fix: improve helper for cli for commands missing positionals

---

src/query-builder/QueryBuilder.ts
test/functional/query-builder/comment/query-builder-comment.ts

This was only removing the first comment end marker, so it was still possible to generate invalid SQL with the comment method.

fix: scrub all comment end markers from comments

---

src/commands/CommandUtils.ts

The solution to `loadDataSource` was probably designed to adapt to various forms of exports coming from ormconfig.js however it failed to adapt to a very regular case where you just do `module.exports = new DataSource({ ... })` resulting in `Error: Given data source file must contain export of a DataSource instance`
Fixes #8810
The loadDataSource did not take into account that the default export might already contain the `DataSource` instance itself. The solution started to iterate over the keys of the `DataSource` in the hope to find a `DataSource` instance under one of those keys. I've adjusted the logic to check if the DataSource is the subject to default export itself then just return it from the function and do not iterate over its keys.

fix: CommandUtils unable to process a regular default export

---

docs/insert-query-builder.md

Changed `datasource` to `dataSource` three times to match the first two references to `dataSource` in this document.
- [✓] Code is up-to-date with the `master` branch
- [N/A] `npm run format` to apply prettier formatting
- [N/A] `npm run test` passes with this change
- [N/A] There are new or updated unit tests validating the change
- [✓] The new commits follow conventions explained in [CONTRIBUTING.md](https://github.com/typeorm/typeorm/blob/master/CONTRIBUTING.md)

docs: fix naming consistency

---

src/persistence/subject-builder/ManyToManySubjectBuilder.ts
test/github-issues/5704/entity/Category.ts
test/github-issues/5704/entity/Post.ts
test/github-issues/5704/issue-5704.ts
test/github-issues/5704/subscriber/CategorySubscriber.ts

In the method `buildForSubjectRelation` of `ManyToManySubjectBuilder`, in order to know if it is needed to insert the relation rows, `databaseRelatedEntityIds` is compared with `relatedEntityRelationIdMap` (line 154). The problem is that `databaseRelatedEntityIds` is not always an "EntityIdMap". If one is overloading the entity in the `afterLoad` event of an EventSubscriber for example then the object compared would contains additionnal field(s) and the ids won't match. This means that the relation is considered has not existing in the DB and the program tries to insert it. And as the relation already exists, a Mysql error is thrown...
To fix this, in this commit, we ensure that `databaseRelatedEntityIds` is containing an "EntityIdMap" by using …

Many to many er dup entry #5704

---

docs/mongodb.md
src/entity-manager/MongoEntityManager.ts
src/repository/MongoRepository.ts

This change exposes countDocuments at the `MongoRepository` layer assisting nestjs applications wanting to move to the non-deprecated version.
Additionally this could be used within `executeFindAndCount` in the MongoEntityManager to follow what's recommended at the driver level.
It seems like there was an optimization in the driver to use `countDocuments` reverted 4 months ago to split them into their own functions but wasn't moved up to the respective manager and repositories.
Ideally MongoRepository should be using countDocuments internally for the `count` overload from `Repository` but I think this is a good start for simply exposing it.
I'm not quite sure how to write good tests expressing this change. Some help on this front would be appreciated.

expose countDocuments in mongodb

---

test/utils/test-utils.ts

Disabling the raft log is going to be disallowed in CockroachDB. Also, this setting wasn't having any effect, since the tests use an in-memory cluster.

test: stop using unsafe CockroachDB setting

---

docs/select-query-builder.md

To use alias as the first argument in the createQueryBuilder method, the entity must be imported into the getRepository method.
I can modify it, such as createQueryBuilder(User, 'user'), but i used getRepository because most of the documents use getRepository.

docs: update select-query-builder.md

---

extra/typeorm-model-shim.js

Adds BaseEntity to model shimming. 
I was going to look at a way to auto-generate it, but it looks like whatever script was used to do that and export the existing shim file isn't in the repo so can tackle that a different day.
Also a very small optimization to not create new functions every decorator call and instead reuse an empty function.
This should fix https://github.com/typeorm/typeorm/issues/8269

fix(shim): add BaseEntity to model-shim

---

src/find-options/FindOptionsWhere.ts

This PR fixes problem, when I want to use custom type witch extends object type for find where argument.
```typescript
await repository.find({
where: {
date: Datestamp.fromYMD(2022, 1, 1),
},
});
```
Error says:
`
Type 'Datestamp' is not assignable to type 'boolean | FindOperator<any> | FindOptionsWhere<Datestamp> | FindOptionsWhere<Datestamp>[] | EqualOperator<Datestamp> | undefined'.
Type 'Datestamp' is not assignable to type 'FindOptionsWhere<Datestamp>'.
Types of property 'getDay' are incompatible.
Type '() => number' is not assignable to type 'undefined'.ts(2322)
`
Datestamp class:
```typescript
class Datestamp {
private readonly ['@instanceof'] = Symbol.for(Datestamp.name);
private readonly year: number;
private readonly month: number;
private readonly day: number;
private readonly …
```

Allow to use custom type witch extends object type for find where argument

---

src/metadata-builder/EntityMetadataBuilder.ts
test/github-issues/10496/entity/A.ts
test/github-issues/10496/entity/B.ts
test/github-issues/10496/entity/Base.ts
test/github-issues/10496/entity/C.ts
test/github-issues/10496/entity/index.ts
test/github-issues/10496/issue-10496.ts

avoid index duplication on the discriminator column when using STI and explicitly defining an index for it
Closes: #10496
Currently, when using Single Table Inheritance, TypeORM will automatically index the discriminator column, with a pre-determined index name, such as "IDX_da86e1027abd881610c93feaee".
Attempting to explicitly specify an index for this column will result in 2 indices being created (the automatically added one, plus the user-defined), which is unnecessary. On Oracle Database, this is actually an error (ORA-01408).
This change adds a check that attempts to validate whether a user-defined index has already been created for the discriminator column, in which case no other indices will be added automatically by TypeORM.
- N/A - no new / updated APIs

feat: user-defined index name for STI discriminator column

---

docs/caching.md

Between v3 and v4 in node-redis the client options changed for a collection of socket related paramaters. In the caching documentation the v3 format for used for `host` and `socket`.
When following the documented example the redis client would default to `localhost` even when a different value for `host` was specified.
Fixes #9987

docs: update redis cache client options

---

src/query-builder/SelectQueryBuilder.ts

In this commit, an error handling logic is added to TypeORM's relationship mapping to deal with scenarios where join columns are missing.
Closes: #7034

fix: add error handling for missing join columns

---

src/persistence/SubjectExecutor.ts
src/subscriber/Broadcaster.ts
src/subscriber/event/InsertEvent.ts
test/github-issues/8221/entity/SettingSubscriber.ts
test/github-issues/9965/entity/Book.ts
test/github-issues/9965/entity/User.ts
test/github-issues/9965/issue-9965.ts
test/github-issues/9965/subscriber/BorrrowedSubscriber.ts

Set entityId on InsertEvent as identifier.  Fixes #9965.
Allows subscribers to have information about join records when they're inserted.

feat: Pass identifier into InsertEvent

---

src/driver/postgres/PostgresQueryRunner.ts
test/github-issues/10043/entity/Foo.ts
test/github-issues/10043/issue-10043.ts
test/github-issues/10043/migration/1699343893360-create-table.ts

Fixes: #10043
Added determining precision and scale values of numeric array columns when loading tables by Postgres query runner.
The reason of these changes is described within the issue that is linked above.
The reason of the issue was found by debugging the source code.

fix: resolve issue of generating migration for numeric array columns repeatedly

---

src/driver/oracle/OracleQueryRunner.ts
test/github-issues/10493/entity/User.ts
test/github-issues/10493/issue-10493.ts

ignore auto-generated virtual columns and attempt to map them into their respective reference columns
Closes: #10493
Ignore automatically generated virtual columns on the Oracle driver, in order to avoid errors when generating migrations and / or synchronizing the entities / schemas to the database.
This is accomplished by ignoring any virtual columns that have the "USER_GENERATED" column set to "NO".
Also, since this mainly happens when a TIMESTAMP WITH TIME ZONE column is indexed, generating a virtual TIMESTAMP column, it is also necessary to infer that this virtual column actually refers to the original one, during indices discovery. This way, TypeORM won't attempt to recreate it.
A test case has been added to reproduce and fix the aforementioned issue.
- Ran tests with only the …

fix: migrations on indexed TIMESTAMP WITH TIME ZONE Oracle columns

---

docs/entities.md
docs/zh_CN/entities.md

https://orkhan.gitbook.io/typeorm/docs/entities#spatial-columns
```ts
.orderBy({
"ST_Distance(geom, ST_SetSRID(ST_GeomFromGeoJSON(:origin), ST_SRID(geom)))":
{
order: "ASC",
},
})
```
When I run the above code, I get the following error:
```
QueryFailedError: syntax error at or near "undefined"
at PostgresQueryRunner.query (<project path>/src/driver/postgres/PostgresQueryRunner.ts:299:19)
at processTicksAndRejections (node:internal/process/task_queues:95:5)
at SelectQueryBuilder.loadRawResults (<project path>/src/query-builder/SelectQueryBuilder.ts:3789:25)
at SelectQueryBuilder.executeEntitiesAndRawResults (<project path>/src/query-builder/SelectQueryBuilder.ts:3541:26)
at SelectQueryBuilder.getRawAndEntities (<project path>/src/query-builder/SelectQueryBuilder.ts:1670:29)
at …
```

docs: fix orderBy of Spatial columns

---

docs/indices.md
src/decorator/Index.ts
src/decorator/options/IndexOptions.ts
src/driver/postgres/PostgresQueryRunner.ts
src/metadata-args/IndexMetadataArgs.ts
src/metadata/IndexMetadata.ts
src/schema-builder/options/TableIndexOptions.ts
src/schema-builder/table/TableIndex.ts

Add the possibility to generate indexes concurrently for postgres, following a similar pattern to background indexes already implemented for mongo.
- [ x ] Code is up-to-date with the `master` branch
- [ x ] `npm run format` to apply prettier formatting
- [ x ] `npm run test` passes with this change
- [ x ] Documentation has been updated to reflect this change
- [ x ] The new commits follow conventions explained in [CONTRIBUTING.md](https://github.com/typeorm/typeorm/blob/master/CONTRIBUTING.md)
Happy to add a test, but struggled to navigate the best place to add it!
Note I have tested manually.

Add possibility to generate concurrent indexes for pg

---

docs/entity-manager-api.md

There was a mistake I found while surfing through the documentation. The manager.findAndCountBy functions name misspelled and wrote as findAndCountBy, the mistake was fixed.

typo fixed in the manager.findAndCountBy documentation

---

src/persistence/SubjectExecutor.ts

Modified the **updateSpecialColumnsInInsertedAndUpdatedEntities** function in _src/persistence/SubjectExecutor.ts_ to check if the column is deletedAt while creating an entity and ignore it since it attaches the deletedAt column to the main entity when reload is false.

fix deletedAt column leaking as side effect of object update while creating a row

---

src/query-builder/SelectQueryBuilder.ts

Allow to serialize `bigint` parameter as string when building query id for caching purposes.
A fix for this issue:
https://github.com/typeorm/typeorm/issues/10336
```ts
@Entity('my_entity')
class MyEntity {
@Column('bigint')
public id: bigint;
}
...
entityRepository.findOne({ id: 1n })
```
- [A] Code is up-to-date with the `master` branch
- [A] `npm run format` to apply prettier formatting
- [N] `npm run test` passes with this change
- [A] This pull request links relevant issues as `Fixes #10336`
- [N] There are new or updated unit tests validating the change
- [N] Documentation has been updated to reflect this change
- [N] The new commits follow conventions explained in [CONTRIBUTING.md](https://github.com/typeorm/typeorm/blob/master/CONTRIBUTING.md)

fix: serialize bigint when building a query id #10336

---

src/driver/Driver.ts
src/driver/cockroachdb/CockroachDriver.ts
src/driver/oracle/OracleDriver.ts
src/driver/postgres/PostgresDriver.ts
src/driver/spanner/SpannerDriver.ts
src/driver/sqlserver/SqlServerDriver.ts
test/functional/repository/aggregate-methods/repository-aggregate-methods.ts
test/github-issues/7308/entity/weather.ts
test/github-issues/7308/issue-7308.ts

Hi, this PR is fixing #7308
The query builder will now use the same identifiers for the same parameters, I've made the change to Postgres, SQL Server, Oracle, Spanner, and CockroachDB. 
Closes #7308

Fix #7308:  QueryBuilder makes different parameter identifiers for same parameter

---

docs/multiple-data-sources.md
src/data-source/DataSource.ts
src/driver/cockroachdb/CockroachConnectionOptions.ts
src/driver/mysql/MysqlConnectionOptions.ts
src/driver/postgres/PostgresConnectionCredentialsOptions.ts
src/driver/postgres/PostgresConnectionOptions.ts
src/driver/postgres/PostgresDriver.ts
src/driver/spanner/SpannerConnectionOptions.ts
src/driver/sqlserver/SqlServerConnectionOptions.ts
src/query-builder/SelectQueryBuilder.ts
test/functional/connection/replication.ts

For many applications that want to use read slaves, data consistency isn't super important, and so all reads can be sent by default to a read slave. For some applications though, it's only select queries that can be sent to read slaves as end-users of the application expect data consistency almost everywhere. This new setting lets apps like those change the default such that query builders need to opt *in* to sending to a read slave, instead of opt out.
For existing replication users, the default for queries is unchanged (send to the slave) but this allows folks who care like me to change the default behaviour.

Default replication mode

---

src/driver/sqlite-abstract/AbstractSqliteQueryRunner.ts
src/util/OrmUtils.ts
test/unit/orm-utils.ts

Fixed a bug that was causing new migration to be generated even when no changes to the Model was made. Generating migration for a table with a column type `simple-enum` (in sqlite) would produce SQL CREATE TABLE query with a column like this:
```sql
"col_name" varchar CHECK("col_name" IN ('FOO', 'BAR', 'BAZ')) NOT NULL,
```
When a TableColumn for this column is created, that CHECK statements was being incorrectly parsed (`','` was used as separator, but the statement included whitespaces not present in that separator.) Given the above column in db, instead of parsing it into `["FOO", "BAR", "BAZ"]` it was parsed into `["FOO', 'BAR', 'BAZ"]`, because of this syncing would attempt to update that table and create a new migration every single time.
To fix the issue I've changed how that CHECK …

fix: sqlite simple-enum column parsing

---

src/query-builder/InsertQueryBuilder.ts
test/github-issues/9015/entity/Post.ts
test/github-issues/9015/issue-9015.ts

Closes: #9015
This PR makes sure to update any `UpdateDateColumn` during an update that is triggered via `upsert`.
There are a couple of corner cases that I made sure to take care of:
- The fix doesn't break `skipUpdateIfNoValuesChanged` like a previous fix attempt
- When a  `UpdateDateColumn` is explicitly updated then I'm excluding it from the new logic

fix: update UpdateDateColumn on upsert

---

CHANGELOG.md
package-lock.json
package.json
src/driver/oracle/OracleConnectionOptions.ts
src/driver/oracle/OracleDriver.ts

Increase node-oracledb version to 6. Since node-oracledb version 6+ the used driver is a Thin Client, no additional Oracle Instant Client Lib is necessary.
Addtional funtionality  for opt in to the  Thick Client was added.
Closes: #10277, #10094
- [N/A] There are new or updated unit tests validating the change 

Use node-oracledb 6

---

src/entity-manager/MongoEntityManager.ts

Removes an underlying `clone` which causes a hanging cursor leading to a memory leak on simple functions like `find`.
fixes: #10315

Resolves a Memory Leak from an Unclosed Cloned Cursor

---

src/error/EntityNotFoundError.ts
test/functional/repository/find-methods/repostiory-find-methods.ts

These properties can be used by consumers to aid in rendering human-readable error messages.
Fixes #10179

feat: Exposed entity and criteria properties on EntityNotFoundError

---

src/driver/sap/SapQueryRunner.ts

Use async API exposed by driver
Usage of synchronous `prepare` was a critical bottleneck. In case of having appropriate parameters we can skip `prepare` execution altogether and call `exec` directly which can improve performance even further.

perf: improve SapQueryRunner performance

---

src/data-source/DataSource.ts
src/platform/BrowserPlatformTools.template
src/query-builder/QueryBuilder.ts
src/query-builder/index.ts

Removes all dynamic require calls from QueryBuilder class in order to make the library compatible with Vite.

fix: Remove dynamic require calls | Vite compatibility fix

---

src/query-builder/InsertQueryBuilder.ts
test/github-issues/10563/issue-10563.ts

Closes: #10587
fix issues on upsert, detected with errors on test repository > basic methods - upsert - should first create then update an entity inside repository-basic-methods.ts

fix: resolve issues on upsert

---

docs/data-source-options.md
src/driver/sqlserver/SqlServerConnectionOptions.ts

[data-source-options.md](https://github.com/typeorm/typeorm/blob/master/docs/data-source-options.md) defines connection settings for a variety of data sources, among which is MSSQL.
Specifically the Data Source Option 'pool.testOnBorrow' indicates that factory.validate or factory.validateAsync is required if this field is used.
The Option pool.testOnBorrow appears to be ignored if populated. The documentation states that factory.validate or factory.validateAsync is required.
The options factory.validate or factory.validateAsync are not defined anywhere in [data-source-options.md](https://github.com/typeorm/typeorm/blob/master/docs/data-source-options.md) or imported in code.
Through research, testing, and discussion on discord, it appears this option is deprecated as testing is …

Fix issue 10176 mssql datasource testonborrow not working

---

docs/data-source-options.md
src/data-source/BaseDataSourceOptions.ts
src/query-builder/QueryBuilder.ts
test/functional/query-builder/isolated-where/entity/User.ts
test/functional/query-builder/isolated-where/query-builder-isolated-where.ts
test/utils/test-utils.ts

- Add `isolateWhereStatements` to the `BaseDataSourceOptions` object and automatically isolate where statements in the query builder if it is true
Fixes #7261 
Fixes #1568 
Fixes #6170

feat: add isolated where statements

---

src/persistence/EntityPersistExecutor.ts
test/functional/entity-subscriber/transaction-flow/entity-subscriber-transaction-flow.ts

Keep `this.options.data` on the `queryRunner` for `subscribers` after the `transaction`
Fixes #10150

fix: correctly keep query.data from ormOption for commit / rollback subscribers

---

package.json
src/driver/cordova/CordovaDriver.ts

I have added the fail callback while opening the database. Doing so, If there is an issue with the database, the error is thrown and the logic can be treated.

Added fail callback

---

docs/mongodb.md

Updating docs for Mongo.  When starting off with a fresh tutorial using the documentation and Mongodb as the database provider.  The `id` property in the entity is always null.  When I change the `id` property to `_id`  I get the desired result.

docs: updates id to _id on Mongodb readme

---

docs/delete-query-builder.md

The getRepository method is missing from the example. 
Delete the "users" written in the createQueryBuilder method because it is not used in the where method.

docs: update Soft-Delete, Restore-Soft-Delete examples

---

src/query-builder/SelectQueryBuilder.ts

I was working with the `.limit()` and `.skip()` methods and noticed some minor typos. Fixed them to improve the development experience.

docs: fix typos in SelectQueryBuilder.ts

---

src/query-builder/InsertQueryBuilder.ts

Fixes issue #10543
Fixes issue #10065 
Multiple insert into SAP hana results in a syntax error,
The commit implemented the changes suggested by [this](https://github.com/typeorm/typeorm/issues/7899#issuecomment-1371451487) comment.

fix: multiple insert in SAP Hana

---

src/metadata/EntityMetadata.ts
src/query-builder/ReturningResultsEntityUpdator.ts
test/github-issues/8450/entity/UserEntity.ts
test/github-issues/8450/issue-8450.ts

Fixes https://github.com/typeorm/typeorm/issues/8450
This is a rework of PR https://github.com/typeorm/typeorm/pull/8472, which was closed due to being outdated.
The values of a column generated by an expression should be returned when inserting or updating a record.

fix: include asExpression columns in returning clause

---

src/query-builder/QueryBuilder.ts
src/query-builder/SelectQueryBuilder.ts
test/integration/sample2-one-to-one.ts
test/integration/sample3-many-to-one.ts

Fixes #4738
Fixes #9298 
Fixes #10481  
Modified to use `queryRunner` when `QueryStrategyRelationIdLoader.loadManyToManyRelationIdsAndGroup` is called.
In the current implementation, if a query is executed with `relationLoadStrategy: query`, a new QueryRunner is created when resolving a relation.
The creation of a new QueryRunner means that a connection is allocated from the connection pool, but when the connection pool is exhausted, it waits for the connection to be released.
Because connections to query the parent table are released after the relation is resolved, if such queries are executed in parallel up to the maximum number of connection pools, a deadlock will occur because no connections will be allocated for queries on the `relation`.
So, this probrem can be solved by using the …

fix: Hangup when load relations with relationLoadStrategy: query

---

.github/workflows/test.yml
.github/workflows/test/better-sqlite3.ormconfig.json
.github/workflows/test/sqlite.ormconfig.json
.github/workflows/test/sqljs.ormconfig.json
src/driver/better-sqlite3/BetterSqlite3QueryRunner.ts

This change splits SQLite (sqljs, sqlite and better-sqlite3) tests into their own workflows.
This change also adds `broadcastBeforeQueryEvent` and `broadcastAfterQueryEvent` that were missing in the better-sqlite3 driver implementation (caught after tests split). Fixes #3302 for better-sqlite3.

Split SQLite tests and fix better-sqlite3

---

CONTRIBUTING.md

Remove the suggestion of github issues as a place for questions about using TypeORM. Instead point people towards stack overflow and discord for questions about using TypeORM, to match our suggestions in the [support doc](https://github.com/typeorm/typeorm/blob/master/docs/support.md) and the [new issue form](https://github.com/typeorm/typeorm/issues/new/choose).

remove github issues as a suggested place for questions

---

src/cache/QueryResultCache.ts

Correct the description for getFromCache, matching the descriptions found on the [redis](https://github.com/typeorm/typeorm/blob/master/src/cache/RedisQueryResultCache.ts#L125-L130) and [db](https://github.com/typeorm/typeorm/blob/master/src/cache/DbQueryResultCache.ts#L133-L138) cache implementations.
Also correct grammar on the description of the synchronize method.

docs: update QueryResultCache method descriptions

---

docs/query-runner.md

Connection is deprecated, so updated naming 'connection' to 'dataSource'.

docs: update deprecated naming

---

docs/faq.md

Removed dead link `how-to-use-typeorm-with-a-dependency-injection-tool` from faq.md.
Content was removed in 3b8a031

docs: removed dead link about using typeorm with DI from faq.md

---

docs/find-options.md

changed 'findby' to 'findBy' in dataSource.getRepository
changed 'titles' to 'title' in native SQL example

docs: update find-options.md

---

docs/data-source-api.md
docs/entity-manager-api.md
docs/repository-api.md
src/data-source/DataSource.ts
src/entity-manager/EntityManager.ts
src/repository/Repository.ts

Added documentation for parameters in query methods of Repository, DataSource, and EntityManager. Without this addition, it is not even obvious this option exists, which could pose a serious risk of SQL injection attacks if used incorrectly. 
This has already caused some confusion, see #881

docs: documentation for parameters in Repository, DataSource, EntityManager query methods

---

docs/repository-api.md

The docs have been updated to contain the important information that using `repository.softDelete()` allows the user to specify multiple id's, or other row attributes as it happens with the `delete()` operation, for instance.

docs: Include info about using soft delete in Repository API

---

docs/find-options.md

Corrects imports in `docs/find-options.md`

docs: fix imports in 'Or' find operator example

---

src/driver/postgres/PostgresQueryRunner.ts
src/persistence/SubjectExecutor.ts
src/persistence/SubjectTopologicalSorter.ts
src/query-builder/InsertQueryBuilder.ts
src/query-builder/QueryBuilder.ts
src/schema-builder/RdbmsSchemaBuilder.ts
test/integration/sample2-one-to-one.ts
test/integration/sample3-many-to-one.ts

Fixing the small typo in SubjectTopoligicalSorter and renaming it as SubjectTopologicalSorter.
The actual change is in 2 files
- `src/persistence/SubjectExecutor.ts`
- `src/persistence/SubjectTopologicalSorter.ts`
Other changes are the result of `npm run format`

Rename SubjectTopoligicalSorter as SubjectTopologicalSorter

---

package-lock.json
package.json
src/commands/QueryCommand.ts
src/commands/SchemaLogCommand.ts
src/platform/BrowserPlatformTools.template
src/platform/PlatformTools.ts

Replace `cli-highlight@2.1.11` which is using an older version of `highlight.js` with `sql-highlight@6.0.0`.
- `sql-highlight` has no dependencies and only 15Kb (see https://npmgraph.js.org/?q=sql-highlight@6.0.0)
- `cli-highlight` has 28 (sub-)dependencies which total 3MB (see https://npmgraph.js.org/?q=cli-highlight@2.1.11). It uses `highlight.js` to parse SQL and convert to HTML, then it uses `parse5` to parse the HTML and convert to ANSI colored text.
`cli-highlight` was also used to highlight JSON, but that can be done by the built-in `console.dir`, again much simpler.

refactor: use sql-highlight instead of cli-highlight

---

README.md

Uses the GitHub Actions pipeline badge instead of CircleCI.

chore: replace CircleCI badge with GitHub Actions badge

---

docs/migrations.md

Running migrations using current documentation ends with error:
`Error: Given data source file must contain export of a DataSource instance`
- `npm run test` passes with this change N/A
- This pull request links relevant issues as `Fixes #0000` N/A
- There are new or updated unit tests validating the change N/A
- Documentation has been updated to reflect this change N/A
- The new commits follow conventions explained in [CONTRIBUTING.md](https://github.com/typeorm/typeorm/blob/master/CONTRIBUTING.md) N/A

docs: fix missing DataSource in migrations config

---

docs/custom-repository.md
docs/view-entities.md

"It's" is a contraction for "it is". "its" is the possessive form of "it".

docs: correct "it's" -> "its"

---

.github/workflows/test/oracle.docker-compose
docker-compose.yml
package-lock.json
src/commands/InitCommand.ts

Fixes #11319
when creating a new project with `npx typeorm init ... --docker` as instructed in the [docs](https://github.com/typeorm/typeorm?tab=readme-ov-file#quick-start) it will create a `docker-compose.yml` file with `version: '3'`, which when running 
```shell
docker compose up -d
```
will emit the following warning: 
```shell
WARN[0000] /<redacted path>/docker-compose.yml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion 
```
This change will remove these lines from the template and will not emit this warning.

chore: don't use version in docker-compose files

---

src/driver/sap/SapDriver.ts

Passes the schema configured in TypeORM DataSource options to the client library, similar to other drivers.
Fixes #10622 properly.
Allows us to find a solution for #10099 as well.

fix(sap): pass the configured schema to the db client

---

src/driver/sap/SapDriver.ts
test/functional/database-schema/column-types/sap/column-types-sap.ts

Columns defined as `simple-array` or `simple-json` should now be stored as `NCLOB` instead of `TEXT` (which used to be an alias of `NCLOB`). The `TEXT` data type has been removed from newer SAP HANA versions.
Fixes #6985.

fix(sap): incorrect handling of simple array/json data type

---

extra/typeorm-model-shim.js

Adding the missing VirtualColumn decorator to the model-shim.
I also checked if another decorator was missing but this is the only one

Add VirtualColumn to model shim

---

docs/migrations.md
src/commands/MigrationCreateCommand.ts
src/commands/MigrationGenerateCommand.ts
test/functional/commands/templates/generate/cockroachdb.ts
test/functional/commands/templates/generate/mssql.ts
test/functional/commands/templates/generate/mysql.ts
test/functional/commands/templates/generate/oracle.ts
test/functional/commands/templates/generate/postgres.ts
test/functional/commands/templates/generate/sqlite.ts
test/functional/commands/templates/result-templates-create.ts

Removed generated unused TypeScript imports in generated migration.
Fixes #9149

fix: remove unnecessary import from JS migration

---

test/utils/test-setup.ts

Fixes: #11246
Updates the `test-setup.ts` to set `process.env.TZ = 'UTC'`. Tests that parse/format dates rely on the runtime timezone, and if assertions are hard coded then it can be easy for the formatted results to be off by an hour(s) or day(s). To mitigate, we set an environment variable to instruct node and other code what time zone to operate under.

chore(test): set timezone to UTC

---

src/query-builder/SelectQueryBuilder.ts
test/github-issues/11285/entity/user.ts
test/github-issues/11285/issue-11285.ts

Fixes input parameter conversion in SelectQueryBuilder when using an MSSQL connection.
Closes #11285
Instead of passing raw input paramters as it is this change uses the available driver.parametrizeValue method to convert parameters into MSSQL format. 
This implementation was referred from existing usage in [UpdateQueryBuilder](https://github.com/typeorm/typeorm/blob/master/src/query-builder/UpdateQueryBuilder.ts#L553) and [InsertQueryBuilder](https://github.com/typeorm/typeorm/blob/master/src/query-builder/InsertQueryBuilder.ts#L887)
Please note that this issue currently only fixes where condition when used under `.find` method. On testing it was not working for `.createQueryBuilder(..).where()` usage. Could use some insights on a proper approach to implement this parameter …

fix: ensure correct MSSQL parameter conversion in where conditions

---

src/find-options/FindOptionsSelect.ts
test/functional/find-options/select/entity/Category.ts
test/functional/find-options/select/entity/Post.ts
test/functional/find-options/select/entity/Tag.ts
test/functional/find-options/select/find-options-select.ts
test/functional/find-options/select/types.ts

FindOptionsSelect type now resolves to properties of object OR boolean when property is an object. Fixes #11358
FindOptionsSelect throws a type error when the type of column is an object.
This can happen when ValueTransformer is used in columns, and the expected type might be an object. Or simply in case of json columns having an interface as type.
For example:
When selecting:
The error:
Types of object should be selectable

fix: FindOptionsSelect to use correct type when property is an object

---

src/index.ts
src/subscriber/event/QueryEvent.ts

This PR exports the types added in PR #10234 - `QueryEvent` (`AfterQueryEvent`, `BeforeQueryEvent`) so that one can build subscribers that use the `before..` and `afterQuery` listeners.
Also the JS doc for the `AfterQueryEvent` is updated to clarify that execution time is in milliseconds to remove guess-work.

fix: export QueryEvent before/after types

---

src/driver/mongodb/MongoConnectionOptions.ts
src/driver/mongodb/MongoDriver.ts

Update (and sort) the MongoDB connection options to match the supported version (v5).
Supersedes #11078
Fixes #10448
Fixes #10642
Fixes #10972
Fixes #11064

fix: mongodb connection options

---

src/migration/MigrationExecutor.ts

In the log of a successful non-fake migration, there is an unnecessary space as shown in the screenshot. This PR remove this.

fix: remove unnecessary spaces in message when running non-fake migrations

---

docs/entities.md
src/driver/sap/SapDriver.ts
src/driver/sap/SapQueryRunner.ts
test/functional/database-schema/column-length/sap/column-length-sap.ts
test/functional/database-schema/column-types/sap/column-types-sap.ts

Convert [SAP HANA data types](https://help.sap.com/docs/SAP_HANA_PLATFORM/4fe29514fd584807ac9f2a04f6754767/20a1569875191014b507cf392724b7eb.html) that have been deprecated/removed in SAP HANA Cloud to [compatible alternatives](https://help.sap.com/docs/hana-cloud-database/sap-hana-cloud-sap-hana-database-sql-reference-guide/data-types).
Based on the database version (cloud version starts at 4.0), the deprecated ASCII types are converted to their Unicode alternatives, similar to how HANA does it (to avoid incorrect migrations), while the removed types are converted to their best alternative to allow backwards-compatibility.
Fixes #11354.

fix(sap): normalize deprecated/removed data types in SAP HANA Cloud

---

src/driver/postgres/PostgresQueryRunner.ts
test/functional/cube/postgres/cube-postgres.ts
test/github-issues/9318/issue-9318.ts

Fixes version detection for PostgreSQL. The version might not always be followed by a space (similar to MySQL/MariaDB).
Example version strings:
```
PostgreSQL 9.3.25 on x86_64-pc-linux-musl, compiled by gcc (Alpine 11.2.1_git20220219) 11.2.1 20220219, 64-bit
PostgreSQL 9.6.24 on x86_64-pc-linux-musl, compiled by gcc (Alpine 11.2.1_git20220219) 11.2.1 20220219, 64-bit
PostgreSQL 10.23 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 8.5.0 20210514 (Red Hat 8.5.0-15), 64-bit
PostgreSQL 14.9 (Debian 14.9-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
PostgreSQL 14.10 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 8.5.0 20210514 (Red Hat 8.5.0-20), 64-bit
PostgreSQL 17.2 (Debian 17.2-1.pgdg120+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian …
```

fix: version detection for Postgres derived variants

---

src/driver/postgres/PostgresQueryRunner.ts

Adds a comment explaining why we use `SELECT version()` for Postgres version detection. (Follow up to https://github.com/typeorm/typeorm/pull/11375).

docs: add comment explaining select version()

---

.github/workflows/publish-package.yml

This PR introduces a new GitHub Actions workflow that will publish a new version of TypeORM to npm.
It is based on the guide from GitHub: https://docs.github.com/en/actions/use-cases-and-examples/publishing-packages/publishing-nodejs-packages#publishing-packages-to-the-npm-registry
I have already generated an automation token and put it in the secrets of this repo as `NPM_TOKEN`, which should allow the publish to take place and not be stopped by 2-factor auth.
The intended workflow would be:
1. The repo is ready for a new release
2. A PR is made which bumps the package version in package.json and updates the changelog by running `npm run changelog`
3. The PR is merged
4. A new Release is created using the GitHub releases feature. In this process a new tag is created, e.g. `v0.3.22`.
5. …

chore: Add package publishing workflow

---

.github/workflows/publish-package.yml

- The publish command was being executed as 2 separate `run` steps, which meant that the `cd build/package` didn't have an effect on the subsequent publish command, so it attempted to publish from the root, which doesn't work because the root package.json is private (plus the contents of the package would have been totally wrong.
I also added the `workflow_dispatch` trigger so I can manually trigger this without needing to create a new release.

chore: Fix publish command

---

package-lock.json
package.json

Fixes the generation of changelog for new releases.
`standard-changelog` automatically generates the changelog in the same format until now, without requiring any configuration.

chore: fix changelog generation

---

docs/listeners-and-subscribers.md
src/subscriber/event/UpdateEvent.ts

Documents the availability of the primary keys in the entity subscribers when update operations are performed. The issue is explained [in this repo](https://github.com/jovanadjuric/typeorm-onupdate-subscriber-issue).
- [Discord discussion](https://discord.com/channels/1124626013360488529/1298590310447841300/1341594239120838757)

docs(entity-subscribers): document primary key availability in UpdateEvent

---

src/driver/types/GeoJsonTypes.ts

This change requires all Point objects to match the defined structure specified in [RFC 7946](https://datatracker.ietf.org/doc/html/rfc7946#section-3.1.1). I also updated all the links to the specification.
> There MUST be two or more elements. [...] Altitude or elevation MAY be included as an optional third element.

refactor: define Position type for GeoJSON objects

---

docs/repository-api.md

This pull request adds on to discussion #5050 regarding https://github.com/typeorm/typeorm/issues/5050#issuecomment-2649287909
I've updated part of official documentation regarding the usage of `chunk` property in advanced options of repository. 
I strongly believe that current examples given in the official documentation gets blindly copied and lead to unexpected bugs due to inappropriate usage 
Instead of 
There should be 
```
// users contains array of User Entities
userRepository.save(users, { chunk: 1000 })
```

docs: update repository additional chunk option usage example

---

.github/workflows/database-tests.yml

Sets up a testing matrix for PostgreSQL so we run tests on 14 and 17.
This is prompted by https://github.com/typeorm/typeorm/pull/10986 which depends on changes introduced in Postgres 15. Instead of testing all active versions of Postgres in CI on every change, this continues to test version 14, and adds 17 which is the latest version. We can always add more versions later if we need to verify functionality on a specific version.
Versions correspond to postgis docker images https://hub.docker.com/r/postgis/postgis

build: setup testing matrix for postgres 14 and 17

---

CHANGELOG.md

This copies the note about a breaking change in 0.3.23 from the GitHub releases to the CHANGELOG so it's easy to discover.
> Can a newly discovered breaking change also be added to CHANGELOG.md in the future? I only checked that, thinking it should contain the same info as GitHub releases, and then proceeded to waste time re-discovering the breaking change, ending up here
> https://github.com/typeorm/typeorm/issues/11455#issuecomment-2873243454

chore: add note about breaking change in 0.3.23

---

.github/workflows/database-tests.yml

Adds the database version for mssql and postgres to Coverall's flag-name.
This fixes an issue where Coveralls was combining the coverage report for mssql and postgres because we have a matrix setup to test multiple versions of the respective databases. The flag name was setup to be unique by node version, but would combine coverage reports for different database versions.

build: include db version in coveralls flag-name

---

CHANGELOG.md

Addendum to #11469
The breaking change note should cover `update({})` as well as `delete({})`

chore: include warning about update({}) in changelog

---

.github/PULL_REQUEST_TEMPLATE.md
CONTRIBUTING.md

Clarifies our documentation for commit messages and pull request descriptions.
The intention is to make it easier for people to contribute and for maintainers to review changes. Since we squash and merge all PRs when merging to master, we can revise some of our existing guidelines.
Specifically this reduces our commit message convention to a recommendation instead of a requirement. Maintainers should still follow the conventions when squashing and merging PRs. It also removes the ask to rebase and force push new changes. It's often easier for us to review changes when revisions are added as new commits.

chore: clarify commit practices

---

src/driver/sqlserver/SqlServerDriver.ts
test/github-issues/11285/issue-11285.ts

Fixes #11474 (bug introduced in #11468)
Arrays of parameters provided as arguments to FindOperators should not be mutated in place when transforming them into typed MssqlParameter objects. A new array should be produced.
- Documentation has been updated to reflect this change (N/A)

fix(mssql): avoid mutating input parameter array values

---

src/driver/capacitor/CapacitorDriver.ts
src/driver/capacitor/CapacitorQueryRunner.ts

This PR addresses a critical issue in Capacitor driver that prevents proper schema synchronization and migration functionality. The root cause lies in how PRAGMA statements are executed in the SQLite driver.
Related issue: #10687
The current implementation incorrectly routes PRAGMA statements through `run` method in `CapacitorQueryRunnner.ts`, which return `0` instead of the expected metadata results. This causes schema synchronization to fail with errors like:
```
const pos = tableColumn.type.indexOf is not a function. (In 'dbColumns.map(async (dbColumn) => {
```
When TypeORM attempts to retrieve table metadata using PRAGMA statements in `AbstractSqliteQueryRunner`, it receives empty results:
```javascript
// This returns empty results (dbColumns=0, dbIndices=0, dbForeignKeys=0)
const …
```

fix: capacitor driver PRAGMA bug

---

src/query-builder/QueryExpressionMap.ts
test/github-issues/10678/entity/user.ts
test/github-issues/10678/issue-10678.ts

Make sure that the `useIndex` property is copied over when calling `QueryExpressionMap#clone`

fix: preserve `useIndex` when cloning a QueryExpressionMap (or a QueryBuilder)

---

docs/docs/query-runner.md
src/driver/mongodb/MongoQueryRunner.ts
src/query-runner/BaseQueryRunner.ts
src/query-runner/QueryRunner.ts
test/functional/driver/sap/connection-pool.ts
test/functional/query-runner/async-dispose.ts
test/functional/query-runner/entity/Company.ts
test/functional/query-runner/entity/Employee.ts

This PR adds support for Explicit Resource Management in `QueryRunner`. See more:
- [await using - JavaScript | MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/await_using)
- [TypeScript 5.2 Release Notes](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-5-2.html): [`using` Declarations and Explicit Resource Management](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-5-2.html#using-declarations-and-explicit-resource-management)
The `QueryRunner` will be released automatically at the end of its scope:
```typescript
async function updateSalaries() {
await using queryRunner = dataSource.createQueryRunner();
await queryRunner.manager.update(Employee, { level: "junior" }, { bonus: 0.2 });
await …
```

feat: support explicit resource management in QueryRunner
