typeorm/typeorm

- src/driver/postgres/PostgresDriver.ts
https://github.com/typeorm/typeorm/issues/82
> Fixed: duplicate JSON.parse

- src/driver/mysql/MysqlDriver.ts
- src/driver/oracle/OracleDriver.ts
- src/driver/postgres/PostgresDriver.ts
- src/driver/sqlite/SqliteDriver.ts
- src/driver/sqlserver/SqlServerDriver.ts
> resolving problem when hydrating entity with date

- src/query-builder/QueryBuilder.ts
- test/github-issues/131/entity/Employee.ts
- test/github-issues/131/entity/Person.ts
- test/github-issues/131/issue-131.ts
> Fixed: error with single table inheritance query without additional conditions

- src/index.ts
> Export schema-builder classes to be used in migrations

- src/driver/sqlite/SqliteQueryRunner.ts
Added missing apostrophe for hasTable sql statement
> Fixed hasTable SQL statement for SqliteQueryRunner

- src/driver/postgres/PostgresDriver.ts
- src/driver/postgres/PostgresQueryRunner.ts
- src/metadata/types/ColumnTypes.ts
- test/functional/json/entity/Record.ts
- test/functional/json/json.ts
- test/functional/json/jsonb.ts
#41 
Please give me some pointers on how you would like me to write the tests for this. I just found out about typeorm today and am not sure about your test structure/requirements.
> Added support for Postgres jsonb type

- .idea/vcs.xml
- src/util/DataTransformationUtils.ts
- test/github-issues/134/entity/Post.ts
- test/github-issues/134/issue-134.ts
TIME was converted to 'HH-mm' instead of 'HH:mm', that was causing an error in the SQL query.
> TIME is converted to 'HH-mm' instead of 'HH:mm'

- ormconfig.json.dist
- src/driver/DriverOptions.ts
- src/driver/postgres/PostgresDriver.ts
- src/driver/postgres/PostgresQueryRunner.ts
- test/functional/connection/connection.ts
add `schemaName` property, default value is `public`
Issue #152
> Can change postgres default schema name

- src/query-builder/QueryBuilder.ts
- test/github-issues/215/entity/Abbreviation.ts
- test/github-issues/215/entity/Author.ts
- test/github-issues/215/entity/Post.ts
- test/github-issues/215/issue-215.ts
> encode dot in regex

- src/driver/postgres/PostgresDriver.ts
- test/functional/json/jsonb.ts
In the past pr #83 , I modified the wrong line.
> I made a mistake

- src/driver/sqlserver/SqlServerDriver.ts
Fix for #229 
Add condition to set useUTC default option if it doesn't exist
> Add condition to set useUTC default option #229

- src/driver/postgres/PostgresQueryRunner.ts
- src/metadata/types/ColumnTypes.ts
- test/functional/uuid/entity/Record.ts
- test/functional/uuid/jsonb.ts
Support for UUID columns in PostgreSQL (see #271)
> add support for UUID column type in PostgreSQL (#271)

- src/entity-manager/EntityManager.ts
- src/repository/Repository.ts
- test/functional/repository/find-methods/repostiory-find-methods.ts
> Adding count method

- README.md
Adds some minor grammar tweaks to the README for readability and clarity.
> README grammar tweaks

- src/query-builder/QueryBuilder.ts
Fixed getCount with Oracle case sensitivity for aliases
> fixed getCount for oracle alias case sensitivy

- src/find-options/FindOneOptions.ts
- src/find-options/JoinOptions.ts
> Fixed missing import/export in FindOneOptions, JoinOptions

- src/query-builder/QueryBuilder.ts
- test/github-issues/521/entity/Car.ts
- test/github-issues/521/issue-521.ts
> fix #521 related to typo in QB

- src/driver/sqlite/SqliteQueryRunner.ts
- test/github-issues/513/entity/Post.ts
- test/github-issues/513/issue-513.ts
> Issue #513 : fixed time and datetime column types for SQLite driver

- src/metadata/IndexMetadata.ts
- test/github-issues/587/entity/Post.ts
- test/github-issues/587/issue-587.ts
This PR fixes issue #587 
This probably isn't the most elegant solution to this problem that one can come up with. This is the safest modification I could do with my lacking knowledge about the codebase.
> fix ordering of columns in IndexMetadata

- src/query-builder/DeleteQueryBuilder.ts
- src/query-builder/InsertQueryBuilder.ts
- src/query-builder/QueryExpressionMap.ts
- src/query-builder/UpdateQueryBuilder.ts
- test/github-issues/660/entity/User.ts
- test/github-issues/660/issue-660.ts
> #660 Specifying a RETURNING or OUTPUT clause with QueryBuilder

- src/metadata/IndexMetadata.ts
- test/github-issues/587/entity/Tag.ts
Clean PR regarding issue #587 (previous PR #611 was cluttered with merged changes) with fix for relation fields.
> fix column ordering in composite index with relation fields

- src/entity-manager/MongoEntityManager.ts
- test/functional/mongodb/basic/repository-actions/entity/Post.ts
- test/functional/mongodb/basic/repository-actions/mongodb-repository-actions.ts
Hi all,
this pull request fixes sorting in mongodb entity manager, as I had a "bad sorting specification" Error with the previous code.
I added the tests in mongodb-repository-actions, @pleerock please tell me if it's the right place, and if the tests are sufficient.
Thks!
> mongodb: fix sorting

- src/query-builder/relation-count/RelationCountLoader.ts
This pr fix this issue: #772 
I am not familiar with SQL and I do not know whether this change will break something. But this change work for me which solve above issue.
> fix unknown column error when using relationCount

- src/query-builder/SelectQueryBuilder.ts
> Fix error sql generation in executeCountQuery

- src/find-options/FindOneOptions.ts
- src/find-options/FindOptionsUtils.ts
- src/query-builder/SelectQuery.ts
- src/query-builder/SelectQueryBuilder.ts
- src/query-builder/transformer/RawSqlResultsToEntityTransformer.ts
- test/functional/repository/find-options/entity/Photo.ts
- test/functional/repository/find-options/repository-find-options.ts
Hey @pleerock, so I tried to implement #718. It works up to the point where the [raw result is transformed into an entity](https://github.com/typeorm/typeorm/blob/master/src/query-builder/SelectQueryBuilder.ts#L1557). Since the result does not have all the relevant columns, it is not converted into an entity. I'm not sure exactly how to handle that. Thoughts?
Fixes #718
> Select only specific columns

- src/driver/postgres/PostgresQueryRunner.ts
- test/functional/database-schema/unique-constraints/entity/Person.ts
- test/functional/database-schema/unique-constraints/unique-constraints.ts
Fix unique constraint names in Postgres and add a test
> Fix for issue #770

- src/commands/MigrationCreateCommand.ts
Refs #860 
I missed one more occurrence of deprecated imports. 🙈 
Sorry about that!
> Remove deprecated imports from MigrationCreateCommand

- src/driver/postgres/PostgresQueryRunner.ts
- src/schema-builder/RdbmsSchemaBuilder.ts
- test/github-issues/197/entities/person.ts
- test/github-issues/197/issue-197.ts
This is a fix for issues #197 and #790, now column removal and indices works well.
Please pull
> Issue #197 and #790

- src/index.ts
We need this so that we can create entity schema's easier
> Export Entity Schema (Issue #880)

- docs/entities.md
- src/decorator/options/ColumnCommonOptions.ts
- src/decorator/options/ColumnOptions.ts
- src/decorator/options/ValueTransformer.ts
- src/driver/mongodb/MongoDriver.ts
- src/driver/mysql/MysqlDriver.ts
- src/driver/oracle/OracleDriver.ts
- src/driver/postgres/PostgresDriver.ts
- src/driver/sqlite-abstract/AbstractSqliteDriver.ts
- src/driver/sqlserver/SqlServerDriver.ts
- src/metadata/ColumnMetadata.ts
- test/functional/columns/value-transformer/entity/Post.ts
- test/functional/columns/value-transformer/value-transformer.ts
This closes #289. Let me know if there's anything that needs to be changed. 😄
> Add support for value transformers

- src/driver/postgres/PostgresQueryRunner.ts
I wasn't sure how to test this, happy to add some if you've got an example or idea of how to add them. I worked off of the implementation in the MySqlQueryRunner for most of this but didn't see any coverage added when that functionality was added.
Relates to #403.
> add initial support for postgres migration generation

- src/entity-schema/EntitySchema.ts
Small trivial pull request to split EntitySchema into more interfaces (EntitySchemaTable, EntitySchemaColumn, EntitySchemaIndex, EntitySchemaRelation) so that a large entity can be created easier using typed objects
> Entity schema split

- src/index.ts
Export Brackets and WhereExpression
> Query builder exports

- src/driver/sqlite-abstract/AbstractSqliteQueryRunner.ts
- src/schema-builder/schema/TableSchema.ts
- test/functional/database-schema/column-length/sqlite/column-length-sqlite..ts
- test/functional/database-schema/column-length/sqlite/entity/Post.ts
Two fixes are needed for this.
1. We support length for sqilte properly
2. We calculate the generation strategy for primary keys since this caused dropping and recreating them always
Add test
> Fix for issue #919

- src/driver/sqlite-abstract/AbstractSqliteQueryRunner.ts
- test/github-issues/945/entity/TestEntity.ts
- test/github-issues/945/issue-945.ts
> Issue 945: Sqlite with multiple primary keys

- src/schema-builder/schema/Table.ts
- test/github-issues/952/issue-952.ts
@iz-iznogood is this what you had in mind? I'm not sure, that's the most beautiful way of doing it.
fixes #952
> SchemaBuilder: Table.addPrimaryKeys and Table.removePrimaryKeys (issue 952)

- src/driver/mysql/MysqlDriver.ts
- test/github-issues/953/entity/user.ts
- test/github-issues/953/issue-953.ts
> fix: typeorm/typeorm#953

- README.md
- docs/roadmap.md
- docs/supported-platforms.md
This PR adds references to the ionic example
> Docs: Ionic example

- docs/active-record-data-mapper.md
- docs/caching.md
- docs/connection-api.md
- docs/connection-options.md
Thank you for your hard work putting together the new docs. Here are some improvements for the first four doc pages. I don't know if you like "Learn more about x", but to me, it sounds better the original wording.
Also added cordova connection options to the docs.
Related to #977
> [Docs] spelling and general improvements

- docs/connection.md
- docs/custom-repository.md
- docs/decorator-reference.md
- docs/delete-query-builder.md
The next four pages. I have a couple of questions here. Please see below.
Related to #977
> [docs] spelling and general improvements (part 2)

- docs/decorator-reference.md
- docs/eager-and-lazy-relations.md
- docs/embedded-entities.md
- docs/entities.md
- docs/entity-inheritance.md
- docs/entity-manager-api.md
- docs/example-with-express.md
- docs/faq.md
- docs/find-options.md
Part 3 of I don't know how many...
The content of [entity-inheritance.md](https://github.com/typeorm/typeorm/tree/master/docs/entity-inheritance.md) is also in [entities.md#entity-inheritance](https://github.com/typeorm/typeorm/blob/master/docs/entities.md#entity-inheritance). Do you want to have two files or one? I would remove one of the two.
Related to #977
> [docs] spelling and general improvements (part 3)

- docs/active-record-data-mapper.md
- docs/connection-options.md
- docs/decorator-reference.md
- docs/indices.md
- docs/insert-query-builder.md
- docs/listeners-and-subscribers.md
- docs/logging.md
- docs/many-to-many-relations.md
- docs/many-to-one-one-to-many-relations.md
- docs/migrations.md
- docs/mongodb.md
- docs/multiple-connections.md
- docs/naming-strategy.md
- docs/one-to-one-relations.md
- docs/relational-query-builder.md
Part 4 of hopefully 5
Related to #977
> [docs] spelling and general improvements (part 4)

- README.md
#540 Converting database to typeorm entities (Reverse engineering)
> #540 added typeorm-model-generator to extensions section in README

- src/driver/mysql/MysqlQueryRunner.ts
Hi, I was trying to get replication working in mysql and saw every request was going to slave. I believe this will fix that issue.
> expression was missing mode

- README.md
Just a simple link fix-up in the main readme.
> docs: fix select-query-builder.md link

- src/find-options/FindOneOptions.ts
- src/find-options/FindOptionsUtils.ts
- test/functional/repository/find-options/repository-find-options.ts
[#1057](https://github.com/typeorm/typeorm/issues/1057)
> Caching from repository

- CHANGELOG.md
- docs/caching.md
- docs/find-options.md
Docs for PR [#1072](https://github.com/typeorm/typeorm/pull/1072)
> Repository caching docs

- CHANGELOG.md
> updated changelog for #1075

- src/commands/InitCommand.ts
Fixed MissingDriver error for sqlite
> Added sqlite type in ormTemplate

- CHANGELOG.md
:feelsbadman: (imagine this emoji)
> fix changelog typo error

- src/query-builder/SelectQueryBuilder.ts
- test/other-issues/take-multiple-pk/entity/Role.ts
- test/other-issues/take-multiple-pk/entity/User.ts
- test/other-issues/take-multiple-pk/take-multiple-pk.ts
Both conditions and parameters were invalid. Try running my tests against the old code. These changes fix the problem - though I'm not sure if they match the original intent.
> fixed bad query when using take on entity with multiple pk

- docs/caching.md
> Fix a typo in caching.md

- src/driver/oracle/OracleDriver.ts
> pool.connect => pool.getConnection

- test/functional/sqljs/auto-save.ts
> driver(sqljs): added missing promises in test

- test/github-issues/1099/entity/Animal.ts
- test/github-issues/1099/issue-1099.ts
sql generation error with skip condition
> issue #1099

- test/github-issues/1055/entity/Child.ts
- test/github-issues/1055/entity/Parent.ts
- test/github-issues/1055/issue-1055.ts
In the tests, I denote the errors I am getting.
> Added tests for GitHub issue #1055

- package-lock.json
- test/github-issues/1034/entity/Circle.ts
- test/github-issues/1034/entity/User.ts
- test/github-issues/1034/issue-1034.ts
Failing test when setting users in promises, related to issue #1034
> Failing test for issue #1034

- test/github-issues/1034/issue-1034.ts
test/github-issues/1034/issue-1034.ts was using a removed method
> Fixed broken test - test/github-issues/1034/issue-1034.ts

- CHANGELOG.md
- src/util/StringUtils.ts
Fix Issue #281 by updating regex
Test is here: https://regex101.com/r/QeSm2I/1
> Fix Issue 281

- CHANGELOG.md
This updates the changelog to refrect the resent releases
> updated changelog (0.1.2 - 0.1.6)

- CHANGELOG.md
- docs/supported-platforms.md
- package.json
This will finally support node projects that use webpack. I also put together the needed changed to make it work in Ionic over at the [example](https://github.com/typeorm/ionic-example#typeorm--018).
fixes #1009
> Webpack: Remove automatic selection of browser version

- CHANGELOG.md
- docs/find-options.md
- docs/supported-platforms.md
@pleerock, do you think this would be enough?
related to #1280
> Improves docs for webpack changes and new find option

- src/entity-manager/MongoEntityManager.ts
- src/find-options/FindOneOptions.ts
- src/find-options/FindOptionsUtils.ts
- test/github-issues/1147/entity/Post.ts
- test/github-issues/1147/issue-1147.ts
This issue was closed, but this fix was never merged to master. 
Also would be nice to get merged back to `next` soon too please
> Issues #1147

- src/connection/Connection.ts
Minor typo: entityManger -> entityManager
> Minor Typo Connection.ts

- test/github-issues/1268/default.ts
- test/github-issues/1268/entity/User.ts
still don't how to fix #1268, but this is a test case for it
> test case for issue #1268 (sqlite insert with default columns)

- src/driver/mysql/MysqlDriver.ts
> fix #1373 - check require('mysql') call

- docs/relations.md
> orthography

- src/driver/postgres/PostgresDriver.ts
> Handle create extension exceptions for Postgres driver

- src/entity-manager/EntityManager.ts
- src/find-options/FindOptionsUtils.ts
- test/github-issues/1416/entity/Author.ts
- test/github-issues/1416/entity/Photo.ts
- test/github-issues/1416/entity/PhotoMetadata.ts
- test/github-issues/1416/issue-1416.ts
> Join eager relations of a specified relation

- src/subscriber/Broadcaster.ts
- test/github-issues/1369/entity/AbstractEntity.ts
- test/github-issues/1369/entity/ConcreteEntity.ts
- test/github-issues/1369/issue-1369.ts
- test/github-issues/1369/subscriber/AbstractEntitySubscriber.ts
Added test for #1369
Added check for subclasses in Broadcaster isAllowedSubscriber method
> Added check for subclasses in Broadcaster isAllowedSubscriber method

- test/functional/sqljs/auto-save.ts
This will make skipping the sqljs auto save tests possible.
@pleerock, should these changes also go into master?
> test(sqljs): fixed auto save tests so they can be skipped

- src/error/LimitOnUpdateNotSupportedError.ts
- src/error/LockNotSupportedOnGivenDriverError.ts
- src/query-builder/UpdateQueryBuilder.ts
- test/functional/query-builder/update/query-builder-update.ts
> UpdateQueryBuilder will now support "limit" and "orderBy" functions for MySQL

- test/functional/sqljs/auto-save.ts
This is the same change as #1462 but this time for `master`.
> test(sqljs): changed auto save tests so they can be skipped (master)

- ISSUE_TEMPLATE.md
@pleerock that's the template that I would go with as it includes some guidelines and information that is always nessecary, but not to much.
> Issue template for new issues

- docs/relations.md
https://github.com/typeorm/typeorm/issues/1478
> Corrected documentation on `eager` relation option

- src/entity-schema/EntitySchemaColumn.ts
- src/entity-schema/EntitySchemaTransformer.ts
- test/github-issues/1510/issue-1510.ts
@pleerock 
Fixes:
https://github.com/typeorm/typeorm/issues/1510
> Bugfix/1510: Added support for mode="objectId" using entity schema JSON

- docs/mongodb.md
Line 193 was importing getMongoManager instead of getMongoRepository.
> Fixed typo in mongodb.md

- CHANGELOG.md
- src/driver/mysql/MysqlDriver.ts
- src/driver/oracle/OracleDriver.ts
- src/driver/postgres/PostgresDriver.ts
- src/driver/sqlite-abstract/AbstractSqliteDriver.ts
- src/driver/sqlserver/SqlServerDriver.ts
- test/github-issues/1140/entity/Post.ts
- test/github-issues/1140/issue-1140.ts
This is a pull request that replaces #1524 addressing:
- Correct behaviour for all drivers
- Adding a changelog entry
- Implementing a test
> Prevent transforms breaking on datetime types (closes #1140)

- docs/entities.md
> removing repeat types at postgres and sqlite

- test/github-issues/1551/issue-1551.ts
https://github.com/typeorm/typeorm/issues/1551
> Add 3 more tests to issue 1551

- test/github-issues/1569/entity/Item.ts
- test/github-issues/1569/issue-1569.ts
Failing test case for Issue #1569
> create failing test case for issue #1569

- src/index.ts
For a compatibility with a Repository API, when build an 3rd party tools
> chore(common): export DeepPartial from common

- src/commands/CommandUtils.ts
- src/commands/EntityCreateCommand.ts
> [issue #1624] Check if entity file already exists

- src/driver/DriverUtils.ts
- test/github-issues/1493/issue-1493.ts
In addition to the discussion in #1493, there is a fix for the case where password contains colons
> Issue #1493. Fix connection url parsing

- src/entity-manager/EntityManager.ts
- test/github-issues/1680/entity/User.ts
- test/github-issues/1680/issue-1680.ts
Let me know if any changes are needed :)
> fix for #1680 - Delete & Updates checks for empty criterias

- docs/migrations.md
- src/connection/BaseConnectionOptions.ts
- src/migration/MigrationExecutor.ts
A good to have option to be able to change the migration table name
> Feature to provide custom migration table name

- test/github-issues/1685/entity/month.ts
- test/github-issues/1685/entity/user-month.ts
- test/github-issues/1685/entity/user.ts
- test/github-issues/1685/entity/year.ts
- test/github-issues/1685/issue-1685.ts
github issues > #1685 JoinColumn from JoinColum is not considered when inserting new value
> add unit test for issue 1685

- .travis.yml
- package-lock.json
- package.json
Changed default test script to use mocha directly instead of running CI tests.
Added precommit script to use tsling with fix flag.
> chore(tests): Changed default tests to use mocha directly

- src/driver/Driver.ts
- src/driver/mongodb/MongoDriver.ts
- src/driver/mysql/MysqlDriver.ts
- src/driver/oracle/OracleDriver.ts
- src/driver/postgres/PostgresDriver.ts
- src/driver/sqlite-abstract/AbstractSqliteDriver.ts
- src/driver/sqlserver/SqlServerDriver.ts
- src/query-builder/InsertQueryBuilder.ts
- src/schema-builder/util/TableUtils.ts
Fixes #1677 for next branch
See #1678
> Proper default column for postgres

- src/driver/postgres/PostgresDriver.ts
> Proper default column type for postgres

- docs/connection.md
- docs/multiple-connections.md
- src/index.ts
> Add ability to create connection by name

- src/driver/cordova/CordovaQueryRunner.ts
- src/driver/websql/WebsqlQueryRunner.ts
This is the fix to address my comment in #1157 and fix the inserts for websql and cordova.
> next - cordova and websql inserts

- src/driver/mysql/MysqlDriver.ts
- src/driver/postgres/PostgresDriver.ts
- src/driver/sqlite-abstract/AbstractSqliteDriver.ts
- src/driver/sqlserver/SqlServerDriver.ts
- src/util/DateUtils.ts
- test/github-issues/1716/entity/mariadbEntity.ts
- test/github-issues/1716/entity/mssqlEntity.ts
- test/github-issues/1716/entity/mysqlEntity.ts
- test/github-issues/1716/entity/pgEntity.ts
- test/github-issues/1716/issue-1716.ts
fixes #1716, #1694, #1240, #976, #838 and #1328 
(next branch PR of #1717)
> send timestamp to database without converting it into UTC (next branch)

- README.md
Small grammatical updates within readme.md for the repository to improve readability and understanding.
> Grammatical Clarity Updates for Readme

- package-lock.json
- test/github-issues/1788/entity/Personalization.ts
- test/github-issues/1788/entity/Provider.ts
- test/github-issues/1788/issue-1788.ts
I don't really know where to go to from here :)
> Provide failing test for issue #1788

- test/github-issues/1754/entity/cliente.ts
- test/github-issues/1754/entity/tipo-cliente.ts
- test/github-issues/1754/issue-1754.ts
Here is the failing test for #1754
> Issue 1754 - failing test

- src/driver/sqlite-abstract/AbstractSqliteDriver.ts
> Fix date conversion issue

- test/github-issues/1825/entity/thing.ts
- test/github-issues/1825/issue-1825.ts
> failing test case for issue #1825

- src/driver/mongodb/MongoConnectionOptions.ts
- src/driver/mongodb/MongoDriver.ts
Just added the option to MongoConnectionOptions and the corresponding parameter to MongoClient's connect (from docs: http://mongodb.github.io/node-mongodb-native/3.0/api/MongoClient.html#.connect)
> add authentication mechanism option

- docs/connection-options.md
- src/driver/mongodb/MongoConnectionOptions.ts
Issue #1810. In addition to PR #1850, it fixes description of the new option.
> [Issue #1810] fix option comment & add it to docs

- README.md
> add missing import in README

- src/driver/mysql/MysqlQueryRunner.ts
[@See #1388 ](https://github.com/typeorm/typeorm/issues/1388)
> fix nullable: true in mysql

- src/driver/DriverUtils.ts
- test/github-issues/1909/issue-1909.ts
Issue #1909. The case with no password has been fixed
> Issue #1909: Password-less connection strings broken

- package-lock.json
package-lock.json was not in sync with package.json
> syncing package-lock.json with package.json

- src/metadata-builder/EntityMetadataBuilder.ts
Got the error and noticed the sentence was a bit odd.
> Fixed a typo

- docs/select-query-builder.md
I found there was no example of `Brackets` on docs. So, I added an example!
>  Add a Brackets example on Where section in select-query-build.md

- src/query-builder/InsertQueryBuilder.ts
- test/github-issues/2044/entity/Photo.ts
- test/github-issues/2044/entity/User.ts
- test/github-issues/2044/issue-2044.ts
Related to the issue #2044 and the issue #1542.
All i need is a way to use my custom generated Id but it doesn't work since relationship id will not be saved with custom id.
I dig some and find we get the embedded value twice and the todo in code already said we should consider remove this function. 😄
> Fix the issue that should not get embedded column value twice

- src/driver/postgres/PostgresQueryRunner.ts
> fix @Index wrong migration

- docs/many-to-one-one-to-many-relations.md
While trying out the examples given in 'Many-to-one / one-to-many relations' , getting an error. `error: null value in column "name" violates not-null constraint`. So added a minor change in that example to insert name in User Table.
> Minor changes in Many-to-one / one-to-many relations examples

- docs/entities.md
- also format the entites.md by remove trailing spaces and delete unnecessary newlines. Rendered view still keeps the same.
> add mssql rowversion to entities.md

- src/query-builder/InsertQueryBuilder.ts
- test/github-issues/2199/entity/Bar.ts
- test/github-issues/2199/issue-2199.ts
fix : https://github.com/typeorm/typeorm/issues/2199
> fix: enable explicitly insert primary key value into mysql database . #Issue-2199

- docs/find-options.md
Delete unnecessary double quotes in find-options.md
> Delete unnecessary double quotes

- src/persistence/SubjectDatabaseEntityLoader.ts
- test/github-issues/2251/entity/Bar.ts
- test/github-issues/2251/entity/Foo.ts
- test/github-issues/2251/issue-2251.ts
> Fix saving of duplicate entities

- docs/entity-manager-api.md
- docs/repository-api.md
add the methods increment and decrement to entity-manager-api.md and repository-api.md
> Add missing methods increment and decrement

- docs/indices.md
- docs/sequelize-migration.md
name oredr change nomally , and single quote -> double quote
> name oredr change, and single quote -> double

- src/driver/types/ColumnTypes.ts
```
ERROR: src/driver/types/ColumnTypes.ts[166, 22]: comment must start with a space
```
> Fix tslint issue

- src/repository/BaseEntity.ts
- test/github-issues/2313/entity/Post.ts
- test/github-issues/2313/issue-2313.ts
> Add a static findOneOrFail() method to BaseEntity

- docs/migrations.md
> [doc] import missing declarations

- src/connection/ConnectionManager.ts
This PR adds the ability to get all the connections currently registered with a manager.
Use case: In our application, we dynamically establish 0 or more connections.  This change would allow us to simplify shutdown code to something like:
```typescript
const connections = getAllConnections();
for (const connection of connections) {
if (connection.isConnected) {
await connection.close();
}
}
```
> feature: add ability to get all registered connections from manager

- package-lock.json
- test/github-issues/2201/entity/ver1/context.ts
- test/github-issues/2201/entity/ver1/record.ts
- test/github-issues/2201/entity/ver1/user.ts
- test/github-issues/2201/entity/ver2/context.ts
- test/github-issues/2201/entity/ver2/record.ts
- test/github-issues/2201/entity/ver2/user.ts
- test/github-issues/2201/issue-2201.ts
1. when naming the primary columns in a junction table it creates two columns per one: 'userId' and 'user_id'
2. when updating the main entity ('Record'), the ORM tries to update the junction table as well, twice, and the 2nd time it fails.
there's no reason to do so even once.
> two issues:

- docs/find-options.md
Added additional information in documentation for users utilizing MSSQL database and wanting to use take a certain amount of accounts.
> Add information for MSSQL user for limit use

- docs/connection.md
> Docs fix - Closes unclosd triple backtick code block

- src/util/OrmUtils.ts
- test/functional/columns/value-transformer/entity/PhoneBook.ts
- test/functional/columns/value-transformer/value-transformer.ts
- tsconfig.json
> Can't save a ES6 Map or Set variable as a string or blob type in the Column

- DEVELOPER.md
- src/metadata-builder/JunctionEntityMetadataBuilder.ts
- test/functional/columns/value-transformer/value-transformer.ts
- test/github-issues/2464/entity/Bar.ts
- test/github-issues/2464/entity/Foo.ts
- test/github-issues/2464/issue-2464.ts
- Update ORM config in developer documentation
- Remove `.only` in `value-transformer.ts` test 
- Fix ManyToMany onDelete option
- #2464
> Fix many to many on delete option

- src/commands/InitCommand.ts
Per: https://github.com/typeorm/typeorm/issues/1767
> Fixed the Init template code so that the deprecated RemoveById call is no longer there

- src/index.ts
Updated the index.ts, to expose the ValueTransformer interface
> Exposed the ValueTransformer

- docs/entity-manager-api.md
- docs/repository-api.md
insert() takes a single entity, or array of entities.
> Update docs for insert()

- docs/multiple-connections.md
I guess the term `database` should be `connection` 😄
> fix a doc error

- README.md
- docs/support.md
> Docs: Include link to slack group

- docs/entities.md
A linebreak was making a single bulleted list look like two separate lists.
> docs: Fix separated bulleted list

- README.md
The only change I want to propose is on line 585.
Not sure why the GitHub editor sees changes on line 18-20.
> typo: missing words, formating

- src/driver/sqlserver/SqlServerConnectionOptions.ts
- src/driver/sqlserver/SqlServerDriver.ts
I have add this flag, though I am having problems running tests in my current dev environment and haven't added them, though as I seen other options also doesn't have test.
https://github.com/typeorm/typeorm/issues/2311
> Add flag to disable output for sql server

- src/query-builder/SelectQueryBuilder.ts
- test/github-issues/2588/entity/Post.ts
- test/github-issues/2588/entity/PostReview.ts
- test/github-issues/2588/issue-2588.ts
I've attempted to fix #2588.
My approach is to check for existing joins in the query and to not add a leftJoinAndSelect for any relations that are already specified.
> Github2588 fix

- src/driver/DriverUtils.ts
Fix TYPEORM_URL to actually work (e.g. switch Object.assign( ... ) to…… actually update urlDriverOptions to options)
> Fix TYPEORM_URL to actually work

- src/commands/CacheClearCommand.ts
> Fix cache:clear command for a case when cache is not configured

- src/metadata-args/MetadataArgsStorage.ts
- src/metadata-builder/EntityMetadataBuilder.ts
- test/github-issues/2800/entity/Car.ts
- test/github-issues/2800/entity/Plane.ts
- test/github-issues/2800/entity/Vehicle.ts
- test/github-issues/2800/issue-2800.ts
- Fix the embedded columns overriding in STI implementations
- Fix the embedded columns not being marked as nullable
> Fix overriden embedded in STI

- src/driver/mongodb/MongoConnectionOptions.ts
- src/driver/mongodb/MongoDriver.ts
According to issue #2270, I added missed configuration option to MongoDB driver.
> Add useNewUrlParser to mongodb driver

- src/query-builder/ReturningResultsEntityUpdator.ts
This is a problem related to https://github.com/typeorm/typeorm/issues/2005 and https://github.com/typeorm/typeorm/issues/2006 and fixed for inserts in https://github.com/typeorm/typeorm/commit/6acbf70a98b7ba1035cd40b5cbb9a802c6b04024.
This PR fixes it also for updates.
> Prevent setting to default value the columns that are being updated

- docs/entity-manager-api.md
Fix decrement documentation in entity manager api
> Wrong decrement documentation in manager api

- src/entity-manager/MongoEntityManager.ts
- test/github-issues/1929/entity/Product.ts
- test/github-issues/1929/issue-1929.ts
In the issue 1929, 'select' optionis not effective in mongodb's finds function. So I use mongodb's project function to realize this.
> Add Select Compatibility for Mongo Driver, Fix issue 1929

- src/find-options/FindOptionsUtils.ts
- test/github-issues/1576/issue-1576.ts
- test/github-issues/953/issue-953.ts
Some tests fail to compile with my version of typescript. Small corrections allow to compile.
> For newest typescript to compile

- docs/multiple-connections.md
Shouldn't it be the table `user`?
> [Doc] Typo?

- ISSUE_TEMPLATE.md
The aim of this PR is only to facilitate user's issue reporting
> Fix issue template MD checkboxes

- ISSUE_TEMPLATE.md
> Revert "Fix issue template MD checkboxes"

- src/metadata-builder/RelationJoinColumnBuilder.ts
- src/metadata/RelationMetadata.ts
> Add onUpdate to relation metadata

- docs/connection-options.md
Documentation update which fixes issue: #2628
> [Docs] fix default value of supportBigNumbers and bigNumberStrings

- src/decorator/options/ColumnCommonOptions.ts
About https://github.com/typeorm/typeorm/issues/3049#issuecomment-436327548
> Add comment to ColumnCommonOptions 'default' property

- src/entity-manager/EntityManager.ts
Resolves #3013 
not sure if there is a applicable unit test for this or not
> Fix findOne not setting underlying query to limit 1

- src/query-builder/RelationLoader.ts
- test/github-issues/2965/entity/note.ts
- test/github-issues/2965/entity/person.ts
- test/github-issues/2965/index.ts
Resolves https://github.com/typeorm/typeorm/issues/2965
> Reuse preloaded lazy relations

- src/decorator/options/ColumnEmbeddedOptions.ts
- src/metadata/EmbeddedMetadata.ts
- test/functional/columns/embedded-columns/columns-embedded-columns.ts
- test/functional/columns/embedded-columns/entity/Counters.ts
- test/functional/columns/embedded-columns/entity/Post.ts
- Makes embedded column prefix option behavior match source documentation
- Resolves #3019
- Allows boolean to explicitly disable or enable the prefix
> Fix embedded column prefix option

- docs/using-ormconfig.md
- src/connection/options-reader/ConnectionOptionsEnvReader.ts
Addition of debug to env variables is usefull for myself and maybe others.
> Simple ENV addition

- src/entity-manager/EntityManager.ts
- src/repository/Repository.ts
- test/functional/repository/decrement/entity/PostBigInt.ts
- test/functional/repository/decrement/repository-decrement.ts
- test/functional/repository/increment/entity/PostBigInt.ts
- test/functional/repository/increment/repository-increment.ts
- Fix #2288
- add tests with bigint
> Fix #2288 - Increment/decrement accept string as input value

- CONTRIBUTING.md
- README-zh_CN.md
- README.md
Accordingly with https://github.com/typeorm/typeorm/pull/2863#discussion_r239581433
let's remove links to gitter and use slack as the main resource.
Editor fixed the formatting of md files automatically
> Drop gitter

- docs/faq.md
Related: https://github.com/typeorm/typeorm/issues/3200#issuecomment-444744508
> Adds some information about transpiling migration files with Webpack

- docs/repository-api.md
- src/repository/RemoveOptions.ts
- src/repository/SaveOptions.ts
Fixed inline documentation for Options as well.
Issue: #3241
> Added documentation for repository - SaveOptions and RemoveOptions

- docs/migrations.md
Multiple Issues such as #1675 #371 are opened because of this missing documentation.
> Note that migrations work with `js` files only

- src/metadata-builder/EntityMetadataBuilder.ts
> Removed STI compound index

- src/query-builder/SelectQueryBuilder.ts
SQL Server only supports offset and limit functionality as a part of their ORDER BY syntax. This means if a query doesn't have an order clause we will generate invalid syntax when setting a limit. To avoid this when a limit or offset is requested and no order is given we add an ORDER BY for the first primary key of the table. This shouldn't have any effect on the query performance or the order of the results but the alternative would be a non-functional query so this will always be an improvement anyway.
**Note:** Tests still fail when mssql is enabled for other reasons. This only fixes the issue created in #3014.
> Add dummy order by to make offset/limit work for mssql

- test/functional/embedded/embedded-one-to-one/embedded-one-to-one.ts
- test/github-issues/1581/issue-1581.ts
- test/github-issues/1591/issue-1591.ts
- test/github-issues/1929/issue-1929.ts
- test/github-issues/1972/issue-1972.ts
- test/github-issues/2147/issue-2147.ts
Making test output a little cleaner.
> cleaning up some console logs in tests

- src/driver/mysql/MysqlDriver.ts
- src/driver/postgres/PostgresDriver.ts
- test/github-issues/3112/entity/User.ts
- test/github-issues/3112/issue-3112.ts
`default: null` in column options should set `null` as default value. Previously in some drivers set `"null"`.
> close #3112 - default: null in column options

- src/query-builder/RelationLoader.ts
- test/functional/relations/lazy-relations/basic-lazy-relation/basic-lazy-relations.ts
Seeing these properties when JSON.stringifying and like functions is jarring, and as far as I can tell there's no need for these properties to be enumerable
> Uses defineProperty so that __has_ and __promise_ variables are not enumerable

- src/persistence/tree/NestedSetSubjectExecutor.ts
- test/github-issues/3422/entity/User.ts
- test/github-issues/3422/issue-3422.ts
> Fix table name when using schema and nested-set

- docs/using-ormconfig.md
Hello!
In this PR I've updated the documentation to clarify how Typeorm decides the configuration that will be used.
> (#3420) Add documentation on typeorm config load

- CHANGELOG.md
- CONTRIBUTING.md
- 0.2.12 changelog 
- I think all PR and changes (or most of them) should include changelog record. So I added **Unreleased** section and added note to the contributing guide
> chore(changelog): 0.2.12 changelog + add Unreleased section

- docs/select-query-builder.md
Documentation: actions discussion on: https://github.com/typeorm/typeorm/issues/3428
> Note about reusing parameters in SelectQueryBuilder's docs

- docs/zh_CN/select-query-builder.md
> :memo: update zh_CN doc for #3467

- src/find-options/FindOptionsUtils.ts
Function is Object need excepted
> fix  $raw is Function but value=false

- docs/select-query-builder.md
> Add documentation for array parameter syntax

- src/metadata/IndexMetadata.ts
- test/functional/indices/embeddeds-index-test/embeddeds-unique-index-test.ts
- test/functional/indices/embeddeds-index-test/entity/Customer.ts
- test/functional/indices/embeddeds-index-test/entity/Profile.ts
- test/functional/mongodb/basic/mongo-embeddeds-index/entity/Information.ts
- test/functional/mongodb/basic/mongo-embeddeds-index/entity/Post.ts
- test/functional/mongodb/basic/mongo-embeddeds-index/mongo-embeddeds-index.ts
> Fix embeddeds indices

- src/decorator/Index.ts
- src/decorator/options/IndexOptions.ts
- src/metadata-args/IndexMetadataArgs.ts
- src/metadata/IndexMetadata.ts
- src/schema-builder/MongoSchemaBuilder.ts
- test/functional/mongodb/basic/mongo-index/entity/Post.ts
> Mongo index options

- CHANGELOG.md
- src/driver/mysql/MysqlDriver.ts
- src/driver/oracle/OracleDriver.ts
- src/driver/postgres/PostgresDriver.ts
- src/driver/sqlite-abstract/AbstractSqliteDriver.ts
- src/driver/sqlserver/SqlServerDriver.ts
- test/github-issues/3395/entity/Post.ts
- test/github-issues/3395/issue-3395.ts
Fixes https://github.com/typeorm/typeorm/issues/3395
Also we can close https://github.com/typeorm/typeorm/pull/2777 in favor of this PR.
> fix(3395): handle transformer.from method in case column is NULL

- CHANGELOG.md
- src/persistence/SubjectChangedColumnsComputer.ts
- test/github-issues/3496/entity/Post.ts
- test/github-issues/3496/issue-3496.ts
> Fix jsonb comparison.

- CHANGELOG.md
- docs/caching.md
- src/cache/RedisQueryResultCache.ts
> Enchancement - Add support for ioredis Cluster object 2nd parameter

- docs/zh_CN/connection-api.md
- docs/zh_CN/repository-api.md
#3612 Update links in connection-api docs
#3625 Fix incorrect pagination argument in documentation
> Sync #3612,#3625 to zh_CN docs

- README.md
Property `isPublished` is missing in starting example model.
> Update README: missing property in example model

- src/util/OrmUtils.ts
- test/github-issues/3654/entity/User.ts
- test/github-issues/3654/issue-3654.ts
The buffer compare function shows a quirk bug, see the picture i captured below:
The function instanceof Function check failed and we need to add more checks.
BWT. How many frequency we publish a new version? which including bug fix version. 
I think the predictable frequency is very help for more contributing and more robust for formal application.
> Fix the quirk bug that the buffer compare function is not working.

- src/query-builder/RelationLoader.ts
- test/functional/relations/lazy-relations/basic-lazy-relation/basic-lazy-relations.ts
> Revert "Uses defineProperty so that __has_ and __promise_ variables are not enumerable"

- docs/zh_CN/connection-options.md
> :memo: update docs

- docs/example-with-express.md
Trying to update the documentation to include required components otherwise the user who read the documentation will not be able to execute the code `console.log`
> updated documentation

- src/schema-builder/RdbmsSchemaBuilder.ts
- src/schema-builder/table/TableIndex.ts
- test/github-issues/3158/entity/Session.ts
- test/github-issues/3158/entity/SessionSettings.ts
- test/github-issues/3158/issue-3158.ts
Spatial and fulltext indices were not properly handled in drivers not supporting such features.
Test is disabled on postgres - postgres driver thinks id column has changed(uniqe added), not sure how to fix it there yet.
Closes #3158
> fixes #3158 - index syncing problems

- docs/connection-api.md
- docs/connection-options.md
- docs/example-with-express.md
- docs/faq.md
- docs/migrations.md
- docs/repository-api.md
- docs/select-query-builder.md
- docs/supported-platforms.md
- docs/transactions.md
- docs/tree-entities.md
- docs/using-ormconfig.md
This PR fixes some minor issues in the `EN` docs.
* it corrects some Markdown Anchors to refer to the correct headlines
* it fixes some typos
Feedback is welcome!
> Fix Docs (Typos, Markdown, ...)

- src/driver/mysql/MysqlDriver.ts
related: https://github.com/typeorm/typeorm/issues/3127
> avoid option.acquireTimeout when using mysql2

- docker-compose.yml
- src/driver/cockroachdb/CockroachDriver.ts
- test/functional/database-schema/column-types/cockroachdb/column-types-cockroach.ts
- test/functional/database-schema/rowid-column/rowid-column.ts
- test/functional/decorators/relation-count/relation-count-many-to-many/relation-count-decorator-many-to-many.ts
- test/functional/query-builder/relation-count/relation-count-many-to-many/load-relation-count-and-map-many-to-many.ts
- test/functional/query-runner/rename-column.ts
- test/functional/schema-builder/change-column.ts
- test/functional/schema-builder/drop-column.ts
- test/github-issues/1261/issue-1261.ts
- test/github-issues/197/issue-197.ts
updated CockroachDB driver to latest version
> Crdb master latest

- src/metadata-builder/EntityMetadataBuilder.ts
- src/metadata/EmbeddedMetadata.ts
- src/metadata/EntityMetadata.ts
- src/metadata/IndexMetadata.ts
- src/metadata/UniqueMetadata.ts
- test/github-issues/3142/entity/Contact.ts
- test/github-issues/3142/entity/Person.ts
- test/github-issues/3142/issue-3142.ts
> fixed unique constraints in embeds (#3142)

- CHANGELOG.md
- src/entity-manager/EntityManager.ts
- src/entity-manager/MongoEntityManager.ts
- src/repository/Repository.ts
> Removed unused declarations from insert/update/delete methods

- docs/zh_CN/find-options.md
> [doc][zh_CN] added option in FindOptions

- CHANGELOG.md
- src/query-builder/transformer/DocumentToEntityTransformer.ts
- test/functional/mongodb/basic/embedded-columns/entity/Information.ts
- test/functional/mongodb/basic/embedded-columns/mongodb-embedded-columns.ts
> Fix transform embeddeds (mongodb)

- docs/repository-api.md
- src/entity-manager/EntityManager.ts
> Disabled listeners in `insert`, `update`, `delete` methods

- docs/repository-api.md
- src/entity-manager/EntityManager.ts
> Revert "Disabled listeners in `insert`, `update`, `delete` methods"

- docs/relations.md
Each of the listed relation types has its own doc page, so I made the list items link to those pages.
> [docs] Link relations.md to other relations-related doc pages

- docs/zh_CN/decorator-reference.md
- docs/zh_CN/relations.md
- docs/zh_CN/view-entities.md
view entity docs #3943 
link relations.md to other relations-related doc pages #4002
> [doc][zh_CN] add view entity docs and link relations.md to other relations-related doc pages

- src/metadata/UniqueMetadata.ts
- src/schema-builder/MongoSchemaBuilder.ts
> fix mongodb uniques

- src/schema-builder/MongoSchemaBuilder.ts
- test/functional/mongodb/basic/mongo-index/entity/Post.ts
> Mongo index

- CHANGELOG.md
- src/metadata/EntityMetadata.ts
- test/github-issues/3857/entity/Men.ts
- test/github-issues/3857/entity/Person.ts
- test/github-issues/3857/entity/Women.ts
- test/github-issues/3857/issue-3857.ts
As I mentioned in my [bug repor](https://github.com/typeorm/typeorm/issues/3957)t, table inheritance by STI pattern didn't inherit schema name. So I make this quick fix. It should work as expected.
> Fix issue with schema inheritance in STI pattern

- src/query-builder/InsertQueryBuilder.ts
- test/github-issues/2199/issue-2199.ts
> fix: enable explicitly insert primary key value into sqlite database

- docs/zh_CN/decorator-reference.md
- docs/zh_CN/entities.md
> [doc][zh-CN] deprecate readonly in favor of update+insert

- src/query-builder/RelationIdLoader.ts
- src/query-builder/RelationLoader.ts
- test/github-issues/1576/entity/Category.ts
- test/github-issues/184/issue-184.ts
- test/other-issues/sqlite-relations-too-many-parameters/entity/Category.ts
- test/other-issues/sqlite-relations-too-many-parameters/sqlite-relations-too-many-parameters.ts
Fixing failing tests on next branch.
Remaining 4 tests require old entity factory, so I will fix them after #3962 is merged(or just in that PR).
> fixing tests

- docs/zh_CN/find-options.md
- docs/zh_CN/select-query-builder.md
> [doc][zh-CN]added dirty read(NOLOCK) in SQLServer

- docs/select-query-builder.md
fixed broken doc on select-query-builder.md
> Added code block closing

- docs/migrations.md
- docs/using-cli.md
> Improving cli doc

- CHANGELOG.md
- src/query-builder/QueryExpressionMap.ts
- test/github-issues/4156/entity/Author.ts
- test/github-issues/4156/entity/Post.ts
- test/github-issues/4156/issue-4156.ts
> fixes #4156 - QueryExpressionMap not cloning all values correctly

- CHANGELOG.md
I forgot to update the changelog in #4195 - here is the fix for that.
> fix(changelog): Added missing line for PR #4195

- CHANGELOG.md
- src/query-builder/transformer/RawSqlResultsToEntityTransformer.ts
- test/github-issues/4220/entity/User.ts
- test/github-issues/4220/issue-4220.ts
See the #4220 for details.
I guess this is my third PR which to resolve the Buffer kind of issues. LOL
You may give me the buffer sufferer reward. 😄
> Fix the buffer as primary key merge bug

- src/driver/sqlite/SqliteDriver.ts
If a `key` option is passed to the Sqlite driver, the connection promise does not wait on it and resolves on the first pragma. This PR makes sure that the Promise returned will wait for the key PRAGMA to be run.
Also took some time to simplify the reading of the createDatabaseConnection() function.
> Fix promise waiting for sqlite with `key` option

- package-lock.json
- package.json
Building current version on windows OS is failing 🤒
> build: update sqlite3 package

- docs/supported-platforms.md
- src/driver/sqljs/SqljsDriver.ts
> Revert "fix: improve sql.js v1.0 support in browser environment"

- docs/faq.md
> revert: "docs: fix typographical error in faq"

- extra/typeorm-model-shim.js
This link http://webpack.github.io/docs/configuration.html#resolve no longer exist
> Updated typeorm-model-shim.js comment link

- ormconfig.circleci.json
- ormconfig.json.dist
- ormconfig.travis.json
- src/driver/mongodb/MongoConnectionOptions.ts
- src/driver/mongodb/MongoDriver.ts
> add mongodb `useUnifiedTopology` config parameter

- docs/many-to-many-relations.md
Make the example of the last section `many-to-many relations with custom properties` more clear and general.
> docs: Update many-to-many-relations.md, make it easier to understand

- docs/zh_CN/entities.md
> docs: Update entities.md

- src/decorator/columns/PrimaryColumn.ts
- test/github-issues/4570/issue-4570.ts
> fix: change PrimaryColumn decorator to clone passed options

- package-lock.json
- src/query-builder/InsertQueryBuilder.ts
- test/github-issues/4513/entity/User.ts
- test/github-issues/4513/issue-4513.ts
> feat: add support for ON CONFLICT for cockroach

- src/decorator/entity-view/ViewEntity.ts
- src/decorator/options/ViewEntityOptions.ts
- src/driver/oracle/OracleQueryRunner.ts
- src/metadata-args/TableMetadataArgs.ts
- src/schema-builder/RdbmsSchemaBuilder.ts
- src/schema-builder/options/ViewOptions.ts
- src/schema-builder/view/View.ts
feat: add option to synchronize or not to synchronize ViewEntity
Fixes #4317
Fixes  #3996
Tests must be added probably, but I have some issues with running them in Docker.
> feat: add materialized View support for Postgres

- src/query-builder/RelationRemover.ts
- test/github-issues/2632/entity/Category.ts
- test/github-issues/2632/entity/Post.ts
- test/github-issues/2632/issue-2632.ts
> fix: createQueryBuilder relation remove works only if using ID

- src/metadata/EntityMetadata.ts
> Github #4598 issue fix

- src/platform/PlatformTools.ts
This fixes an issue when the driver couldn't be loaded if the project is minimized with webpack.
> fix: loading of aurora-data-api driver

- src/query-builder/JoinAttribute.ts
> docs: fix typo in JoinAttribute.ts

- sample/sample4-many-to-many/entity/Post.ts
While trying to better understand how TypeORM handles many-to-many relations, I came across this sample code with comments. Some of the comments seemed mistakenly copy/pasted, so I tried to clarify them as best as I could.
Thanks for all of the work on TypeORM!
> doc: clarify comments on many-to-many sample

- src/query-builder/QueryExpressionMap.ts
- test/github-issues/4842/entity/Post.ts
- test/github-issues/4842/issue-4842.ts
> fix #4842: ensure distinct property is respected cloning query builder

- src/connection/Connection.ts
- Fix issue find metadata does not exist with webpack
> Connection Reuse is broken in a Lambda environment:

- src/index.ts
add the export of FindOptionUtils to use it in other project
Closes: #4745
> fix: FindOptionUtils export

- docs/relational-query-builder.md
docs: update the mistaken import in doc.
replace `getRepository` with `getManager`.
> Change getManager to getRepository

- README-zh_CN.md
- README.md
https://github.com/typeorm/typeorm/pull/4928
this should work
> fix README link to docs

- docs/mongodb.md
Show how to use Advanced Options such as “Equal”, “LessThan”, “In”, “Not In”, “Or” in find()
> Add some usages of Advanced Options in find()

- package-lock.json
- package.json
- src/util/StringUtils.ts
Initial discussion @ https://github.com/typeorm/typeorm/issues/5249
> Use sha.js instead of crypto for hash calculation

- docs/repository-api.md
Add missing note about return value if no entity was found
> docs: preload doc in repository

- src/query-builder/InsertQueryBuilder.ts
- test/github-issues/4452/entity/User.ts
- test/github-issues/4452/issue-4452.ts
> Oracle sql expression for date column

- package-lock.json
- src/find-options/FindOptions.ts
- src/query-builder/QueryExpressionMap.ts
- src/query-builder/SelectQueryBuilder.ts
- test/functional/mongodb/basic/embedded-columns/mongodb-embedded-columns.ts
- test/functional/repository/find-options-locking/find-options-locking.ts
- test/github-issues/3118/issue-3118.ts
- test/github-issues/4156/issue-4156.ts
Fixes:
- `package-lock.json` not synchronized with `package.json`
- compiler errors
- find option locking
- cloning query builder
> Next fixes

- src/decorator/Index.ts
- src/decorator/options/IndexOptions.ts
- src/driver/aurora-data-api/AuroraDataApiQueryRunner.ts
- src/driver/mysql/MysqlQueryRunner.ts
- src/entity-schema/EntitySchemaIndexOptions.ts
- src/entity-schema/EntitySchemaTransformer.ts
- src/metadata-args/IndexMetadataArgs.ts
- src/metadata/IndexMetadata.ts
- src/schema-builder/RdbmsSchemaBuilder.ts
- src/schema-builder/options/TableIndexOptions.ts
- src/schema-builder/table/TableIndex.ts
- test/functional/indices/fulltext-index-test/entity/Post.ts
- test/functional/indices/fulltext-index-test/fulltext-index-test.ts
This adds support for parser option for fulltext index.
[MySQL > ngram Full-Text Parser](https://dev.mysql.com/doc/refman/8.0/en/fulltext-search-ngram.html)
[MySQL > Full-Text Parser Plugins](https://dev.mysql.com/doc/refman/8.0/en/plugin-types.html#full-text-plugin-type)
Closes #3777
> feat: add fulltext parser option

- docs/listeners-and-subscribers.md
Updates subscribers page to mention that the connection option should be set
> docs: mention subscribers connection option in listeners

- src/driver/sap/SapConnectionCredentialsOptions.ts
- src/driver/sap/SapDriver.ts
Unfortunately left some obvious copy paste errors in the last fix. #5343
> fix: SAP HANA driver fixes

- src/driver/mysql/MysqlDriver.ts
> Return NULL when normalize default null value

- src/naming-strategy/DefaultNamingStrategy.ts
Function simplified by re-using target column name string.
> refactor: columnName method simplified

- docs/select-query-builder.md
Solves: https://github.com/typeorm/typeorm/issues/1329
> Demostrate an IN Query

- src/driver/sqlite-abstract/AbstractSqliteDriver.ts
- test/github-issues/4147/entity/Post.ts
- test/github-issues/4147/issue-4147.ts
I also stumbled across #4147 today and found that #4379 fixed that bug.
This PR continues that PR by fixing the formatting error and adding a test that reproduces the steps described in #4147 (and indeed fails without the fix).
Fixes #4147 and closes #4379
> fix(sqlite): fixes simple-enum bug

- docs/using-cli.md
adds 's' to scripts section reference
> very small typo fix

- src/util/OrmUtils.ts
Change check in util/OrmUtils to prevent 'Cannot convert object to primitive value' error iss #4750
> Small fix for iss #4750

- DEVELOPER.md
Since I didn't really know how to use it when i started developing, i think this is helpful info for a new developer on this project.
> tips for using the test-fast script

- docs/connection-options.md
> docs: add documentation for specifying SQL Server instance name

- docs/zh_CN/connection.md
> docs: typo fix

- docs/decorator-reference.md
- docs/delete-query-builder.md
- docs/many-to-many-relations.md
- docs/repository-api.md
Added documentation for the soft-delete features.
This is from PR https://github.com/typeorm/typeorm/pull/5034
Just copied this from @iWinston documentation in [Typeorm+](https://github.com/iWinston/typeorm-plus)
Let me know if there is missing or needs more details.
Thank you.
> docs: added soft-delete documentation

- src/entity-manager/LiteralEntityManager.ts
- src/entity-manager/LiteralMongoEntityManager.ts
- src/repository/BaseEntity.ts
- src/repository/LiteralMongoRepository.ts
- src/repository/LiteralRepository.ts
- test/github-issues/2500/entity/Post.mongo.ts
- test/github-issues/2500/entity/Post.sql.ts
- test/github-issues/2500/issue-2500.ts
FIX for #2500 in the next branch. Remade https://github.com/typeorm/typeorm/pull/5859.
> fix: findOne(undefined|null|false) returns undefined

- docs/entities.md
Mostly copied text from the decorator reference: https://github.com/typeorm/typeorm/blob/master/docs/decorator-reference.md#deletedatecolumn
> Add @DeleteDateColumn to special columns docs

- src/connection/ConnectionOptionsReader.ts
> Fix grammar for ormconfig error

- docs/select-query-builder.md
Fixes #5979 if removing the question mark from the link is acceptable.
> docs: Fix select query builder link

- src/driver/sqljs/SqljsQueryRunner.ts
for information check discussion on https://github.com/sql-js/sql.js/pull/375
> Prevent TypeError when calling bind function with sql.js 1.2.X

- docs/decorator-reference.md
> docs: added enumName property

- docs/migrations.md
Add documentantion for this https://github.com/typeorm/typeorm/issues/1333
> Documentation for connection option

- extra/typeorm-class-transformer-shim.js
- extra/typeorm-model-shim.js
> fix: resolve missing decorators on shim

- docs/mongodb.md
Easy peasy examples for querying subdocuments and array of subdocuments
> docs: Add advance subdocument query documentation

- src/index.ts
> fix: exporting missing load event

- docs/supported-platforms.md
> docs: fix grammatical error

- README.md
Hi, just a small change in docs to avoid install @types as PRD dependency
> doc: change @types/node install to install in dev dependencies

- README-zh_CN.md
- README.md
- docs/zh_CN/README.md
- docs/zh_CN/index.md
Updates the badge to point at CircleCI for the passing / failing status
> doc: use CircleCI for CI badge

- docs/support.md
> docs: Update slack invite link for typeorm.io support page

- docs/find-options.md
- docs/zh_CN/find-options.md
- src/find-options/operator/ILike.ts
- test/functional/repository/find-options-operators/repository-find-operators.ts
> Add doc + tests for case insensitive like operator

- test/functional/table-inheritance/single-table/relations/one-to-many-casecade-save/entity/Faculty.ts
- test/functional/table-inheritance/single-table/relations/one-to-many-casecade-save/entity/Professor.ts
- test/functional/table-inheritance/single-table/relations/one-to-many-casecade-save/entity/Researcher.ts
- test/functional/table-inheritance/single-table/relations/one-to-many-casecade-save/entity/Staff.ts
- test/functional/table-inheritance/single-table/relations/one-to-many-casecade-save/one-to-many-cascade-save.ts
Adding a test for [the fix](https://github.com/typeorm/typeorm/pull/6219#issuecomment-687258512) for #2544
> test: Testing that the discriminatorValue gets saved for ChildEntity when saved by cascade

- src/platform/PlatformTools.ts
> bugfix: hdb-pool is not namespaced under @sap

- src/commands/EntityCreateCommand.ts
- src/commands/SubscriberCreateCommand.ts
somehow #6807 passed as a PR but failed when merged in - this fixes the issues
that cropped up after it was merged in
> fix: fixes TS errors in EntityCreateCommand & SubscriberCreateCommand

- src/find-options/FindOperatorType.ts
- src/find-options/operator/ILike.ts
- src/index.ts
- src/query-builder/QueryBuilder.ts
- test/functional/repository/find-options-operators/repository-find-operators.ts
the next branch has support for ilike and this backports
the FindOperator into the main branch
> feat: backport ilike from next

- src/metadata-builder/EntityMetadataValidator.ts
> fix: remove @DiscriminatorValue from error message

- src/query-builder/QueryBuilder.ts
I did some profiling and found that this function was a bottleneck when using a cache. With these changes I was able to get about 5x better performance.
> Improve replacePropertyNames performance

- src/query-builder/QueryBuilder.ts
- test/github-issues/3685/entity/user.ts
- test/github-issues/3685/issue-3685.ts
> fix: Cannot read property 'hasMetadata' of undefined

- test/functional/relations/multiple-primary-keys/multiple-primary-keys-many-to-many/entity/Category.ts
- test/functional/relations/multiple-primary-keys/multiple-primary-keys-many-to-many/entity/Tag.ts
set explicitly lengths of primary key fields
> test: multiple primary keys many-to-many can fail with 'Specified key was too long'

- extra/typeorm-model-shim.js
this updates the shim to include all current decorators
exported from index.ts - adding @Unique and a few others
fixes: #6288
fixes: #5920
> fix: sync the typeorm-model-shim

- test/github-issues/6900/issue-6900.ts
test 6900 only ran correctly in local testing & didn't correctly
handle the different hostnames in CI / CD
> test: fix test 6900 in CI

- docs/entities.md
> docs: fix decorators in example class using adjacency list

- src/commands/InitCommand.ts
As suggested https://github.com/typeorm/typeorm/issues/4347\#issuecomment-676228784
> init / postgres - upgrade to pg ^8.4

- docs/zh_CN/many-to-many-relations.md
- docs/zh_CN/many-to-one-one-to-many-relations.md
- docs/zh_CN/one-to-one-relations.md
> docs: Remove unused variable

- src/index.ts
Export `LoggerOptions`, which allows developers to properly type their own variables (eg. configurations).
> refactor: export LoggerOptions interface

- docs/connection-options.md
> doc: add missing connection options for mongodb

- README.md
Added `typeorm-uml` to the extensions list. This tool allows users to generate ER diagrams based on entities defined in the project. Here is an example:
> Added tyeorm-uml to the extensions list.

- test/github-issues/3158/issue-3158.ts
- test/github-issues/3588/issue-3588.ts
Adds describe to a couple of tests and refactors them to match other tests.
> test: add describe to a couple of tests and refactor them

- test/github-issues/6284/issue-6284.ts
- test/github-issues/863/issue-863.ts
Updates the description for some tests to include "github issues > #issueNum".
> test: update the description for some tests to include "github issues > #issueNum"

- test/github-issues/4415/issue-4415.ts
> test: remove unnecessary await

- test/github-issues/300/issue-300.ts
- test/github-issues/306/issue-306.ts
- test/github-issues/341/issue-341.ts
- test/github-issues/345/issue-345.ts
- test/github-issues/4782/issue-4782.ts
Updates the description for some tests under test/github-issues to include #issueNum
> test: update the description for some tests under test/github-issues to include #issueNum

- package-lock.json
- package.json
Closes: #7259
`cli-highlight` updated to v2.1.10
- N/A There are new or updated unit tests validating the change
- N/A Documentation has been updated to reflect this change
> Update dependency cli-highlight to v2.1.10

- docs/using-ormconfig.md
> docs: add .ts to supported ormconfig formats

- docs/relations.md
updated cascade options in the docs
> docs: update cascade options

- docs/indices.md
I am always helped by this wonderful library.
I thought it would be more appropriate to give an example of a `Geometry` type.
> docs: Describe an example of a Geometry type

- src/query-builder/QueryBuilder.ts
> fix: avoid regex lookbehind for compatibility

- docs/relations.md
- docs/zh_CN/relations.md
As mentioned [here](https://github.com/typeorm/typeorm/pull/7105#issuecomment-758497070), this PR updates the documentation with the `orphaned rows` option added with this PR #7105.
> doc: update relations files with orphaned rows option

- docs/eager-and-lazy-relations.md
> fix: correct typo

- src/util/DateUtils.ts
This updates `DateUtils.mixedDateToDateString` method to not use `any` type as input argument and returning value.  returning `any` type value does not match the comment's description. Also, if `any` type is included in the input argument, type cannot be properly inferred, only any is inferred.
> refactor: update dateUtils method type

- docs/many-to-many-relations.md
Fix typos and improve phrasing in `many-to-many-relations.md` documentation.
> docs: fix typos in many-to-many-relations.md

- src/persistence/SubjectExecutor.ts
- test/github-issues/5520/entity/TestChild.ts
- test/github-issues/5520/entity/TestParent.ts
- test/github-issues/5520/issue-5520.ts
Generated fields got overridden by undefined in the entity returned by save, if there are one to many relations in the entity.
I changed this, so the generated fields get merged and not overriden. 
Fixes #5520
Fixes #2422
Fixes #4090
- [not needed] Documentation has been updated to reflect this change
> fix: save does not return id, save does not return generated

- src/query-builder/SelectQueryBuilder.ts
- test/github-issues/7065/entity/Contact.ts
- test/github-issues/7065/entity/Email.ts
- test/github-issues/7065/entity/Phone.ts
- test/github-issues/7065/entity/User.ts
- test/github-issues/7065/entity/index.ts
- test/github-issues/7065/issue-7065.ts
Add discriminator condition on JOIN statement for child entity of STI.
Fixes #7065 
Fixes #3181
- [not needed] Documentation has been updated to reflect this change
> fix(issue-7065): append condition to STI child entity join

- src/decorator/relations/ManyToOne.ts
Grammar and punctuation fixes in ManyToOne.ts
> update comments for grammar and punctuation in ManyToOne.ts

- docs/query-runner.md
I added basic documentation for the `QueryRunner` interface that was missing for 3 years. I based on the `Connection` interface doc. I didn't document all features, only the basic usage.
> docs: add queryRunner docs

- test/github-issues/6950/entity/post_with_null_1.entity.ts
- test/github-issues/6950/entity/post_with_null_2.entity.ts
- test/github-issues/6950/issue-6950.ts
This commit adds tests to demonstrate the bug found in #6950
This has been a bug impacting our team for months now.  While I am not able at this time to fix the bug, I thought I would at least contribute a few tests.
I hope that these tests will make it easier for developers to work on the fix when the time comes.  I have made them `skip` for now, but should be un-skipped when #6950 is fixed
> test: add test for #6950

- src/query-builder/SelectQueryBuilder.ts
Adds support of PostGIS `maxdecimaldigits` option. The value comes from the existing `precision` option. Currently, it isn't possible, so the precision is always 9, therefore small, detailed elements either overlap or cannot be found using ST_Intersects, ST_Overlaps, etc. By default, PostGIS rounds all decimal places beyond `maxdecimaldigits`, which causes precision issues/ruins searching. This PR makes `precision` not only affect `double` but `geometry` types as well.
Fixes #7165
> Support maxdecimaldigits option by geometry type

- docs/active-record-data-mapper.md
Really small typo fix to fix documentation grammar.
> fix small typo

- docs/using-cli.md
Add missing colon in JSON property at `package.json` `"script"` example
> Fix small typo on package.json script example

- package-lock.json
- package.json
- sample/sample11-all-types-entity/app.ts
- sample/sample2-one-to-one/entity/Post.ts
- sample/sample3-many-to-one/entity/Post.ts
- src/driver/postgres/PostgresDriver.ts
- src/entity-manager/MongoEntityManager.ts
- src/query-runner/BaseQueryRunner.ts
- test/integration/sample2-one-to-one.ts
- test/integration/sample3-many-to-one.ts
updated to the latest typescript version
> chore: typescript version upgrade

- DEVELOPER.md
- README.md
This PR improves the formatting of the code examples in the README.md and DEVLOPER.md files. The changes are self-explanatory.
> refactor: improve README.md and DEVLOPER.md code examples formatting

- test/github-issues/3246/entity/Broker.ts
- test/github-issues/3246/entity/Order.ts
- test/github-issues/3246/entity/OrderCustomer.ts
- test/github-issues/3246/issue-3246.ts
- test/github-issues/3246/repository/BrokerRepository.ts
- test/github-issues/3246/repository/OrderRepository.ts
Submitting test case for https://github.com/typeorm/typeorm/issues/3246
> Add reproduction for issue 3246

- src/commands/InitCommand.ts
Closes: #3582
Added options for installing package either using npm or yarn by providing `--pm` or `--manager` option
> init cli: add option for installing package

- docs/entities.md
Fixes small grammar issue.
Add an `s` to fix a small grammer issue
> docs: fix typo in entities.md

- src/driver/mongodb/typings.ts
see https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/mongodb/index.d.ts#L2821
> fix: mongodb typings for Cursor

- docs/migrations.md
Adding --transpile-only to the typeorm commands speeds up the process significantly, which is very useful for frequent development migrations or deployment speeds.
> doc: Speed up TS migration command

- docs/entities.md
Added minor documentation for #4824
> doc: Added enumName column option in docs

- src/schema-builder/RdbmsSchemaBuilder.ts
- test/github-issues/7586/entity/Test.ts
- test/github-issues/7586/entity/ViewA.ts
- test/github-issues/7586/entity/ViewB.ts
- test/github-issues/7586/entity/ViewC.ts
- test/github-issues/7586/issue-7586.ts
> Fixes #7586

- src/commands/MigrationRunCommand.ts
> fix: use migrationsTransactionMode while running migration from cli

- docs/multiple-connections.md
Fix code example for executing a Raw Query on a Slave Query Runner.
> docs: Documentation only changes

- CONTRIBUTING.md
The link to the graph of contributors is correct in the README on https://github.com/typeorm/typeorm but is not when viewing https://github.com/typeorm/typeorm/blob/master/CONTRIBUTING.md ; this has been fixed.
> doc: fix link to contributors

- src/util/ObjectUtils.ts
ObjectUtils.assign() doesn't actually return anything, so I changed the return type to void and updated the JSDoc.
> refactor: Corrected ObjectUtils.assign() return type and JSDoc

- src/connection/ConnectionMetadataBuilder.ts
The returned value from the slice() call is unused, so the whole statement is a no-op and can be removed.  This was identified by sonarlint.
> refactor: Remove NOOP slice() call

- docs/migrations.md
> Add example for yarn v2 with pnp

- docs/relational-query-builder.md
Fix code example for loading relational entities with the relational query builder.
> docs: fix entity used in example

- docs/many-to-one-one-to-many-relations.md
> updated link to cascades page

- src/driver/DriverUtils.ts
> fix: restored `DriverUtils.buildColumnAlias()` for backward compatibility

- test/functional/query-builder/count/query-builder-count.ts
- test/functional/query-builder/relation-id/many-to-many/basic-functionality/basic-functionality.ts
- test/functional/repository/basic-methods/repository-basic-methods.ts
- test/functional/repository/clear/repository-clear.ts
- test/github-issues/1147/issue-1147.ts
- test/github-issues/1545/issue-1545.ts
- test/github-issues/219/issue-219.ts
- test/github-issues/234/issue-234.ts
- test/github-issues/5691/issue-5691.ts
- test/other-issues/take-multiple-pk/take-multiple-pk.ts
`Promise.all` will execute all promises at once.  Because of the
way that the current code is written these mostly execute
serially, but that's just coincidental.  It's possible for them
to execute in different orders if there are any extra async layers
between the test and the query executor, such as through a
refactoring.
single-connection databases can get out of order which breaks
the insert return code.  because these tests are not meant to
detect race conditions behavior, I've refactored them to avoid
this problem by removing `Promise.all` in some cases.
> test: update test to not use `Promise.all` in some cases

- src/driver/mysql/MysqlQueryRunner.ts
- test/github-issues/7698/entity/Test.ts
- test/github-issues/7698/issue-7698.ts
Avoid adding NULL/NOT NULL when creating STORED columns in MariaDB
Closes: #7698
> fix: Do not add NULL/NOT NULL for stored columns

- test/utils/test-utils.ts
adds some extra queries when connecting to cockroach for testing to improve the test speed
> test: cockroachdb performance in tests settings

- docs/tree-entities.md
This edit removes the note which links to the closed/fixed issue https://github.com/typeorm/typeorm/issues/2032,  that is supposed to be fixed in this PR https://github.com/typeorm/typeorm/pull/7156 .
> Doc update: Remove note that is no longer relevant

- docs/many-to-one-one-to-many-relations.md
- docs/one-to-one-relations.md
Fix the  **cascade** broken links in
-  https://typeorm.io/#/one-to-one-relations 
- https://typeorm.io/#/many-to-one-one-to-many-relations 
By just replicating the wokring at https://typeorm.io/#/many-to-many-relations, as it appears in its source: 
https://github.com/typeorm/typeorm/blob/master/docs/many-to-many-relations.md  
or similar to this commit  https://github.com/typeorm/typeorm/commit/c1480994c96976effb9de2da381320a46c666fcf 
- [ x] The new commits follow conventions explained in [CONTRIBUTING.md](https://github.com/typeorm/typeorm/blob/master/CONTRIBUTING.md)
> docs: fix brokens cascade links in one-to-one and many-to-one

- src/driver/cordova/CordovaQueryRunner.ts
- src/schema-builder/RdbmsSchemaBuilder.ts
the cordova driver silently ignores all attempts to begin
or commit transactions.  this leads to data loss and invalid
operations occurring when developers expect transactions to work
and then they are silently ignored
fixes #4075
> fix: prevent transactions in the Cordova driver

- docs/find-options.md
the example had a parameter but wrapped it in quotes for some
reason.  this removes the quotes
fixes #7368
> docs: example used invalid parameter

- src/query-builder/DeleteQueryBuilder.ts
- src/query-builder/QueryBuilder.ts
- src/query-builder/SelectQueryBuilder.ts
- src/query-builder/SoftDeleteQueryBuilder.ts
- src/query-builder/UpdateQueryBuilder.ts
- test/functional/query-builder/select/entity/ExternalPost.ts
- test/functional/query-builder/select/query-builder-select.ts
> refactor: use brackets & object literal to do where-in-ids

- src/driver/oracle/OracleDriver.ts
- src/driver/oracle/OracleQueryRunner.ts
> refactor: pass `outFormat` to oracle as part of execute

- src/driver/mongodb/MongoDriver.ts
support of `writeConcern` in `extras` as `w` and `j` are deprecated.
fixes #7604
> feat: add writeConcern option as a possible `extras` for mongodb

- src/driver/oracle/OracleQueryRunner.ts
this allows commands like the QueryRunner.clear() for oracle to
operate when a schema has been provided
fixes #7779
> fix: use fully qualified and escaped table names for oracle

- src/connection/ConnectionManager.ts
> refactor: use a `Map` for ConnectionManager to improve lookups

- src/query-builder/SelectQueryBuilder.ts
> fix: typing so SelectQueryBuilder.getRawOne may return undefined

- src/query-builder/InsertQueryBuilder.ts
- src/query-builder/UpdateQueryBuilder.ts
- test/github-issues/7100/entity/Post.ts
- test/github-issues/7100/issue-7100.ts
> fix: enable returning additional columns with MSSQL

- src/driver/better-sqlite3/BetterSqlite3QueryRunner.ts
- src/driver/cockroachdb/CockroachQueryRunner.ts
- src/driver/cordova/CordovaQueryRunner.ts
- src/driver/expo/ExpoQueryRunner.ts
- src/driver/mysql/MysqlQueryRunner.ts
- src/driver/nativescript/NativescriptQueryRunner.ts
- src/driver/oracle/OracleQueryRunner.ts
- src/driver/postgres/PostgresQueryRunner.ts
- src/driver/react-native/ReactNativeQueryRunner.ts
- src/driver/sap/SapQueryRunner.ts
- src/driver/sqlite/SqliteQueryRunner.ts
- src/driver/sqljs/SqljsQueryRunner.ts
- src/driver/sqlserver/SqlServerQueryRunner.ts
cut down on going from connection -> driver -> connection.
this just uses the options that are in the driver itself instead.
> refactor: use maxQueryExecutionTime from driver options

- src/driver/mongodb/MongoDriver.ts
> Adding retryWrites support

- src/metadata/EntityMetadata.ts
- src/metadata/types/TableTypes.ts
> docs: fix comment on tabletype to remove invalid types

- src/driver/oracle/OracleDriver.ts
this allows us to more explicitly pass the SID correctly as the SID
fixes #5408
> fix: craft oracle connectString as a descriptor

- gulpfile.ts
- package.json
this removes the unused gulp CI Testing code
> chore: drop gulp test runner code

- src/util/StringUtils.ts
- test/functional/util/StringUtils.ts
handles an edge case for the snake case code to be more comprehensive
this also simplifies the regular expressions
fixes #4387
closes #7870
> fix: handle snake case of ABcD which should become a_bc_d

- src/entity-manager/EntityManager.ts
- src/find-options/FindOptionsUtils.ts
- test/github-issues/5684/entity/Company.ts
- test/github-issues/5684/entity/User.ts
- test/github-issues/5684/issue-5684.ts
> fix: eager relation skips children relations

- src/find-options/FindOptionsUtils.ts
- test/github-issues/7882/entity/Example.ts
- test/github-issues/7882/entity/ExampleText.ts
- test/github-issues/7882/issue-7882.ts
because of how we modify it as part of a recursive function
we were erasing the `relations` array when iterating over them.
this fixes that so we don't mess with the inputs like that
and instead copy it
fixes #7882
> fix: prevent modification of the FindOptions.relations

- src/driver/sap/SapQueryRunner.ts
each statement takes up a pool so if you query frequently you can
exhaust that pool of statement handles.  this drops the statement
after we're done with it so we don't exhaust the pool of statements
fixes #7344
> fix: drop SAP statement after `prepare` per Hana client docs

- src/find-options/FindOptionsUtils.ts
- src/query-builder/SelectQueryBuilder.ts
fix regression introduced by #7888
> fix: regression when making `join` conditions `undefined`-able

- src/cache/DbQueryResultCache.ts
- src/driver/aurora-data-api/AuroraDataApiQueryRunner.ts
- src/driver/cockroachdb/CockroachQueryRunner.ts
- src/driver/mysql/MysqlQueryRunner.ts
- src/driver/oracle/OracleQueryRunner.ts
- src/driver/postgres/PostgresQueryRunner.ts
- src/driver/sap/SapQueryRunner.ts
- src/driver/sqlite-abstract/AbstractSqliteQueryRunner.ts
- src/driver/sqlserver/SqlServerQueryRunner.ts
- src/migration/MigrationExecutor.ts
- src/query-runner/BaseQueryRunner.ts
- src/schema-builder/RdbmsSchemaBuilder.ts
- src/schema-builder/options/TableOptions.ts
- src/schema-builder/table/Table.ts
- test/functional/multi-schema-and-database/multi-schema-and-database-basic-functionality/multi-schema-and-database-basic-functionality.ts
includes a fully qualified path name, as well as the database
and schema on the Table object used by the QueryRunner
part of a fix for #7867 and related issues
> feat: add path, database, and schema to Table

- src/driver/oracle/OracleQueryRunner.ts
allows oracle to use schemas in queries
> fix: properly escape oracle table paths

- src/driver/oracle/OracleQueryRunner.ts
the OracleQueryRunner did not correctly handle `hasDatabase`, `createDatabase(..., ifNotExists: true)`, and also would fail to load tables correctly if the database & schema had been set correctly.
> fix: handle schemas in OracleQueryRunner more correctly

- src/driver/cockroachdb/CockroachQueryRunner.ts
- src/driver/sqlserver/SqlServerQueryRunner.ts
> fix: typo prevented us from pulling the schema correctly in some cases

- src/driver/aurora-data-api/AuroraDataApiQueryRunner.ts
- src/driver/cockroachdb/CockroachQueryRunner.ts
- src/driver/mysql/MysqlQueryRunner.ts
- src/driver/oracle/OracleQueryRunner.ts
- src/driver/postgres/PostgresQueryRunner.ts
- src/driver/sap/SapQueryRunner.ts
- src/driver/sqlite-abstract/AbstractSqliteQueryRunner.ts
- src/driver/sqlserver/SqlServerQueryRunner.ts
> fix: pass table to namingstrategy when we can instead of table name

- src/driver/sqlserver/SqlServerQueryRunner.ts
these changes ensure that the forieng keys and tables we pull from
SQL Server are the correct ones we were looking for even if they have
the same name as objects in other databases
> fix: improve query for MSSQL to fetch foreign keys and tables

- src/driver/aurora-data-api/AuroraDataApiQueryRunner.ts
- src/driver/cockroachdb/CockroachQueryRunner.ts
- src/driver/mongodb/MongoQueryRunner.ts
- src/driver/mysql/MysqlQueryRunner.ts
- src/driver/oracle/OracleQueryRunner.ts
- src/driver/postgres/PostgresQueryRunner.ts
- src/driver/sap/SapQueryRunner.ts
- src/driver/sqlite-abstract/AbstractSqliteQueryRunner.ts
this allows passing `database.schema` in all `createSchema` calls.
> fix: support fully qualified schema in createSchema 

- src/driver/oracle/OracleQueryRunner.ts
> fix: support table names between schemas in oracle

- README.md
Added typeorm-extension to `Readme.md`.
It allows to create or drop of a database with given connection information, provided by an ormconfig file or environment variables.
- [ x] Code is up-to-date with the `master` branch
- [ x] `npm run lint` passes with this change
- [ x] `npm run test` passes with this change
- [ x] There are new or updated unit tests validating the change
- [ x] Documentation has been updated to reflect this change
- [ x] The new commits follow conventions explained in [CONTRIBUTING.md](https://github.com/typeorm/typeorm/blob/master/CONTRIBUTING.md)
> added typeorm-extension to readme

- docs/embedded-entities.md
The documentation on [embedded entities](https://typeorm.io/#/embedded-entities) for some reason names a `type` identifier in the arrow syntax. Linters (and some TypeScript compilers) will show error such as: `'type' is declared but its value is never read.` (ts) or `'type' is defined but never used.` (eslint). Furthermore, `type` is a TypeScript keyword, so best to avoid it as variable name.
Apparently, a variable is not needed per the last comment in #2915 , so simply replacing it with `()`
> Remove unused type variable from examples

- test/github-issues/7851/entity/message.ts
- test/github-issues/7851/entity/user.ts
- test/github-issues/7851/issue-7851.ts
Create failing test for typeorm#7851
> Test: add failing test for typeorm#7851

- test/github-issues/7852/entity/user.ts
- test/github-issues/7852/entity/usersObject.ts
- test/github-issues/7852/issue-7852.ts
Create failing test for typeorm#7852
> Test: add failing test for typeorm#7852

- src/metadata/ColumnMetadata.ts
- src/persistence/Subject.ts
- src/persistence/SubjectChangedColumnsComputer.ts
- src/query-builder/UpdateQueryBuilder.ts
- test/github-issues/4060/entity/Bar.ts
- test/github-issues/4060/entity/Foo.ts
- test/github-issues/4060/issue-4060.ts
- test/github-issues/7851/issue-7851.ts
- test/github-issues/7852/issue-7852.ts
Fixes #4060
Fixes #4235
Fixes #7851
Fixes #7852
Closes #7622
- `N/A` Documentation has been updated to reflect this change
> fix: Buffer in primary columns causes bugs with relations

- docs/relations.md
> build error

- src/driver/aurora-data-api/AuroraDataApiQueryRunner.ts
- src/driver/cockroachdb/CockroachQueryRunner.ts
- src/driver/mysql/MysqlQueryRunner.ts
- src/driver/oracle/OracleQueryRunner.ts
- src/driver/postgres/PostgresQueryRunner.ts
- src/driver/sap/SapQueryRunner.ts
- src/driver/sqlserver/SqlServerQueryRunner.ts
- src/schema-builder/options/ViewOptions.ts
- src/schema-builder/view/View.ts
Adds `database` and `schema` properties to the `View` class.
This allows us to be more explicit in the view paths & use the same code for both `Table` and `View`.
> feat: add property for database and schema in views

- .github/ISSUE_TEMPLATE/bug-report.md
- .github/ISSUE_TEMPLATE/documentation-issue.md
- .github/ISSUE_TEMPLATE/feature-request.md
@imnotjames need your opinion on a proposed changes. I'm not really fan of the proposed emoji-based approach, but want to hear other people opinions about it.
> example of the new bug report template

- test/core/xfail/xfail.ts
- test/github-issues/3105/entity/Child.ts
- test/github-issues/3105/entity/Parent.ts
- test/github-issues/3105/issue-3105.ts
- test/github-issues/3387/issue-3387.ts
- test/utils/xfail.ts
in cases where we have tests that have been created for existing
issues this can be utilized so that we can confirm the tests
continue to fail - and we can also determine if a different
code change has resolved it
closes #3391
closes #3451
closes #4070
> test: Add XFail test helper and some tests that utilize it

- package-lock.json
- package.json
yargs 17 was released with some security fixes so lets pull that on in
fixes #7965
> chore: bump yargs to 17.0.1

- src/driver/cockroachdb/CockroachDriver.ts
- src/driver/oracle/OracleDriver.ts
- src/driver/postgres/PostgresDriver.ts
- src/driver/sap/SapDriver.ts
- src/driver/sqlserver/SqlServerDriver.ts
this updates a few of the drivers to explicitly throw an error if they've not been connected but they attempt to obtain an actual connection
fixes #7208
> fix: throw error when not connected in drivers

- src/find-options/FindConditions.ts
this was added to our typing to work around issue described in
microsoft/TypeScript#21592 - however, as of TS 3.6.3 it has not been
an issue
fixes #7338
> chore: remove workaround for "Excessive Stack Depth" from TS3.2

- docs/find-options.md
Improve find options docs by adding sql examples to basic options section.
Closes #7843
> docs: add sql examples to basic options

- src/connection/ConnectionManager.ts
> Fix retrieving connection from ConnectionManager

- src/driver/oracle/OracleConnectionCredentialsOptions.ts
- src/driver/oracle/OracleDriver.ts
adds an explicit `serviceName` for connecting to oracle
fixes #8006
> feat: add serviceName option for oracle connections

- test/functional/schema-builder/custom-db-and-schema-sync.ts
makes the `custom-db-and-schema-sync` test clearer by splitting the tests into 3
>  test: split custom-db-and-schema-sync tests 

- docs/connection-options.md
> add migration transaction mode to connection options documentation

- test/functional/query-builder/composite-primary/composite-primary.ts
- test/functional/query-builder/composite-primary/entity/Bar.ts
- test/functional/query-builder/composite-primary/entity/Foo.ts
this pulls the tests from a PR that had fixed this issue so we can confirm that
master now handles this case
closes #7815
> test: confirm finding by a relation with a composite key works

- test/functional/query-builder/soft-delete/query-builder-soft-delete.ts
fixes the test for `SoftDelete`s where the `deletedAt` was added to a model but the tests weren't updated to match.
closes #8062
this fixes the broken build
> test: expect new `deletedAt` field in test `Photo` model

- src/driver/DriverFactory.ts
we were missing cockroachdb from this list
> fix: include all drivers in driverfactory error message

- src/driver/mysql/MysqlQueryRunner.ts
- test/github-issues/8011/entity/Example.ts
- test/github-issues/8011/issue-8011.ts
Current implementation uses `"'"` in `.replace` which only replaces first occurrence of `'`.
```typescript
value.replace("'", "''") // "dog's and cat's food" -> "dog''s and cat's food"
```
Changing to `/'/g` will allow for all instances of apostrophes to be replaced.
```typescript
value.replace(/'/g, "''") // "dog's and cat's food" -> "dog''s and cat''s food"
```
Closes: #8011
> fix: correctly handle enum values with multiple apostrophes in MySQL

- src/driver/sap/SapQueryRunner.ts
> fix: SAP HANA inserts used incorrect value for returning query

- README.md
Using the correct documentation guideline for installing mongodb, the current version (4.1.0 as of this writing) is installed. However, mongodb version 3.6.0 is listed as a peer-dependency for typeorm. This change adds `@^3.6.0` to the `npm install` for mongodb.
Installating the current version of mongodb causes the following issues:
- https://github.com/typeorm/typeorm/issues/8071
- https://github.com/typeorm/typeorm/issues/7907
> docs: add correct MongoDB installation version

- src/driver/oracle/OracleQueryRunner.ts
- test/functional/query-runner/stream.ts
> feat: support QueryRunner.stream with Oracle

- src/driver/Driver.ts
- src/driver/aurora-data-api/AuroraDataApiDriver.ts
- src/driver/aurora-data-api/AuroraDataApiQueryRunner.ts
- src/driver/cockroachdb/CockroachDriver.ts
- src/driver/cockroachdb/CockroachQueryRunner.ts
- src/driver/mysql/MysqlDriver.ts
- src/driver/mysql/MysqlQueryRunner.ts
- src/driver/oracle/OracleDriver.ts
- src/driver/oracle/OracleQueryRunner.ts
- src/driver/postgres/PostgresDriver.ts
- src/driver/postgres/PostgresQueryRunner.ts
- src/driver/sap/SapDriver.ts
- src/driver/sqlite-abstract/AbstractSqliteDriver.ts
- src/driver/sqlserver/SqlServerDriver.ts
- src/driver/sqlserver/SqlServerQueryRunner.ts
- test/functional/commands/templates/result-templates-generate.ts
- test/github-issues/4415/results-templates.ts
- test/github-issues/5119/issue-5119.ts
- test/github-issues/6442/issue-6442.ts
> fix: prevent using absolute table path in migrations unless required

- README.md
- docs/support.md
> chore: update slack invite link

- docs/zh_CN/decorator-reference.md
- docs/zh_CN/transactions.md
> docs: fix typo

- src/commands/SchemaLogCommand.ts
- src/commands/SchemaSyncCommand.ts
Fixes typo in logs 
syncronization -> synchronization
> ✏️ Fix typos in word 'syncronization'

- docs/tree-entities.md
Fixed the language for the Working With Entities description.
> docs: fix language

- docs/many-to-many-relations.md
In the doc, on line number 111, question.categories.filter was not returning boolean so added return statement.
> doc: fixed question.categories.filter not returning boolean

- docs/zh_CN/relations-faq.md
Translate 'Avoid foreign key constraint creation' section to Chinese
> docs: update relations-faq.md

- package-lock.json
- src/connection/options-reader/ConnectionOptionsYmlReader.ts
runs an `npm update` to ensure the lockfile is up to date & builds fine.  without this, there had been an issue with `node-gyp` and `sqlite3` in development environments.
> chore: npm update

- package-lock.json
- package.json
- src/cli.ts
`yargonaut` is no longer maintained and is causing some grief with a security issue.  as such, remove it.
fixes #8220
> chore: drop yargonaut as it is no longer maintained

- src/driver/aurora-data-api-pg/AuroraDataApiPostgresQueryRunner.ts
- src/driver/aurora-data-api/AuroraDataApiQueryRunner.ts
- src/driver/cockroachdb/CockroachQueryRunner.ts
- src/driver/expo/ExpoQueryRunner.ts
- src/driver/mysql/MysqlQueryRunner.ts
- src/driver/oracle/OracleQueryRunner.ts
- src/driver/postgres/PostgresQueryRunner.ts
- src/driver/sap/SapQueryRunner.ts
- src/driver/sqlite-abstract/AbstractSqliteQueryRunner.ts
- src/driver/sqlserver/SqlServerQueryRunner.ts
- src/entity-manager/MongoEntityManager.ts
- src/query-builder/DeleteQueryBuilder.ts
- src/query-builder/InsertQueryBuilder.ts
- src/query-builder/SelectQueryBuilder.ts
- src/query-builder/SoftDeleteQueryBuilder.ts
- src/query-builder/UpdateQueryBuilder.ts
- src/subscriber/Broadcaster.ts
- src/subscriber/BroadcasterResult.ts
- test/functional/query-builder/count/query-builder-count.ts
- test/functional/repository/clear/repository-clear.ts
- test/functional/repository/delete-by-id-and-ids/repository-remove-by-id-and-ids.ts
- test/functional/repository/find-methods/repostiory-find-methods.ts
- test/github-issues/3685/issue-3685.ts
- test/github-issues/5691/issue-5691.ts
- test/github-issues/7974/issue-7974.ts
adds a new `broadcast` function on the `broadcaster` which creates
the BroadcastResult and returns a promise which awaits on all of the
events that have been broadcasted
refactors many places to use that instead where it won't affect performance
and gets us closer to a standard event emitter API.
this also makes it simpler to mock out the broadcaster should we need to!
> refactor: abstract away Broadcaster boilerplate

- src/query-runner/BaseQueryRunner.ts
Use deep-compare for the enum to detect column schema changes (as done in other places).
Fixes #8161
> fix: Do not generate migration for unchanged enum column (#8161)

- .gitignore
- DEVELOPER.md
- docker-compose.oracle.yml
- docker-compose.yml
- docker/oracle/Dockerfile
- docker/oracle/config/ormconfig.json
- docker/oracle/docker-entrypoint.d/030-npm-install.sh
- docker/oracle/docker-entrypoint.d/040-instantclient.sh
- docker/oracle/docker-entrypoint.d/050-npm-compile.sh
- docker/oracle/docker-entrypoint.sh
- test/utils/test-utils.ts
An easy way to run unit tests for Oracle XE locally
> build: local development with oracle

- src/driver/mysql/MysqlDriver.ts
- test/functional/uuid/mysql/uuid-mysql.ts
Reverts typeorm/typeorm#7853
Fixes: #8002
> Revert "feat: use char(36) for uuid representation in mysql"

- DEVELOPER.md
Document the `npm run pack` command
> docs: document npm run pack

- src/driver/aurora-data-api/AuroraDataApiQueryRunner.ts
- src/driver/cockroachdb/CockroachQueryRunner.ts
- src/driver/mysql/MysqlQueryRunner.ts
- src/driver/oracle/OracleDriver.ts
- src/driver/oracle/OracleQueryRunner.ts
- src/driver/postgres/PostgresQueryRunner.ts
- src/driver/sap/SapQueryRunner.ts
- src/driver/sqlserver/SqlServerQueryRunner.ts
- test/github-issues/8158/entity/User.ts
- test/github-issues/8158/entity/UserMeta.ts
- test/github-issues/8158/issue-8158.ts
See original issue for detailed description. This PR is based on #8157, but applies fix for all drivers and adds a test showing erroneous behavior.
Fixes #8158
Closes #8157
> fix: incorrect composite `UNIQUE` constraints detection

- docs/connection-api.md
> docs: fix a typo in connection-api.md

- docs/decorator-reference.md
- docs/many-to-many-relations.md
* Fix a typo on `decorator-reference.md`
* Fix double spacing and improve formatting consistency on `many-to-many-relations.md`
> fix: typo on `decorator-reference.md` and `many-to-many-relations.md`

- CONTRIBUTING.md
- docs/active-record-data-mapper.md
- docs/caching.md
- docs/find-options.md
- docs/many-to-many-relations.md
- docs/many-to-one-one-to-many-relations.md
- docs/migrations.md
- docs/multiple-connections.md
- docs/one-to-one-relations.md
- docs/select-query-builder.md
- docs/using-cli.md
- docs/zh_CN/find-options.md
- src/commands/QueryCommand.ts
- src/connection/Connection.ts
- src/entity-manager/EntityManager.ts
- src/query-builder/DeleteQueryBuilder.ts
- src/query-builder/InsertQueryBuilder.ts
- src/query-builder/QueryBuilder.ts
- src/query-builder/RelationQueryBuilder.ts
- src/query-builder/SelectQueryBuilder.ts
- src/query-builder/SoftDeleteQueryBuilder.ts
- src/query-builder/UpdateQueryBuilder.ts
- src/repository/AbstractRepository.ts
- src/repository/BaseEntity.ts
- src/repository/Repository.ts
* Add code syntax highlight on `leftJoinAndSelect` word
* Capitalise SQL word on docs and classes methods docs
> docs: Improve various formatting code syntax and capitalisation

- docs/decorator-reference.md
Fix the header to be consistent with file name and menu item
Decorators reference -> Decorator reference
> fix(docs): Update decorator-reference.md

- docs/zh_CN/connection-api.md
> fix: Connection Options link

- src/migration/MigrationExecutor.ts
> Fixed log message

- src/find-options/operator/Like.ts
> Docs: typo in Example comment sting --> string

- test/functional/repository/find-options/repository-find-options.ts
Without this await, the next test will fail sometimes, because there can be still an active connection.
> test: add missing await

- docs/relations-faq.md
change line 139 in relations-faq from 
`const users = await connection.getRepository(User).find({ relations: ["profile", "photos", "videos"] });`
to
`const users = await connection.getRepository(User).find({ relations: { profile: true, photos: true, videos: true} });`
to reflect version 0.3.0 changes
> docs: change relations option definition

- docs/relations-faq.md
The change is simply made to correct a grammatical **typo** in the second question of the [page](https://typeorm.io/#/relations-faq/how-to-use-relation-id-without-joining-relation) related to **relations-faq.md** 
`Sometimes you want to have in your object id of the related object without loading it.`
changes into this: 
`Sometimes you want to have, in your object, the id of the related object without loading it.`
> docs: update relations-faq.md typo

- src/find-options/operator/Not.ts
> docs: put proper documentation for Not operator

- src/driver/mongodb/MongoConnectionOptions.ts
This fixes the following error:
```
TypeError: The "path" argument must be of type string or an instance of Buffer or URL. Received an instance of Array
at Object.openSync (node:fs:577:10)
at Object.readFileSync (node:fs:453:35)
at .../node_modules/mongodb/lib/operations/connect.js:257:32
at Array.forEach (<anonymous>)
at resolveTLSOptions (.../node_modules/mongodb/lib/operations/connect.js:255:34)
at .../node_modules/mongodb/lib/operations/connect.js:305:5
at .../node_modules/mongodb/lib/core/uri_parser.js:133:9
at parseConnectionString (.../node_modules/mongodb/lib/core/uri_parser.js:744:3)
at QueryReqWrap.callback (.../node_modules/mongodb/lib/core/uri_parser.js:127:7)
at QueryReqWrap.onresolve [as oncomplete] (node:dns:230:10)
```
> Fix MongoConnectionOptions sslCA type mismatch

- src/driver/aurora-data-api/AuroraDataApiQueryRunner.ts
Fixed column `comment` mapping from database to column metadata. 
Fixes #8162
Closes #8165
> fix: [aurora-data-api] proper column `comment` mapping from database to metadata

- package.json
- src/commands/CacheClearCommand.ts
- src/commands/EntityCreateCommand.ts
- src/commands/InitCommand.ts
- src/commands/MigrationCreateCommand.ts
- src/commands/MigrationGenerateCommand.ts
- src/commands/MigrationRevertCommand.ts
- src/commands/MigrationRunCommand.ts
- src/commands/MigrationShowCommand.ts
- src/commands/QueryCommand.ts
- src/commands/SchemaDropCommand.ts
- src/commands/SchemaLogCommand.ts
- src/commands/SchemaSyncCommand.ts
- src/commands/SubscriberCreateCommand.ts
- src/platform/PlatformTools.ts
- Constructed and used PlatformTools method for logging cli Command specific errors. Simplified catch blocks for Command classes by minimizing unnecessary code repetition.
- Removed ```@types/dotenv``` - dotenv type definitions are exported in the package itself.
> style: improve Commands error handling with simplified and reusable PlatformTools method.

- src/repository/TreeRepository.ts
- test/github-issues/8443/closure-table/closure-table.ts
- test/github-issues/8443/closure-table/entity/Category.ts
- test/github-issues/8443/materialized-path/entity/Category.ts
- test/github-issues/8443/materialized-path/materialized-path.ts
- test/github-issues/8443/nested-set/entity/Category.ts
- test/github-issues/8443/nested-set/nested-set.ts
fix QueryFailedError when tree entity with JoinColumn (#8443)
Fixes: #8443
> fix: QueryFailedError when tree entity with JoinColumn (#8443)

- docs/select-query-builder.md
Documentation update on select-query-builder.md -> RelationQueryBuilder section. Just added a example how to use the RelationQueryBuilder.
> docs: update select-query-builder RelationQueryBuilder, added a new example

- src/query-builder/RelationLoader.ts
Updates relative require. I believe this will fix #8665
> Fix Path to FindOptionsUtils

- src/entity-schema/EntitySchemaTransformer.ts
> fix: minor spelling fix

- src/naming-strategy/DefaultNamingStrategy.ts
> fix: DefaultNamingStrategy#getTableName should be protected, not private

- sample/sample5-subscribers/subscriber/EverythingSubscriber.ts
> remove spaces for consistency

- docs/select-query-builder.md
- src/driver/Driver.ts
- src/driver/aurora-mysql/AuroraMysqlDriver.ts
- src/driver/cockroachdb/CockroachDriver.ts
- src/driver/mongodb/MongoDriver.ts
- src/driver/mysql/MysqlDriver.ts
- src/driver/oracle/OracleDriver.ts
- src/driver/postgres/PostgresDriver.ts
- src/driver/sap/SapDriver.ts
- src/driver/sqlite-abstract/AbstractSqliteDriver.ts
- src/driver/sqlserver/SqlServerDriver.ts
- src/driver/types/CteCapabilities.ts
- src/query-builder/DeleteQueryBuilder.ts
- src/query-builder/InsertQueryBuilder.ts
- src/query-builder/QueryBuilder.ts
- src/query-builder/QueryBuilderCte.ts
- src/query-builder/QueryExpressionMap.ts
- src/query-builder/SelectQueryBuilder.ts
- src/query-builder/SoftDeleteQueryBuilder.ts
- src/query-builder/UpdateQueryBuilder.ts
- test/functional/query-builder/cte/entity/foo.ts
- test/functional/query-builder/cte/helpers.ts
- test/functional/query-builder/cte/recursive-cte.ts
- test/functional/query-builder/cte/simple-cte.ts
- test/github-issues/4753/issue-4753.ts
Resolves #1116 #5149 #5484
This pull request adds support for common table expressions in QueryBuilder.
> feat: support for Common Table Expressions

- src/commands/MigrationCreateCommand.ts
Fix regression introduced in `0.3.0`.
Fixes #8794.
> fix: Fix missing timestamp to created migrations filenames

- src/driver/mysql/MysqlDriver.ts
> fix: PoolConnection leaked by MysqlDriver

- README.md
- README_ko.md
* added "erdia" extension to readme
* Update README.md, README_ko.md
> docs: added "erdia" extension to readme

- docs/select-query-builder.md
bad indentation break syntax highlighting.
> docs: fix code indentation

- docs/data-source-options.md
- docs/using-cli.md
Updates to using-cli.md and data-source-options.md
removed cli.migrationsDir
updated related cli docs
> update generate migration docs

- src/commands/MigrationGenerateCommand.ts
Migration output now displays the timestamp part of the migration file name
- [ x] This pull request links relevant issues as `Fixes #0000`
> Fixes (#8903): Migration successfull now displays full name of the migration file 

- docs/repository-api.md
Edited mistypes in the example code in findAndCountBy and findOneBy method.
> docs: edit mistypes in the Repository API document

- docs/migrations.md
> Update migrations.md - fixed bug on migration down

- src/entity-schema/EntitySchemaColumnOptions.ts
- src/entity-schema/EntitySchemaTransformer.ts
> feat: enumName support for EntitySchema

- package.json
> Fix issue-9075

- src/find-options/FindOptionsWhere.ts
Little change, fix typo in FindOptionsWhere.ts. 😁
> Fix typo in FindOptionsWhere.ts

- package-lock.json
- package.json
This PR will upgrade the `ioredis` peer dependency from v4 to v5. 
All breaking changes are listed [here](https://github.com/luin/ioredis/blob/main/CHANGELOG.md#breaking-changes)
> Upgrade ioredis from v4 to v5

- src/commands/InitCommand.ts
- test/github-issues/8975/issue-8975.ts
Closes: #8975
The`package.json` created dynamically through the cli's `init` command used outdated package versions that introduced peer dependencies with the base project.
> fix: resolve cli init peer dependency issues

- src/data-source/DataSource.ts
- src/entity-manager/EntityManager.ts
- src/entity-manager/MongoEntityManager.ts
- src/globals.ts
- src/query-builder/RelationIdLoader.ts
- src/query-builder/SoftDeleteQueryBuilder.ts
- src/query-builder/UpdateQueryBuilder.ts
- src/query-builder/transformer/PlainObjectToNewEntityTransformer.ts
- src/repository/AbstractRepository.ts
- src/repository/TreeRepository.ts
- test/github-issues/1510/issue-1510.ts
- test/github-issues/2871/enumTools.ts
- test/github-issues/8681/issue-8681.ts
- test/other-issues/mssql-add-column-with-default-value/mssql-add-column-with-default-value.ts
TypeScript 4.8 will include stricter assignability rules for unconstrained type parameters. Our [error detection infrastructure](https://github.com/microsoft/TypeScript/issues/49461) caught several build failures in your codebase due to that change.
Nearly throughout the codebase, type parameters named `Entity` were unconstrained. However, they were usually eventually assigned to something constrained to `ObjectLiteral` which is guaranteed to be non-nullable. An unconstrained type parameter `Entity` may be instantiated with `null` or `undefined`, so this was unsafe, and TypeScript 4.8 will fix this bug. I went ahead and updated your codebase as I was investigating the real-world effects of this fix.
> Fix compilation errors in TypeScript 4.8

- docs/data-source-options.md
- docs/zh_CN/connection-options.md
- src/driver/oracle/OracleConnectionOptions.ts
- src/driver/postgres/PostgresConnectionOptions.ts
- src/driver/sqlserver/SqlServerConnectionOptions.ts
> docs: correct useUTC default value

- docs/entity-manager-api.md
Fix wrong method example for `withRepository` in docs.
> docs: fix method example in EntityManager API

- DEVELOPER.md
I change to use `DataSource` instead of `Connection` in test code template.
> docs: update test template in DEVELOPER.md

- DEVELOPER.md
> docs: fix DEVELOPER.md typo

- docs/query-runner.md
> fix: `query-runner.md` typos

- docs/data-source-options.md
- src/driver/sqlserver/SqlServerConnectionOptions.ts
Added a config option for the application name in node-mssql: https://github.com/tediousjs/node-mssql/blob/master/lib/tedious/connection-pool.js#L45
> feat: implement new mssql option appName

- src/driver/sqlite-abstract/AbstractSqliteQueryRunner.ts
adds deferrable options for sqlite foreign keys
relates to https://github.com/typeorm/typeorm/issues/2191 and https://github.com/typeorm/typeorm/pull/3904/commits
> sqlite - deferrable options for foreign keys

- package-lock.json
- package.json
- src/data-source/DataSource.ts
- src/entity-manager/EntityManager.ts
- src/find-options/FindOptionsUtils.ts
- src/query-builder/DeleteQueryBuilder.ts
- src/query-builder/InsertQueryBuilder.ts
- src/query-builder/QueryBuilder.ts
- src/query-builder/QueryPartialEntity.ts
- src/query-builder/RelationQueryBuilder.ts
- src/query-builder/SelectQueryBuilder.ts
- src/repository/BaseEntity.ts
Fixes #9331 - added type constraints on `Entity` to extend `ObjectLiteral`. See issue for more information
> fix: typescript 4.8 type issues #9331

- docs/listeners-and-subscribers.md
> Fix docblock

- docker-compose.yml
- src/commands/InitCommand.ts
> feat: update db image versions in docker compose

- docs/listeners-and-subscribers.md
fix the typo in the AfterRecover example
> docs: fix typo of AfterRecover example

- README_ko.md
Fixed wrong typo!
Fix wrong words to correct words. 
And change korean words to english which can't explain by korean.
> Fix typo in readme_ko.md

- docs/delete-query-builder.md
Improved the docs for delete query builder, it is putting examples about soft delete.
> Improve delete query builder docs

- docs/zh_CN/find-options.md
> docs:fix some small  zh docs mistakes

- docs/tree-entities.md
Few grammar changes for more readability.
> docs: Fix general grammar

- package.json
> feat: allow peerDependency of better-sqlite3 version 8.x.x

- src/persistence/tree/MaterializedPathSubjectExecutor.ts
- src/util/TreeRepositoryUtils.ts
- test/github-issues/9534/entity/Category.ts
- test/github-issues/9534/issue-9534.ts
> fix: the mpath is incorrect when the parent of the tree entity is null

- DEVELOPER.md
- docs/relations-faq.md
- Add in an example for issue https://github.com/typeorm/typeorm/issues/4526
- Fix a few typos too
> docs: add in an example for 4526

- src/query-builder/SelectQueryBuilder.ts
- test/functional/find-options/basic-usage/find-options-order.ts
- test/functional/find-options/basic-usage/find-options-relations.ts
- test/functional/find-options/basic-usage/find-options-select.ts
- test/functional/find-options/basic-usage/find-options-test-utils.ts
- test/functional/find-options/basic-usage/find-options-where.ts
Fixes #9395 , fixes #9411 
Use a left join rather than an inner join for where or + optional relations
Builds upon the excellent foundational work laid by @PedroLimaComputacao and @carantunes
> fix: left instead of inner join for where or + optional relations

- src/migration/MigrationExecutor.ts
Make easier to view logs and search record, especially when the number of migration files is large.
> refactor: add id in migrate:show command logging

- src/data-source/DataSource.ts
> Revert "fix(DataSource): assign isInitialized: true at the end of initialize"

- package-lock.json
- src/commands/InitCommand.ts
The typeorm stopped using getRepository but in the "cli" sample this had not changed. I have mutated and improved the methods of the UserController class
> fix: Updating the code and improving

- src/commands/MigrationGenerateCommand.ts
Exiting successful process with 0 for migration:generate CLI command.
> Exiting successful process with 0

- src/driver/Driver.ts
- src/driver/oracle/OracleDriver.ts
- src/driver/sap/SapDriver.ts
- src/entity-manager/EntityManager.ts
- src/query-builder/QueryBuilder.ts
- src/query-builder/SelectQueryBuilder.ts
- src/repository/Repository.ts
- test/functional/query-builder/exists/entity/Test.ts
- test/functional/query-builder/exists/query-builder-exists.ts
- test/functional/repository/find-methods/repostiory-find-methods.ts
Adding `Exists` method to query builder and EntityManager, to check whether a row exists given the conditions
Closes: #2815
Added a new methods to check if a row exists. 
Also added a method to add `EXISTS` clause to a given query.
> feat: implement exists query method

- src/driver/postgres/PostgresQueryRunner.ts
> fix : primary constraint name undefined erorr for PostgresQueryRunner.ts

- docs/separating-entity-definition.md
> Fix missing )

- docs/logging.md
- docs/relations-faq.md
- docs/select-query-builder.md
I found typos in several files in the docs and have corrected them.
> Fix typo in some docs

- docs/data-source.md
Corrected a typographical error in the first paragraph of the documentation
> docs: correct typo in first paragraph of docs

- src/find-options/mongodb/MongoFindOneOptions.ts
- test/github-issues/9518/entity/Post.ts
- test/github-issues/9518/issue-9518.ts
> fix: allow to pass ObjectLiteral in mongo find where condition

- docs/migrations.md
- Fix typo on document about migration.
> fix: fix some typo on migration document

- .gitignore
`*.iml` files are IntelliJ IDEA module definitions. While there is an entry `.idea` in the `.gitignore`, there is no `*.iml` so far. `.gitignore` should be updated to make a life easier for IDEA users.
> chore: add *.iml to .gitignore

- test/github-issues/2331/entity/Post.ts
- test/github-issues/2331/issue-2331.ts
* closes #2331
I was facing this issue in a private repo which still uses typorm 0.2.x. I figured I'll give it a look and wrote the test but the issue isn't appearing anymore. I ran the same test against pre 0.3.0 and it failed as expected. So I'd consider the mentioned issue to be resolved.
> Add test to prove that issue #2331 is resolved

- test/github-issues/1200/entity/Category.ts
- test/github-issues/1200/entity/Group.ts
- test/github-issues/1200/entity/Post.ts
- test/github-issues/1200/entity/User.ts
- test/github-issues/1200/issue-1200.ts
Closes: #1200
Tests for updating multiple nested embedded entities. This is a corrected version of tests proposed in #1200. Since that PR is closed I decided to create a new PR but keep the old number of a github issue.
> test: update multiple nested embedded entities

- src/query-builder/SelectQueryBuilder.ts
> fix: overriding caching settings when alwaysEnabled is true

- src/migration/MigrationExecutor.ts
Replace 'was' with 'were' in the no migrations found log message to reflect 'migrations' being plural.
> fix: Fix grammar error in no migrations found log

- src/driver/sqlite-abstract/AbstractSqliteDriver.ts
- test/github-issues/9715/entity/ExampleEntity.ts
- test/github-issues/9715/issue-9715.ts
- test/github-issues/9715/migration/1674040078325-init.ts
> fix: resolve issue with "simple-enum" in sqlite

- docs/select-query-builder.md
getCount() is currently only mentioned in the documentation once, and you're never shown how to use it. This patch adds a little documentation for getCount()
> documented getCount()

- docs/relations-faq.md
Proposed a better safe-type workaround for circular dependencies.
Updated the example workaround of circular dependencies. Instead of providing the value of a key of related class, I would propose to use the type we actually imported to make it a bit more type safe :)
- [+] Code is up-to-date with the `master` branch
- [+] `npm run format` to apply prettier formatting
- [+] `npm run test` passes with this change
- [+] Documentation has been updated to reflect this change
- [+] The new commits follow conventions explained in [CONTRIBUTING.md](https://github.com/typeorm/typeorm/blob/master/CONTRIBUTING.md)
> docs: update relations-faq

- src/driver/sqlserver/SqlServerDriver.ts
- src/driver/sqlserver/SqlServerQueryRunner.ts
- src/query-runner/BaseQueryRunner.ts
- test/github-issues/9457/entity/ExampleEntity.ts
- test/github-issues/9457/issue-9457.ts
- test/github-issues/9457/migration/1676011161422-init.ts
fix: resolve issues for mssql migration when simple-enum was changed
- Changes are now detected
- Incorrect update Statement was split into a DROP CONSTRAINT and ADD CONSTRAINT Statement
* fixes #7785
* fixes #9457
- [~] Documentation has been updated to reflect this change
> fix: resolve issues for mssql migration when simple-enum was changed Fixes: #7785 #9457

- docs/migrations.md
Update documentation related to generating migrations.
There is outdated cli command.
> Update migrations docs

- src/find-options/FindOperator.ts
- src/query-builder/SelectQueryBuilder.ts
- test/github-issues/9381/entity/ExampleEntity.ts
- test/github-issues/9381/entity/JsonExampleEntity.ts
- test/github-issues/9381/issue-9381.ts
The column transformer didn't work in combination with FindOperators.
This correction does not perform a transformation on a FindOperator value
Fixes: #9381
[~ ] Documentation has been updated to reflect this change
> fix: transform values for FindOperators #9381

- docs/entity-manager-api.md
typo:
const timber = await manager.findOne(User, { firstName: "Timber" })
→   const timber = await manager.findOneBy(User, { firstName: "Timber" })
> docs: update entity-manager-api.md

- src/query-builder/SelectQueryBuilder.ts
- test/github-issues/9960/entity/ExampleEntity.ts
- test/github-issues/9960/issue-9960.ts
> fix: select + addOrderBy broke in 0.3.14

- src/commands/InitCommand.ts
`$ npx typeorm init --name typeormMigration --database postgres --module esm --express --docker`
I fixed a bug in the code generated by the `--express` option in the above command.
> fix: express option bug in init command

- src/metadata-builder/EntityMetadataBuilder.ts
- src/metadata/EntityMetadata.ts
- src/persistence/EntityPersistExecutor.ts
- src/query-builder/transformer/PlainObjectToNewEntityTransformer.ts
- test/github-issues/2927/issue-2927.ts
- test/github-issues/7558/entity/Animal.ts
- test/github-issues/7558/entity/Cat.ts
- test/github-issues/7558/entity/Content.ts
- test/github-issues/7558/entity/Dog.ts
- test/github-issues/7558/entity/NnaryOperator.ts
- test/github-issues/7558/entity/NumberEntry.ts
- test/github-issues/7558/entity/OperatorTreeEntry.ts
- test/github-issues/7558/entity/Person.ts
- test/github-issues/7558/entity/Photo.ts
- test/github-issues/7558/issue-7758.ts
- test/github-issues/9033/entity/Animal.ts
- test/github-issues/9033/entity/Cat.ts
- test/github-issues/9033/issue-9033.ts
This PR fixes an issue when saving entities from a Single Table Inheritance schema linked to another entity (e.g. one entity, many STI-children). The wrong class was created (wrong discriminator saved to the DB).
Take the example from the issue, then when saving `Animals` (explicitly: `Dogs` and `Cats` inheriting from `Animal`) connected to a `Person`, only `Animals` were created.
Now, the `create` function also checks whether the expected value is an entity of a class of a child entity and creates the correct class.
Fixes #7558
Fixes #9033
> fix: Create correct children during cascade saving entities with STI

- src/driver/mysql/MysqlDriver.ts
- test/github-issues/10040/entity/person.ts
- test/github-issues/10040/entity/todo.ts
- test/github-issues/10040/issue-10040.ts
- Create failing test for #10040 
- Fix #10040
> fix: #10040 TypeORM synchronize database even if it is up to date

- docs/logging.md
Correct a minor error in the document example. Change `implements` to `extends`.
> docs: change `implements` to `extends`

- docs/multiple-data-sources.md
update example to indicate that apart from using setQueryRunner, a query runner can also be passed as an optional argument with createQueryBuilder.
> docs: update usage of query runner with query builder

- docs/data-source-options.md
This commit adds the options serviceName and sid on [data-source-options documentation](https://github.com/typeorm/typeorm/blob/master/docs/data-source-options.md).
Fixes #10181
> Add the some options on Oracle documentation

- src/repository/Repository.ts
I want to use repository.extend method like this.
`const customUserRepository = entityManager.getRepository(User).extend({~~}).extend({~~~~}).extend({~~~~~});
`
So I upgrade the repository.extend method, and now chaining call is possible.
> feat: modify repository.extend method (for chaining call!)

- src/driver/DriverUtils.ts
- src/find-options/FindOptionsUtils.ts
- src/naming-strategy/DefaultNamingStrategy.ts
- src/naming-strategy/NamingStrategyInterface.ts
- test/github-issues/2200/naming/NamingStrategyUnderTest.ts
- test/github-issues/9944/entity/A.ts
- test/github-issues/9944/entity/B.ts
- test/github-issues/9944/entity/C.ts
- test/github-issues/9944/entity/D.ts
- test/github-issues/9944/issue-9944.ts
Fix alias error for nested relations. When loading eager relations from nested
levels only the first level was handled through the alias builder
Closes: #9944
When loading eager relations from nested levels only the first level was handled through the alias builder
resulting in the following error `TypeORMError: "A__b" alias was not found. Maybe you forgot to join it?`.
By appropiately handling deeply nested relations, just as any other relations they are able to be fetched as usual
Fixes #9944
> fix: resolve issue building eager relation alias for nested relations

- docker-compose.yml
The previous version is going out of support. v23.1.9 is the latest release, so we test with that instead.
> test: test with CockroachDB v23.1.9

- src/driver/sap/SapDriver.ts
> fix: circular dependency breaking node.js 20.6

- docs/separating-entity-definition.md
- src/entity-schema/EntitySchemaOptions.ts
- src/entity-schema/EntitySchemaTransformer.ts
- test/github-issues/10494/entity/A.ts
- test/github-issues/10494/entity/B.ts
- test/github-issues/10494/entity/Base.ts
- test/github-issues/10494/entity/C.ts
- test/github-issues/10494/entity/index.ts
- test/github-issues/10494/issues-10494.ts
- test/github-issues/10494/schema/A.ts
- test/github-issues/10494/schema/B.ts
- test/github-issues/10494/schema/Base.ts
- test/github-issues/10494/schema/C.ts
- test/github-issues/10494/schema/index.ts
add discriminator value metadata to EntitySchema
Closes: #10494
Currently, there is no way to customize discriminator values when using Single Table Inheritance with `EntitySchema` (separate entity definition).
This change adds a `discriminatorValue` to `EntitySchemaOptions`, which then gets added as a discriminator value metadata to the `MetadataArgsStorage`, on `EntitySchemaTransformer`. This is similar to what is done by the `@ChildEntity` decorator.
> feat: custom STI discriminator value for EntitySchema

- docs/delete-query-builder.md
For previous examples typescript error occurs in createQueryBuilder that says “Argument of type 'string' is not assignable to parameter of type 'QueryRunner'.ts(2345)”. 
If you check the type of createQueryBuilder, the string cannot come as the first argument.
The types of createQueryBuilder are as follows.
myDataSource.createQueryBuilder<ObjectLiteral>(entityClass: EntityTarget<ObjectLiteral>, alias: string, queryRunner?: QueryRunner | undefined):
> docs: update delete-query-builder.md

- src/driver/sap/SapDriver.ts
- src/driver/sap/SapQueryRunner.ts
- src/platform/PlatformTools.ts
- test/functional/query-runner/stream.ts
Fixes #10510 Add streaming support for SAP HANA
> feat: implement streaming for SAP HANA

- src/driver/sap/SapDriver.ts
- src/driver/sap/SapQueryRunner.ts
- test/functional/columns/comments/columns-comments.ts
- test/functional/commands/migration-create.ts
- test/functional/schema-builder/add-column.ts
- test/functional/schema-builder/change-column.ts
- test/functional/schema-builder/entity/Post.ts
- test/github-issues/8485/issue-8485.ts
Fixes #10501 feature request: implement persisting column comments in SAP HANA. Also fixes #9947.
> feat: implement column comments for SAP HANA

- src/query-builder/SelectQueryBuilder.ts
Fixes https://github.com/typeorm/typeorm/issues/10500
> fix: Caching always enabled not caching queries

- .circleci/config.yml
> build: removed Node.js 14 from CircleCi

- src/entity-manager/MongoEntityManager.ts
Fixed calling new of ObjectId class type which shoudn't be available in runtime?
> fix: undefined is not constructor

- package-lock.json
- package.json
> fix: bump better-sqlite3 version range

- docs/many-to-many-relations.md
The example started with Question and Category example entities, then moved to Post and Category. I just changed Post to Question to keep in line with the example
> docs: update the docs to keep in line with the example

- docs/entity-manager-api.md
- docs/repository-api.md
- src/entity-manager/EntityManager.ts
- src/repository/BaseEntity.ts
- src/repository/Repository.ts
- test/functional/query-builder/exists/query-builder-exists.ts
- test/functional/repository/find-methods/repostiory-find-methods.ts
This PR deprecates `exist` in favor of `exists` and `existsBy`.
> feat: add exists and exists by

- src/driver/oracle/OracleDriver.ts
> feat(oracle): enabled CTE for oracle driver

- src/driver/postgres/PostgresDriver.ts
- src/driver/postgres/PostgresQueryRunner.ts
- test/github-issues/10567/entity/address-history.ts
- test/github-issues/10567/issue-10567.ts
Extend spatial column type with range types for postgres. This fixes a bug when using spatial indices.
Closes: #10567
> fix: extend spatial column types for postgres driver

- src/query-builder/SelectQueryBuilder.ts
- test/github-issues/10431/entity/Category.ts
- test/github-issues/10431/entity/Product.ts
- test/github-issues/10431/entity/index.ts
- test/github-issues/10431/issue-10431.ts
A reproduction and fixes #10431
> fix: empty objects being hydrated when eager loading relations that have a `@VirtualColumn`

- src/driver/cockroachdb/CockroachQueryRunner.ts
CockroachDB driver did not correctly handle error events emitted by a borrowed connection - much like previous issues found and fixed in PostgreSQL driver (which CockroachDB driver was based on) - #5112 and others. This lead to application crashes in case a connection was closed abruptly.
This PR backports latest connection acquire/release handling code from postgres driver without any other significant changes.
> fix: backport postgres connection error handling to crdb

- docs/migrations.md
Fix minor typos in the documentation.
> chore: fix typos

- docs/embedded-entities.md
- src/metadata/ColumnMetadata.ts
- src/metadata/EntityMetadata.ts
- src/query-builder/transformer/RawSqlResultsToEntityTransformer.ts
- test/github-issues/300/issue-300.ts
- test/github-issues/3913/entity/Test.ts
- test/github-issues/3913/issue-3913.ts
- test/github-issues/762/issue-762.ts
Closes #3913
This PR introduces a breaking change by modifying the embedded entities behaviour to make them nullable (maybe enable it under a specific config?)
When dealing with embedded entities where all columns are `null`, we can consider the entire entity to be `null`
The same principle applies when setting `null` as a value for the embedded entity while updating, it sets all the embedded columns to `null`
> feat: nullable embedded entities

- src/cache/DbQueryResultCache.ts
- src/query-builder/QueryExpressionMap.ts
- src/query-builder/SelectQueryBuilder.ts
- test/functional/repository/aggregate-methods/repository-aggregate-methods.ts
- test/github-issues/9910/entity/User.ts
- test/github-issues/9910/issue-9910.ts
> fix: should automatically cache if alwaysEnable

- src/driver/postgres/PostgresQueryRunner.ts
- src/schema-builder/RdbmsSchemaBuilder.ts
- test/github-issues/10612/entity/ExampleEntity.ts
- test/github-issues/10612/issue-10612.ts
Added table comment for Postgres.
Fixes #10612
> feat: add table comment for postgres

- docs/select-query-builder.md
I noticed two sections of the [Select using Query Builder](https://typeorm.io/select-query-builder) need to be added in the table of contents.
> docs: fix table of contents missing sections

- docs/one-to-one-relations.md
> docs: update the content of one-to-one to be more emphatic and grammatically complete

- src/data-source/DataSource.ts
Fixes https://github.com/typeorm/typeorm/issues/9695
> fix: fallback runMigrations transaction to DataSourceOptions

- src/driver/sqlite/SqliteQueryRunner.ts
- src/query-builder/InsertQueryBuilder.ts
- test/functional/repository/find-options-locking/find-options-locking.ts
- test/github-issues/10191/entity/Example.ts
- test/github-issues/10191/index-10191.ts
- test/github-issues/9988/issue-9988.ts
- test/utils/xfail.ts
> fix: don't escape indexPredicate

- docs/view-entities.md
I just changed "Let" to "Lets".
> docs: grammar mistake fixed

- src/query-builder/QueryBuilder.ts
- src/query-builder/SelectQueryBuilder.ts
added missing parentheses in where conditions and with And/Or operators
Closes: #10534
if we use:
```
const result = await database
.getRepository(Gift)
.findBy({
startDate: MoreThanOrEqual(initialDate),
endDate: Or(
LessThanOrEqual(finalDate),
IsNull(),
),
})
```
before, the generated SQL was the following:
```
SELECT ... FROM gift
WHERE (start_date >= $1 AND end_date <= $2 OR end_date IS NULL)
```
now:
```
SELECT ... FROM gift
WHERE ((start_date >= $1) AND (((end_date <= $2) OR (end_date IS NULL))))
```
> fix: added missing parentheses in where conditions

- src/driver/sap/SapQueryRunner.ts
This reverts PR #10123 (commit dd595242a7fbb8c7445cc79bf0b751f1ed1762bd).
_Partially_ fixes #10622.
> Revert "fix: prevent using absolute table path in migrations unless required (#10123)"

- docs/zh_CN/custom-repository.md
I encountered the issue of `'EntityRepository' is deprecated` when trying to create a custom repository, and found that this document is not the latest. hope it will be helpful.
> docs: update the custom-repository.md file in the docs/zh_CN directory

- package-lock.json
- package.json
- src/metadata/ColumnMetadata.ts
- test/functional/tree-tables/nested-set/nested-set.ts
- test/github-issues/1551/issue-1551.ts
- test/github-issues/7068/issue-7068.ts
- test/other-issues/composite-keys/composite-keys.ts
- test/other-issues/composite-keys/entity/Group.ts
- test/other-issues/composite-keys/entity/Policy.ts
- test/other-issues/composite-keys/entity/PolicyGroup.ts
This is a PR to uncover the underlying composite key save issue
Changes:
- Added test to match use case uncovered in local codebase
> chore(TypeORM): Create test case to uncover TypeORM composite key save issue

- README.md
- docs/future-of-typeorm.md
Adds the announcement for the future of TypeORM to the docs.
> chore(docs): add announcement

- .github/workflows/test.yml
This makes it so that you can run the CI/CD on the forks and other branches when this pipeline file is present in the branch.
> test: remove restriction of CI/CD runs for fork branches

- src/driver/postgres/PostgresQueryRunner.ts
- src/query-builder/InsertQueryBuilder.ts
- src/query-builder/QueryBuilder.ts
- src/schema-builder/RdbmsSchemaBuilder.ts
- test/integration/sample2-one-to-one.ts
- test/integration/sample3-many-to-one.ts
I ran `npm run format` and that was the result, looks like that wasn't applied before.
> style: apply formatting

- docs/data-source.md
change datasource documentation sentence for better spelling
don't need to do that since this only md changes
> docs(datasource): some sentence updated for datasource doc

- README-zh_CN.md
- README.md
- README_ko.md
- docs/zh_CN/README.md
- docs/zh_CN/index.md
Fixes https://github.com/typeorm/typeorm/issues/11178
The Vesper project repo has not been updated in 6 years and the website is dead.
> Remove links to defunct Vesper project

- docs/data-source-options.md
Refine MD language for better clarity and grammar
Markdown changes only
> docs: Refine Markdown Language for Better Clarity and Grammar

- docs/select-query-builder.md
> Typo - setOnLock -> setOnLocked

- src/decorator/relations/OneToOne.ts
Fixes comments with the explanation of one-to-one relation
- N/A `npm run test` passes with this change
- N/A This pull request links relevant issues as `Fixes #0000`
- N/A There are new or updated unit tests validating the change
> docs: one-to-one relation explanation fix

- docs/multiple-data-sources.md
Fixes spacing in Multiple Data Sources page of documentation
- [N/A] `npm run test` passes with this change
- [N/A] There are new or updated unit tests validating the change
> docs(multiple-data-sources.md): fix spacing

- docs/data-source-options.md
- src/driver/aurora-mysql/AuroraMysqlConnectionCredentialsOptions.ts
- src/driver/cockroachdb/CockroachConnectionCredentialsOptions.ts
- src/driver/cockroachdb/CockroachConnectionOptions.ts
- src/driver/mongodb/MongoConnectionOptions.ts
- src/driver/mysql/MysqlConnectionCredentialsOptions.ts
- src/driver/mysql/MysqlConnectionOptions.ts
- src/driver/oracle/OracleConnectionCredentialsOptions.ts
- src/driver/oracle/OracleConnectionOptions.ts
- src/driver/postgres/PostgresConnectionCredentialsOptions.ts
- src/driver/postgres/PostgresConnectionOptions.ts
- src/driver/spanner/SpannerConnectionCredentialsOptions.ts
- src/driver/spanner/SpannerConnectionOptions.ts
- src/driver/sqlserver/SqlServerConnectionCredentialsOptions.ts
- src/driver/sqlserver/SqlServerConnectionOptions.ts
- I fixed the description of the `url` property, in documentation & comments
- I fixed a description typo "severs" -> "servers"
> Docs: fix connection options description

- src/entity-manager/EntityManager.ts
> refactor: update EntityManager.ts

- docs/tree-entities.md
Added one sentance to tree entites docs page to Clarify that the TreeRepository doesn't support adjaceny list to stop misleading reader
Fixes #2540
> docs: clarify adjacency list

- src/query-builder/transformer/RawSqlResultsToEntityTransformer.ts
Improve the performance of `RawSqlResultsToEntityTransformer`. This makes it about twice as fast in queries in my testing.
> perf: improve results transformer performance

- DEVELOPER.md
I did some work in another PR and it wasn't entirely clear to me how to setup tests quickly. So after being asked I gave the documentation a pass to clarify some things and generally copy edit it.
Asked here in Discord: https://discord.com/channels/1124626013360488529/1338927560397946983/1339634447557070889
> Give the DEVELOPER.md documentation a pass

- docs/performance-optimizing.md
> docs: add performance and optimizing

- gulpfile.ts
- package-lock.json
- package.json
This fixes a couple of issues I encountered when following Umed's instructions to create a new TypeORM release.
> Fix release issues

- docs/logging.md
- docs/zh_CN/logging.md
- package-lock.json
- package.json
- src/commands/CacheClearCommand.ts
- src/commands/EntityCreateCommand.ts
- src/commands/InitCommand.ts
- src/commands/MigrationCreateCommand.ts
- src/commands/MigrationGenerateCommand.ts
- src/commands/QueryCommand.ts
- src/commands/SchemaDropCommand.ts
- src/commands/SchemaLogCommand.ts
- src/commands/SchemaSyncCommand.ts
- src/commands/SubscriberCreateCommand.ts
- src/platform/BrowserPlatformTools.template
- src/platform/PlatformTools.ts
Replaces `chalk` with `ansis`. This is smaller, faster and has no dependencies. It's also recently updated and allows us to use ANSI codes directly (for the syntax highlighter).
The syntax highlighter now uses colors similar to the ones we had before PR #11221 was merged.
Also updated `uuid`. The only breaking change is the minimum supported node version, which is within TypeORM's range as well.
> refactor: use ansis instead of chalk

- docs/faq.md
This pull-request resolves #11284
> docs: add "How to use Vite for the backend" entry to faq

- test/functional/cache/custom-cache-provider.ts
- test/functional/query-builder/cache/query-builder-cache.ts
Fixes #10863
Rename the tests to better describe the case.
> test: rename tests to better describe the case

- new_doc/docusaurus.config.ts
- new_doc/src/css/custom.css
Improved color pallete to be more aligned with the [W3 Guidelines](https://www.w3.org/TR/WCAG21/#contrast-minimum).
In order to run you need to `cd` to the `new_doc` folder, run `npm install` and then `npm run start`
> docs: improve accessibility

- sample/sample9-entity-listeners/entity/Post.ts
- src/commands/MigrationGenerateCommand.ts
- src/driver/cockroachdb/CockroachDriver.ts
- src/driver/cockroachdb/CockroachQueryRunner.ts
- src/driver/postgres/PostgresDriver.ts
- src/driver/postgres/PostgresQueryRunner.ts
- test/functional/database-schema/enums-array/entity/EnumArrayEntity.ts
- test/functional/database-schema/enums-array/enums-array.ts
Fix issues identified by CodeQL
> fix: sql escape issues identified by CodeQL

- CHANGELOG.md
- package-lock.json
- package.json
Bumps the version and updates the changelog for v0.3.22
> chore: Bump version to v0.3.22 and generate changelog

- src/query-builder/QueryBuilder.ts
- src/query-builder/SelectQueryBuilder.ts
> Fix(undefined-null-flags): Handle null for relations

- CHANGELOG.md
- docs/docs/Advanced Topics/7-performance-optimizing.md
- src/entity-manager/EntityManager.ts
- src/error/InitializedRelationError.ts
- src/metadata/ColumnMetadata.ts
> Fix(new-docs): Update links

- docs/docusaurus.config.ts
- docs/package-lock.json
- docs/package.json
- docs/redirects.ts
> Feature(new-docs): Add redirects to support legacy paths

- CHANGELOG.md
- README.md
- docs/docs/guides/4-example-with-express.md
- docs/docs/guides/6-sequelize-migration.md
- docs/docs/help/1-faq.md
- docs/docs/help/3-decorator-reference.md
- docs/docs/working-with-entity-manager/5-entity-manager-api.md
- docs/docs/working-with-entity-manager/6-repository-api.md
- docs/docusaurus.config.ts
> Fix: Update leftover cross-references in the docs

- docs/entities.md
Corrected the word "its" to "it's" in Entities documentation.
> docs: Correct "its" -> "it's"

- src/driver/sap/SapQueryRunner.ts
- test/functional/query-runner/stream.ts
Implement proper cleanup for row streams in SAP HANA.
> fix(sap): cleanup after streaming

- src/common/PrimitiveCriteria.ts
- src/entity-manager/EntityManager.ts
- src/repository/Repository.ts
- src/util/OrmUtils.ts
- test/github-issues/10517/entity/Post.ts
- test/github-issues/10517/issue-10517.ts
> fix: update/delete/softDelete by criteria of condition objects

- CHANGELOG.md
- DEVELOPER.md
- package-lock.json
- package.json
Updating to v0.3.23.
PR also includes a description of the release process in the DEVELOPER.md.
After merge, creation of a new release will trigger the publish workflow.
> chore: Version 0.3.23

- .github/workflows/preview.yml
- package.json
> use pnpm for preview releases

- .github/workflows/preview.yml
- package-lock.json
- package.json
> fix: resolve pkg.pr.new issue

- src/persistence/SubjectDatabaseEntityLoader.ts
Improve save performance during entities update. In my test case 2 300 entities were updated. It used to take 27 seconds, now only 3 seconds, almost 10 times improvement.
> perf: improve save performance during entities update
